function CalculatorsComponentStyle(){this.initByNamespace("calculators");
}CalculatorsComponentStyle.inherits(ComponentStyle);
function CalculatorsComponent(criterion){this.calSumI18n=i18n.discernabu.calculators_o1;
this.calcDomain="";
this.jsonFileUrl="";
this.defaultSpecialty="";
this.currentSpecialty="";
this.setCriterion(criterion);
this.setStyles(new CalculatorsComponentStyle());
this.setComponentRenderTimerName("ENG:MPG_Calculators render component");
this.setComponentLoadTimerName("USR:MPG_Calculators load component");
this.calcListJson={};
}CalculatorsComponent.prototype=new MPageComponent();
CalculatorsComponent.prototype.constructor=MPageComponent;
MP_Util.setObjectDefinitionMapping("CALCULATOR",CalculatorsComponent);
CalculatorsComponent.prototype.setMedcalcURL=function(calcURL){calcURL=calcURL.replace(/&#092;/g,"\\");
calcURL=calcURL.replace(/&#047;/g,"/");
calcURL=calcURL.replace(/&#039;/g,"'");
calcURL=calcURL.replace(/&#034;/g,'"');
calcURL=calcURL.replace(/&#060;/g,"<");
if(calcURL.charAt(calcURL.length-1)!=="/"&&calcURL.charAt(calcURL.length-1)!=="\\"){calcURL+="/";
}this.calcDomain=calcURL;
this.jsonFileUrl=calcURL.replace("NoteRight3000/","")+"calculatorList.json";
};
CalculatorsComponent.prototype.loadFilterMappings=function(){this.addFilterMappingObject("CALCULATOR_MEDCALC_URL",{setFunction:this.setMedcalcURL,type:"STRING",field:"FREETEXT_DESC"});
};
CalculatorsComponent.prototype.retrieveComponentData=function(){var self=this;
$.ajax({type:"GET",url:self.jsonFileUrl,async:true,jsonpCallback:"jsonCallback",contentType:"application/json",dataType:"jsonp",success:function(calcList){self.calcListJson=calcList;
var request=new MP_Core.ScriptRequest(self,self.getComponentLoadTimerName());
request.setProgramName("MP_GET_USER_PREFS");
var criterion=self.getCriterion();
request.setParameters(["^MINE^",criterion.provider_id+".0","^CALCULATORS_PREFS^"]);
request.setAsync(true);
MP_Core.XMLCCLRequestCallBack(self,request,self.renderComponent);
},error:function(err){MP_Util.LogJSError(err,self,"calculators-o1.js","JSON Ajax Request");
throw err;
}});
};
CalculatorsComponent.prototype.calcTypeCount=function(calcSpecObject){var key;
var size=0;
for(key in calcSpecObject){if(calcSpecObject.hasOwnProperty(key)){size++;
}}return String(size);
};
CalculatorsComponent.prototype.generateCalcComponentHTML=function(){var calcSpecialty=this.currentSpecialty;
var calcListHtml="";
if(this.defaultSpecialty.length>0){calcListHtml=this.generateCalcListHTML();
}else{calcListHtml=this.generateSpecialtyListHTML();
}var calcComponentHtml="<div class='calc-top-nav-bar'><a class='calc-medcalc-home-link' href='index.htm' title='MedCalc Home' onclick='return false;'>MedCalc 3000</a><div class='calc-index-link'><a href='#'>"+this.calSumI18n.INDEX+"</a></div></div><div class='calc-medcalc-homepage'>";
calcComponentHtml+='<div class="calc-spec-dropdown-bar"><div class="calc-spec-dropdown"';
if(this.defaultSpecialty.length===0){calcComponentHtml+=' style="display:none"';
}calcComponentHtml+=">"+this.calSumI18n.VIEW+':<select class="calc-specialty-select">';
for(specialty in this.calcListJson){if(this.calcListJson.hasOwnProperty(specialty)){calcComponentHtml+='<option value ="'+specialty+'" ';
if(specialty===this.currentSpecialty){calcComponentHtml+="selected";
}calcComponentHtml+=">"+specialty+"</option>";
}}calcComponentHtml+='</select><a href="#" onclick="return false;" class="calc-default-specialty-link"';
if(this.defaultSpecialty.length>0&&calcSpecialty===this.defaultSpecialty){calcComponentHtml+=" style='display:none'";
}calcComponentHtml+=">"+this.calSumI18n.SET_DEFAULT+'</a></div><div class="calc-allcalc-link"><a class="calc-medcalc-links" href="eq-idx.htm" title="All Calculators" onclick="return false;">'+this.calSumI18n.ALL_CALCULATORS+'</a></div></div><div class="calc-specialty-list-container">'+calcListHtml+'</div><div class="calc-medcalc-disclaimer"><h1 class="calc-medcalc-disclaimer-header">'+this.calSumI18n.LEGAL_DISCLAIMER_1+"</h1>";
calcComponentHtml+="<p>"+this.calSumI18n.LEGAL_DISCLAIMER_2+'<span class="calc-medcalc-disclaimer-warning">'+this.calSumI18n.LEGAL_DISCLAIMER_3+'</span><a class="calc-medcalc-links" title="view disclaimer" href="disclaimer.htm" onclick="return false">'+this.calSumI18n.LEGAL_DISCLAIMER_4+'</a></p><p class="calc-medcalc-disclaimer-copyright">'+this.calSumI18n.LEGAL_DISCLAIMER_5+"</p></div>";
calcComponentHtml+="</div><iframe class='calc-iframe-medcalc' src='' frameborder='0' style='display:none'></iframe><div class='calc-footer'><p>"+this.calSumI18n.POWEREDBY+" MEDCALC <span class='calc-medcalc-number'>3000</span></p></div>";
return calcComponentHtml;
};
CalculatorsComponent.prototype.generateCalcListHTML=function(){var calcSpecialty=this.currentSpecialty;
var calcUrlObj="";
var calcTypeCalcArray=[];
var calcType="";
var calcIndex=0;
var calcListHtml="";
var calcListElements="";
var calcListHtmlhead="";
var calcTypeCounter=0;
var calcTypeClass="";
var calcTypeColCount=this.calcTypeCount(this.calcListJson[calcSpecialty]);
for(calcType in this.calcListJson[calcSpecialty]){if(this.calcListJson[calcSpecialty].hasOwnProperty(calcType)){calcTypeCalcArray=this.calcListJson[calcSpecialty][calcType];
calcTypeCounter++;
for(calcIndex=0;
calcIndex<calcTypeCalcArray.length;
calcIndex++){calcListElements+='<li><a class = "calc-medcalc-links" title="'+calcTypeCalcArray[calcIndex].description+'" href= "'+calcTypeCalcArray[calcIndex].url+'" onclick="return false;">'+calcTypeCalcArray[calcIndex].name+"</a></li>";
}if(calcTypeCounter===1){calcTypeClass=calcTypeColCount+"-col";
}else{calcTypeClass=calcTypeColCount+"-col calc-lists";
}calcListHtmlhead='<ul id ="'+calcType+'" class ="calc-'+calcTypeClass+'"><h1 class="calc-type-header">'+calcType+"</h1>";
calcListHtml+=calcListHtmlhead+calcListElements+"</ul>";
calcListHtmlhead="";
calcListElements="";
}}return calcListHtml;
};
CalculatorsComponent.prototype.generateSpecialtyListHTML=function(){var self=this;
var specialtyCalcJSON=self.calcListJson;
var specialtyListHtml="";
var columnHtml=["<div><ul class='calc-3-col'>","<div><ul class='calc-3-col calc-lists'>","<div><ul class='calc-3-col calc-lists'>"];
var columnIndex=0;
for(specialty in specialtyCalcJSON){if(specialtyCalcJSON.hasOwnProperty(specialty)){columnHtml[columnIndex]+="<li><a class='specialty-link' href='#' onclick='return false;'>"+specialty+"</a></li>";
columnIndex++;
columnIndex=(columnIndex===3?0:columnIndex);
}}columnHtml[0]+="</ul></div>";
columnHtml[1]+="</ul></div>";
columnHtml[2]+="</ul></div>";
specialtyListHtml=columnHtml[0]+columnHtml[1]+columnHtml[2];
return specialtyListHtml;
};
CalculatorsComponent.prototype.openMedCalcPage=function(calcLinkObj){var calcLink="";
var slaTimer=null;
var calcTitle="";
if($(calcLinkObj).attr("title")!==undefined){calcTitle=$(calcLinkObj).attr("title");
}var calcHref=$(calcLinkObj).attr("href");
if(calcHref==="eq-idx.htm"){slaTimer=MP_Util.CreateTimer("CAP:MPG_Calculators launch all calculators",calcTitle);
}else{if(calcHref==="disclaimer.htm"||calcHref==="index.htm"){if(this.calcDomain.indexOf("NoteRight3000")>=0){calcHref="../"+calcHref;
}}else{slaTimer=MP_Util.CreateTimer("CAP:MPG_Calculators launch calculator",calcTitle);
}}if(slaTimer){slaTimer.Stop();
}calcLink=this.calcDomain+calcHref;
$(".calc-iframe-medcalc").attr("src",calcLink);
$(".calc-medcalc-homepage").hide();
$(".calc-iframe-medcalc").show();
};
CalculatorsComponent.prototype.resizeComponent=function(){var iframePsuedoMargin=0;
var col2CalclistMargin=0;
iframePsuedoMargin=$(".sec-hd").outerHeight(true)+$(".calc-top-nav-bar").outerHeight(true)+$(".calc-footer").outerHeight(true)+28;
col2CalclistMargin=iframePsuedoMargin+$(".calc-spec-dropdown-bar").outerHeight(true)+$(".calc-medcalc-disclaimer").outerHeight(true)+$("").outerHeight(true)+11;
$(".calc-iframe-medcalc").css({height:$(".mp-calc-summary").find(".col2").outerHeight(false)-iframePsuedoMargin+"px"});
$(".calc-specialty-list-container").css({height:$(".mp-calc-summary").find(".col2").outerHeight(false)-col2CalclistMargin+"px"});
};
CalculatorsComponent.prototype.renderComponent=function(reply){var renderTimer=null;
var self=reply.getComponent();
try{renderTimer=MP_Util.CreateTimer(self.getComponentRenderTimerName());
if(reply.getStatus()==="S"){var recordData=reply.getResponse();
var prefJson=JSON.parse(recordData.PREF_STRING);
self.defaultSpecialty=prefJson.specialty;
self.currentSpecialty=prefJson.specialty;
}var sHTML=self.generateCalcComponentHTML();
MP_Util.Doc.FinalizeComponent(sHTML,self,"");
$(".calc-medcalc-homepage").on("click",".calc-medcalc-links",function(event){self.openMedCalcPage(this);
});
$(".calc-medcalc-homepage").on("click",".specialty-link",function(event){self.currentSpecialty=$(this).text();
$(".calc-specialty-select").val(self.currentSpecialty);
$(".calc-spec-dropdown").show();
$(".calc-specialty-list-container").html(self.generateCalcListHTML());
});
$(".calc-medcalc-home-link").on("click",function(event){self.openMedCalcPage(this);
});
$(".calc-specialty-select").change(function(){self.currentSpecialty=$(this).find("option:selected").val();
if(self.currentSpecialty===self.defaultSpecialty){$(".calc-default-specialty-link").hide();
}else{$(".calc-default-specialty-link").show();
}$(".calc-specialty-list-container").html(self.generateCalcListHTML());
});
$(".calc-default-specialty-link").click(function(){self.WritePreferences({specialty:self.currentSpecialty},"CALCULATORS_PREFS",true,self.getComponentId());
self.defaultSpecialty=self.currentSpecialty;
$(this).hide();
});
$(".calc-index-link").click(function(){$(".calc-iframe-medcalc").hide();
$(".calc-iframe-medcalc").attr("src","");
$(".calc-medcalc-homepage").show();
});
if(window.addEventListener){window.addEventListener("message",function(e){var medCalcReply={};
try{medCalcReply=JSON.parse(e.data);
}catch(err){MP_Util.LogJSError(err,self,"calculators-o1.js","MedCalc message JSON parse");
return;
}if(medCalcReply.hasOwnProperty("medcalc-calctxt")){if(window.clipboardData&&clipboardData.setData){clipboardData.setData("text",medCalcReply["medcalc-calctxt"]);
}}},false);
}else{if(window.attachEvent){window.attachEvent("onmessage",function(e){var medCalcReply={};
try{medCalcReply=JSON.parse(e.data);
}catch(err){MP_Util.LogJSError(err,self,"calculators-o1.js","MedCalc message JSON parse");
return;
}if(medCalcReply.hasOwnProperty("medcalc-calctxt")){if(window.clipboardData&&clipboardData.setData){clipboardData.setData("text",medCalcReply["medcalc-calctxt"]);
}}});
}}}catch(err){if(renderTimer){renderTimer.Abort();
renderTimer=null;
}MP_Util.LogJSError(err,self,"calculators-o1.js","renderComponent");
throw err;
}finally{if(renderTimer){renderTimer.Stop();
}}};
CalculatorsComponent.prototype.WritePreferences=function(jsonObject,prefIdent,saveAsync,compID){var info=(CERN_BrowserDevInd)?new XMLHttpRequest():new XMLCclRequest();
if(!saveAsync){saveAsync=false;
}info.onreadystatechange=function(){if(this.readyState==4&&this.status==200){MP_Util.LogScriptCallInfo(null,this,"mp_core.js","WritePreferences");
var jsonEval=JSON.parse(this.responseText);
var recordData=jsonEval.RECORD_DATA;
if(recordData.STATUS_DATA.STATUS=="Z"){return;
}else{if(recordData.STATUS_DATA.STATUS=="S"){return;
}else{MP_Util.LogScriptCallError(null,this,"mp_core.js","WritePreferences");
var errAr=[];
var statusData=recordData.STATUS_DATA;
errAr.push("STATUS: "+statusData.STATUS);
for(var x=0,xl=statusData.SUBEVENTSTATUS.length;
x<xl;
x++){var ss=statusData.SUBEVENTSTATUS[x];
errAr.push(ss.OPERATIONNAME,ss.OPERATIONSTATUS,ss.TARGETOBJECTNAME,ss.TARGETOBJECTVALUE);
}window.status="Error saving user preferences: "+errAr.join(",");
}}}};
var component=MP_Util.GetCompObjById(compID);
var sJson=(jsonObject!==null)?JSON.stringify(jsonObject):"";
var ar=["^mine^",component.criterion.provider_id+".0","^"+prefIdent+"^","~"+sJson+"~"];
if(CERN_BrowserDevInd){var url="MP_MAINTAIN_USER_PREFS?parameters="+ar.join(",");
info.open("GET",url,saveAsync);
info.send(null);
}else{info.open("GET","MP_MAINTAIN_USER_PREFS",saveAsync);
info.send(ar.join(","));
}};
