var registerNS=function(b){for(var b=b.split("."),a=window,e=0,e=0;e<b.length;e++){if(null===a[b[e]]||"object"!==typeof a[b[e]])a[b[e]]={};a=a[b[e]]}};registerNS("com.cerner.oncology.util");com.cerner.oncology.util=com.cerner.oncology.util;
com.cerner.oncology.util.getViewportWidth=function(){var b=0;document.documentElement&&document.documentElement.clientWidth?b=document.documentElement.clientWidth:document.body&&document.body.clientWidth?b=document.body.clientWidth:window.innerWidth&&(b=window.innerWidth-18);return b};
com.cerner.oncology.util.getViewportHeight=function(){var b=0;document.documentElement&&document.documentElement.clientHeight?b=document.documentElement.clientHeight:document.body&&document.body.clientHeight?b=document.body.clientHeight:window.innerHeight&&(b=window.innerHeight-18);return b};
com.cerner.oncology.util.getViewportScrollX=function(){var b=0;document.documentElement&&document.documentElement.scrollLeft?b=document.documentElement.scrollLeft:document.body&&document.body.scrollLeft?b=document.body.scrollLeft:window.pageXOffset?b=window.pageXOffset:window.scrollX&&(b=window.scrollX);return b};
com.cerner.oncology.util.getViewportScrollY=function(){var b=0;document.documentElement&&document.documentElement.scrollTop?b=document.documentElement.scrollTop:document.body&&document.body.scrollTop?b=document.body.scrollTop:window.pageYOffset?b=window.pageYOffset:window.scrollY&&(b=window.scrollY);return b};com.cerner.oncology.util.getAbsoluteViewportWidth=function(){return+com.cerner.oncology.util.getViewportWidth()+com.cerner.oncology.util.getViewportScrollX()};
com.cerner.oncology.util.getAbsoluteViewportHeight=function(){return+com.cerner.oncology.util.getViewportHeight()+com.cerner.oncology.util.getViewportScrollY()};com.cerner.oncology.util.stripUnit=function(b){return parseInt(b.replace(/[^\d\.]/g,""),10)};
com.cerner.oncology.util.positionPopup=function(b,a){$(b).css("position","absolute");var e=com.cerner.oncology.util.getAbsoluteViewportWidth(),f=com.cerner.oncology.util.getAbsoluteViewportHeight(),k=$(b).width(),h=$(b).height(),l=+a.clientX+com.cerner.oncology.util.getViewportScrollX(),m=+a.clientY+com.cerner.oncology.util.getViewportScrollY();l+k+10>=e?(e=a.pageX-k-10,$(b).css({left:0>e?0:e})):$(b).css({left:+a.pageX+10});m+h+10>=f?(f=a.pageY-h-10,$(b).css({top:0>f?0:f})):$(b).css({top:+a.pageY+
10})};com.cerner.oncology.util.movePopupToBody=function(b){$("#"+b).remove().appendTo("body")};com.cerner.oncology.util.createRow=function(b,a,e,f){var k=$(document.createElement("tr"));e&&e.length&&$(k).addClass(e.join(" "));for(var e=f&&f.length?f.join(" "):[],h=$(document.createElement(a?"th":"td")),f=0;f<b;f++)a=$(h).clone(),e.length&&a.addClass(e),$(k).append(a);return k};
com.cerner.oncology.util.createTable=function(b,a,e){b=$(document.createElement("table")).attr("summary",b);a&&$(b).attr("id",a);e&&e.length&&$(b).addClass(e.join(" "));a=$(document.createElement("thead"));$(b).append(a);a=$(document.createElement("tbody"));$(b).append(a);return b};com.cerner.oncology.util.getTextWidth=function(b){var a;a=$(document.createElement("div")).hide();$("body").append(a);$(a).text($(b).text());b=$(a).width();$(a).remove();return b};
com.cerner.oncology.util.findLongestText=function(b){var a,e,f,k;a=f=0;for(e=$(b).length;a<e;a++)k=com.cerner.oncology.util.getTextWidth(b[a]),f=k>f?k:f;return f};com.cerner.oncology.util.isTextOverflowing=function(b){return com.cerner.oncology.util.getTextWidth(b)>$(b).width()};com.cerner.oncology.util.loadBedrockConfig=function(b){var a;b.toLowerCase();window.m_bedrockMpage&&(a=$.grep(m_bedrockMpage.MPAGE[0].COMPONENT,function(a){return a.FILTER_MEAN===b}));return a&&a.length?a[0]:null};
(function(b){function a(c,j){return function(a){return o(c.call(this,a),j)}}function e(c){return function(j){return this.lang().ordinal(c.call(this,j))}}function f(){}function k(c){l(this,c)}function h(c){var j=this._data={},a=c.years||c.year||c.y||0,b=c.months||c.month||c.M||0,i=c.weeks||c.week||c.w||0,u=c.days||c.day||c.d||0,g=c.hours||c.hour||c.h||0,h=c.minutes||c.minute||c.m||0,e=c.seconds||c.second||c.s||0,c=c.milliseconds||c.millisecond||c.ms||0;this._milliseconds=c+1E3*e+6E4*h+36E5*g;this._days=
u+7*i;this._months=b+12*a;j.milliseconds=c%1E3;e+=m(c/1E3);j.seconds=e%60;h+=m(e/60);j.minutes=h%60;g+=m(h/60);j.hours=g%24;u+=m(g/24);u+=7*i;j.days=u%30;b+=m(u/30);j.months=b%12;a+=m(b/12);j.years=a}function l(c,j){for(var a in j)j.hasOwnProperty(a)&&(c[a]=j[a]);return c}function m(c){return 0>c?Math.ceil(c):Math.floor(c)}function o(c,j){for(var a=c+"";a.length<j;)a="0"+a;return a}function t(c,j,a){var b=j._milliseconds,i=j._days,j=j._months,g;b&&c._d.setTime(+c+b*a);i&&c.date(c.date()+i*a);j&&(g=
c.date(),c.date(1).month(c.month()+j*a).date(Math.min(g,c.daysInMonth())))}function n(c,j){var a=Math.min(c.length,j.length),b=Math.abs(c.length-j.length),i=0,g;for(g=0;g<a;g++)~~c[g]!==~~j[g]&&i++;return i+b}function r(c){return c?(!w[c]&&C&&require("./lang/"+c),w[c]):g.fn._lang}function x(c){switch(c){case "DDDD":return O;case "YYYY":return P;case "YYYYY":return Q;case "S":case "SS":case "SSS":case "DDD":return R;case "MMM":case "MMMM":case "dd":case "ddd":case "dddd":case "a":case "A":return S;
case "X":return T;case "Z":case "ZZ":return D;case "T":return U;case "MM":case "DD":case "YY":case "HH":case "hh":case "mm":case "ss":case "M":case "D":case "d":case "H":case "h":case "m":case "s":return V;default:return RegExp(c.replace("\\",""))}}function E(c){var j,a=[];if(!c._d){for(j=0;7>j;j++)c._a[j]=a[j]=null==c._a[j]?2===j?1:0:c._a[j];a[3]+=c._tzh||0;a[4]+=c._tzm||0;j=new Date(0);c._useUTC?(j.setUTCFullYear(a[0],a[1],a[2]),j.setUTCHours(a[3],a[4],a[5],a[6])):(j.setFullYear(a[0],a[1],a[2]),
j.setHours(a[3],a[4],a[5],a[6]));c._d=j}}function y(c){var a=c._f.match(F),b=c._i,g,i;c._a=[];for(g=0;g<a.length;g++)if((i=(x(a[g]).exec(b)||[])[0])&&(b=b.slice(b.indexOf(i)+i.length)),s[a[g]]){var h=c,e=void 0,f=h._a;switch(a[g]){case "M":case "MM":f[1]=null==i?0:~~i-1;break;case "MMM":case "MMMM":e=r(h._l).monthsParse(i);null!=e?f[1]=e:h._isValid=!1;break;case "D":case "DD":case "DDD":case "DDDD":null!=i&&(f[2]=~~i);break;case "YY":f[0]=~~i+(68<~~i?1900:2E3);break;case "YYYY":case "YYYYY":f[0]=
~~i;break;case "a":case "A":h._isPm="pm"===(i+"").toLowerCase();break;case "H":case "HH":case "h":case "hh":f[3]=~~i;break;case "m":case "mm":f[4]=~~i;break;case "s":case "ss":f[5]=~~i;break;case "S":case "SS":case "SSS":f[6]=~~(1E3*("0."+i));break;case "X":h._d=new Date(1E3*parseFloat(i));break;case "Z":case "ZZ":h._useUTC=!0,(e=(i+"").match(W))&&e[1]&&(h._tzh=~~e[1]),e&&e[2]&&(h._tzm=~~e[2]),e&&"+"===e[0]&&(h._tzh=-h._tzh,h._tzm=-h._tzm)}null==i&&(h._isValid=!1)}c._isPm&&12>c._a[3]&&(c._a[3]+=12);
!1===c._isPm&&12===c._a[3]&&(c._a[3]=0);E(c)}function X(c,a,b,g,i){return i.relativeTime(a||1,!!b,c,g)}function G(c,a,b){a=b-a;b-=c.day();return b>a&&(b-=7),b<a-7&&(b+=7),Math.ceil(g(c).add("d",b).dayOfYear()/7)}function H(c){var a=c._i,q=c._f;if(null===a||""===a)c=null;else{"string"==typeof a&&(c._i=a=r().preparse(a));if(g.isMoment(a))c=l({},a),c._d=new Date(+a._d);else if(q)if("[object Array]"===Object.prototype.toString.call(q)){for(var a=c,h,i,e=99;a._f.length;){h=l({},a);h._f=a._f.pop();y(h);
q=new k(h);if(q.isValid()){i=q;break}h=n(h._a,q.toArray());h<e&&(e=h,i=q)}l(a,i)}else y(c);else if(i=c,a=i._i,q=Y.exec(a),a===b)i._d=new Date;else if(q)i._d=new Date(+q[1]);else if("string"==typeof a)if(q=i._i,Z.exec(q)){i._f="YYYY-MM-DDT";for(a=0;4>a;a++)if(I[a][1].exec(q)){i._f+=I[a][0];break}D.exec(q)&&(i._f+=" Z");y(i)}else i._d=new Date(q);else"[object Array]"===Object.prototype.toString.call(a)?(i._a=a.slice(0),E(i)):i._d=a instanceof Date?new Date(+a):new Date(a);c=new k(c)}return c}function J(c,
a){g.fn[c]=g.fn[c+"s"]=function(c){var b=this._isUTC?"UTC":"";return null!=c?(this._d["set"+b+a](c),this):this._d["get"+b+a]()}}function aa(c){g.duration.fn[c]=function(){return this._data[c]}}function K(c,a){g.duration.fn["as"+c]=function(){return+this/a}}for(var g,v=Math.round,p,w={},C="undefined"!=typeof module&&module.exports,Y=/^\/?Date\((\-?\d+)/i,F=/(\[[^\[]*\])|(\\)?(Mo|MM?M?M?|Do|DDDo|DD?D?D?|ddd?d?|do?|w[o|w]?|W[o|W]?|YYYYY|YYYY|YY|a|A|hh?|HH?|mm?|ss?|SS?S?|X|zz?|ZZ?|.)/g,L=/(\[[^\[]*\])|(\\)?(LT|LL?L?L?|l{1,4})/g,
V=/\d\d?/,R=/\d{1,3}/,O=/\d{3}/,P=/\d{1,4}/,Q=/[+\-]?\d{1,6}/,S=/[0-9]*[a-z\u00A0-\u05FF\u0700-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+|[\u0600-\u06FF]+\s*?[\u0600-\u06FF]+/i,D=/Z|[\+\-]\d\d:?\d\d/i,U=/T/i,T=/[\+\-]?\d+(\.\d{1,3})?/,Z=/^\s*\d{4}-\d\d-\d\d((T| )(\d\d(:\d\d(:\d\d(\.\d\d?\d?)?)?)?)?([\+\-]\d\d:?\d\d)?)?/,I=[["HH:mm:ss.S",/(T| )\d\d:\d\d:\d\d\.\d{1,3}/],["HH:mm:ss",/(T| )\d\d:\d\d:\d\d/],["HH:mm",/(T| )\d\d:\d\d/],["HH",/(T| )\d\d/]],W=/([\+\-]|\d\d)/gi,z="Month Date Hours Minutes Seconds Milliseconds".split(" "),
A={Milliseconds:1,Seconds:1E3,Minutes:6E4,Hours:36E5,Days:864E5,Months:2592E6,Years:31536E6},B={},M="DDD w W M D d".split(" "),N="MDHhmswW".split(""),s={M:function(){return this.month()+1},MMM:function(c){return this.lang().monthsShort(this,c)},MMMM:function(c){return this.lang().months(this,c)},D:function(){return this.date()},DDD:function(){return this.dayOfYear()},d:function(){return this.day()},dd:function(c){return this.lang().weekdaysMin(this,c)},ddd:function(c){return this.lang().weekdaysShort(this,
c)},dddd:function(c){return this.lang().weekdays(this,c)},w:function(){return this.week()},W:function(){return this.isoWeek()},YY:function(){return o(this.year()%100,2)},YYYY:function(){return o(this.year(),4)},YYYYY:function(){return o(this.year(),5)},a:function(){return this.lang().meridiem(this.hours(),this.minutes(),!0)},A:function(){return this.lang().meridiem(this.hours(),this.minutes(),!1)},H:function(){return this.hours()},h:function(){return this.hours()%12||12},m:function(){return this.minutes()},
s:function(){return this.seconds()},S:function(){return~~(this.milliseconds()/100)},SS:function(){return o(~~(this.milliseconds()/10),2)},SSS:function(){return o(this.milliseconds(),3)},Z:function(){var c=-this.zone();return 0>c&&(c=-c),"+"+o(~~(c/60),2)+":"+o(~~c%60,2)},ZZ:function(){var c=-this.zone();return 0>c&&(c=-c),"+"+o(~~(10*c/6),4)},X:function(){return this.unix()}};M.length;)p=M.pop(),s[p+"o"]=e(s[p]);for(;N.length;)p=N.pop(),s[p+p]=a(s[p],2);s.DDDD=a(s.DDD,3);f.prototype={set:function(c){var a,
b;for(b in c)a=c[b],"function"==typeof a?this[b]=a:this["_"+b]=a},_months:"January February March April May June July August September October November December".split(" "),months:function(c){return this._months[c.month()]},_monthsShort:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),monthsShort:function(c){return this._monthsShort[c.month()]},monthsParse:function(c){var a,b,h;this._monthsParse||(this._monthsParse=[]);for(a=0;12>a;a++)if(this._monthsParse[a]||(b=g([2E3,a]),h="^"+this.months(b,
"")+"|^"+this.monthsShort(b,""),this._monthsParse[a]=RegExp(h.replace(".",""),"i")),this._monthsParse[a].test(c))return a},_weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),weekdays:function(c){return this._weekdays[c.day()]},_weekdaysShort:"Sun Mon Tue Wed Thu Fri Sat".split(" "),weekdaysShort:function(c){return this._weekdaysShort[c.day()]},_weekdaysMin:"Su Mo Tu We Th Fr Sa".split(" "),weekdaysMin:function(c){return this._weekdaysMin[c.day()]},_longDateFormat:{LT:"h:mm A",
L:"MM/DD/YYYY",LL:"MMMM D YYYY",LLL:"MMMM D YYYY LT",LLLL:"dddd, MMMM D YYYY LT"},longDateFormat:function(c){var a=this._longDateFormat[c];return!a&&this._longDateFormat[c.toUpperCase()]&&(a=this._longDateFormat[c.toUpperCase()].replace(/MMMM|MM|DD|dddd/g,function(c){return c.slice(1)}),this._longDateFormat[c]=a),a},meridiem:function(c,a,b){return 11<c?b?"pm":"PM":b?"am":"AM"},_calendar:{sameDay:"[Today at] LT",nextDay:"[Tomorrow at] LT",nextWeek:"dddd [at] LT",lastDay:"[Yesterday at] LT",lastWeek:"[last] dddd [at] LT",
sameElse:"L"},calendar:function(c,a){var b=this._calendar[c];return"function"==typeof b?b.apply(a):b},_relativeTime:{future:"in %s",past:"%s ago",s:"a few seconds",m:"a minute",mm:"%d minutes",h:"an hour",hh:"%d hours",d:"a day",dd:"%d days",M:"a month",MM:"%d months",y:"a year",yy:"%d years"},relativeTime:function(c,a,b,g){var h=this._relativeTime[b];return"function"==typeof h?h(c,a,b,g):h.replace(/%d/i,c)},pastFuture:function(c,a){var b=this._relativeTime[0<c?"future":"past"];return"function"==
typeof b?b(a):b.replace(/%s/i,a)},ordinal:function(c){return this._ordinal.replace("%d",c)},_ordinal:"%d",preparse:function(c){return c},postformat:function(c){return c},week:function(c){return G(c,this._week.dow,this._week.doy)},_week:{dow:0,doy:6}};g=function(c,a,b){return H({_i:c,_f:a,_l:b,_isUTC:!1})};g.utc=function(c,a,b){return H({_useUTC:!0,_isUTC:!0,_l:b,_i:c,_f:a})};g.unix=function(c){return g(1E3*c)};g.duration=function(c,a){var b=g.isDuration(c),e="number"==typeof c,i=b?c._data:e?{}:c,
f;return e&&(a?i[a]=c:i.milliseconds=c),f=new h(i),b&&c.hasOwnProperty("_lang")&&(f._lang=c._lang),f};g.version="2.0.0";g.defaultFormat="YYYY-MM-DDTHH:mm:ssZ";g.lang=function(c,a){if(!c)return g.fn._lang._abbr;a?(a.abbr=c,w[c]||(w[c]=new f),w[c].set(a)):w[c]||r(c);g.duration.fn._lang=g.fn._lang=r(c)};g.langData=function(c){return c&&c._lang&&c._lang._abbr&&(c=c._lang._abbr),r(c)};g.isMoment=function(c){return c instanceof k};g.isDuration=function(c){return c instanceof h};g.fn=k.prototype={clone:function(){return g(this)},
valueOf:function(){return+this._d},unix:function(){return Math.floor(+this._d/1E3)},toString:function(){return this.format("ddd MMM DD YYYY HH:mm:ss [GMT]ZZ")},toDate:function(){return this._d},toJSON:function(){return g.utc(this).format("YYYY-MM-DD[T]HH:mm:ss.SSS[Z]")},toArray:function(){return[this.year(),this.month(),this.date(),this.hours(),this.minutes(),this.seconds(),this.milliseconds()]},isValid:function(){return null==this._isValid&&(this._a?this._isValid=!n(this._a,(this._isUTC?g.utc(this._a):
g(this._a)).toArray()):this._isValid=!isNaN(this._d.getTime())),!!this._isValid},utc:function(){return this._isUTC=!0,this},local:function(){return this._isUTC=!1,this},format:function(c){for(var a=this,c=c||g.defaultFormat,b=function(c){return a.lang().longDateFormat(c)||c},h=5;h--&&L.test(c);)c=c.replace(L,b);if(!B[c]){var i=b=c,e=i.match(F),f,k;f=0;for(k=e.length;f<k;f++)s[e[f]]?e[f]=s[e[f]]:e[f]=e[f].match(/\[.*\]/)?e[f].replace(/^\[|\]$/g,""):e[f].replace(/\\/g,"");B[b]=function(c){var a="";
for(f=0;f<k;f++)a+="function"==typeof e[f].call?e[f].call(c,i):e[f];return a}}c=B[c](a);return this.lang().postformat(c)},add:function(c,a){var b;return"string"==typeof c?b=g.duration(+a,c):b=g.duration(c,a),t(this,b,1),this},subtract:function(c,a){var b;return"string"==typeof c?b=g.duration(+a,c):b=g.duration(c,a),t(this,b,-1),this},diff:function(c,a,b){var c=this._isUTC?g(c).utc():g(c).local(),h=6E4*(this.zone()-c.zone()),e,f;return a&&(a=a.replace(/s$/,"")),"year"===a||"month"===a?(e=432E5*(this.daysInMonth()+
c.daysInMonth()),f=12*(this.year()-c.year())+(this.month()-c.month()),f+=(this-g(this).startOf("month")-(c-g(c).startOf("month")))/e,"year"===a&&(f/=12)):(e=this-c-h,f="second"===a?e/1E3:"minute"===a?e/6E4:"hour"===a?e/36E5:"day"===a?e/864E5:"week"===a?e/6048E5:e),b?f:m(f)},from:function(a,b){return g.duration(this.diff(a)).lang(this.lang()._abbr).humanize(!b)},fromNow:function(a){return this.from(g(),a)},calendar:function(){var a=this.diff(g().startOf("day"),"days",!0);return this.format(this.lang().calendar(-6>
a?"sameElse":-1>a?"lastWeek":0>a?"lastDay":1>a?"sameDay":2>a?"nextDay":7>a?"nextWeek":"sameElse",this))},isLeapYear:function(){var a=this.year();return 0===a%4&&0!==a%100||0===a%400},isDST:function(){return this.zone()<g([this.year()]).zone()||this.zone()<g([this.year(),5]).zone()},day:function(a){var b=this._isUTC?this._d.getUTCDay():this._d.getDay();return null==a?b:this.add({d:a-b})},startOf:function(a){a=a.replace(/s$/,"");switch(a){case "year":this.month(0);case "month":this.date(1);case "week":case "day":this.hours(0);
case "hour":this.minutes(0);case "minute":this.seconds(0);case "second":this.milliseconds(0)}return"week"===a&&this.day(0),this},endOf:function(a){return this.startOf(a).add(a.replace(/s?$/,"s"),1).subtract("ms",1)},isAfter:function(a,b){return b="undefined"!=typeof b?b:"millisecond",+this.clone().startOf(b)>+g(a).startOf(b)},isBefore:function(a,b){return b="undefined"!=typeof b?b:"millisecond",+this.clone().startOf(b)<+g(a).startOf(b)},isSame:function(a,b){return b="undefined"!=typeof b?b:"millisecond",
+this.clone().startOf(b)===+g(a).startOf(b)},zone:function(){return this._isUTC?0:this._d.getTimezoneOffset()},daysInMonth:function(){return g.utc([this.year(),this.month()+1,0]).date()},dayOfYear:function(a){var b=v((g(this).startOf("day")-g(this).startOf("year"))/864E5)+1;return null==a?b:this.add("d",a-b)},isoWeek:function(a){var b=G(this,1,4);return null==a?b:this.add("d",7*(a-b))},week:function(a){var b=this.lang().week(this);return null==a?b:this.add("d",7*(a-b))},lang:function(a){return a===
b?this._lang:(this._lang=r(a),this)}};for(p=0;p<z.length;p++)J(z[p].toLowerCase().replace(/s$/,""),z[p]);J("year","FullYear");g.fn.days=g.fn.day;g.fn.weeks=g.fn.week;g.fn.isoWeeks=g.fn.isoWeek;g.duration.fn=h.prototype={weeks:function(){return m(this.days()/7)},valueOf:function(){return this._milliseconds+864E5*this._days+2592E6*this._months},humanize:function(a){var b=+this,e;e=!a;var h=this.lang(),g=v(Math.abs(b)/1E3),f=v(g/60),k=v(f/60),l=v(k/24),m=v(l/365),g=45>g&&["s",g]||1===f&&["m"]||45>f&&
["mm",f]||1===k&&["h"]||22>k&&["hh",k]||1===l&&["d"]||25>=l&&["dd",l]||45>=l&&["M"]||345>l&&["MM",v(l/30)]||1===m&&["y"]||["yy",m];e=(g[2]=e,g[3]=0<b,g[4]=h,X.apply({},g));return a&&(e=this.lang().pastFuture(b,e)),this.lang().postformat(e)},lang:g.fn.lang};for(p in A)A.hasOwnProperty(p)&&(K(p,A[p]),aa(p.toLowerCase()));K("Weeks",6048E5);g.lang("en",{ordinal:function(a){var b=a%10;return a+(1===~~(a%100/10)?"th":1===b?"st":2===b?"nd":3===b?"rd":"th")}});C&&(module.exports=g);"undefined"==typeof ender&&
(this.moment=g);"function"==typeof define&&define.amd&&define("moment",[],function(){return g})}).call(this);registerNS("com.cerner.oncology.clinical.trials");com.cerner.oncology.clinical.trials.wasLoaded=!1;
com.cerner.oncology.clinical.trials.call=function(b,a,e){var f;com.cerner.oncology.clinical.trials.wasLoaded||((f=MP_Util.CreateTimer("CAP:2012.1.00123.2"))&&f.Stop(),com.cerner.oncology.clinical.trials.wasLoaded=!0);return function(f){var h,l;h=CERN_BrowserDevInd?new XMLHttpRequest:new XMLCclRequest;h.onreadystatechange=function(){var l,o,t,n,r;n="script: "+b+"\n";n=n+"inputs: "+f+"\n";if(4===h.readyState)if(200===h.status){l=!0;try{t=$.parseJSON(h.responseText);r=null;for(o in t)if(t[o].STATUS_DATA){r=
t[o].STATUS_DATA;break}r&&r.STATUS&&(e?e(r):/[fp]/i.test(r.STATUS)&&(n="CCL failure or partial status returned.\n"+n,n+=JSON.stringify(r),alert(n),l=!1));l&&a(t)}catch(x){n="error parsing reply.\nmessage: "+x.message+"\n"+n,n=n+"response text: "+h.responseText,alert(n)}}else n="ajax status non-success: "+h.status+"\n"+n,n=n+"status text: "+h.statusText,alert(n)};CERN_BrowserDevInd?(l=b+"?parameters="+f,h.open("GET",l),h.send(null)):(h.open("GET",b),h.send(f))}};registerNS("com.cerner.oncology.clinical.trials");
$.extend(com.cerner.oncology.clinical.trials,{therapeuticInd:0,clinTrialsComponentConfig:null,getDate:function(b){var a;a="";b=/\/Date\((.+)\)\//.exec(b);/^(0|(21))/.test(b[1])||(d=moment(b[1]),a=d.format(MPAGE_LOCALE.fulldate4yr.toUpperCase()));return a},setTableScrolling:function(){var b,a,e;b=$("#id-7FE8F7-6");this.clinTrialsComponentConfig&&(this.clinTrialsComponentConfig.SCROLL_ENABLED&&this.clinTrialsComponentConfig.SCROLL_NUM)&&($(b).addClass("scrollable-7FE8F7"),a=this.clinTrialsComponentConfig.SCROLL_NUM,
e=$("#id-7FE8F7-5").children().length,e>a&&$(b).height(18*a))},addHover:function(b){return function(a){var e,f;$(a.target).closest("tr").attr("class","").addClass("hover-7FE8F7");$("p.popupData-7FE8F7").each(function(a,e){$(e).text("");switch(a){case 0:$(e).text(b.PRIMARY_MNEMONIC_AMENDMENT);break;case 1:$(e).text(b.STATUS);break;case 2:if(this.getDate(b.ON_STUDY_DT_TM)){var f=moment(b.ON_STUDY_DATE),f=f.format(MPAGE_LOCALE.fulldate4yr.toUpperCase());$(e).text(f)}break;case 3:this.getDate(b.OFF_TREATMENT_DT_TM)&&
(f=moment(b.OFF_TREATMENT_DATE),f=f.format(MPAGE_LOCALE.fulldate4yr.toUpperCase()),$(e).text(f));break;case 4:this.getDate(b.OFF_STUDY_DT_TM)&&(f=moment(b.OFF_STUDY_DATE),f=f.format(MPAGE_LOCALE.fulldate4yr.toUpperCase()),$(e).text(f));break;case 5:$(e).text(b.CONTACT_PERSON_NAME);break;case 6:$(e).text(b.CONTACT_ROLE_NAME);break;case 7:$(e).text(b.CONTACT_ORGANIZATION_NAME);break;case 8:b.CONTACT_PHONE_NUM&&$(e).text(i18n.oncology.clintrials.PHONE+": "+b.CONTACT_PHONE_NUM);break;case 9:b.CONTACT_PAGER_NUM&&
$(e).text(i18n.oncology.clintrials.PAGER+": "+b.CONTACT_PAGER_NUM);break;case 10:$(e).text(b.CONTACT_EMAIL_ADDR);break;case 11:$(e).text(b.PROT_TITLE)}}.bind(this));f=com.cerner.oncology.util.findLongestText($("p.popupData-7FE8F7"));f=350<f?350:f;$("td.popupDataCont-7FE8F7").width(f);e=$("#id-7FE8F7-2");$(e).width(30+f+$("td.popupLabelCont-7FE8F7").width());$(e).show();com.cerner.oncology.util.positionPopup(e,a)}.bind(this)},addTrial:function(b){var a,e,f,k,h,l,m,o;m="";a=$("#id-7FE8F7-5");o=com.cerner.oncology.util.createRow(4,
!1);$(a).append(o);$(o).addClass($(a).children().length%2?"odd":"even");h=$(o).attr("class");l=$(document.createElement("p")).addClass("overflow-7FE8F7 textPadding-7FE8F7");a=$(o).children();for(k=0;4>k;k++){f=a[k];$(f).addClass(k?"width20p-7FE8F7":"width40p-7FE8F7");e=$(l).clone();$(f).append(e);switch(k){case 0:m=b.PRIMARY_MNEMONIC;break;case 1:b.ON_STUDY_DATE&&(m=new Date,m=moment(b.ON_STUDY_DATE),m=m.format(MPAGE_LOCALE.fulldate4yr.toUpperCase()));break;case 2:m=b.STATUS;break;case 3:m=b.CONTACT_PERSON_NAME}$(e).text(m)}$(o).hover(this.addHover(b),
function(){$(this).attr("class",h);$("#id-7FE8F7-2").hide()})},retrieveTrials:function(){var b,a,e;e=function(a){var b;if(b=$("#id-7FE8F7-3").closest('div[class~="sec-content"]'))b=$(b).prev().find('span[class~="sec-total"]'),$(b).text(a),$(b).removeClass("hidden")};a=function(a){var b,h,l,a=a.DATA.TRIALS;if(a.length){a.sort(function(a,b){var e,f;e=moment(this.getDate(a.ON_STUDY_DT_TM));f=moment(this.getDate(b.ON_STUDY_DT_TM));return e<f?1:e>f?-1:0}.bind(this));h=0;for(l=a.length;h<l;h++)b=a[h],this.addTrial(b);
this.setTableScrolling()}else h=$("#id-7FE8F7-5"),b=com.cerner.oncology.util.createRow(4,!1),$(h).append(b),h=$(document.createElement("p")).addClass("res-none"),$(b).children(":first").append(h),$(h).text(i18n.NO_RESULTS_FOUND);e("("+a.length+")")}.bind(this);"undefined"!==typeof m_criterionJSON?(b=JSON.parse(m_criterionJSON),b=b.CRITERION.PERSON_ID):b="$PAT_PersonId$";b="^MINE^,"+b+","+this.therapeuticInd;e(i18n.LOADING_DATA+"...");this.call("onc_mp_clin_trials",a)(b)},movePopupTable:function(){var b=
$("#id-7FE8F7-2");$(b).remove();$(document.body).append(b)},setPopupWidth:function(){var b;b=com.cerner.oncology.util.findLongestText($(".popupLabel-7FE8F7"));$("td.popupLabelCont-7FE8F7").width(b+15);this.movePopupTable();this.retrieveTrials()},localize:function(){$("#id-7FE8F7-7").text(i18n.oncology.clintrials.ON_STUDY);$("#id-7FE8F7-8").text(i18n.STATUS);$("#id-7FE8F7-9").text(i18n.oncology.clintrials.CONTACT);$("#id-7FE8F7-10").text(i18n.oncology.clintrials.PROTOCOL+":");$("#id-7FE8F7-11").text(i18n.STATUS+
":");$("#id-7FE8F7-12").text(i18n.oncology.clintrials.ON_STUDY+":");$("#id-7FE8F7-13").text(i18n.oncology.clintrials.OFF_TREATMENT+":");$("#id-7FE8F7-14").text(i18n.oncology.clintrials.OFF_STUDY+":");$("#id-7FE8F7-15").text(i18n.oncology.clintrials.CONTACT+":");$("#id-7FE8F7-16").text(i18n.oncology.clintrials.TRIAL_NAME+":");this.setPopupWidth()}});function ClinicalTrialsComponentStyle(){this.initByNamespace("ct")}ClinicalTrialsComponentStyle.inherits(ComponentStyle);
function ClinicalTrialsComponent(b){this.therapeuticInd=0;this.setTherapeuticInd=function(a){this.therapeuticInd=+a};this.setStyles(new ClinicalTrialsComponentStyle);this.setCriterion(b);this.setAlwaysExpanded(!1);this.InsertData=function(){MP_Util.Doc.FinalizeComponent(this.getHTML(),this,"");com.cerner.oncology.clinical.trials.therapeuticInd=this.therapeuticInd;com.cerner.oncology.clinical.trials.clinTrialsComponentConfig={SCROLL_ENABLED:this.isScrollingEnabled(),SCROLL_NUM:this.getScrollNumber()};
com.cerner.oncology.clinical.trials.localize()};this.HandleSuccess=function(){};this.getHTML=function(){var a=[];a.push('<div id="id-7FE8F7-3">');a.push('<table id="id-7FE8F7-1" summary="clinical trials header table">');a.push("<thead>");a.push('<tr class="content-hdr">');a.push('<th class="width40p-7FE8F7 th-7FE8F7"></th>');a.push('<th class="width20p-7FE8F7 th-7FE8F7"><p id="id-7FE8F7-7" class="textPadding-7FE8F7"></p></th>');a.push('<th class="width20p-7FE8F7 th-7FE8F7"><p id="id-7FE8F7-8" class="textPadding-7FE8F7"></p></th>');
a.push('<th class="width20p-7FE8F7 th-7FE8F7"><p id="id-7FE8F7-9" class="textPadding-7FE8F7"></p></th>');a.push("</tr>");a.push("</thead>");a.push("<tbody>");a.push("<tr>");a.push('<td colspan="4">');a.push('<div id="id-7FE8F7-6">');a.push('<table summary="clinical trials data table">');a.push('<tbody id="id-7FE8F7-5">');a.push("</tbody>");a.push("</table>");a.push("</div>");a.push("</td>");a.push("</tr>");a.push("</tbody>");a.push("</table>");a.push('<div id="id-7FE8F7-2" style="display: none;">');
a.push('<table summary="clinical trials popup table">');a.push("<tbody>");a.push("<tr>");a.push('<td class="alignRight-7FE8F7 popupLabelCont-7FE8F7"><p id="id-7FE8F7-10" class="popupLabel-7FE8F7 textPadding-7FE8F7"></p></td>');a.push('<td class="popupDataCont-7FE8F7"><p class="popupData-7FE8F7 textPadding-7FE8F7"></p></td>');a.push("</tr>");a.push("<tr>");a.push('<td class="alignRight-7FE8F7 popupLabelCont-7FE8F7"><p id="id-7FE8F7-11" class="popupLabel-7FE8F7 textPadding-7FE8F7"></p></td>');a.push('<td class="popupDataCont-7FE8F7"><p class="popupData-7FE8F7 textPadding-7FE8F7"></p></td>');
a.push("</tr>");a.push("<tr>");a.push('<td class="alignRight-7FE8F7 popupLabelCont-7FE8F7"><p id="id-7FE8F7-12" class="popupLabel-7FE8F7 textPadding-7FE8F7"></p></td>');a.push('<td class="popupDataCont-7FE8F7"><p class="popupData-7FE8F7 textPadding-7FE8F7"></p></td>');a.push("</tr>");a.push("<tr>");a.push('<td class="alignRight-7FE8F7 popupLabelCont-7FE8F7"><p id="id-7FE8F7-13" class="popupLabel-7FE8F7 textPadding-7FE8F7"></p></td>');a.push('<td class="popupDataCont-7FE8F7"><p class="popupData-7FE8F7 textPadding-7FE8F7"></p></td>');
a.push("</tr>");a.push("<tr>");a.push('<td class="alignRight-7FE8F7 popupLabelCont-7FE8F7"><p id="id-7FE8F7-14" class="popupLabel-7FE8F7 textPadding-7FE8F7"></p></td>');a.push('<td class="popupDataCont-7FE8F7"><p class="popupData-7FE8F7 textPadding-7FE8F7"></p></td>');a.push("</tr>");a.push("<tr>");a.push('<td class="alignRight-7FE8F7 popupLabelCont-7FE8F7"><p id="id-7FE8F7-15" class="popupLabel-7FE8F7 textPadding-7FE8F7"></p></td>');a.push('<td class="popupDataCont-7FE8F7"><p class="popupData-7FE8F7 textPadding-7FE8F7"></p></td>');
a.push("</tr>");a.push("<tr>");a.push('<td class="alignRight-7FE8F7 popupLabelCont-7FE8F7"><p class="popupLabel-7FE8F7 textPadding-7FE8F7"></p></td>');a.push('<td class="popupDataCont-7FE8F7"><p class="popupData-7FE8F7 textPadding-7FE8F7"></p></td>');a.push("</tr>");a.push("<tr>");a.push('<td class="alignRight-7FE8F7 popupLabelCont-7FE8F7"><p class="popupLabel-7FE8F7 textPadding-7FE8F7"></p></td>');a.push('<td class="popupDataCont-7FE8F7"><p class="popupData-7FE8F7 textPadding-7FE8F7"></p></td>');
a.push("</tr>");a.push("<tr>");a.push('<td class="alignRight-7FE8F7 popupLabelCont-7FE8F7"><p class="popupLabel-7FE8F7 textPadding-7FE8F7"></p></td>');a.push('<td class="popupDataCont-7FE8F7"><p class="popupData-7FE8F7 textPadding-7FE8F7"></p></td>');a.push("</tr>");a.push("<tr>");a.push('<td class="alignRight-7FE8F7 popupLabelCont-7FE8F7"><p class="popupLabel-7FE8F7 textPadding-7FE8F7"></p></td>');a.push('<td class="popupDataCont-7FE8F7"><p class="popupData-7FE8F7 textPadding-7FE8F7"></p></td>');
a.push("</tr>");a.push("<tr>");a.push('<td class="alignRight-7FE8F7 popupLabelCont-7FE8F7"><p class="popupLabel-7FE8F7 textPadding-7FE8F7"></p></td>');a.push('<td class="popupDataCont-7FE8F7"><p class="popupData-7FE8F7 textPadding-7FE8F7"></p></td>');a.push("</tr>");a.push("<tr>");a.push('<td class="alignRight-7FE8F7 popupLabelCont-7FE8F7"><p id="id-7FE8F7-16" class="popupLabel-7FE8F7 textPadding-7FE8F7"></p></td>');a.push('<td class="popupDataCont-7FE8F7"><p class="popupData-7FE8F7 textPadding-7FE8F7"></p></td>');
a.push("</tr>");a.push("</tbody>");a.push("</table>");a.push("</div>");a.push("</div>");return a.join("")}}ClinicalTrialsComponent.inherits(MPageComponent);