function CurStatusComponentO1Style(){this.initByNamespace("curstat");
}CurStatusComponentO1Style.inherits(ComponentStyle);
function CurStatusComponentO1(criterion){this.setCriterion(criterion);
this.setStyles(new CurStatusComponentO1Style());
this.setComponentLoadTimerName("USR:MPG.RehabCurrentStatus.O1 - load component");
this.setComponentRenderTimerName("ENG:MPG.RehabCurrentStatus.O1 - render component");
this.setIncludeLineNumber(true);
CurStatusComponentO1.method("InsertData",function(){CERN_CurrentStatusO1.GetCurrentStatusO1Table(this);
});
CurStatusComponentO1.method("HandleSuccess",function(recordData){CERN_CurrentStatusO1.RenderComponent(this,recordData);
});
CurStatusComponentO1.method("setAssessmentEventSets",function(value){this.m_assessmentEventSets=value;
});
CurStatusComponentO1.method("getAssessmentEventSets",function(){return this.m_assessmentEventSets;
});
CurStatusComponentO1.method("setVitalMeasureEventSets",function(value){this.m_vitalMeasureEventSets=value;
});
CurStatusComponentO1.method("getVitalMeasureEventSets",function(){return this.m_vitalMeasureEventSets;
});
CurStatusComponentO1.method("setBowelBladderEventSets",function(value){this.m_bowelBladderEventSets=value;
});
CurStatusComponentO1.method("getBowelBladderEventSets",function(){return this.m_bowelBladderEventSets;
});
CurStatusComponentO1.method("setSkinAssessTolEventSets",function(value){this.m_skinAssessTolEventSets=value;
});
CurStatusComponentO1.method("getSkinAssessTolEventSets",function(){return this.m_skinAssessTolEventSets;
});
CurStatusComponentO1.method("setOrthonticsShedEventSets",function(value){this.m_orthonticsShedEventSets=value;
});
CurStatusComponentO1.method("getOrthonticsShedEventSets",function(){return this.m_orthonticsShedEventSets;
});
CurStatusComponentO1.method("setADLEventSets",function(value){this.m_adlEventSets=value;
});
CurStatusComponentO1.method("getADLEventSets",function(){return this.m_adlEventSets;
});
CurStatusComponentO1.method("setIADLEventSets",function(value){this.m_iadlEventSets=value;
});
CurStatusComponentO1.method("getIADLEventSets",function(){return this.m_iadlEventSets;
});
CurStatusComponentO1.method("setCogCommunicateEventSets",function(value){this.m_cogCommunicateEventSets=value;
});
CurStatusComponentO1.method("getCogCommunicateEventSets",function(){return this.m_cogCommunicateEventSets;
});
CurStatusComponentO1.method("openTab",function(){var criterion=this.getCriterion();
var paramString=criterion.person_id+"|"+criterion.encntr_id+"|"+0+"|0|0";
javascript:MPAGES_EVENT("POWERFORM",paramString);
MP_Util.LogMpagesEventInfo(this,"POWERFORM",paramString,"current_status.js","openTab");
});
CurStatusComponentO1.method("openDropDown",function(formID){var criterion=this.getCriterion();
var paramString=criterion.person_id+"|"+criterion.encntr_id+"|"+formID+"|0|0";
javascript:MPAGES_EVENT("POWERFORM",paramString);
MP_Util.LogMpagesEventInfo(this,"POWERFORM",paramString,"current_status.js","openDropDown");
});
}CurStatusComponentO1.inherits(MPageComponent);
var CERN_CurrentStatusO1=function(){return{GetCurrentStatusO1Table:function(component){var sendAr=[];
var criterion=component.getCriterion();
var cusrstO1_lookbackUnits=0;
var cusrstO1_lookbackType=0;
cusrstO1_encntr=(component.getScope()==1)?"0.0":(criterion.encntr_id+".0");
cusrstO1_lookbackUnits=(component.getLookbackUnits()!=null)?component.getLookbackUnits():"0";
cusrstO1_lookbackType=(component.getLookbackUnitTypeFlag()!=null)?component.getLookbackUnitTypeFlag():"-1";
sendAr.push("^MINE^",criterion.person_id+".0",cusrstO1_encntr,cusrstO1_lookbackUnits,cusrstO1_lookbackType);
sendAr.push((component.getAssessmentEventSets()!=null)?"value("+component.getAssessmentEventSets().join(",")+")":"0.0");
sendAr.push((component.getVitalMeasureEventSets()!=null)?"value("+component.getVitalMeasureEventSets().join(",")+")":"0.0");
sendAr.push((component.getBowelBladderEventSets()!=null)?"value("+component.getBowelBladderEventSets().join(",")+")":"0.0");
sendAr.push((component.getSkinAssessTolEventSets()!=null)?"value("+component.getSkinAssessTolEventSets().join(",")+")":"0.0");
sendAr.push((component.getOrthonticsShedEventSets()!=null)?"value("+component.getOrthonticsShedEventSets().join(",")+")":"0.0");
sendAr.push((component.getADLEventSets()!=null)?"value("+component.getADLEventSets().join(",")+")":"0.0");
sendAr.push((component.getIADLEventSets()!=null)?"value("+component.getIADLEventSets().join(",")+")":"0.0");
sendAr.push((component.getCogCommunicateEventSets()!=null)?"value("+component.getCogCommunicateEventSets().join(",")+")":"0.0");
MP_Core.XMLCclRequestWrapper(component,"mp_reh_get_current_status",sendAr,true);
},GraphResults:function(personId,encntrId,eventCd,staticContent,lookBackUnits,lookBackType){var wParams="left=0,top=0,width=1200,height=700,toolbar=no";
encntrId="value("+encntrId+")";
var sParams="^MINE^,"+personId+","+unescape(encntrId)+","+eventCd+",^"+unescape(staticContent)+"\\discrete-graphing^,"+lookBackUnits+","+lookBackType;
var graphCall="javascript:CCLLINK('mp_reh_current_status_graph', '"+sParams+"',1)";
javascript:CCLNEWSESSIONWINDOW(graphCall,"_self",wParams,0,1);
Util.preventDefault();
},RenderComponent:function(component,recordData){try{var jsCURSTO1HTML=[];
var m_rootComponentNode=null;
m_rootComponentNode=component.getRootComponentNode();
var criterion=component.getCriterion();
var lookBackUnits=(component.getLookbackUnits()!=null)?component.getLookbackUnits():"365";
var lookBackType=(component.getLookbackUnitTypeFlag()!=null)?component.getLookbackUnitTypeFlag():"0";
var staticContent='"'+escape(criterion.static_content)+'"';
var prsnlInfo=criterion.getPersonnelInfo();
var encntrs=prsnlInfo.getViewableEncounters();
var encntrVal=(component.getScope()==1)?'"'+escape(encntrs)+'"':criterion.encntr_id;
var patResult="";
var assessmentContent=[];
var vitalContent=[];
var bowelContent=[];
var skinAssessmentContent=[];
var orthoticsContent=[];
var adlContent=[];
var iadlContent=[];
var cognitionContent=[];
var endDate="";
var dateTime=new Date();
totInterv=0;
var numberOfSections=8;
var numberOfRows=0;
jsCURSTO1HTML.push("<div class='",MP_Util.GetContentClass(component,component.getScrollNumber()),"'>");
for(var i=0;
i<recordData.TYPE_CNT;
i++){switch(recordData.TYPES[i].SECTION_IND){case 0:assessmentContent.push("<div id='assessmentStatus'>");
for(var j=0;
j<recordData.TYPES[i].CNT;
j++){if(recordData.TYPES[i].QUAL[j].NUMERICAL_RESULT_IND==1){assessmentContent.push("<dl class='cursts-info' id='cursts'><dt class='cursts-dt'>","<a class='lr-link' onClick='CERN_CurrentStatusO1.GraphResults(",criterion.person_id,",",encntrVal,",",recordData.TYPES[i].QUAL[j].EVENTCD,",",staticContent,",",lookBackUnits,",",lookBackType,");'>",recordData.TYPES[i].QUAL[j].TITLE,"</a>");
}else{assessmentContent.push("<dl class='cursts-info' id='cursts'><dt class='cursts-dt'>",recordData.TYPES[i].QUAL[j].TITLE);
}assessmentContent.push("</dt><dd class='cursts-info-dd'>",recordData.TYPES[i].QUAL[j].RESULT,"</dd>");
assessmentContent.push("<dd class='cursts-ico-dd'>",recordData.TYPES[i].QUAL[j].DATE,"</dd></dl>");
}assessmentContent.push("</div>");
assessmentContent=assessmentContent.join("");
break;
case 1:vitalContent.push("<div id='vitalStatus'>");
for(var j=0;
j<recordData.TYPES[i].CNT;
j++){if(recordData.TYPES[i].QUAL[j].NUMERICAL_RESULT_IND==1){vitalContent.push("<dl class='cursts-info' id='cursts'><dt class='cursts-dt'>","<a class='lr-link' onClick='CERN_CurrentStatusO1.GraphResults(",criterion.person_id,",",encntrVal,",",recordData.TYPES[i].QUAL[j].EVENTCD,",",staticContent,",",lookBackUnits,",",lookBackType,");'>",recordData.TYPES[i].QUAL[j].TITLE,"</a>");
}else{vitalContent.push("<dl class='cursts-info' id='cursts'><dt class='cursts-dt'>",recordData.TYPES[i].QUAL[j].TITLE);
}vitalContent.push("</dt><dd class='cursts-info-dd'>",recordData.TYPES[i].QUAL[j].RESULT,"</dd>");
vitalContent.push("<dd class='cursts-ico-dd'>",recordData.TYPES[i].QUAL[j].DATE,"</dd></dl>");
}vitalContent.push("</div>");
vitalContent=vitalContent.join("");
break;
case 2:bowelContent.push("<div id='bowelStatus'>");
for(var j=0;
j<recordData.TYPES[i].CNT;
j++){if(recordData.TYPES[i].QUAL[j].NUMERICAL_RESULT_IND==1){bowelContent.push("<dl class='cursts-info' id='cursts'><dt class='cursts-dt'>","<a class='lr-link' onClick='CERN_CurrentStatusO1.GraphResults(",criterion.person_id,",",encntrVal,",",recordData.TYPES[i].QUAL[j].EVENTCD,",",staticContent,",",lookBackUnits,",",lookBackType,");'>",recordData.TYPES[i].QUAL[j].TITLE,"</a>");
}else{bowelContent.push("<dl class='cursts-info' id='cursts'><dt class='cursts-dt'>",recordData.TYPES[i].QUAL[j].TITLE);
}bowelContent.push("</dt><dd class='cursts-info-dd'>",recordData.TYPES[i].QUAL[j].RESULT,"</dd>");
bowelContent.push("<dd class='cursts-ico-dd'>",recordData.TYPES[i].QUAL[j].DATE,"</dd></dl>");
}bowelContent.push("</div>");
bowelContent=bowelContent.join("");
break;
case 3:skinAssessmentContent.push("<div id='skinAssessmentStatus'>");
for(var j=0;
j<recordData.TYPES[i].CNT;
j++){if(recordData.TYPES[i].QUAL[j].NUMERICAL_RESULT_IND==1){skinAssessmentContent.push("<dl class='cursts-info' id='cursts'><dt class='cursts-dt'>","<a class='lr-link' onClick='CERN_CurrentStatusO1.GraphResults(",criterion.person_id,",",encntrVal,",",recordData.TYPES[i].QUAL[j].EVENTCD,",",staticContent,",",lookBackUnits,",",lookBackType,");'>",recordData.TYPES[i].QUAL[j].TITLE,"</a>");
}else{skinAssessmentContent.push("<dl class='cursts-info' id='cursts'><dt class='cursts-dt'>",recordData.TYPES[i].QUAL[j].TITLE);
}skinAssessmentContent.push("</dt><dd class='cursts-info-dd'>",recordData.TYPES[i].QUAL[j].RESULT,"</dd>");
skinAssessmentContent.push("<dd class='cursts-ico-dd'>",recordData.TYPES[i].QUAL[j].DATE,"</dd></dl>");
}skinAssessmentContent.push("</div>");
skinAssessmentContent=skinAssessmentContent.join("");
break;
case 4:orthoticsContent.push("<div id='orthoticsStatus'>");
for(var j=0;
j<recordData.TYPES[i].CNT;
j++){if(recordData.TYPES[i].QUAL[j].NUMERICAL_RESULT_IND==1){orthoticsContent.push("<dl class='cursts-info' id='cursts'><dt class='cursts-dt'>","<a class='lr-link' onClick='CERN_CurrentStatusO1.GraphResults(",criterion.person_id,",",encntrVal,",",recordData.TYPES[i].QUAL[j].EVENTCD,",",staticContent,",",lookBackUnits,",",lookBackType,");'>",recordData.TYPES[i].QUAL[j].TITLE,"</a>");
}else{orthoticsContent.push("<dl class='cursts-info' id='cursts'><dt class='cursts-dt'>",recordData.TYPES[i].QUAL[j].TITLE);
}orthoticsContent.push("</dt><dd class='cursts-info-dd'>",recordData.TYPES[i].QUAL[j].RESULT,"</dd>");
orthoticsContent.push("<dd class='cursts-ico-dd'>",recordData.TYPES[i].QUAL[j].DATE,"</dd></dl>");
}orthoticsContent.push("</div>");
orthoticsContent=orthoticsContent.join("");
break;
case 5:adlContent.push("<div id='adlStatus'>");
for(var j=0;
j<recordData.TYPES[i].CNT;
j++){if(recordData.TYPES[i].QUAL[j].NUMERICAL_RESULT_IND==1){adlContent.push("<dl class='cursts-info' id='cursts'><dt class='cursts-dt'>","<a class='lr-link' onClick='CERN_CurrentStatusO1.GraphResults(",criterion.person_id,",",encntrVal,",",recordData.TYPES[i].QUAL[j].EVENTCD,",",staticContent,",",lookBackUnits,",",lookBackType,");'>",recordData.TYPES[i].QUAL[j].TITLE,"</a>");
}else{adlContent.push("<dl class='cursts-info' id='cursts'><dt class='cursts-dt'>",recordData.TYPES[i].QUAL[j].TITLE);
}adlContent.push("</dt><dd class='cursts-info-dd'>",recordData.TYPES[i].QUAL[j].RESULT,"</dd>");
adlContent.push("<dd class='cursts-ico-dd'>",recordData.TYPES[i].QUAL[j].DATE,"</dd></dl>");
}adlContent.push("</div>");
adlContent=adlContent.join("");
break;
case 6:iadlContent.push("<div id='iadlStatus'>");
for(var j=0;
j<recordData.TYPES[i].CNT;
j++){if(recordData.TYPES[i].QUAL[j].NUMERICAL_RESULT_IND==1){iadlContent.push("<dl class='cursts-info' id='cursts'><dt class='cursts-dt'>","<a class='lr-link' onClick='CERN_CurrentStatusO1.GraphResults(",criterion.person_id,",",encntrVal,",",recordData.TYPES[i].QUAL[j].EVENTCD,",",staticContent,",",lookBackUnits,",",lookBackType,");'>",recordData.TYPES[i].QUAL[j].TITLE,"</a>");
}else{iadlContent.push("<dl class='cursts-info' id='cursts'><dt class='cursts-dt'>",recordData.TYPES[i].QUAL[j].TITLE);
}iadlContent.push("</dt><dd class='cursts-info-dd'>",recordData.TYPES[i].QUAL[j].RESULT,"</dd>");
iadlContent.push("<dd class='cursts-ico-dd'>",recordData.TYPES[i].QUAL[j].DATE,"</dd></dl>");
}iadlContent.push("</div>");
iadlContent=iadlContent.join("");
break;
case 7:cognitionContent.push("<div id='cognitionStatus'>");
for(var j=0;
j<recordData.TYPES[i].CNT;
j++){if(recordData.TYPES[i].QUAL[j].NUMERICAL_RESULT_IND==1){cognitionContent.push("<dl class='cursts-info' id='cursts'><dt class='cursts-dt'>","<a class='lr-link' onClick='CERN_CurrentStatusO1.GraphResults(",criterion.person_id,",",encntrVal,",",recordData.TYPES[i].QUAL[j].EVENTCD,",",staticContent,",",lookBackUnits,",",lookBackType,");'>",recordData.TYPES[i].QUAL[j].TITLE,"</a>");
}else{cognitionContent.push("<dl class='cursts-info' id='cursts'><dt class='cursts-dt'>",recordData.TYPES[i].QUAL[j].TITLE);
}cognitionContent.push("</dt><dd class='cursts-info-dd'>",recordData.TYPES[i].QUAL[j].RESULT,"</dd>");
cognitionContent.push("<dd class='cursts-ico-dd'>",recordData.TYPES[i].QUAL[j].DATE,"</dd></dl>");
}cognitionContent.push("</div>");
cognitionContent=cognitionContent.join("");
break;
}}jsCURSTO1HTML.push("<div class='sub-sec'><h3 class='sub-sec-hd'><span class='sub-sec-hd-tgl' title='",patResult,"'>-</span>","<span class='sub-sec-title' id='assessment'>Assessments</span></h3><div class='content-body'><div class='sub-sec-content' id='assessment'><h3 class='cursts-info-hd'><span>patResult</span></h3>");
jsCURSTO1HTML.push(assessmentContent);
jsCURSTO1HTML.push("</div></div></div>");
jsCURSTO1HTML.push("<div class='sub-sec'><h3 class='sub-sec-hd'><span class='sub-sec-hd-tgl' title='",patResult,"'>-</span>","<span class='sub-sec-title' id='vital'>Vital Signs/Measurements</span></h3><div class='content-body'><div class='sub-sec-content' id='vital'><h3 class='cursts-info-hd'><span>patResult</span></h3>");
jsCURSTO1HTML.push(vitalContent);
jsCURSTO1HTML.push("</div></div></div>");
jsCURSTO1HTML.push("<div class='sub-sec'><h3 class='sub-sec-hd'><span class='sub-sec-hd-tgl' title='",patResult,"'>-</span>","<span class='sub-sec-title' id='bowel'>Bowel/Bladder</span></h3><div class='content-body'><div class='sub-sec-content' id='bowel'><h3 class='cursts-info-hd'><span>patResult</span></h3>");
jsCURSTO1HTML.push(bowelContent);
jsCURSTO1HTML.push("</div></div></div>");
jsCURSTO1HTML.push("<div class='sub-sec'><h3 class='sub-sec-hd'><span class='sub-sec-hd-tgl' title='",patResult,"'>-</span>","<span class='sub-sec-title' id='skinAssessment'>Skin Assessment/Tolerance</span></h3><div class='content-body'><div class='sub-sec-content' id='skinAssessment'><h3 class='cursts-info-hd'><span>patResult</span></h3>");
jsCURSTO1HTML.push(skinAssessmentContent);
jsCURSTO1HTML.push("</div></div></div>");
jsCURSTO1HTML.push("<div class='sub-sec'><h3 class='sub-sec-hd'><span class='sub-sec-hd-tgl' title='",patResult,"'>-</span>","<span class='sub-sec-title' id='orthotics'>Orthotics Schedule</span></h3><div class='content-body'><div class='sub-sec-content' id='orthotics'><h3 class='cursts-info-hd'><span>patResult</span></h3>");
jsCURSTO1HTML.push(orthoticsContent);
jsCURSTO1HTML.push("</div></div></div>");
jsCURSTO1HTML.push("<div class='sub-sec'><h3 class='sub-sec-hd'><span class='sub-sec-hd-tgl' title='",patResult,"'>-</span>","<span class='sub-sec-title' id='iadl'>ADL</span></h3><div class='content-body'><div class='sub-sec-content' id='adl'><h3 class='cursts-info-hd'><span>patResult</span></h3>");
jsCURSTO1HTML.push(adlContent);
jsCURSTO1HTML.push("</div></div></div>");
jsCURSTO1HTML.push("<div class='sub-sec'><h3 class='sub-sec-hd'><span class='sub-sec-hd-tgl' title='",patResult,"'>-</span>","<span class='sub-sec-title' id='adl'>IADL</span></h3><div class='content-body'><div class='sub-sec-content' id='iadl'><h3 class='cursts-info-hd'><span>patResult</span></h3>");
jsCURSTO1HTML.push(iadlContent);
jsCURSTO1HTML.push("</div></div></div>");
jsCURSTO1HTML.push("<div class='sub-sec'><h3 class='sub-sec-hd'><span class='sub-sec-hd-tgl' title='",patResult,"'>-</span>","<span class='sub-sec-title' id='cognition'>Cognition/Communication</span></h3><div class='content-body'><div class='sub-sec-content' id='cognition'><h3 class='cursts-info-hd'><span>patResult</span></h3>");
jsCURSTO1HTML.push(cognitionContent);
jsCURSTO1HTML.push("</div></div></div>");
jsCURSTO1HTML=jsCURSTO1HTML.join("");
MP_Util.Doc.FinalizeComponent(jsCURSTO1HTML,component,"");
}catch(err){throw (err);
}finally{}}};
}();
