var HcmReferral=HcmReferral||{};
HcmReferral.recentlyReferredTable=function(component,people){this.people=people;
this.component=component;
this.table=function(){var table=new ComponentTable(),component=this.component,patientInfoInd=component.getEditPatientInfoInd(),addEditInd=component.getAddEditInd(),namespace=component.namespace,customClass=(patientInfoInd&&addEditInd)?namespace+"-width-five-column":namespace+"-width-four-column";
table.setNamespace(namespace);
table.addColumn(createColumn("name",customClass,HcmReferral.i18n.PERSON,"${CHART_LINK} <br> ${DEMOGRAPHICS}"));
table.addColumn(createColumn("case-type",customClass,HcmReferral.i18n.CASE_TYPE_TABLE_HEADER,"${CASE_TYPE_DISP}"));
table.addColumn(createColumn("referral-reason",customClass,HcmReferral.i18n.REFERRAL_REASON_TABLE_HEADER,"${REFERRAL_REASON_DISP}"));
table.addColumn(createColumn("date-assigned",customClass,HcmReferral.i18n.DATE_ASSIGNED,"${ASSIGNED_DATE}"));
if(patientInfoInd&&addEditInd){table.addColumn(createColumn("modify",customClass,"","<a href='#' class='"+namespace+"-modify-pat-details' id='${ID}'> "+HcmReferral.i18n.EDIT_PATIENT_INFORMATION+" </a>"));
}return table;
};
this.html=function(options){var table=this.table(),component=this.component,modifyPatientDetails="."+component.namespace+"-modify-pat-details",tableHeader="";
formatDataForTable(this.people);
table.bindData(this.people);
$(document).off("click",modifyPatientDetails).on("click",modifyPatientDetails,function(event){component.modifyPatientDetails(event.target.id);
});
if(options.header){var tableHeader="<div class='"+component.namespace+"-recently-assigned-table-header'> "+options.header+" </div>";
}return(tableHeader+table.render());
};
var formatDataForTable=function(people){var df=new mp_formatter.DateTimeFormatter(MPAGE_LOCALE),dateOfBirth;
$.each(people,function(_,person){person.ASSIGNED_DATE=person.CASE_ASSIGNED_DT_TM?df.formatISO8601(person.CASE_ASSIGNED_DT_TM,mp_formatter.DateTimeFormatter.FULL_DATE_4YEAR):HcmReferral.i18n.NO_DATA;
if(CERN_Platform.inMillenniumContext()){person.CHART_LINK='<a href=\'javascript:APPLINK(0,"Powerchart.exe","/PERSONID='+person.ID+" /ENCNTRID="+person.ENCNTR_ID+" /FIRSTTAB=^^\")'>"+person.FULL_NAME+"</a>";
}else{person.CHART_LINK=person.FULL_NAME;
}if(person.BIRTH_DT_TM){dateOfBirth=new Date();
dateOfBirth.setISO8601(person.BIRTH_DT_TM);
person.DATE_OF_BIRTH=dateOfBirth.format(MPAGE_LOCALE.fulldate4yr,true);
}else{person.DATE_OF_BIRTH=HcmReferral.i18n.NO_DATA;
}person.FIN_NUM=getFinNumDisplay(person.ENCOUNTER_ALIASES);
if(person.FIN_NUM){person.DEMOGRAPHICS="<span class='disabled'>"+HcmReferral.i18n.PERSON_DEMOGRAPHICS_TEMPLATE.replace("${AGE}",person.AGE).replace("${SEX_DISP}",person.SEX_DISP).replace("${DATE_OF_BIRTH}",person.DATE_OF_BIRTH)+"</span><br><span class='disabled'>"+HcmReferral.i18n.PERSON_FIN_TEMPLATE.replace("${FIN_NUM}",person.FIN_NUM)+"</span>";
}else{person.DEMOGRAPHICS="<span class='disabled'>"+HcmReferral.i18n.PERSON_DEMOGRAPHICS_TEMPLATE.replace("${AGE}",person.AGE).replace("${SEX_DISP}",person.SEX_DISP).replace("${DATE_OF_BIRTH}",person.DATE_OF_BIRTH)+"</span>";
}});
};
var getFinNumDisplay=function(aliases){var encounterAliases=aliases||[];
var finNbrAliases=$.grep(encounterAliases,function(alias){return alias.TYPE_MEANING==="FIN NBR";
});
return finNbrAliases.length?finNbrAliases[0].ALIAS:null;
};
var createColumn=function(columnId,columnClass,display,template){var column=new TableColumn();
column.setColumnId(columnId);
column.setCustomClass(columnClass);
column.setColumnDisplay(display);
column.setRenderTemplate(template);
return column;
};
HcmReferral.__recentlyReferredTable={formatDataForTable:formatDataForTable};
return this;
};
