function FutureOrdersComponentStyle(){this.initByNamespace("fo");
}FutureOrdersComponentStyle.inherits(ComponentStyle);
function FutureOrdersComponent(criterion){this.setCriterion(criterion);
this.setStyles(new FutureOrdersComponentStyle());
this.setComponentLoadTimerName("USR:MPG.FUTURE_ORDERS.O1 - load component");
this.setComponentRenderTimerName("ENG:MPG.FUTURE_ORDERS.O1 - render component");
this.setScope(0);
this.firstOverdueValue=3;
this.firstOverdueUnit="M";
this.lastUpcomingValue=3;
this.lastUpcomingUnit="M";
this.m_tab1=null;
this.m_tabDisplay1=null;
this.m_tab2=null;
this.m_tabDisplay2=null;
this.m_tab3=null;
this.m_tabDisplay3=null;
this.m_tab4=null;
this.m_tabDisplay4=null;
this.m_tab5=null;
this.m_tabDisplay5=null;
this.m_tab6=null;
this.m_tabDisplay6=null;
this.m_tab7=null;
this.m_tabDisplay7=null;
this.m_tab8=null;
this.m_tabDisplay8=null;
this.m_tab9=null;
this.m_tabDisplay9=null;
this.m_allTabDisplay=null;
FutureOrdersComponent.method("setTab1",function(value){this.m_tab1=value;
});
FutureOrdersComponent.method("getTab1",function(){return this.m_tab1;
});
FutureOrdersComponent.method("setTabDisplay1",function(value){this.m_tabDisplay1=value;
});
FutureOrdersComponent.method("getTabDisplay1",function(){return this.m_tabDisplay1;
});
FutureOrdersComponent.method("setTab2",function(value){this.m_tab2=value;
});
FutureOrdersComponent.method("getTab2",function(){return this.m_tab2;
});
FutureOrdersComponent.method("setTabDisplay2",function(value){this.m_tabDisplay2=value;
});
FutureOrdersComponent.method("getTabDisplay2",function(){return this.m_tabDisplay2;
});
FutureOrdersComponent.method("setTab3",function(value){this.m_tab3=value;
});
FutureOrdersComponent.method("getTab3",function(){return this.m_tab3;
});
FutureOrdersComponent.method("setTabDisplay3",function(value){this.m_tabDisplay3=value;
});
FutureOrdersComponent.method("getTabDisplay3",function(){return this.m_tabDisplay3;
});
FutureOrdersComponent.method("setTab4",function(value){this.m_tab4=value;
});
FutureOrdersComponent.method("getTab4",function(){return this.m_tab4;
});
FutureOrdersComponent.method("setTabDisplay4",function(value){this.m_tabDisplay4=value;
});
FutureOrdersComponent.method("getTabDisplay4",function(){return this.m_tabDisplay4;
});
FutureOrdersComponent.method("setTab5",function(value){this.m_tab5=value;
});
FutureOrdersComponent.method("getTab5",function(){return this.m_tab5;
});
FutureOrdersComponent.method("setTabDisplay5",function(value){this.m_tabDisplay5=value;
});
FutureOrdersComponent.method("getTabDisplay5",function(){return this.m_tabDisplay5;
});
FutureOrdersComponent.method("setTab6",function(value){this.m_tab6=value;
});
FutureOrdersComponent.method("getTab6",function(){return this.m_tab6;
});
FutureOrdersComponent.method("setTabDisplay6",function(value){this.m_tabDisplay6=value;
});
FutureOrdersComponent.method("getTabDisplay6",function(){return this.m_tabDisplay6;
});
FutureOrdersComponent.method("setTab7",function(value){this.m_tab7=value;
});
FutureOrdersComponent.method("getTab7",function(){return this.m_tab7;
});
FutureOrdersComponent.method("setTabDisplay7",function(value){this.m_tabDisplay7=value;
});
FutureOrdersComponent.method("getTabDisplay7",function(){return this.m_tabDisplay7;
});
FutureOrdersComponent.method("setTab8",function(value){this.m_tab8=value;
});
FutureOrdersComponent.method("getTab8",function(){return this.m_tab8;
});
FutureOrdersComponent.method("setTabDisplay8",function(value){this.m_tabDisplay8=value;
});
FutureOrdersComponent.method("getTabDisplay8",function(){return this.m_tabDisplay8;
});
FutureOrdersComponent.method("setTab9",function(value){this.m_tab9=value;
});
FutureOrdersComponent.method("getTab9",function(){return this.m_tab9;
});
FutureOrdersComponent.method("setTabDisplay9",function(value){this.m_tabDisplay9=value;
});
FutureOrdersComponent.method("getTabDisplay9",function(){return this.m_tabDisplay9;
});
FutureOrdersComponent.method("setAllTabDisplay",function(value){this.m_allTabDisplay=value;
});
FutureOrdersComponent.method("getAllTabDisplay",function(){return this.m_allTabDisplay;
});
FutureOrdersComponent.method("setLookBack",function(object){this.firstOverdueValue=object.value;
this.firstOverdueUnit=object.units.substr(0,1);
var upperUnit=this.firstOverdueUnit.toUpperCase();
if(upperUnit!="M"&&upperUnit!="W"&&upperUnit!="D"){this.firstOverdueUnit="M";
}});
FutureOrdersComponent.method("getLookBack",function(){return this.firstOverdueValue+","+this.firstOverdueUnit;
});
FutureOrdersComponent.method("setLookAhead",function(object){this.lastUpcomingValue=object.value;
this.lastUpcomingUnit=object.units.substr(0,1);
var upperUnit=this.lastUpcomingUnit.toUpperCase();
if(upperUnit!="M"&&upperUnit!="W"&&upperUnit!="D"){this.lastUpcomingUnit="M";
}});
FutureOrdersComponent.method("getLookAhead",function(){return this.lastUpcomingValue+","+this.lastUpcomingUnit;
});
FutureOrdersComponent.method("InsertData",function(){CERN_FUTURE_ORDERS_O1.GetFutureOrders(this);
});
FutureOrdersComponent.method("HandleSuccess",function(recordData){CERN_FUTURE_ORDERS_O1.RenderComponent(this,recordData);
});
this.catalogTypeCodes=MP_Util.GetCodeSet(6000,false);
this.arrFutureOrderTabData=[];
this.tabOrder=[];
this.tabDisplay=[];
this.sortOrderArray=[];
this.isFirstLoad=true;
this.numAJAXCalls=0;
this.PowerOrdersMPageUtils=null;
this.currentTab=0;
this.allTabIdx=-1;
this.providerFilterList=[];
this.selectedProviderFilter="all";
this.locationFilterList=[];
this.selectedLocationFilter="all";
this.totalNumOrders=0;
this.typeTimer=0;
this.openAccordion="";
}FutureOrdersComponent.inherits(MPageComponent);
var CERN_FUTURE_ORDERS_O1=function(){return{GetFutureOrders:function(component){var sendAr=BuildRequestParameters(component);
MP_Core.XMLCclRequestWrapper(component,"MP_CPOE_GET_FUTURE_ORDERS",sendAr,true);
},SetProcessing:function(componentId,increment){var component=MP_Util.GetCompObjById(componentId);
var processingElement=_g("foProcessing"+componentId);
component.numAJAXCalls+=increment;
if(component.numAJAXCalls==0){Util.Style.acss(processingElement,"fo-hide");
}else{Util.Style.rcss(processingElement,"fo-hide");
}},RefreshFutureOrdersTable:function(componentId){var component=MP_Util.GetCompObjById(componentId);
component.setEditMode(true);
CERN_FUTURE_ORDERS_O1.SetProcessing(componentId,1);
component.selectedProviderFilter=_g(componentId+"-provider-filter").value;
component.selectedLocationFilter=_g(componentId+"-location-filter").value;
component.firstOverdueValue=_g(componentId+"-overdue-value").value;
component.firstOverdueUnit=_g(componentId+"-overdue-units").value;
component.lastUpcomingValue=_g(componentId+"-upcoming-value").value;
component.lastUpcomingUnit=_g(componentId+"-upcoming-units").value;
var sendAr=BuildRequestParameters(component);
var request=new MP_Core.ScriptRequest(component,component.getComponentLoadTimerName());
request.setProgramName("MP_CPOE_GET_FUTURE_ORDERS");
request.setParameters(sendAr);
request.setAsync(true);
MP_Core.XMLCCLRequestCallBack(component,request,CERN_FUTURE_ORDERS_O1.RefreshCallBack);
},RefreshCallBack:function(reply){try{var component=reply.getComponent();
var recordData=reply.getResponse();
var componentId=component.getComponentId();
component.arrFutureOrderTabData=[];
component.totalNumOrders=0;
CERN_FUTURE_ORDERS_O1.InitiateTabArray(component);
CERN_FUTURE_ORDERS_O1.FillOutTabArray(component,recordData);
CERN_FUTURE_ORDERS_O1.CreateTabs(component);
CERN_FUTURE_ORDERS_O1.CreateTabTables(component);
BuildProviderFilter(component);
BuildLocationFilter(component);
component.setEditMode(false);
if(component.isFirstLoad==false){CERN_FUTURE_ORDERS_O1.SetProcessing(componentId,-1);
}}catch(err){var errMsg=[];
errMsg.push("<b>",i18n.JS_ERROR,"</b><br><ul><li>",i18n.MESSAGE,": ",err.message,"</li><li>",i18n.NAME,": ",err.name,"</li><li>",i18n.NUMBER,": ",(err.number&65535),"</li><li>",i18n.DESCRIPTION,": ",err.description,"</li></ul>");
var countText=MP_Util.CreateTitleText(component,component.totalNumOrders);
MP_Util.Doc.FinalizeComponent(MP_Util.HandleErrorResponse(component.getStyles().getNameSpace(),errMsg.join("")),component,countText);
if(timerRenderComponent){timerRenderComponent.Abort();
timerRenderComponent=null;
}throw (err);
}},RenderComponent:function(component,recordData){var timerRenderComponent=MP_Util.CreateTimer(component.getComponentRenderTimerName());
try{var componentId=component.getComponentId();
var foI18N=i18n.cpoe.future_orders_o1;
var secHTMLArray=[];
var countText="";
component.setEditMode(true);
component.totalNumOrders=recordData.PATIENTS[0].ORDERS.length;
if(component.isFirstLoad==true){var foRootNode=_g("fo"+componentId);
var titleFrag=Util.ce("span");
var innerHTMLArr=[];
innerHTMLArr.push('<span id="foProcessing',+componentId,'" class="fo-processing fo-subtext fo-hide">',foI18N.PROCESSING,"</span>");
titleFrag.innerHTML=innerHTMLArr.join("");
var secTitle=Util.Style.g("sec-title",foRootNode,"span")[0];
Util.ia(titleFrag,secTitle);
}secHTMLArray.push("<div id='",componentId,"-body' class='",MP_Util.GetContentClass(component,component.totalNumOrders),"'>");
CERN_FUTURE_ORDERS_O1.InitiateTabArray(component);
CERN_FUTURE_ORDERS_O1.FillOutTabArray(component,recordData);
secHTMLArray.push("<span><div id='",componentId,"-filter-row' class='fo-filter-row fo-filter-row-hd'></div></span>");
secHTMLArray.push("<div class='fo-hd'><ul id='",componentId,"-tabs' class='fo-tabrow'></ul></div>");
secHTMLArray.push("<div id='",componentId,"-tab-sections' class='fo-body'></div>");
secHTMLArray.push("</div>");
countText=MP_Util.CreateTitleText(component,component.totalNumOrders);
MP_Util.Doc.FinalizeComponent(secHTMLArray.join(""),component,countText);
CERN_FUTURE_ORDERS_O1.CreateFilterRow(component);
CERN_FUTURE_ORDERS_O1.CreateTabs(component);
CERN_FUTURE_ORDERS_O1.CreateTabTables(component);
}catch(err){var errMsg=[];
errMsg.push("<b>",i18n.JS_ERROR,"</b><br><ul><li>",i18n.MESSAGE,": ",err.message,"</li><li>",i18n.NAME,": ",err.name,"</li><li>",i18n.NUMBER,": ",(err.number&65535),"</li><li>",i18n.DESCRIPTION,": ",err.description,"</li></ul>");
countText=MP_Util.CreateTitleText(component,component.totalNumOrders);
MP_Util.Doc.FinalizeComponent(MP_Util.HandleErrorResponse(component.getStyles().getNameSpace(),errMsg.join("")),component,countText);
if(timerRenderComponent){timerRenderComponent.Abort();
timerRenderComponent=null;
}throw (err);
}finally{if(timerRenderComponent){timerRenderComponent.Stop();
}component.setEditMode(false);
component.isFirstLoad=false;
}},InitiateTabArray:function(component){if(component.isFirstLoad){component.tabOrder.push(component.getTab1());
component.tabOrder.push(component.getTab2());
component.tabOrder.push(component.getTab3());
component.tabOrder.push(component.getTab4());
component.tabOrder.push(component.getTab5());
component.tabOrder.push(component.getTab6());
component.tabOrder.push(component.getTab7());
component.tabOrder.push(component.getTab8());
component.tabOrder.push(component.getTab9());
component.tabDisplay.push(component.getTabDisplay1());
component.tabDisplay.push(component.getTabDisplay2());
component.tabDisplay.push(component.getTabDisplay3());
component.tabDisplay.push(component.getTabDisplay4());
component.tabDisplay.push(component.getTabDisplay5());
component.tabDisplay.push(component.getTabDisplay6());
component.tabDisplay.push(component.getTabDisplay7());
component.tabDisplay.push(component.getTabDisplay8());
component.tabDisplay.push(component.getTabDisplay9());
component.catalogTypeCodes.sort(theSubset("value",byString("display",1)));
component.catalogTypeCodes.sort(theSubset("value",byInt("sequence",1,true)));
}var catalogTypeCodes=component.catalogTypeCodes;
component.arrFutureOrderTabData=[];
var tabOrderCount=component.tabOrder.length;
for(var i=0;
i<tabOrderCount;
i++){if(!component.tabOrder[i]){continue;
}var tabData={};
if(component.tabDisplay[i]){tabData.tabDisplay=component.tabDisplay[i];
}else{var catalogTypeCount=catalogTypeCodes.length;
for(var j=0;
j<catalogTypeCount;
j++){if(component.tabOrder[i]==catalogTypeCodes[j].value.codeValue){tabData.tabDisplay=catalogTypeCodes[j].value.display;
break;
}}}tabData.tabCodeValue=component.tabOrder[i];
tabData.tabOrders=[];
tabData.tabSelectedOrders=[];
component.arrFutureOrderTabData.push(tabData);
if(component.isFirstLoad){var overdueSort={field:"BEGIN_DUE_DT_TM",order:1};
component.sortOrderArray.push(overdueSort);
}}component.allTabIdx=component.arrFutureOrderTabData.length;
tabData={};
var allTabDisplay=component.getAllTabDisplay();
if(!allTabDisplay){tabData.tabDisplay=i18n.cpoe.future_orders_o1.ALL;
}else{tabData.tabDisplay=allTabDisplay;
}tabData.tabCodeValue=-1;
tabData.tabTotalNumOrders=0;
tabData.tabOrders=[];
tabData.tabSelectedOrders=[];
component.arrFutureOrderTabData.push(tabData);
if(component.isFirstLoad){var overdueSort={field:"BEGIN_DUE_DT_TM",order:1};
component.sortOrderArray.push(overdueSort);
}},FillOutTabArray:function(component,recordData){var futureOrderTabs=component.arrFutureOrderTabData;
var catalogTypeCodes=component.catalogTypeCodes;
var orderCount=recordData.PATIENTS[0].ORDERS.length;
for(var i=0;
i<orderCount;
i++){var oOrder=recordData.PATIENTS[0].ORDERS[i];
if(component.selectedProviderFilter!=oOrder.RESPONSIBLE_PROVIDER_NAME&&component.selectedProviderFilter!="all"){continue;
}if(component.selectedLocationFilter!="all"){if(oOrder.ORDERING_LOCATION_INFORMATION.length==1){if(component.selectedLocationFilter!=oOrder.ORDERING_LOCATION_INFORMATION[0].ORDERING_LOCATION_DISPLAY){continue;
}}else{continue;
}}var bCatalogTypeFound=false;
if(component.allTabIdx!=-1){var allTabOrders=futureOrderTabs[component.allTabIdx].tabOrders;
var allTabOrdersCount=allTabOrders.length;
for(var j=0;
j<allTabOrdersCount;
j++){if(allTabOrders[j].subSectionCodeValue==oOrder.CATALOG_TYPE_CD){allTabOrders[j].subSectionOrders.push(oOrder);
futureOrderTabs[component.allTabIdx].tabTotalNumOrders++;
bCatalogTypeFound=true;
break;
}}if(bCatalogTypeFound==false){var catalogTypesCount=catalogTypeCodes.length;
for(var j=0;
j<catalogTypesCount;
j++){var catTypeCodeValue=catalogTypeCodes[j].value;
if(catTypeCodeValue.codeValue==oOrder.CATALOG_TYPE_CD){var subSectionData={};
subSectionData.subSectionDisplay=catTypeCodeValue.display;
subSectionData.subSectionCodeValue=catTypeCodeValue.codeValue;
subSectionData.subSectionOrders=[];
subSectionData.subSectionOrders.push(oOrder);
futureOrderTabs[component.allTabIdx].tabTotalNumOrders++;
allTabOrders.push(subSectionData);
break;
}}}}var futureOrderTabsCount=futureOrderTabs.length;
for(var j=0;
j<futureOrderTabsCount;
j++){if(futureOrderTabs[j].tabCodeValue==oOrder.CATALOG_TYPE_CD){futureOrderTabs[j].tabOrders.push(oOrder);
break;
}}var bFound=false;
var providerFilterCount=component.providerFilterList.length;
for(j=0;
j<providerFilterCount;
j++){if(oOrder.RESPONSIBLE_PROVIDER_NAME==component.providerFilterList[j]){bFound=true;
}}if(bFound===false&&oOrder.RESPONSIBLE_PROVIDER_NAME!=""){component.providerFilterList.push(oOrder.RESPONSIBLE_PROVIDER_NAME);
}if(oOrder.ORDERING_LOCATION_INFORMATION.length==1){bFound=false;
var locationFilterCount=component.locationFilterList.length;
for(j=0;
j<locationFilterCount;
j++){if(oOrder.ORDERING_LOCATION_INFORMATION[0].ORDERING_LOCATION_DISPLAY==component.locationFilterList[j]){bFound=true;
}}if(bFound===false&&oOrder.ORDERING_LOCATION_INFORMATION[0].ORDERING_LOCATION_DISPLAY!=""){component.locationFilterList.push(oOrder.ORDERING_LOCATION_INFORMATION[0].ORDERING_LOCATION_DISPLAY);
}}}},CreateFilterRow:function(component){var componentId=component.getComponentId();
var foI18N=i18n.cpoe.future_orders_o1;
var filterHTMLArray=[];
var filterRowHTMLArray=[];
var codeDays=MP_Util.GetCodeValueByMeaning("DAYS",54);
var codeWeeks=MP_Util.GetCodeValueByMeaning("WEEKS",54);
var codeMonths=MP_Util.GetCodeValueByMeaning("MONTHS",54);
filterRowHTMLArray.push("<span class='fo-filter-group'><span class='fo-filter'>",foI18N.LOOK_BACK,":&nbsp;","<input type='text' id='",componentId,"-overdue-value' maxLength=3 class='fo-input' ","onClick='this.select();' ","onkeypress='return CERN_FUTURE_ORDERS_O1.foValidateIntegerInput(event);' ","onkeyup='CERN_FUTURE_ORDERS_O1.TypeTimer(",componentId,", ","function(){CERN_FUTURE_ORDERS_O1.RefreshFutureOrdersTable(",componentId,");}, 1000 );' />","<select id='",componentId,"-overdue-units' class='fo-select-list' ","onChange='CERN_FUTURE_ORDERS_O1.RefreshFutureOrdersTable(",componentId,");'>","<option value='D' selected='selected'>",codeDays.display,"</option>","<option value='W'>",codeWeeks.display,"</option>","<option value='M'>",codeMonths.display,"</option></select>","</span></span>");
filterRowHTMLArray.push("<span class='fo-filter-group'><span class='fo-filter'>",foI18N.LOOK_FORWARD,":&nbsp;","<input type='text' id='",componentId,"-upcoming-value' maxLength=3 class='fo-input' ","onClick='this.select();' ","onkeypress='return CERN_FUTURE_ORDERS_O1.foValidateIntegerInput(event);' ","onkeyup='CERN_FUTURE_ORDERS_O1.TypeTimer(",componentId,", ","function(){CERN_FUTURE_ORDERS_O1.RefreshFutureOrdersTable(",componentId,");}, 1000 );' />","<select id='",componentId,"-upcoming-units' class='fo-select-list' ","onChange='CERN_FUTURE_ORDERS_O1.RefreshFutureOrdersTable(",componentId,");'>","<option value='D' selected='selected'>",codeDays.display,"</option>","<option value='W'>",codeWeeks.display,"</option>","<option value='M'>",codeMonths.display,"</option></select>","</span></span>");
filterRowHTMLArray.push("<span class='fo-filter-group'><span class='fo-filter'>",foI18N.PROVIDER,":&nbsp;","<select id='",componentId,"-provider-filter' class='fo-select-list' ","onChange='CERN_FUTURE_ORDERS_O1.RefreshFutureOrdersTable(",componentId,");'>","<option value='all'>",foI18N.ALL_PROVIDERS,"</option></select></span></span>");
filterRowHTMLArray.push("<span class='fo-filter-group'><span class='fo-filter'>",foI18N.LOCATION,":&nbsp;","<select id='",componentId,"-location-filter' class='fo-select-list' ","onChange='CERN_FUTURE_ORDERS_O1.RefreshFutureOrdersTable(",componentId,");'>","<option value='all'>",foI18N.ALL_LOCATIONS,"</option></select></span></span></span>");
var dateFilterNode=_g(componentId+"-filter-row");
dateFilterNode.innerHTML=filterRowHTMLArray.join("");
BuildProviderFilter(component);
BuildLocationFilter(component);
_g(componentId+"-provider-filter").value=component.selectedProviderFilter;
_g(componentId+"-location-filter").value=component.selectedLocationFilter;
_g(componentId+"-overdue-value").value=component.firstOverdueValue;
_g(componentId+"-overdue-units").value=component.firstOverdueUnit;
_g(componentId+"-upcoming-value").value=component.lastUpcomingValue;
_g(componentId+"-upcoming-units").value=component.lastUpcomingUnit;
},CreateTabs:function(component){var componentId=component.getComponentId();
var futureOrderTabs=component.arrFutureOrderTabData;
var tabsHTMLArray=[];
if(futureOrderTabs.length==1){var tabsNode=_g(componentId+"-tabs");
if(component.allTabIdx==-1){tabsHTMLArray.push("<h3 class='fo-hdr-txt'>",futureOrderTabs[0].tabDisplay,"</h3>");
tabsNode.innerHTML=tabsHTMLArray.join("");
}else{Util.Style.rcss(tabsNode,"fo-hd");
}return;
}var futureOrderTabsCount=futureOrderTabs.length;
for(var i=0;
i<futureOrderTabsCount;
i++){if(i==component.currentTab){tabsHTMLArray.push("<li id='",componentId,"tab",i,"' class='fo-selected'>",futureOrderTabs[i].tabDisplay);
}else{tabsHTMLArray.push("<li id='",componentId,"tab",i,"'>",futureOrderTabs[i].tabDisplay);
}if(i==component.allTabIdx){tabsHTMLArray.push(" (",futureOrderTabs[i].tabTotalNumOrders,")</li>");
}else{tabsHTMLArray.push(" (",futureOrderTabs[i].tabOrders.length,")</li>");
}}var tabsNode=_g(componentId+"-tabs");
tabsNode.innerHTML=tabsHTMLArray.join("");
for(i=0;
i<futureOrderTabsCount;
i++){var tabId=componentId+"tab"+i;
var curTab=_g(tabId);
if(curTab){Util.addEvent(curTab,"click",function(){foSelectTab(componentId,this.id);
});
}}},CreateTabTables:function(component){var componentId=component.getComponentId();
var futureOrderTabs=component.arrFutureOrderTabData;
var foI18N=i18n.cpoe.future_orders_o1;
var tabSecHTMLArray=[];
var futureOrderTabsCount=futureOrderTabs.length;
for(var i=0;
i<futureOrderTabsCount;
i++){if(i==component.currentTab){tabSecHTMLArray.push("<div id='",componentId,"tabsec",i,"' class='fo-tabsec-display'>");
}else{tabSecHTMLArray.push("<div id='",componentId,"tabsec",i,"' class='fo-tabsec-hide'>");
}tabSecHTMLArray.push("<div class='fo-tabsec-body'>");
if(i===component.allTabIdx){if(futureOrderTabs[i].tabTotalNumOrders==0){tabSecHTMLArray.push("<div class='sub-sec'><h5 class='fo-cat-type-sec-hd'>","<div class='sub-sec-hd-hide'></div>","<span class='fo-sub-sec-title'>",foI18N.ALL_ORDERS,"</span></h5>","<div class='fo-cat-type-sec-content'>");
tabSecHTMLArray.push("<span class='res-none'>",foI18N.NO_ORDERS,"</span></div></div>");
}tabSecHTMLArray.push(CERN_FUTURE_ORDERS_O1.BuildColumnHeader(component,i));
var catalogTypesCount=component.catalogTypeCodes.length;
for(var j=0;
j<catalogTypesCount;
j++){var tabOrdersCount=futureOrderTabs[i].tabOrders.length;
for(var k=0;
k<tabOrdersCount;
k++){if(component.catalogTypeCodes[j].value.codeValue==futureOrderTabs[i].tabOrders[k].subSectionCodeValue){var allTabSection=futureOrderTabs[i].tabOrders[k];
if(allTabSection.subSectionOrders.length===0){tabSecHTMLArray.push("<div class='sub-sec closed'><h2 class='fo-sub-sec-hd fo-cat-type'>","<div class='sub-sec-hd-hide'></div>");
}else{tabSecHTMLArray.push("<div class='sub-sec'><h2 class='fo-sub-sec-hd fo-cat-type'>","<span class='sub-sec-hd-tgl' title='",foI18N.HIDE_SECTION,"'>-</span>");
}tabSecHTMLArray.push("<span class='sub-sec-title'>",allTabSection.subSectionDisplay," <span class='fo-subtext'>(",allTabSection.subSectionOrders.length,")</span></span></h2>","<div class='fo-cat-type-sec-content'>");
tabSecHTMLArray.push(CERN_FUTURE_ORDERS_O1.BuildSubSection(component,allTabSection.subSectionOrders));
tabSecHTMLArray.push("</div></div>");
break;
}}}}else{tabSecHTMLArray.push(CERN_FUTURE_ORDERS_O1.BuildColumnHeader(component,i));
tabSecHTMLArray.push(CERN_FUTURE_ORDERS_O1.BuildSubSection(component,futureOrderTabs[i].tabOrders));
}tabSecHTMLArray.push("</div>");
var codeActivate=MP_Util.GetCodeValueByMeaning("ACTIVATE",6003);
var codeCancelDC=MP_Util.GetCodeValueByMeaning("CANCEL DC",6003);
var sActivate="";
var sCanceDC="";
if(codeActivate==null){sActivate=foI18N.ACTIVATE;
}else{sActivate=codeActivate.display;
}if(codeCancelDC==null){sCancelDC=foI18N.CANCEL;
}else{sCancelDC=codeCancelDC.display;
}tabSecHTMLArray.push('<div class="fo-btn-row">');
tabSecHTMLArray.push("<span class='fo-filter'>","<a onclick='CERN_FUTURE_ORDERS_O1.RefreshFutureOrdersTable(",componentId,");'>","<img src='",component.getCriterion().static_content,"\\images\\3688_16.png' />","&nbsp;",foI18N.REFRESH,"</a></span>");
tabSecHTMLArray.push('<input type="button" id="btnActivateTab',i,'" name="btnActivateTab',i,'" class="fo-btn" disabled="false" value="',sActivate,'" onclick="CERN_FUTURE_ORDERS_O1.foOnActivate(',componentId,", ",i,');" />');
tabSecHTMLArray.push('<input type="button" id="btnCancelTab',i,'" name="btnCancelTab',i,'" class="fo-btn" disabled="false" value="',sCancelDC,'" onclick="CERN_FUTURE_ORDERS_O1.foOnCancel(',componentId,", ",i,');"/>');
tabSecHTMLArray.push("</div>");
tabSecHTMLArray.push("</div>");
}var tabSectionsNode=_g(componentId+"-tab-sections");
tabSectionsNode.innerHTML=tabSecHTMLArray.join("");
var styles=component.getStyles();
var node=component.getSectionContentNode();
MP_Util.Doc.InitHovers(styles.getInfo(),node,component);
MP_Util.Doc.InitSubToggles(node,"sub-sec-hd-tgl");
},BuildColumnHeader:function(component,tabIdx){var componentId=component.getComponentId();
var foI18N=i18n.cpoe.future_orders_o1;
var columnHeaderArray=[];
columnHeaderArray.push("<dl class='fo-info-hdr fo-hdr'>","<dd class='fo-ico'></dd><dd class='fo-ico'></dd>");
columnHeaderArray.push("<dd class='fo-col-hdr fo-lbl ",DetermineSortClass("MNEMONIC",component.sortOrderArray[tabIdx].field,component.sortOrderArray[tabIdx].order),"' onclick='CERN_FUTURE_ORDERS_O1.foSortColumn(",componentId,",",'"MNEMONIC",',-component.sortOrderArray[tabIdx].order,");'>",foI18N.ORDER,"</dd>");
columnHeaderArray.push("<dd class='fo-col-hdr fo-txt ",DetermineSortClass("BEGIN_DUE_DT_TM",component.sortOrderArray[tabIdx].field,component.sortOrderArray[tabIdx].order),"' onclick='CERN_FUTURE_ORDERS_O1.foSortColumn(",componentId,",",'"BEGIN_DUE_DT_TM",',-component.sortOrderArray[tabIdx].order,");'>",foI18N.GRACE_PERIOD,"</dd>");
columnHeaderArray.push("<dd class='fo-col-hdr fo-txt ",DetermineSortClass("ORIGINAL_ORDER_DT_TM",component.sortOrderArray[tabIdx].field,component.sortOrderArray[tabIdx].order),"' onclick='CERN_FUTURE_ORDERS_O1.foSortColumn(",componentId,",",'"ORIGINAL_ORDER_DT_TM",',-component.sortOrderArray[tabIdx].order,");'>",foI18N.ORDER_DATE,"</dd>");
columnHeaderArray.push("<dd class='fo-col-hdr fo-txt ",DetermineSortClass("RESPONSIBLE_PROVIDER_NAME",component.sortOrderArray[tabIdx].field,component.sortOrderArray[tabIdx].order),"' onclick='CERN_FUTURE_ORDERS_O1.foSortColumn(",componentId,",",'"RESPONSIBLE_PROVIDER_NAME",',-component.sortOrderArray[tabIdx].order,");'>",foI18N.PROVIDER,"</dd>");
columnHeaderArray.push("<dd class='fo-col-hdr fo-txt ",DetermineSortClass("ORDERING_LOCATION_DISPLAY",component.sortOrderArray[tabIdx].field,component.sortOrderArray[tabIdx].order),"' onclick='CERN_FUTURE_ORDERS_O1.foSortColumn(",componentId,",",'"ORDERING_LOCATION_DISPLAY",',-component.sortOrderArray[tabIdx].order,");'>",foI18N.LOCATION,"</dd>");
columnHeaderArray.push("<dd class='fo-col-hdr fo-blob ",DetermineSortClass("CLINICAL_DISPLAY_LINE",component.sortOrderArray[tabIdx].field,component.sortOrderArray[tabIdx].order),"' onclick='CERN_FUTURE_ORDERS_O1.foSortColumn(",componentId,",",'"CLINICAL_DISPLAY_LINE",',-component.sortOrderArray[tabIdx].order,");'>",foI18N.DETAILS,"</dd>");
columnHeaderArray.push("</dl></div><div class='content-body'>");
return columnHeaderArray.join("");
},BuildSubSection:function(component,orderArray){var componentId=component.getComponentId();
var secHTMLArray=[];
var foI18N=i18n.cpoe.future_orders_o1;
var subHeaders=[foI18N.OVERDUE,foI18N.DUE,foI18N.UPCOMING];
var arrOrdersSections=[];
var arrOrdersDue=[];
var arrOrdersOverdue=[];
var arrOrdersUpcoming=[];
var allSubSectionDisplay;
var dtEstStart=new Date();
var dtBeginDue=new Date();
var dtDueBy=new Date();
var dtOrigOrder=new Date();
var orderArrayCount=orderArray.length;
for(var i=0;
i<orderArrayCount;
i++){var oOrder=orderArray[i];
if(oOrder.DUE_STATUS_FLAG==1){arrOrdersDue.push(oOrder);
}else{if(oOrder.DUE_STATUS_FLAG==2){arrOrdersOverdue.push(oOrder);
}else{if(oOrder.DUE_STATUS_FLAG==0){arrOrdersUpcoming.push(oOrder);
}}}}arrOrdersSections.splice(0,0,arrOrdersOverdue);
arrOrdersSections.splice(1,0,arrOrdersDue);
arrOrdersSections.splice(2,0,arrOrdersUpcoming);
for(i=0;
i<3;
i++){var arrSectionOrders=arrOrdersSections[i];
var sortIdx=component.sortOrderArray[component.currentTab].field;
var sortOrder=component.sortOrderArray[component.currentTab].order;
if(arrSectionOrders.length>0){secHTMLArray.push("<div class='sub-sec'><h6 class='fo-sub-sec-hd'>");
secHTMLArray.push("<span class='sub-sec-hd-tgl' title='",foI18N.HIDE_SECTION,"'>-</span>","<span class='fo-sub-sec-title'>");
}else{secHTMLArray.push("<div class='sub-sec closed'><h6 class='fo-sub-sec-hd'>");
secHTMLArray.push("<div class='sub-sec-hd-hide'></div><span class='fo-sub-sec-disabled'>");
}secHTMLArray.push(subHeaders[i]," <span class='fo-subtext'>(",arrSectionOrders.length,") </span></span></h6>","<div class='sub-sec-content'><div class='content-hdr'>");
if(arrSectionOrders.length>0){switch(sortIdx){case"MNEMONIC":case"RESPONSIBLE_PROVIDER_NAME":case"CLINICAL_DISPLAY_LINE":arrSectionOrders.sort(byString(sortIdx,sortOrder,true));
break;
case"BEGIN_DUE_DT_TM":case"ORIGINAL_ORDER_DT_TM":arrSectionOrders.sort(byISO8601Date(sortIdx,sortOrder));
break;
case"ORDERING_LOCATION_DISPLAY":arrSectionOrders.sort(theArrayIndex("ORDERING_LOCATION_INFORMATION",0,byString(sortIdx,sortOrder,true)));
break;
default:arrSectionOrders.sort(byString(sortIdx,sortOrder,true));
}sectionOrdersCount=arrSectionOrders.length;
for(var j=0;
j<sectionOrdersCount;
j++){var oOrder=arrSectionOrders[j];
dtEstStart.setISO8601(oOrder.START_DT_TM);
dtBeginDue.setISO8601(oOrder.BEGIN_DUE_DT_TM);
dtDueBy.setISO8601(oOrder.END_DUE_DT_TM);
dtOrigOrder.setISO8601(oOrder.ORIGINAL_ORDER_DT_TM);
secHTMLArray.push("<dl class='fo-info ",(j%2)==0?"even":"odd","' onclick='CERN_FUTURE_ORDERS_O1.foSelectRow(",componentId,", this, ",oOrder.ORDER_ID,")'>","<dt class='fo-ico'>&nbsp;</dt>");
if(oOrder.PLAN_INFORMATION.length==1){secHTMLArray.push("<dd class='fo-ico'><img src='",component.getCriterion().static_content,"\\images\\6404_16.png' /></dd>");
}else{if(oOrder.ORDER_SET_INFORMATION.length==1){secHTMLArray.push("<dd class='fo-ico'><img src='",component.getCriterion().static_content,"\\images\\order_set.png' /></dd>");
}else{secHTMLArray.push("<dd class='fo-ico'></dd>");
}}if(oOrder.ORDER_COMMENT.length>0){secHTMLArray.push("<dd class='fo-ico'><img src='",component.getCriterion().static_content,"\\images\\4972.gif' /></dd>");
}else{secHTMLArray.push("<dd class='fo-ico'></dd>");
}secHTMLArray.push("<dt class='fo-lbl'>",foI18N.ORDER,"</dt>","<dd class='fo-lbl'>",oOrder.MNEMONIC,"</dd>","<dt class='fo-txt'>",foI18N.GRACE_PERIOD,"</dt>","<dd class='fo-txt'>",dtBeginDue.format("shortDate2")," - ",dtDueBy.format("shortDate2"),"</dd>","<dd class='fo-txt'>",dtOrigOrder.format("shortDate2"),"</dd>","<dt class='fo-txt'>",foI18N.PROVIDER,"</dt>","<dd class='fo-txt'>",oOrder.RESPONSIBLE_PROVIDER_NAME,"</dd>","<dt class='fo-txt'>",foI18N.LOCATION,"</dt>");
if(oOrder.ORDERING_LOCATION_INFORMATION.length==1){secHTMLArray.push("<dd class='fo-txt'>",oOrder.ORDERING_LOCATION_INFORMATION[0].ORDERING_LOCATION_DISPLAY,"</dd>");
}else{secHTMLArray.push("<dd class='fo-txt'></dd>");
}secHTMLArray.push("<dt class='fo-blob'>",foI18N.DETAILS,"</dt>","<dd class='fo-blob'>",oOrder.CLINICAL_DISPLAY_LINE,"</dd>","</dl>");
if(oOrder.PLAN_INFORMATION.length==1||oOrder.ORDER_SET_INFORMATION.length==1||oOrder.ORDER_COMMENT.length>0){secHTMLArray.push("<h4 class='det-hd'><span>",foI18N.ORDER,"</span></h4>","<div class='hvr'><dl class='fo-det'>","<dt class='fo-det-dt'><span>",foI18N.ORDER,":</span></dt>","<dd class='fo-det-dt'><span>",oOrder.MNEMONIC,"</span></dd>");
if(oOrder.PLAN_INFORMATION.length==1){secHTMLArray.push("<dt class='fo-det-dt'><span>",foI18N.PLAN_NAME,":</span></dt>","<dd class='fo-det-dt'><span>",oOrder.PLAN_INFORMATION[0].PLAN_NAME,"</span></dd>");
}if(oOrder.ORDER_SET_INFORMATION.length==1){secHTMLArray.push("<dt class='fo-det-dt'><span>",foI18N.CARE_SET_NAME,":</span></dt>","<dd class='fo-det-dt'><span>",oOrder.ORDER_SET_INFORMATION[0].ORDER_SET_NAME,"</span></dd>");
}if(oOrder.ORDER_COMMENT.length>0){secHTMLArray.push("<dt class='fo-det-dt'><span>",foI18N.COMMENTS,":</span></dt>","<dd class='fo-det-dt'><span>",oOrder.ORDER_COMMENT,"</span></dd>");
}secHTMLArray.push("</dl></div>");
}}secHTMLArray.push("</div></div></div>");
}else{secHTMLArray.push("<span class='res-none'>",foI18N.NO_ORDERS,"</span></div></div></div>");
}}return secHTMLArray.join("");
},TypeTimer:function(componentId,callback,ms){var component=MP_Util.GetCompObjById(componentId);
clearTimeout(component.typeTimer);
component.typeTimer=setTimeout(callback,ms);
},foSortColumn:function(componentId,colHeader,sortDir){var component=MP_Util.GetCompObjById(componentId);
var currTab=component.currentTab;
component.sortOrderArray[currTab].field=colHeader;
component.sortOrderArray[currTab].order=sortDir;
CERN_FUTURE_ORDERS_O1.RefreshFutureOrdersTable(componentId);
},foValidateIntegerInput:function(e){var keynum;
var keychar;
var numcheck;
if(window.event){keynum=e.keyCode;
}else{if(e.which){keynum=e.which;
}}keychar=String.fromCharCode(keynum);
numcheck=/\d/;
return numcheck.test(keychar);
},foSelectRow:function(componentId,row,orderId){var component=MP_Util.GetCompObjById(componentId);
var currTab=component.currentTab;
var selectedTabData=component.arrFutureOrderTabData[currTab].tabSelectedOrders;
if(Util.Style.tcss(row,"row-selected")){var executable=component.getCriterion().executable.toLowerCase();
if(!component.PowerOrdersMPageUtils){if(executable=="deptorderentry.exe"||executable=="osmrequisitionorderentry.exe"||executable=="labmpageviewonly.exe"){component.PowerOrdersMPageUtils=window.external.DiscernObjectFactory("LABUTILS");
}else{component.PowerOrdersMPageUtils=window.external.DiscernObjectFactory("POWERORDERS");
}}var hMOEW=component.PowerOrdersMPageUtils.CreateMOEW(component.getCriterion().person_id,component.getCriterion().encntr_id,0,2,127);
if(executable=="labmpageviewonly.exe"){var actionString=0;
}else{var actionString=component.PowerOrdersMPageUtils.GetAvailableOrderActions(hMOEW,orderId);
}component.PowerOrdersMPageUtils.DestroyMOEW(hMOEW);
var orderObj=new foOrderActions();
orderObj.orderId=parseInt(orderId,10);
orderObj.canActivate=((actionString&4)==4);
orderObj.canCancel=((actionString&1)==1);
selectedTabData.push(orderObj);
}else{for(var i=selectedTabData.length;
i--;
){if(selectedTabData[i].orderId==parseInt(orderId,10)){selectedTabData.splice(i,1);
break;
}}}var actionFlag=foCanEnableActionBtn(selectedTabData);
if((actionFlag&1)==1){_g("btnActivateTab"+currTab).disabled=false;
}else{_g("btnActivateTab"+currTab).disabled=true;
}if((actionFlag&2)==2){_g("btnCancelTab"+currTab).disabled=false;
}else{_g("btnCancelTab"+currTab).disabled=true;
}},foOnActivate:function(componentId,tabIdx){var component=MP_Util.GetCompObjById(componentId);
var selectedTabData=component.arrFutureOrderTabData[tabIdx].tabSelectedOrders;
var MoewObj=component.PowerOrdersMPageUtils;
var hMOEW=MoewObj.CreateMOEW(component.getCriterion().person_id,component.getCriterion().encntr_id,0,2,127);
var d=new Date();
var twoDigit=function(num){(String(num).length<2)?num=String("0"+num):num=String(num);
return num;
};
var activateDate=""+d.getFullYear()+twoDigit((d.getMonth()+1))+twoDigit(d.getDate())+twoDigit(d.getHours())+twoDigit(d.getMinutes())+twoDigit(d.getSeconds())+"99";
var selectedTabCount=selectedTabData.length;
for(var i=selectedTabCount;
i--;
){var success=MoewObj.InvokeActivateAction(hMOEW,selectedTabData[i].orderId,activateDate);
}if(success==1){success=MoewObj.SignOrders(hMOEW);
}MoewObj.DestroyMOEW(hMOEW);
if(success==1){CERN_FUTURE_ORDERS_O1.RefreshFutureOrdersTable(componentId);
}},foOnCancel:function(componentId,tabIdx){var component=MP_Util.GetCompObjById(componentId);
var selectedTabData=component.arrFutureOrderTabData[tabIdx].tabSelectedOrders;
var MoewObj=component.PowerOrdersMPageUtils;
var hMOEW=MoewObj.CreateMOEW(component.getCriterion().person_id,component.getCriterion().encntr_id,0,2,127);
var m_dCancelDCReason=0;
var d=new Date();
var twoDigit=function(num){(String(num).length<2)?num=String("0"+num):num=String(num);
return num;
};
var cancelDate=""+d.getFullYear()+twoDigit((d.getMonth()+1))+twoDigit(d.getDate())+twoDigit(d.getHours())+twoDigit(d.getMinutes())+twoDigit(d.getSeconds())+"99";
var selectedTabCount=selectedTabData.length;
for(var i=selectedTabCount;
i--;
){var success=MoewObj.InvokeCancelDCAction(hMOEW,selectedTabData[i].orderId,cancelDate,m_dCancelDCReason);
}if(success==1){success=MoewObj.SignOrders(hMOEW);
}MoewObj.DestroyMOEW(hMOEW);
if(success==1){CERN_FUTURE_ORDERS_O1.RefreshFutureOrdersTable(componentId);
}}};
function BuildRequestParameters(component){var criterion=component.getCriterion();
var sEncntr=criterion.encntr_id;
var sendAr=[];
sendAr.push("^MINE^",criterion.person_id+".0",criterion.provider_id+".0",criterion.encntr_id+".0",criterion.position_cd+".0",criterion.ppr_cd+".0","^"+component.getLookBack()+"^","^"+component.getLookAhead()+"^","^^");
return sendAr;
}function DetermineSortClass(colHeader,sortIdx,sortOrder){if(colHeader==sortIdx){return(sortOrder==1?"fo-hdr-asc":"fo-hdr-desc");
}else{return"";
}}function BuildProviderFilter(component){var componentId=component.getComponentId();
var providerSelect=_g(componentId+"-provider-filter");
providerSelect.innerHTML="";
var newOption=Util.ce("option");
newOption.value="all";
newOption.text=i18n.cpoe.future_orders_o1.ALL_PROVIDERS;
newOption.selected=true;
providerSelect.add(newOption);
var providerListCount=component.providerFilterList.length;
for(var i=0;
i<providerListCount;
i++){newOption=Util.ce("option");
newOption.value=component.providerFilterList[i];
newOption.text=component.providerFilterList[i];
if(component.providerFilterList[i]==component.selectedProviderFilter){newOption.selected=true;
}providerSelect.add(newOption);
}}function BuildLocationFilter(component){var componentId=component.getComponentId();
var locationSelect=_g(componentId+"-location-filter");
locationSelect.innerHTML="";
var newOption=Util.ce("option");
newOption.value="all";
newOption.text=i18n.cpoe.future_orders_o1.ALL_LOCATIONS;
newOption.selected=true;
locationSelect.add(newOption);
var locationListCount=component.locationFilterList.length;
for(var i=0;
i<locationListCount;
i++){newOption=Util.ce("option");
newOption.value=component.locationFilterList[i];
newOption.text=component.locationFilterList[i];
if(component.locationFilterList[i]==component.selectedLocationFilter){newOption.selected=true;
}locationSelect.add(newOption);
}}function byString(index,dir,pushEmptyFieldsDown){return function(a,b){if(a==undefined||a==null){if(pushEmptyFieldsDown==true&&dir>0){a="zzzzzzzzzzzz";
}else{a="";
}}else{a=a[index];
}if(b==undefined||b==null){if(pushEmptyFieldsDown==true&&dir>0){b="zzzzzzzzzzzz";
}else{b="";
}}else{b=b[index];
}return a.toLowerCase()==b.toLowerCase()?0:(a.toLowerCase()<b.toLowerCase()?-1*dir:dir);
};
}function byInt(index,dir,pushNullZeroAndNegativeDown){return function(a,b){if(a==undefined||a==null){if(pushNullZeroAndNegativeDown==true&&dir>0){a=Number.MAX_VALUE;
}else{a=Number.MIN_VALUE;
}}else{a=parseInt(parseFloat(a[index]));
if(pushNullZeroAndNegativeDown==true&&a<=0){if(dir>0){a=Number.MAX_VALUE;
}else{a=Number.MIN_VALUE;
}}}if(b==undefined||b==null){if(pushNullZeroAndNegativeDown==true&&dir>0){b=Number.MAX_VALUE;
}else{b=Number.MIN_VALUE;
}}else{b=parseInt(parseFloat(b[index]));
if(pushNullZeroAndNegativeDown==true&&b<=0){if(dir>0){b=Number.MAX_VALUE;
}else{b=Number.MIN_VALUE;
}}}return a==b?0:(a<b?-1*dir:dir);
};
}function byISO8601Date(index,dir){return function(a,b){if(a==undefined||a==null){var dtA=new Date(1800,1,1);
}else{var dtA=new Date();
dtA.setISO8601(a[index]);
}if(b==undefined||b==null){var dtB=new Date(1800,1,1);
}else{var dtB=new Date();
dtB.setISO8601(b[index]);
}return dtA==dtB?0:(dtA<dtB?-1*dir:dir);
};
}function theSubset(subset,callback){return function(a,b){if(a==undefined||a==null){var A=undefined;
}else{var A=a[subset];
}if(b==undefined||b==null){var B=undefined;
}else{var B=b[subset];
}return callback(A,B);
};
}function theArrayIndex(array,index,callback){return function(a,b){if(a==undefined||a==null){var A=undefined;
}else{var arrA=a[array];
if(arrA.length>0){var A=arrA[index];
}else{A=undefined;
}}if(b==undefined||b==null){var B=undefined;
}else{var arrB=b[array];
if(arrB.length>0){var B=arrB[index];
}else{B=undefined;
}}return callback(A,B);
};
}function foSelectTab(componentId,selectedTabId){var component=MP_Util.GetCompObjById(componentId);
var tabs=component.arrFutureOrderTabData;
var tabsCount=tabs.length;
for(var i=0;
i<tabsCount;
i++){var tempTabId=componentId+"tab"+i;
var tempTabSecId=componentId+"tabsec"+i;
var tab=_g(tempTabId);
var tabsec=_g(tempTabSecId);
if(tempTabId==selectedTabId){tab.className="fo-selected";
tabsec.className="fo-tabsec-display";
component.currentTab=i;
}else{tab.className="";
tabsec.className="fo-tabsec-hide";
}}}function foCanEnableActionBtn(orderActionArray){if(orderActionArray.length==0){return 0;
}var activateInd=1;
var cancelInd=2;
for(var i=orderActionArray.length;
i--;
){var order=orderActionArray[i];
if(!order.canActivate){activateInd=0;
}if(!order.canCancel){cancelInd=0;
}if(!(activateInd||cancelInd)){return 0;
}}return activateInd+cancelInd;
}function foOrderActions(){this.orderId=0;
this.canActivate=false;
this.canCancel=false;
}}();
