function PrecautionsComponentO1Style(){this.initByNamespace("reh_prec");
}PrecautionsComponentO1Style.inherits(ComponentStyle);
function PrecautionsComponentO1(criterion){this.setCriterion(criterion);
this.setStyles(new PrecautionsComponentO1Style());
this.setComponentLoadTimerName("USR:MPG.Precautions.O1 - load component");
this.setComponentRenderTimerName("ENG:MPG.Precautions.O1 - render component");
this.setIncludeLineNumber(true);
this.setScope(2);
this.m_order=null;
PrecautionsComponentO1.method("InsertData",function(){CERN_PrecautionsO1.GetPrecautionsO1Table(this);
});
PrecautionsComponentO1.method("HandleSuccess",function(recordData){CERN_PrecautionsO1.RenderComponent(this,recordData);
});
PrecautionsComponentO1.method("setOrders",function(value){this.m_order=value;
});
PrecautionsComponentO1.method("addOrders",function(value){if(!this.m_order){this.m_order=[];
}this.m_order.push(value);
});
PrecautionsComponentO1.method("getOrders",function(){return this.m_order;
});
PrecautionsComponentO1.method("openTab",function(){MP_Util.LogMpagesEventInfo(this,"ORDERS",criterion.person_id+"|"+criterion.encntr_id+"|{ORDER|0|0|0|0|0}|0|{2|127}{3|127}|8","mp_precautions_o1.js","openTab");
MPAGES_EVENT("ORDERS",criterion.person_id+"|"+criterion.encntr_id+"|{ORDER|0|0|0|0|0}|0|{2|127}{3|127}|8");
});
}PrecautionsComponentO1.inherits(MPageComponent);
var CERN_PrecautionsO1=function(){return{GetPrecautionsO1Table:function(component){var sendAr=[];
var criterion=component.getCriterion();
var io1_encntrOption=0;
io1_encntr=(component.getScope()==1)?"0.0":(criterion.encntr_id+".0");
sendAr.push("^MINE^",criterion.person_id+".0",io1_encntr);
sendAr.push(MP_Util.CreateParamArray(component.getOrders(),1));
MP_Core.XMLCclRequestWrapper(component,"mp_reh_get_precautions",sendAr,true);
},RenderComponent:function(component,recordData){var m_rootComponentNode=component.getRootComponentNode();
var precI18n=i18n.discernabu.PrecautionsComponentO1;
var df=MP_Util.GetDateFormatter();
var jsPrecHTML=[];
var criterion=component.getCriterion();
var endDate="";
var dateTime=new Date();
jsPrecHTML.push("<div class = 'reh_prec_scrollable'>");
for(i=0;
i<recordData.QUAL_CNT;
i++){dateTime.setISO8601(recordData.QUAL[i].DATE);
endDate=df.format(dateTime,mp_formatter.DateTimeFormatter.FULL_DATE_4YEAR);
jsPrecHTML.push("<dl class='reh_prec-info'><dt class='reh_prec-name'>",recordData.QUAL[i].NAME,"</dt><dd class='reh_prec-date'>",endDate,"</dd></dl>");
jsPrecHTML.push("<h4 class='det-hd'><span>Precaution Details</span></h4><div class='hvr'><dl class = 'reh_prec-det'><dt><span>",precI18n.ORDER,":</span></dt><dd><span>",recordData.QUAL[i].NAME,"</dd></span><dt><span>",precI18n.ORDER_DATE,":</span></dt><dd><span>",endDate,"</dd></span><dt><span>",precI18n.ORDER_DETAILS,":</span></dt><dd><span>",recordData.QUAL[i].DETAILS,"</dd></span>");
if(recordData.QUAL[i].COMMENT_TEXT!==""){jsPrecHTML.push("<dt><span>",precI18n.ORDER_COMMENT,":</span></dt>","<dd><span>",recordData.QUAL[i].COMMENT_TEXT,"</span></dd>");
}jsPrecHTML.push("</dl></div>");
}jsPrecHTML.push("</div>");
jsPrecHTML=jsPrecHTML.join("");
MP_Util.Doc.FinalizeComponent(jsPrecHTML,component,"");
if(component.isScrollingEnabled()){if(component.getScrollNumber()<recordData.QUAL_CNT){MP_Util.Doc.InitScrolling(Util.Style.g("reh_prec_scrollable",m_rootComponentNode,"div"),component.getScrollNumber(),"1.6");
}}}};
}();
