function PreopChcklstComponentStyle(){this.initByNamespace("pch");
}PreopChcklstComponentStyle.inherits(ComponentStyle);
function PreopChcklstComponent(criterion){this.m_LastFdIntake=null;
this.m_LastFlIntake=null;
this.m_anesCnst=null;
this.m_bldCnst=null;
this.m_ordrsCmplt=null;
this.m_ecgOrdrs=null;
this.m_hcgOrdrs=null;
this.m_hNp=null;
this.m_surgPrepVer=null;
this.m_IdVerf=null;
this.m_bldBand=null;
this.m_prIdBand=null;
this.m_prSiteVer=null;
this.m_prSiteVerRN=null;
this.m_prSiteVerMD=null;
this.m_prImplntAvail=null;
this.m_prBldAvail=null;
this.m_prEquipAvail=null;
this.m_whoVerfSite=null;
this.m_RNWhoVerfSite=null;
this.m_LastFluidNPO=null;
this.m_LastFoodNPO=null;
this.m_LastFoodEval=null;
this.m_HnPReviewedAndUpdated=null;
this.setCriterion(criterion);
this.setStyles(new PreopChcklstComponentStyle());
this.setComponentLoadTimerName("USR:MPG.PREOPCHKLST.O1 - load component");
this.setComponentRenderTimerName("ENG:MPG.PREOPCHKLST.O1 - render component");
this.setIncludeLineNumber(false);
this.setResourceRequired(true);
this.m_periopCaseObj=null;
PreopChcklstComponent.method("InsertData",function(){CERN_PREOP_CHKLST_O1.GetPreopChcklstTable(this);
});
PreopChcklstComponent.method("HandleSuccess",function(recordData){CERN_PREOP_CHKLST_O1.RenderComponent(this,recordData);
});
PreopChcklstComponent.method("RetrieveRequiredResources",function(){var caseResource=MP_Resources.getSharedResource("periopCaseIds");
var criterion=this.getCriterion();
var scriptParams=[];
if(caseResource){if(caseResource.isResourceAvailable()){this.loadCaseData(null,caseResource.getResourceData());
return;
}else{caseResource.retrieveSharedResourceData();
CERN_EventListener.addListener(this,"periopCaseInfoAvailable",this.loadCaseData,this);
}}else{scriptParams=["^MINE^",criterion.person_id+".0",criterion.encntr_id+".0",criterion.provider_id+".0",criterion.position_cd+".0",criterion.ppr_cd+".0",1];
caseResource=MP_Resources.createSharedResourceObj("periopCaseIds",this,"mp_get_cases",scriptParams,"periopCaseInfoAvailable");
if(caseResource){caseResource.retrieveSharedResourceData();
CERN_EventListener.addListener(this,"periopCaseInfoAvailable",this.loadCaseData,this);
}}});
PreopChcklstComponent.method("loadCaseData",function(element,caseData){try{var casesJSON=JSON.parse(caseData).CASES_REC;
var periopCase=new MP_Core.PeriopCases();
var countDown=casesJSON.PROC_CNTDWN;
periopCase.setCaseID(casesJSON.CASE_ID);
periopCase.setDays(countDown.DAYS);
periopCase.setHours(countDown.HOURS);
periopCase.setMins(countDown.MINS);
periopCase.setCntdwnDscFlg(countDown.CNTDWN_DESC_FLAG);
this.m_periopCaseObj=periopCase;
CERN_PREOP_CHKLST_O1.GetPreopChcklstTable(this);
}catch(err){MP_Util.LogJSError(err,this,"preop-chklst.js","loadCaseData");
var errMsg=[];
errMsg.push("<strong>",i18n.JS_ERROR,"</strong><br><ul><li>",i18n.MESSAGE,": ",err.message,"</li><li>",i18n.NAME,": ",err.name,"</li><li>",i18n.NUMBER,": ",(err.number&65535),"</li><li>",i18n.DESCRIPTION,": ",err.description,"</li></ul>");
MP_Util.Doc.FinalizeComponent(MP_Util.HandleErrorResponse(this.getStyles().getNameSpace(),errMsg.join("")),this,"");
}});
PreopChcklstComponent.method("openTab",function(){var criterion=this.getCriterion();
var sParms="/PERSONID="+criterion.person_id+" /ENCNTRID="+criterion.encntr_id+" /FIRSTTAB=^"+this.getLink()+"+^";
APPLINK(0,criterion.executable,sParms);
this.InsertData();
});
PreopChcklstComponent.method("setLastFdIntake",function(value){this.m_LastFdIntake=value;
});
PreopChcklstComponent.method("getLastFdIntake",function(){if(this.m_LastFdIntake){return this.m_LastFdIntake;
}});
PreopChcklstComponent.method("setLastFlIntake",function(value){this.m_LastFlIntake=value;
});
PreopChcklstComponent.method("getLastFlIntake",function(){if(this.m_LastFlIntake){return this.m_LastFlIntake;
}});
PreopChcklstComponent.method("setAnesCnst",function(value){this.m_anesCnst=value;
});
PreopChcklstComponent.method("getAnesCnst",function(){if(this.m_anesCnst){return this.m_anesCnst;
}});
PreopChcklstComponent.method("setBldCnst",function(value){this.m_bldCnst=value;
});
PreopChcklstComponent.method("getBldCnst",function(){if(this.m_bldCnst){return this.m_bldCnst;
}});
PreopChcklstComponent.method("setSurgCnst",function(value){this.m_surgCnst=value;
});
PreopChcklstComponent.method("getSurgCnst",function(){if(this.m_surgCnst){return this.m_surgCnst;
}});
PreopChcklstComponent.method("setOrdrsCmplt",function(value){this.m_ordrsCmplt=value;
});
PreopChcklstComponent.method("getOrdrsCmplt",function(){if(this.m_ordrsCmplt){return this.m_ordrsCmplt;
}});
PreopChcklstComponent.method("setEcgOrdrs",function(value){this.m_ecgOrdrs=value;
});
PreopChcklstComponent.method("getEcgOrdrs",function(){if(this.m_ecgOrdrs){return this.m_ecgOrdrs;
}});
PreopChcklstComponent.method("setHcgOrdrs",function(value){this.m_hcgOrdrs=value;
});
PreopChcklstComponent.method("getHcgOrdrs",function(){if(this.m_hcgOrdrs){return this.m_hcgOrdrs;
}});
PreopChcklstComponent.method("setHnP",function(value){this.m_hNp=value;
});
PreopChcklstComponent.method("getHnP",function(){if(this.m_hNp){return this.m_hNp;
}});
PreopChcklstComponent.method("setSurgPrepVer",function(value){this.m_surgPrepVer=value;
});
PreopChcklstComponent.method("getSurgPrepVer",function(){if(this.m_surgPrepVer){return this.m_surgPrepVer;
}});
PreopChcklstComponent.method("setIdVerf",function(value){this.m_IdVerf=value;
});
PreopChcklstComponent.method("getIdVerf",function(){if(this.m_IdVerf){return this.m_IdVerf;
}});
PreopChcklstComponent.method("setBldBand",function(value){this.m_bldBand=value;
});
PreopChcklstComponent.method("getBldBand",function(){if(this.m_bldBand){return this.m_bldBand;
}});
PreopChcklstComponent.method("setPrIdBand",function(value){this.m_prIdBand=value;
});
PreopChcklstComponent.method("getPrIdBand",function(){if(this.m_prIdBand){return this.m_prIdBand;
}});
PreopChcklstComponent.method("setPrSiteVer",function(value){this.m_prSiteVer=value;
});
PreopChcklstComponent.method("getPrSiteVer",function(){if(this.m_prSiteVer){return this.m_prSiteVer;
}});
PreopChcklstComponent.method("setPrSiteVerRN",function(value){this.m_prSiteVerRN=value;
});
PreopChcklstComponent.method("getPrSiteVerRN",function(){if(this.m_prSiteVerRN){return this.m_prSiteVerRN;
}});
PreopChcklstComponent.method("setPrSiteVerMD",function(value){this.m_prSiteVerMD=value;
});
PreopChcklstComponent.method("getPrSiteVerMD",function(){if(this.m_prSiteVerMD){return this.m_prSiteVerMD;
}});
PreopChcklstComponent.method("setPrImplntAvail",function(value){this.m_prImplntAvail=value;
});
PreopChcklstComponent.method("getPrImplntAvail",function(){if(this.m_prImplntAvail){return this.m_prImplntAvail;
}});
PreopChcklstComponent.method("setPrBldAvail",function(value){this.m_prBldAvail=value;
});
PreopChcklstComponent.method("getPrBldAvail",function(){if(this.m_prBldAvail){return this.m_prBldAvail;
}});
PreopChcklstComponent.method("setPrEquipAvail",function(value){this.m_prEquipAvail=value;
});
PreopChcklstComponent.method("getPrEquipAvail",function(){if(this.m_prEquipAvail){return this.m_prEquipAvail;
}});
PreopChcklstComponent.method("setWhoVerfSite",function(value){this.m_whoVerfSite=value;
});
PreopChcklstComponent.method("getWhoVerfSite",function(){if(this.m_whoVerfSite){return this.m_whoVerfSite;
}});
PreopChcklstComponent.method("setRNWhoVerfSite",function(value){this.m_RNWhoVerfSite=value;
});
PreopChcklstComponent.method("getRNWhoVerfSite",function(){if(this.m_RNWhoVerfSite){return this.m_RNWhoVerfSite;
}});
PreopChcklstComponent.method("setLastFluidNPO",function(value){this.m_LastFluidNPO=value;
});
PreopChcklstComponent.method("getLastFluidNPO",function(){if(this.m_LastFluidNPO){return this.m_LastFluidNPO;
}});
PreopChcklstComponent.method("setLastFoodNPO",function(value){this.m_LastFoodNPO=value;
});
PreopChcklstComponent.method("getLastFoodNPO",function(){if(this.m_LastFoodNPO){return this.m_LastFoodNPO;
}});
PreopChcklstComponent.method("setLastFoodEval",function(value){this.m_LastFoodEval=value;
});
PreopChcklstComponent.method("getLastFoodEval",function(){if(this.m_LastFoodEval){return this.m_LastFoodEval;
}});
PreopChcklstComponent.method("setHnPReviewedAndUpdated",function(value){this.m_HnPReviewedAndUpdated=value;
});
PreopChcklstComponent.method("getHnPReviewedAndUpdated",function(){if(this.m_HnPReviewedAndUpdated){return this.m_HnPReviewedAndUpdated;
}});
}PreopChcklstComponent.prototype=new MPageComponent();
PreopChcklstComponent.prototype.constructor=MPageComponent;
PreopChcklstComponent.prototype.loadFilterMappings=function(){this.addFilterMappingObject("LAST_FLUID_NPO",{setFunction:this.setLastFluidNPO,type:"NUMBER",field:"FREETEXT_DESC"});
this.addFilterMappingObject("LAST_FOOD_NPO",{setFunction:this.setLastFoodNPO,type:"NUMBER",field:"FREETEXT_DESC"});
this.addFilterMappingObject("LAST_FOOD_EVAL",{setFunction:this.setLastFoodEval,type:"NUMBER",field:"FREETEXT_DESC"});
this.addFilterMappingObject("HP_RVW_UPDATED",{setFunction:this.setHnPReviewedAndUpdated,type:"ARRAY",field:"PARENT_ENTITY_ID"});
};
var CERN_PREOP_CHKLST_O1=function(){return{GetPreopChcklstTable:function(component){var sendAr=[];
var criterion=component.getCriterion();
var periopCase=component.m_periopCaseObj;
var case_id=periopCase.getCaseID();
if(case_id==null){case_id=0;
}function formatForCodeList(eventCodeList){return(eventCodeList&&eventCodeList.length)?"value("+eventCodeList.join(".0,")+".0)":"0.0";
}var fdIntake=component.getLastFdIntake()||{};
var lstFdIntake=(fdIntake.length)?"value("+fdIntake.join(".0,")+".0)":"0.0";
var flIntake=component.getLastFlIntake();
var lstFlIntake=(flIntake&&flIntake!==null&&flIntake.length>0)?"value("+flIntake.join(".0,")+".0)":"0.0";
var anesCnst=component.getAnesCnst();
var anesthCnst=(anesCnst&&anesCnst!==null&&anesCnst.length>0)?"value("+anesCnst.join(".0,")+".0)":"0.0";
var bldCnst=component.getBldCnst();
var buildCnst=(bldCnst&&bldCnst!==null&&bldCnst.length>0)?"value("+bldCnst.join(".0,")+".0)":"0.0";
var surgCnst=component.getSurgCnst();
var surgeryCnst=(surgCnst&&surgCnst!==null&&surgCnst.length>0)?"value("+surgCnst.join(".0,")+".0)":"0.0";
var ordrsCmplt=component.getOrdrsCmplt();
var ordersComplete=(ordrsCmplt&&ordrsCmplt!==null&&ordrsCmplt.length>0)?"value("+ordrsCmplt.join(".0,")+".0)":"0.0";
var ecgOrdrs=component.getEcgOrdrs();
var ecgOrders=(ecgOrdrs&&ecgOrdrs!==null&&ecgOrdrs.length>0)?"value("+ecgOrdrs.join(".0,")+".0)":"0.0";
var hcgOrdrs=component.getHcgOrdrs();
var hcgOrders=(hcgOrdrs&&hcgOrdrs!==null&&hcgOrdrs.length>0)?"value("+hcgOrdrs.join(".0,")+".0)":"0.0";
var hNp=component.getHnP();
var hAndP=(hNp&&hNp!==null&&hNp.length>0)?"value("+hNp.join(".0,")+".0)":"0.0";
var srgPrpVer=component.getSurgPrepVer();
var surgPrepVer=(srgPrpVer&&srgPrpVer!==null&&srgPrpVer.length>0)?"value("+srgPrpVer.join(".0,")+".0)":"0.0";
var idPrpVer=component.getIdVerf();
var idPrepVerf=(idPrpVer&&idPrpVer!==null&&idPrpVer.length>0)?"value("+idPrpVer.join(".0,")+".0)":"0.0";
var bldBnd=component.getBldBand();
var bldBand=(bldBnd&&bldBnd!==null&&bldBnd.length>0)?"value("+bldBnd.join(".0,")+".0)":"0.0";
var prIdBnd=component.getPrIdBand();
var perIdBand=(prIdBnd&&prIdBnd!==null&&prIdBnd.length>0)?"value("+prIdBnd.join(".0,")+".0)":"0.0";
var prStVr=component.getPrSiteVer();
var prSiteVer=(prStVr&&prStVr!==null&&prStVr.length>0)?"value("+prStVr.join(".0,")+".0)":"0.0";
var prStVrRn=component.getPrSiteVerRN();
var prSiteVerRN=(prStVrRn&&prStVrRn!==null&&prStVrRn.length>0)?"value("+prStVrRn.join(".0,")+".0)":"0.0";
var prStVrMd=component.getPrSiteVerMD();
var prSiteVerMD=(prStVrMd&&prStVrMd!==null&&prStVrMd.length>0)?"value("+prStVrMd.join(".0,")+".0)":"0.0";
var prImpltAvail=component.getPrImplntAvail();
var prImplantAvail=(prImpltAvail&&prImpltAvail!==null&&prImpltAvail.length>0)?"value("+prImpltAvail.join(".0,")+".0)":"0.0";
var prBldAval=component.getPrBldAvail();
var prBldAvail=(prBldAval&&prBldAval!==null&&prBldAval.length>0)?"value("+prBldAval.join(".0,")+".0)":"0.0";
var prEqpAval=component.getPrEquipAvail();
var prEquipAvail=(prEqpAval&&prEqpAval!==null&&prEqpAval.length>0)?"value("+prEqpAval.join(".0,")+".0)":"0.0";
var whVrfSte=component.getWhoVerfSite();
var whoVerfSite=(whVrfSte&&whVrfSte!==null&&whVrfSte.length>0)?"value("+whVrfSte.join(".0,")+".0)":"0.0";
var rnWhVrfSte=component.getRNWhoVerfSite();
var RNWhoVerfSite=(rnWhVrfSte&&rnWhVrfSte!==null&&rnWhVrfSte.length>0)?"value("+rnWhVrfSte.join(".0,")+".0)":"0.0";
var lastFluidNPO=component.getLastFluidNPO();
lastFluidNPO=(lastFluidNPO)?lastFluidNPO:"0.0";
var lastFoodNPO=component.getLastFoodNPO();
lastFoodNPO=(lastFoodNPO)?lastFoodNPO:"0.0";
var lastFoodEval=component.getLastFoodEval();
lastFoodEval=(lastFoodEval)?lastFoodEval:"0.0";
var hnPReviewedAndUpdated=formatForCodeList(component.getHnPReviewedAndUpdated());
if(component.getScope()==2){encntrOption=criterion.encntr_id+".0";
}else{var prsnlInfo=criterion.getPersonnelInfo();
var encntrs=prsnlInfo.getViewableEncounters();
encntrOption=(encntrs)?"value("+encntrs+")":"0.0";
}sendAr.push("^MINE^",criterion.person_id+".0",encntrOption,criterion.provider_id,criterion.ppr_cd,case_id+".0",component.getLookbackUnits(),component.getLookbackUnitTypeFlag(),lstFdIntake,lstFlIntake,anesthCnst,buildCnst,surgeryCnst,ecgOrders,hcgOrders,ordersComplete,hAndP,surgPrepVer,idPrepVerf,bldBand,perIdBand,prSiteVer,prSiteVerRN,prSiteVerMD,prImplantAvail,prBldAvail,prEquipAvail,whoVerfSite,RNWhoVerfSite,lastFluidNPO,lastFoodNPO,lastFoodEval,hnPReviewedAndUpdated);
MP_Core.XMLCclRequestWrapper(component,"mp_get_preop_chklst",sendAr,true);
},RenderComponent:function(component,recordData){var timerRenderComponent=MP_Util.CreateTimer(component.getComponentRenderTimerName());
var countText="";
function pchGetIcon(item,numResults){var icon="";
if(item.length<numResults){icon=pchStop;
}else{var color=0;
for(var i=0,l=item.length;
i<l;
i++){if(item[i].COLOR>color){color=item[i].COLOR;
}}if(color==1){icon=pchGo;
}else{if(color==2){icon=pchCaution;
}else{icon=pchStop;
}}}return icon;
}function pchGetFlag(color){var flag="";
if(color==3){flag="<span class='pch-stop'>*";
}else{if(color==2){flag="<span class='pch-caution'>*";
}else{flag="<span>";
}}return flag;
}function buildWithinTime(rowData){var wthnTxt="";
if(rowData.DAYS){wthnTxt=rowData.DAYS+" "+preop_chklst_i18n.DAYS;
}if(rowData.HOURS||wthnTxt){wthnTxt=wthnTxt+" "+rowData.HOURS+" "+preop_chklst_i18n.HOURS;
}if(rowData.MINS){wthnTxt=wthnTxt+" "+rowData.MINS+" "+preop_chklst_i18n.MINS;
}else{wthnTxt=wthnTxt+" "+0+" "+preop_chklst_i18n.MINS;
}return wthnTxt;
}function npoBuildRow(rowName,rowData){var tmpHTML=[];
if(rowData){var npoPtInfo=(rowData.PAT_INFO)?df.formatISO8601(rowData.PAT_INFO,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_4YEAR):"";
var npoDocDtTm=(rowData.DOC_DT_TM)?df.formatISO8601(rowData.DOC_DT_TM,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_4YEAR):"";
tmpHTML.push("<tr><td class='pch-det-lbl'>",pchGetFlag(rowData.COLOR),rowName,":</span></td><td><span>",npoPtInfo,"</span></td><td><span>",npoDocDtTm,"</span></td><td><span>",buildWithinTime(rowData),"</span></td></tr>");
}else{tmpHTML.push("<tr><td class='pch-det-lbl'><span class='pch-stop'>*",rowName,":</span></td><td colspan='3'>&nbsp;</td></tr>");
}return tmpHTML.join("");
}function cnstSigned(cnstResult){if(cnstResult&&cnstResult.SIGNED){var signedValue=cnstResult.SIGNED.toUpperCase();
return(signedValue=="YES"||signedValue=="Y");
}else{return false;
}}function pchGetConIcon(conAnesth,conBlood,conSurg){var icon="";
var surgCnstReqMet=!component.getSurgCnst()||cnstSigned(conSurg);
var bloodCnstReqMet=!component.getBldCnst()||cnstSigned(conBlood);
var anesCnstReqMet=!component.getAnesCnst()||cnstSigned(conAnesth)||conAnesth.CONTAINS_MAC===0;
if(anesCnstReqMet&&bloodCnstReqMet&&surgCnstReqMet){icon=pchGo;
}else{icon=pchStop;
}return icon;
}function conGetFlag(item){var flag="";
var itemType=item.TYPE;
var sgn=item.SIGNED.toUpperCase();
if(((itemType==2&&item.CONTAINS_MAC==1)||itemType!=2)&&(sgn=="NO"||sgn=="N")){flag="<span class='pch-stop'>*";
}else{flag="<span>";
}return flag;
}function conBuildRow(rowName,rowData){var tmpHTML=[];
if(rowData!==""){var sDocDtTm="";
if(rowData.DOC_DT_TM){sDocDtTm=df.formatISO8601(rowData.DOC_DT_TM,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_4YEAR);
}tmpHTML.push("<tr><td>",conGetFlag(rowData),rowName,"</span></td><td><span>",rowData.SIGNED,"</span></td><td><span>",sDocDtTm,"</span></td><td><span>",rowData.COMMENT,"</span></td></tr>");
}else{tmpHTML.push("<tr><td class='pch-det-lbl'><span class='pch-stop'>*",rowName,":</span></td><td colspan='3'>&nbsp;</td></tr>");
}return tmpHTML.join("");
}function hnPBuildRow(hnpItem,hnpLabel,hnpData){var tmpHTML=[];
var hnpDocDt=(hnpItem.DOC_DT_TM)?df.formatISO8601(hnpItem.DOC_DT_TM,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_4YEAR):"";
tmpHTML.push("<tr><td class='pch-det-lbl'>",pchGetFlag(hnpItem.COLOR),hnpLabel+"</span></td><td><span>",hnpData,"</span></td><td><span>",hnpDocDt,"</span></td><td><span>",hnpItem.DOC_BY,"</span></td></tr>");
return tmpHTML.join("");
}function idBuildRow(rowName,rowData){var tmpHTML=[];
if(rowData!==""){var flagInd=0;
var rowVer=rowData.VERIFIED;
var rowVerInd=rowVer.toUpperCase();
var sDocDtTm="";
if(rowVerInd=="NO"||rowVerInd=="N"){flagInd=3;
}if(rowData.DOC_DT_TM){sDocDtTm=df.formatISO8601(rowData.DOC_DT_TM,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_4YEAR);
}tmpHTML=[];
tmpHTML.push("<tr><td class='pch-det-lbl'>",pchGetFlag(flagInd),rowName,":</span></td><td><span>",rowVer,"</span></td><td><span>",sDocDtTm,"</span></td><td><span>",rowData.COMMENT,"</span></td>");
}else{tmpHTML.push("<tr><td class='pch-det-lbl'>",pchGetFlag(3),rowName,":</span></td><td colspan='3'>&nbsp;</td></tr>");
}return tmpHTML.join("");
}function pchGetSiteInd(fam,rn){var ind="";
if(fam!==""){var famVer=fam.VERIFIED.toUpperCase();
if(famVer!="YES"&&famVer!="Y"){ind=3;
}else{if(rn!==""){var rnVer=rn.VERIFIED.toUpperCase();
if(rnVer=="YES"||rnVer=="Y"){ind=1;
}else{ind=2;
}}else{ind=2;
}}}else{ind=3;
}return ind;
}function siteGetFlag(item,siteInd){var flag="";
var itemInd=item.toUpperCase();
if(siteInd==3&&(itemInd!="YES"&&itemInd!="Y")){flag="<span class='pch-stop'>*";
}else{if(siteInd==2&&(itemInd!="YES"&&itemInd!="Y")){flag="<span class='pch-caution'>*";
}else{flag="<span>";
}}return flag;
}function siteBuildRow(rowName,rowData,siteInd,nameFlag){var tmpHTML=[];
var rowVerified="";
var rowVerFlag="";
if(rowData!==""&&rowData!==null){if(nameFlag){rowVerified=rowData.NAME;
rowVerFlag="Y";
}else{rowVerified=rowData.VERIFIED;
rowVerFlag=rowVerified;
}var sDocDtTm="";
if(rowData.DOC_DT_TM){sDocDtTm=df.formatISO8601(rowData.DOC_DT_TM,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_4YEAR);
}tmpHTML.push("<tr><td class='pch-det-lbl'>",siteGetFlag(rowVerFlag,siteInd),rowName,":</span></td><td><span>",rowVerified,"</span></td><td><span>",sDocDtTm,"</span></td><td><span>",rowData.COMMENT,"</span></td></tr>");
}else{if(nameFlag){rowVerFlag="Y";
}tmpHTML.push("<tr><td class='pch-det-lbl'>",siteGetFlag(rowVerFlag,siteInd),rowName,":</span></td><td colspan='3'>&nbsp;</td></tr>");
}return tmpHTML.join("");
}try{var preop_chklst_i18n=i18n.discernabu.preop_chklst_i18n;
var pchObj=recordData;
var jsPchHTML=[];
var hvrHTML=[];
var criterion=component.getCriterion();
var pchGo=criterion.static_content+"/images/4022_16.gif";
var pchCaution=criterion.static_content+"/images/5682.gif";
var pchStop=criterion.static_content+"/images/3727.gif";
var df=new mp_formatter.DateTimeFormatter(MPAGE_LOCALE);
var numRows=0;
var mappedFieldCnt=0;
var groups=component.getGroups();
var fdIntake=component.getLastFdIntake();
var flIntake=component.getLastFlIntake();
if(fdIntake||flIntake){var npoObj=pchObj.NPO||{};
var npoFood="";
var npoFluid="";
for(var i=0,l=npoObj.length;
i<l;
i++){var npoItem=npoObj[i];
var npoType=npoItem.NPO_TYPE;
if(npoType==1){npoFood=npoItem;
}else{if(npoType==2){npoFluid=npoItem;
}}}if(fdIntake){hvrHTML.push(npoBuildRow(preop_chklst_i18n.LAST_FOOD_INTAKE,npoFood));
mappedFieldCnt+=1;
}if(flIntake){hvrHTML.push(npoBuildRow(preop_chklst_i18n.LAST_FLUID_INTAKE,npoFluid));
mappedFieldCnt+=1;
}if(mappedFieldCnt){numRows+=1;
}jsPchHTML.push("<h3 class='pch-info-hd'><span>"+preop_chklst_i18n.NPO+"</span></h3><dl class='pch-info'><dt><span>"+preop_chklst_i18n.NPO+"</span></dt><dd class='pch-ind'><span><img src='",pchGetIcon(npoObj,mappedFieldCnt),"' /></span></dd></dl><h4><span class='pch-det-hd'>"+preop_chklst_i18n.NPO_DETAILS+"</span></h4><div class='pch-det hvr pch-4-col'><dl><dd><table><tr class='pch-det-hdr'><td><span>&nbsp;</span></td><td><span>"+preop_chklst_i18n.PATIENT_INFO+"</span></td><td><span>"+preop_chklst_i18n.DOC_DT_TM+"</span></td><td><span>"+preop_chklst_i18n.WITHIN_SURG_ANT_STRT+"</span></td></tr>",hvrHTML.join(""),"</table></dd></dl></div>");
}var anesCnst=component.getAnesCnst();
var bldCnst=component.getBldCnst();
var surgCnst=component.getSurgCnst();
if(anesCnst||bldCnst||surgCnst){var conObj=pchObj.CONSENTS||{};
var conAnesth="";
var conBlood="";
var conSurg="";
for(var i=0,l=conObj.length;
i<l;
i++){var conItem=conObj[i];
var conType=conItem.TYPE;
if(conType==1){conSurg=conItem;
}else{if(conType==2){conAnesth=conItem;
}else{if(conType==3){conBlood=conItem;
}}}}hvrHTML=[];
mappedFieldCnt=0;
if(anesCnst){hvrHTML.push(conBuildRow(preop_chklst_i18n.ANESTHESIA,conAnesth));
mappedFieldCnt+=1;
}if(bldCnst){hvrHTML.push(conBuildRow(preop_chklst_i18n.BLOOD,conBlood));
mappedFieldCnt+=1;
}if(surgCnst){hvrHTML.push(conBuildRow(preop_chklst_i18n.SURGICAL,conSurg));
mappedFieldCnt+=1;
}if(mappedFieldCnt){numRows+=1;
}jsPchHTML.push("<h3 class='pch-info-hd'><span>",preop_chklst_i18n.CONSENTS,"</span></h3><dl class='pch-info'><dt><span>",preop_chklst_i18n.CONSENTS,"</span></dt><dd class='pch-ind'><span><img src='",pchGetConIcon(conAnesth,conBlood,conSurg),"' /></span></dd></dl><h4><span class='pch-det-hd'>",preop_chklst_i18n.CONSENT_DETAILS,"</span></h4><div class='pch-det hvr pch-4-col'><dl><dd><table><tr class='pch-det-hdr'><td><span>",preop_chklst_i18n.CONSENT,"</span></td><td><span>",preop_chklst_i18n.SIGNED,"</span></td><td><span>",preop_chklst_i18n.DOC_DT_TM,"</span></td><td><span>",preop_chklst_i18n.COMMENT,"</span></td></tr>",hvrHTML.join(""),"</table></dd></dl></div>");
}var ordObj=pchObj.ORDERS_COMPLETE||{};
if(ordObj.length){numRows=numRows+1;
var ordItem=ordObj[0];
pchOrdComplete=ordItem.ORDERS_COMPLETE;
var sOrdDtTm="";
if(ordItem.DOC_DT_TM){sOrdDtTm=df.formatISO8601(ordItem.DOC_DT_TM,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_4YEAR);
}jsPchHTML.push("<h3 class='pch-info-hd'>"+preop_chklst_i18n.ORDERS+"</h3><dl class='pch-info'><dt><span>"+preop_chklst_i18n.ORDERS+"</span></dt><dd class='pch-ind'><span>",pchOrdComplete,"</span></dd></dl><h4><span class='pch-det-hd'>"+preop_chklst_i18n.ORDR_DETAILS+"</span></h4><div class='pch-det hvr'><dl><dt><span>"+preop_chklst_i18n.PREOP_ORDRS_COMPLETE+"</span></dt><dd><span>",pchOrdComplete,"</span></dd><dt><span>"+preop_chklst_i18n.DOC_DT_TM+":</span></dt><dd><span>",sOrdDtTm,"</span></dd><dt><span>"+preop_chklst_i18n.DOC_BY+":</span></dt><dd><span>",ordItem.DOC_BY,"</span></dd></dl></div>");
}var ecgOrdrs=component.getEcgOrdrs();
if(ecgOrdrs){numRows=numRows+1;
var ecgObj=pchObj.ECG||{};
var ecgIcon=pchCaution;
var ecgColor=2;
var ecgMedRec="";
var ecgDocDt="";
var ecgDocBy="";
if(ecgObj.length){var ecgItem=ecgObj[0];
ecgIcon=pchGetIcon(ecgObj,1);
ecgColor=ecgItem.COLOR;
ecgMedRec=ecgItem.IN_MED_REC;
if(ecgItem.DOC_DT_TM){ecgDocDt=df.formatISO8601(ecgItem.DOC_DT_TM,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_4YEAR);
}ecgDocBy=ecgItem.DOC_BY;
}jsPchHTML.push("<h3 class='pch-info-hd'>"+preop_chklst_i18n.ECG+"</h3><dl class='pch-info'><dt><span>"+preop_chklst_i18n.ECG+"</span></dt><dd class='pch-ind'><span><img src='",ecgIcon,"' /></span></dd></dl><h4><span class='pch-det-hd'>"+preop_chklst_i18n.ECG_DETAILS+"</span></h4><div class='pch-det hvr'><dl><dt>",pchGetFlag(ecgColor),preop_chklst_i18n.CURRENT_ECG+":</span></dt><dd><span>",ecgMedRec,"</span></dd><dt><span>"+preop_chklst_i18n.DOC_DT_TM+":</span></dt><dd><span>",ecgDocDt,"</span></dd><dt><span>"+preop_chklst_i18n.DOC_BY+":</span></dt><dd><span>",ecgDocBy,"</span></dd></dl></div>");
}if(recordData.SEX_DISP){var hcgOrdrs=component.getHcgOrdrs();
if(hcgOrdrs){if(recordData.SEX_DISP.toUpperCase()=="FEMALE"){numRows=numRows+1;
var hcgObj=pchObj.HCG||{};
var hcgIcon=pchCaution;
var hcgColor=2;
var hcgLabs="";
var hcgDocDt="";
var hcgDocBy="";
if(hcgObj.length){var hcgItem=hcgObj[0];
hcgIcon=pchGetIcon(hcgObj,1);
hcgColor=hcgItem.COLOR;
hcgLabs=hcgItem.REVIEW_LABS;
if(hcgItem.DOC_DT_TM){hcgDocDt=df.formatISO8601(hcgItem.DOC_DT_TM,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_4YEAR);
}hcgDocBy=hcgItem.DOC_BY;
}jsPchHTML.push("<h3 class='pch-info-hd'>"+preop_chklst_i18n.HCG+"</h3><dl class='pch-info'><dt><span>"+preop_chklst_i18n.HCG+"</span></dt><dd class='pch-ind'><span><img src='",hcgIcon,"' /></span></dd></dl><h4><span class='pch-det-hd'>"+preop_chklst_i18n.HCG_DETAILS+"</span></h4><div class='pch-det hvr'><dl><dt>",pchGetFlag(hcgColor),preop_chklst_i18n.REVIEW_OF_LABS+":</span></dt><dd><span>",hcgLabs,"</span></dd><dt><span>"+preop_chklst_i18n.DOC_DT_TM+":</span></dt><dd><span>",hcgDocDt,"</span></dd><dt><span>"+preop_chklst_i18n.DOC_BY+":</span></dt><dd><span>",hcgDocBy,"</span></dd></dl></div>");
}}}var hnpCodes=component.getHnP();
var hnpRnUCodes=component.getHnPReviewedAndUpdated();
if(hnpCodes||hnpRnUCodes){var hnpObj=pchObj.HNP||{};
var hnprnuObj=pchObj.HNPRNU||{};
var tmpObj="";
var tmpData="";
var tmpLbl="";
numRows+=1;
hvrHTML=[];
if(hnpObj.length){tmpObj=hnpObj[0];
tmpData=hnpObj[0].IN_MED_REC;
tmpLbl=preop_chklst_i18n.CUR_H_P_IN_MED_REC;
}hvrHTML.push(hnPBuildRow(tmpObj,tmpLbl,tmpData));
if(hnprnuObj.length){tmpObj=hnprnuObj[0];
tmpData=hnprnuObj[0].REV_AND_UPT;
tmpLbl=preop_chklst_i18n.CUR_H_P_REV_AND_UPT;
}hvrHTML.push(hnPBuildRow(tmpObj,tmpLbl,tmpData));
var hnpIcon=pchStop;
if((pchGetIcon(hnpObj,1)==pchGo)&&(pchGetIcon(hnprnuObj,1)==pchGo)){hnpIcon=pchGo;
}jsPchHTML.push("<h3 class='pch-info-hd'>"+preop_chklst_i18n.H_P+"</h3><dl class='pch-info'><dt><span>"+preop_chklst_i18n.H_P+"</span></dt><dd class='pch-ind'><span><img src='",hnpIcon,"' /></span></dd></dl><h4><span class='pch-det-hd'>"+preop_chklst_i18n.H_P_DETAILS+"</span></h4><div class='pch-det hvr pch-4-col'><dl><dd><table><tr class='pch-det-hdr'><td><span>&nbsp;</span></td><td><span>",preop_chklst_i18n.VERIFIED,"</span></td><td><span>",preop_chklst_i18n.DOC_DT_TM,"</span></td><td><span>",preop_chklst_i18n.DOC_BY,"</span></td></tr>",hvrHTML.join(""),"</table></dd></dl></div>");
}var srgPrpVer=component.getSurgPrepVer();
if(srgPrpVer){var prepObj=pchObj.PREPVERIFIED||{};
var prepIcon=pchCaution;
var prepColor=2;
var prepVer="";
var prepDocDt="";
var prepDocBy="";
numRows=numRows+1;
if(prepObj.length){prepItem=prepObj[0];
prepIcon=pchGetIcon(prepObj,1);
prepColor=prepItem.COLOR;
prepVer=prepItem.PREP_VERIFIED;
if(prepItem.DOC_DT_TM){prepDocDt=df.formatISO8601(prepItem.DOC_DT_TM,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_4YEAR);
}prepDocBy=prepItem.DOC_BY;
}jsPchHTML.push("<h3 class='pch-info-hd'>"+preop_chklst_i18n.PREP_VERIFIED+"</h3><dl class='pch-info'><dt><span>"+preop_chklst_i18n.PREP_VERIFIED+"</span></dt><dd class='pch-ind'><span><img src='",prepIcon,"' /></span></dd></dl><h4><span class='pch-det-hd'>"+preop_chklst_i18n.PREP_VER_DETAILS+"</span></h4><div class='pch-det hvr'><dl><dt>",pchGetFlag(prepColor),preop_chklst_i18n.SURG_PREP_VERIFIED+"</span></dt><dd><span>",prepVer,"</span></dd><dt><span>"+preop_chklst_i18n.DOC_DT_TM+":</span></dt><dd><span>",prepDocDt,"</span></dd><dt><span>"+preop_chklst_i18n.DOC_BY+":</span></dt><dd><span>",prepDocBy,"</span></dd></dl></div>");
}var idPrpVer=component.getIdVerf();
var bldBnd=component.getBldBand();
var prIdBnd=component.getPrIdBand();
if(idPrpVer||bldBnd||prIdBnd){var idObj=pchObj.IDVERIFICATION||{};
var idLen=idObj.length;
var idFlag=true;
var idIcon="";
if(idLen){idFlag=false;
for(var i=0;
i<idLen;
i++){var idVer=idObj[i].VERIFIED.toUpperCase();
if(idVer!="YES"&&idVer!="Y"){idFlag=true;
}}}if(idFlag){idIcon=pchStop;
}else{idIcon=pchGo;
}var idAl="";
var idBlood="";
var idId="";
for(var i=0;
i<idLen;
i++){var idItem=idObj[i];
var idType=idItem.TYPE;
if(idType==1){idAl=idItem;
}else{if(idType==2){idBlood=idItem;
}else{if(idType==3){idId=idItem;
}}}}hvrHTML=[];
mappedFieldCnt=0;
if(idPrpVer){hvrHTML.push(idBuildRow(preop_chklst_i18n.ALLERGY_BAND,idAl));
mappedFieldCnt+=1;
}if(bldBnd){hvrHTML.push(idBuildRow(preop_chklst_i18n.BLOOD_BAND,idBlood));
mappedFieldCnt+=1;
}if(prIdBnd){hvrHTML.push(idBuildRow(preop_chklst_i18n.ID_BAND,idId));
mappedFieldCnt+=1;
}if(mappedFieldCnt){numRows+=1;
}jsPchHTML.push("<h3 class='pch-info-hd'>",preop_chklst_i18n.ID_VERF,"</h3><dl class='pch-info'><dt><span>",preop_chklst_i18n.ID_VERF,"</span></dt><dd class='pch-ind'><span><img src='",idIcon,"' /></span></dd></dl><h4><span class='pch-det-hd'>",preop_chklst_i18n.IDVERIF_DETAILS,"</span></h4><div class='pch-det hvr pch-4-col'><dl><dd><table><tr class='pch-det-hdr'><td><span>&nbsp;</span></td><td><span>",preop_chklst_i18n.VERIFIED,"</span></td><td><span>",preop_chklst_i18n.DOC_DT_TM,"</span></td><td><span>",preop_chklst_i18n.COMMENT,"</span></td></tr>",hvrHTML.join(""),"</table></dd></dl></div>");
}var prStVr=component.getPrSiteVer();
var prStVrRn=component.getPrSiteVerRN();
var prStVrMd=component.getPrSiteVerMD();
if(prStVr||prStVrRn||prStVrMd){var siteObj=pchObj.SITEVERIFICATION||{};
var siteInd=3;
var siteIcon=pchStop;
var siteFam="";
var siteRN="";
var siteDr="";
var siteRNWho="";
var siteDrWho="";
for(var i=0,l=siteObj.length;
i<l;
i++){var siteItem=siteObj[i];
var siteType=siteItem.TYPE;
if(siteType==1){siteFam=siteItem;
}else{if(siteType==2){siteRN=siteItem;
siteRNWho=(pchObj.RNWHOVERIFIED&&pchObj.RNWHOVERIFIED.length)?pchObj.RNWHOVERIFIED[0]:"";
}else{if(siteType==3){siteDr=siteItem;
siteDrWho=(pchObj.PHYSICIANWHOVERIFIED&&pchObj.PHYSICIANWHOVERIFIED.length)?pchObj.PHYSICIANWHOVERIFIED[0]:"";
}}}}siteInd=pchGetSiteInd(siteFam,siteRN);
if(siteInd==1){siteIcon=pchGo;
}else{if(siteInd==2){siteIcon=pchCaution;
}else{siteIcon=pchStop;
}}jsPchHTML.push("<h3 class='pch-info-hd'>"+preop_chklst_i18n.SITE_VERF+"</h3><dl class='pch-info'><dt><span>"+preop_chklst_i18n.SITE_VERF+"</span></dt><dd class='pch-ind'><span><img src='",siteIcon,"' /></span></dd></dl><h4><span class='pch-det-hd'>"+preop_chklst_i18n.SITE_VERF_DETAILS+"</span></h4><div class='pch-det hvr pch-4-col'><dl><dd><table><tr class='pch-det-hdr'><td><span>"+preop_chklst_i18n.SITE_VERF_BY+":</span></td><td><span>"+preop_chklst_i18n.WHO_VERF+"</span></td><td><span>"+preop_chklst_i18n.DOC_DT_TM+"</span></td><td><span>"+preop_chklst_i18n.COMMENT+"</span></td></tr>",siteBuildRow(preop_chklst_i18n.PATIENT_FAMILY,siteFam),siteBuildRow(preop_chklst_i18n.RN,siteRN),siteBuildRow(preop_chklst_i18n.PHYSICIAN,siteDr),siteBuildRow(preop_chklst_i18n.RN_VERF_SITE,siteRNWho,siteInd,1),siteBuildRow(preop_chklst_i18n.PHYS_VERF_SITE,siteDrWho,siteInd,1),"</table></dd></dl></div>");
}var iaObj=pchObj.IMPLANTSAVAILABLE||{};
if(iaObj.length){numRows=numRows+1;
var iaItem=iaObj[0];
var iaRes=iaItem.RESULT;
var sIaDocDtTm="";
if(iaItem.DOC_DT_TM){sIaDocDtTm=df.formatISO8601(iaItem.DOC_DT_TM,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_4YEAR);
}jsPchHTML.push("<h3 class='pch-info-hd'>"+preop_chklst_i18n.IMPLANTS_AVAIL+"</h3><dl class='pch-info'><dt><span>"+preop_chklst_i18n.IMPLANTS_AVAIL+"</span></dt><dd class='pch-ind'><span>",iaRes,"</span></dd></dl><h4><span class='pch-det-hd'>"+preop_chklst_i18n.IMPL_AVAIL_DETAILS+"</span></h4><div class='pch-det hvr'><dl><dt><span>"+preop_chklst_i18n.IMPLANT_AVAIL+":</span></dt><dd><span>",iaRes,"</span></dd><dt><span>"+preop_chklst_i18n.DOC_DT_TM+":</span></dt><dd><span>",sIaDocDtTm,"</span></dd><dt><span>"+preop_chklst_i18n.DOC_BY+":</span></dt><dd><span>",iaItem.DOC_BY,"</span></dd></dl></div>");
}var baObj=pchObj.BLOODAVAILABLE||{};
if(baObj.length){numRows=numRows+1;
var baItem=baObj[0];
var baRes=baItem.RESULT;
var sBaDocDtTm="";
if(baItem.DOC_DT_TM){sBaDocDtTm=df.formatISO8601(baItem.DOC_DT_TM,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_4YEAR);
}jsPchHTML.push("<h3 class='pch-info-hd'>"+preop_chklst_i18n.BLOOD_AVAILABLE+"</h3><dl class='pch-info'><dt><span>"+preop_chklst_i18n.BLOOD_AVAILABLE+"</span></dt><dd class='pch-ind'><span>",baRes,"</span></dd></dl><h4><span class='pch-det-hd'>"+preop_chklst_i18n.BLOOD_AVAIL_DETAILS+"</span></h4><div class='pch-det hvr'><dl><dt><span>"+preop_chklst_i18n.BLOOD_AVAIL+":</span></dt><dd><span>",baRes,"</span></dd><dt><span>"+preop_chklst_i18n.DOC_DT_TM+":</span></dt><dd><span>",sBaDocDtTm,"</span></dd><dt><span>"+preop_chklst_i18n.DOC_BY+":</span></dt><dd><span>",baItem.DOC_BY,"</span></dd></dl></div>");
}var seaObj=pchObj.SPECIALEQUIPAVAILABLE||{};
if(seaObj.length){numRows=numRows+1;
var seaItem=seaObj[0];
var seaRes=seaItem.RESULT;
var sSeaDocDtTm="";
if(seaItem.DOC_DT_TM){sSeaDocDtTm=df.formatISO8601(seaItem.DOC_DT_TM,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_4YEAR);
}jsPchHTML.push("<h3 class='pch-info-hd'>"+preop_chklst_i18n.SPEC_EQUIP_AVAIL+"</h3><dl class='pch-info'><dt><span>"+preop_chklst_i18n.SPEC_EQUIP_AVAIL+"</span></dt><dd class='pch-ind'><span>",seaRes,"</span></dd></dl><h4><span class='pch-det-hd'>"+preop_chklst_i18n.SPEC_EQUIP_AVAIL_DETAILS+"</span></h4><div class='pch-det hvr'><dl><dt><span>"+preop_chklst_i18n.SPEC_EQIP_AVAIL+":</span></dt><dd><span>",seaRes,"</span></dd><dt><span>"+preop_chklst_i18n.DOC_DT_TM+":</span></dt><dd><span>",sSeaDocDtTm,"</span></dd><dt><span>"+preop_chklst_i18n.DOC_BY+":</span></dt><dd><span>",seaItem.DOC_BY,"</span></dd></dl></div>");
}var content=[];
content.push("<div class='",MP_Util.GetContentClass(component,numRows),"'>",jsPchHTML.join(""),"</div>");
countText="";
MP_Util.Doc.FinalizeComponent(content.join(""),component,countText);
}catch(err){var errMsg=[];
errMsg.push("<b>",i18n.JS_ERROR,"</b><br><ul><li>",i18n.MESSAGE,": ",err.message,"</li><li>",i18n.NAME,": ",err.name,"</li><li>",i18n.NUMBER,": ",(err.number&65535),"</li><li>",i18n.DESCRIPTION,": ",err.description,"</li></ul>");
MP_Util.Doc.FinalizeComponent(MP_Util.HandleErrorResponse(component.getStyles().getNameSpace(),errMsg.join("")),component,countText);
if(timerRenderComponent){timerRenderComponent.Abort();
timerRenderComponent=null;
}throw (err);
}finally{if(timerRenderComponent){timerRenderComponent.Stop();
}}}};
}();
