function SocialHistoryo2ComponentStyle(){this.initByNamespace("sh2");
}SocialHistoryo2ComponentStyle.inherits(ComponentStyle);
function SocialHistoryComponentO2(criterion){this.setCriterion(criterion);
this.setStyles(new SocialHistoryo2ComponentStyle());
this.setComponentLoadTimerName("USR:MPG.SOCIAL_HISTORY.O2 - load component");
this.setComponentRenderTimerName("ENG:MPG.SOCIAL_HISTORY.O2 - render component");
this.setIncludeLineNumber(true);
this.setScope(1);
SocialHistoryComponentO2.method("InsertData",function(){CERN_SOCIAL_HISTORY_O2.GetSocialHistoryO2Table(this);
});
SocialHistoryComponentO2.method("HandleSuccess",function(recordData){CERN_SOCIAL_HISTORY_O2.RenderComponent(this,recordData);
});
SocialHistoryComponentO2.method("resizeComponent",function(){MPageComponent.prototype.resizeComponent.call(this,null);
var contentBody=$("#"+this.getStyles().getContentId()).find(".content-body");
if(contentBody.length){var maxHeight=parseInt($(contentBody).css("max-height").replace("px",""),10);
if(!isNaN(maxHeight)){if($(contentBody).outerHeight()>=maxHeight){$("#headerSocHistoryo2"+this.getComponentId()).addClass("sh2-inner-div-shifted");
}else{$("#headerSocHistoryo2"+this.getComponentId()).removeClass("sh2-inner-div-shifted");
}}}});
}SocialHistoryComponentO2.inherits(MPageComponent);
var CERN_SOCIAL_HISTORY_O2=function(){return{GetSocialHistoryO2Table:function(component){var sendAr=[];
var criterion=component.getCriterion();
sendAr.push("^MINE^",criterion.person_id+".0",criterion.provider_id+".0",criterion.ppr_cd+".0");
MP_Core.XMLCclRequestWrapper(component,"MP_GET_SOCIAL_HISTORY",sendAr,true);
CERN_EventListener.fireEvent(component,component,EventListener.EVENT_COUNT_UPDATE,{count:0});
},RenderComponent:function(component,recordData){try{var i=0;
var j=0;
var shhtml="";
var compId=component.getComponentId();
var tblHdrId="headerSocHistoryo2"+compId;
var hhcount=0;
var social;
var socDetlCnt=0;
var socDetl="";
var comntCnt=0;
var comment="";
var shArray=[];
var category="";
var riskAssessment="";
var updatedPrsn="";
var personnelArray=MP_Util.LoadPersonelListJSON(recordData.PRSNL);
var codeArray=MP_Util.LoadCodeListJSON(recordData.CODES);
var df=new mp_formatter.DateTimeFormatter(MPAGE_LOCALE);
var updateDT=new Date();
var eventObj="";
var socialCnt=recordData.SOCIAL_CNT;
shArray.push("<div class='sh2-outer-div'><div id='",tblHdrId,"'><table class='sh2-table'><tr><th class='sh2-left-fixed-header'>",i18n.CATEGORY,"</th><th class='sh2-right-fixed-header'>",i18n.DETAILS,"</th></tr></table></div></div><div  class ='",MP_Util.GetContentClass(component,socialCnt),"'><table class='sh2-table'>");
recordData.SOCIAL.sort(function(a,b){if(a.CATEGORY.toUpperCase()<b.CATEGORY.toUpperCase()){return -1;
}return 1;
});
for(i=0;
i<socialCnt;
i++){hhcount=i;
social=recordData.SOCIAL[i];
category=social.CATEGORY;
if(social.RISK_ASSESSMENT_CD>0){eventObj=MP_Util.GetValueFromArray(social.RISK_ASSESSMENT_CD,codeArray);
riskAssessment=eventObj.display;
}else{riskAssessment="";
}var updatedTime="";
if(social.UPDT_DT_TM!==""){updateDT.setISO8601(social.UPDT_DT_TM);
updatedTime=df.format(updateDT,mp_formatter.DateTimeFormatter.FULL_DATE_4YEAR);
}if(social.UPDT_PRSNL_ID>0){var prsnlObj=MP_Util.GetValueFromArray(social.UPDT_PRSNL_ID,personnelArray);
updatedPrsn=prsnlObj.fullName;
}else{updatedPrsn="";
}var comments=social.COMMENTS;
var commentTxt="";
if(social.COMMENT_CNT>0){var commentsLen=comments.length;
for(var x=0;
x<commentsLen;
x++){var cmmtDate=df.formatISO8601(comments[x].COMMENT_DT,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_4YEAR);
commentTxt+=cmmtDate+" - "+comments[x].COMMENT_PRSNL_NAME+" - "+comments[x].COMMENT_TXT+"<br />";
}}var detailTxt=[];
var detailTag="";
var detailsCnt=0;
var howerht="howerhtSocHistoryo2"+compId+"_";
var yellowFill="yellowFillSocHistoryo2"+compId+"_";
var shHoverText=[];
detailTxt.push("<dl class='sh2-info result-info'><dt>",i18n.DETAILS,"</dt><dd>");
if(social.SHX_DETAIL_CNT>0){detailsCnt=social.SHX_DETAIL[0].DETAIL_QUAL.length;
for(j=0;
j<detailsCnt;
j++){if(j<4){detailTxt.push("<span class='sh2-detail-lbl'>",social.SHX_DETAIL[0].DETAIL_QUAL[j].DETAIL_LABEL,"</span> <span class='sh2-detail'>",social.SHX_DETAIL[0].DETAIL_QUAL[j].DETAIL_RESPONSE,"</span>");
}else{shHoverText.push("<dt><span class='sh2-detail-lbl'>",social.SHX_DETAIL[0].DETAIL_QUAL[j].DETAIL_LABEL,"</span></dt><dt><span class='sh2-detail'>",social.SHX_DETAIL[0].DETAIL_QUAL[j].DETAIL_RESPONSE,"</span></dt><br />");
}}detailTxt.push("</dd></dl><div id = '",howerht+hhcount,"' class = 'result-details hover'><h4 class='det-hd'>",i18n.SOCIAL_HISTORY_DETAILS,":</h4><dl class='sh2-det'>",shHoverText.join(""),"<dt><span class='sh2-detail-lbl'>",i18n.RCM_LAST_REVIEW_DATE,":</span></dt><dt><span class='sh2-detail'>",updatedTime,"</span></dt><br/><dt><span class='sh2-detail-lbl'>",i18n.LAST_UPDATED,":</span></dt><dt><span class='sh2-detail'>",updatedTime,"</span></dt><br/><dt><span class='sh2-detail-lbl'>",i18n.LAST_UPDATED_BY,":</span></dt><dt><span class='sh2-detail'>",updatedPrsn,"</span></dt><br /><dt><span class='sh2-detail-lbl'>",i18n.COMMENTS,":</span></dt><dt><span class='sh2-detail' style='padding-bottom:6px'>",commentTxt,"</span>","</dt></dl></div>");
}else{detailTxt.push("<span class='sh2-detail-lbl'>--</span>   </dd></dl>");
detailTxt.push("<div id = '",howerht+hhcount,"' class = 'result-details hover'><h4 class='det-hd'>",i18n.SOCIAL_HISTORY_DETAILS,":</h4><dl class='sh2-det'>",shHoverText.join(""),"<dt><span class='sh2-detail-lbl'>",i18n.RCM_LAST_REVIEW_DATE,":</span></dt><dt><span class='sh2-detail'>",updatedTime,"</span></dt><br/><dt><span class='sh2-detail-lbl'>",i18n.LAST_UPDATED,":</span></dt><dt><span class='sh2-detail'>",updatedTime,"</span></dt><br/><dt><span class='sh2-detail-lbl'>",i18n.LAST_UPDATED_BY,":</span></dt><dt><span class='sh2-detail'>",updatedPrsn,"</span></dt><br /><dt><span class='sh2-detail-lbl'>",i18n.COMMENTS,":</span></dt><dt><span class='sh2-detail' style='padding-bottom:6px'>",commentTxt,"</span>","</dt></dl></div>");
}var riskAssessHigh="";
if(eventObj.meaning=="HIGHRISK"){riskAssessHigh="res-severe";
}var zebraStriping=(i%2===0)?"odd":"even";
var zebraRowId="zebraRowIdSocHistoryo2"+compId+"_";
shArray.push("<tr class='",zebraStriping,"' id = '",zebraRowId+hhcount,"' ><td class='sh2-cell-1' >",category,"</td><td class='sh2-cell-2' id='",yellowFill+hhcount,"'><div  onmouseover=CERN_SOCIAL_HISTORY_O2.twoColHover(",hhcount,",",detailsCnt,"); onmouseleave = CERN_SOCIAL_HISTORY_O2.getOrgColor(",hhcount,") >",detailTxt.join(""),"</div></td></tr>");
this.twoColHover=function(id,e){$("#yellowFillSocHistoryo2"+compId+"_"+id).css("background-color","#FFC");
var social=recordData.SOCIAL[id];
var vheight=$(window).height();
var hheight=$("#howerhtSocHistoryo2"+compId+"_"+id).height();
var split=e/2;
var splitTruncate=(split%2===0)?split:parseInt(split,10)+1;
var shHoverText1=[];
var shHoverText2=[];
var shHoverText12=[];
var detailTxt12=[];
var detailTag="";
var ar=[];
var category=social.CATEGORY;
if(social.RISK_ASSESSMENT_CD>0){eventObj=MP_Util.GetValueFromArray(social.RISK_ASSESSMENT_CD,codeArray);
riskAssessment=eventObj.display;
}else{riskAssessment="";
}var updatedTime="";
if(social.UPDT_DT_TM!==""){updateDT.setISO8601(social.UPDT_DT_TM);
updatedTime=df.format(updateDT,mp_formatter.DateTimeFormatter.FULL_DATE_4YEAR);
}if(social.UPDT_PRSNL_ID>0){var prsnlObj=MP_Util.GetValueFromArray(social.UPDT_PRSNL_ID,personnelArray);
updatedPrsn=prsnlObj.fullName;
}else{updatedPrsn="";
}var comments=social.COMMENTS;
var commentTxt="";
if(social.COMMENT_CNT>0){var commentsLen=comments.length;
for(var x=0;
x<commentsLen;
x++){var cmmtDate=df.formatISO8601(comments[x].COMMENT_DT,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_4YEAR);
commentTxt+=cmmtDate+" - "+comments[x].COMMENT_PRSNL_NAME+" - "+comments[x].COMMENT_TXT+"<br />";
}}$("#howerhtSocHistoryo2"+compId+"_"+id).css("width","400px");
for(j=0;
j<e;
j++){if(j>=4){shHoverText12.push("<dt><span class='sh2-detail-lbl'>",social.SHX_DETAIL[0].DETAIL_QUAL[j].DETAIL_LABEL,"</span></dt><dt><span class='sh2-detail'>",social.SHX_DETAIL[0].DETAIL_QUAL[j].DETAIL_RESPONSE,"</span></dt><br />");
}}detailTxt12.push("<div><dl class='sh2-det'>",shHoverText12.join(""),"<dt><span class='sh2-detail-lbl'>",i18n.RCM_LAST_REVIEW_DATE,":</span></dt><dt><span class='sh2-detail'>",updatedTime,"</span></dt><br/><dt><span class='sh2-detail-lbl'>",i18n.LAST_UPDATED,":</span></dt><dt><span class='sh2-detail'>",updatedTime,"</span></dt><br/><dt><span class='sh2-detail-lbl'>",i18n.LAST_UPDATED_BY,":</span></dt><dt><span class='sh2-detail'>",updatedPrsn,"</span></dt><br /><dt><span class='sh2-detail-lbl'>",i18n.COMMENTS,":</span></dt><dt><span class='sh2-detail' style='padding-bottom:6px'>",commentTxt,"</span>","</dt></dl></div>");
var app=(detailTxt12.join(""));
$("#howerhtSocHistoryo2"+compId+"_"+id).html(app);
if(hheight+25>=vheight){if((e-4)>=4){$("#howerhtSocHistoryo2"+compId+"_"+id).css("width","820px");
for(var soc=4;
soc<splitTruncate+4;
soc++){shHoverText1.push("<dt><span class='sh2-detail-lbl'>",social.SHX_DETAIL[0].DETAIL_QUAL[soc].DETAIL_LABEL,"</span></dt><dt><span class='sh2-detail'>",social.SHX_DETAIL[0].DETAIL_QUAL[soc].DETAIL_RESPONSE,"</span></dt><br />");
}for(var i=splitTruncate+4;
i<e;
i++){shHoverText2.push("<dt><span class='sh2-detail-lbl'>",social.SHX_DETAIL[0].DETAIL_QUAL[i].DETAIL_LABEL,"</span></dt><dt><span class='sh2-detail'>",social.SHX_DETAIL[0].DETAIL_QUAL[i].DETAIL_RESPONSE,"</span></dt><br />");
}shHoverText2.push("<dt><span class='sh2-detail-lbl'>",i18n.RCM_LAST_REVIEW_DATE,":</span></dt><dt><span class='sh2-detail'>",updatedTime,"</span></dt><br/><dt><span class='sh2-detail-lbl'>",i18n.LAST_UPDATED,":</span></dt><dt><span class='sh2-detail'>",updatedTime,"</span></dt><br/><dt><span class='sh2-detail-lbl'>",i18n.LAST_UPDATED_BY,":</span></dt><dt><span class='sh2-detail'>",updatedPrsn,"</span></dt><br /><dt><span class='sh2-detail-lbl'>",i18n.COMMENTS,":</span></dt><dt><span class='sh2-detail' style='padding-bottom:6px'>",commentTxt,"</span>","</dt>");
detailTag=i18n.DETAILS;
ar=["<ul id = 'hower' style='width:900px; height: auto;'><div class='sh2-inner'>",shHoverText1.join(""),"</div><div class='sh2-divider'></div><div class='sh2-inner' style='padding-left: 16px;'>",shHoverText2.join(""),"</div></ul>"];
var hvrconcat=(ar.join(""));
$("#howerhtSocHistoryo2"+compId+"_"+id).html(hvrconcat);
}}};
this.getOrgColor=function(o){var cName=document.getElementById("zebraRowIdSocHistoryo2"+compId+"_"+o).className;
if(cName=="even"){$("#yellowFillSocHistoryo2"+compId+"_"+o).css("background-color","#e8ebf5");
}else{$("#yellowFillSocHistoryo2"+compId+"_"+o).css("background-color","#FFF");
}};
}shArray.push("</table></div>");
shhtml=shArray.join("");
countText=MP_Util.CreateTitleText(component,socialCnt);
component.finalizeComponent(shhtml,countText);
CERN_EventListener.fireEvent(component,component,EventListener.EVENT_COUNT_UPDATE,{count:socialCnt});
}catch(err){throw (err);
}finally{}}};
}();
