function TopThreeGoalsComponentStyle(){this.initByNamespace("topthreegoals");
}TopThreeGoalsComponentStyle.inherits(ComponentStyle);
function TopThreeGoalsComponent(criterion){this.setCriterion(criterion);
this.setStyles(new TopThreeGoalsComponentStyle());
}TopThreeGoalsComponent.prototype=new MPageComponent();
TopThreeGoalsComponent.prototype.constructor=MPageComponent;
TopThreeGoalsComponent.prototype.retrieveComponentData=function(){var criterion=this.getCriterion();
var prsnlInfo=criterion.getPersonnelInfo();
var encntrs=prsnlInfo.getViewableEncounters();
var encntrVal=(encntrs)?"value("+encntrs+")":"0.0";
var sendAr=["^MINE^",criterion.person_id+".0",encntrVal,"^LTC^",0];
MP_Core.XMLCclRequestWrapper(this,"INN_MP_GET_LTC_OUTCOMES",sendAr,true);
};
TopThreeGoalsComponent.prototype.renderComponent=function(recordData){var scriptStatus=recordData.STATUS_DATA.STATUS;
switch(scriptStatus){case"S":var tableHtml="<div class='content-hdr'><dl class='outcome-info-hdr hdr'><dd>"+i18n.innov.topthreegoals.TITLE_PRIORITY+"</dd><dd>"+i18n.innov.topthreegoals.TITLE_GOAL+"</dd><dd>"+i18n.innov.topthreegoals.TITLE_STATUS+"</dd></dl></div><div class='content-body'>";
var unmetOutcomes=recordData.UNMETOUTCOMES;
unmetOutcomes.sort(function(a,b){return a.PRIORITY-b.PRIORITY;
});
var typeList=recordData.TYPELIST;
var categoryList=recordData.CATEGORYLIST;
for(var i=0,l=unmetOutcomes.length;
i<l;
i++){var unmetOutcome=unmetOutcomes[i];
var priority=unmetOutcome.PRIORITY;
var rowHtml="";
if(priority<=3&&priority>=1){var status="";
var type=[];
var category=[];
if(unmetOutcome.METIND===1){status=i18n.innov.topthreegoals.STATUS_MET;
}else{status=i18n.innov.topthreegoals.STATUS_UNMET;
}for(var j=0,tlength=unmetOutcome.TYPE.length;
j<tlength;
j++){for(var m=0,typeL=typeList.length;
m<typeL;
m++){if(typeList[m].CODE_VALUE===unmetOutcome.TYPE[j].TYPE_CD){type.push(typeList[m].DISPLAY);
}}}for(j=0,clength=unmetOutcome.CATEGORY.length;
j<clength;
j++){var outcomeCategoryCd=unmetOutcome.CATEGORY[j].CATEGORY_CD;
for(var n=0,catL=categoryList.length;
n<catL;
n++){if(categoryList[n].CODE_VALUE===outcomeCategoryCd){category.push(categoryList[n].DISPLAY);
}}}var startDtTm=new Date();
startDtTm.setISO8601(unmetOutcome.STARTDTTM);
var startDate=startDtTm.format("longDateTime3");
rowHtml+="<dl class='outcome-info result-info'><dd>"+priority+"</dd><dd>"+unmetOutcome.DESCRIPTION+"</dd><dd>"+status+"</dd></dl>";
rowHtml+="<div class='hover result-details'><dl>";
rowHtml+="<dt><span>"+i18n.innov.topthreegoals.TITLE_PRIORITY+": "+priority+"</span></dt>";
rowHtml+="<dt><span>"+i18n.innov.topthreegoals.TITLE_GOAL+": "+unmetOutcome.DESCRIPTION+"</span></dt>";
rowHtml+="<dt><span>"+i18n.innov.topthreegoals.TITLE_INTERVENTION+":</span>";
for(var o=0,interL=unmetOutcome.INTERVENTIONS.length;
o<interL;
o++){rowHtml+="<dt><span>"+(o+1)+". "+unmetOutcome.INTERVENTIONS[o].INTERVENTION+" (";
if(unmetOutcome.INTERVENTIONS[o].FLAG){rowHtml+=i18n.innov.topthreegoals.FLAG_MET;
}else{rowHtml+=i18n.innov.topthreegoals.FLAG_NOTMET;
}rowHtml+=")</span></dt>";
}rowHtml+="</dt>";
rowHtml+="<dt><span>"+i18n.innov.topthreegoals.TITLE_TYPE+": "+type.join("; ")+"</span></dt>";
rowHtml+="<dt><span>"+i18n.innov.topthreegoals.TITLE_CATEGORY+": "+category.join("; ")+"</span></dt>";
rowHtml+="<dt><span>"+i18n.innov.topthreegoals.TITLE_STATUS+": "+status+"</span></dt>";
rowHtml+="<dt><span>"+i18n.innov.topthreegoals.TITLE_COMMENT+": "+unmetOutcome.COMMENT+"</span></dt>";
rowHtml+="<dt><span>"+i18n.innov.topthreegoals.CREATED+": "+startDate+" - "+unmetOutcome.PROVIDER_NAME_FULL_FORMATTED+"</span></dt>";
rowHtml+="<dt><span>"+i18n.innov.topthreegoals.LASTUPDATE+": "+unmetOutcome.LAST_UPDATE_DT_TM+" - "+unmetOutcome.LAST_UPDATE_PROVIDER_NAME_FULL_FORMATTED+"</span></dt>";
rowHtml+="</dl></div>";
tableHtml+=rowHtml;
}}tableHtml+="</div>";
break;
case"Z":tableHtml=i18n.innov.topthreegoals.ERROR;
break;
case"F":tableHtml=i18n.innov.topthreegoals.NODATA;
break;
}this.finalizeComponent(tableHtml,"");
};
MP_Util.setObjectDefinitionMapping("TOP_3_PARAMS",TopThreeGoalsComponent);
