;****************************************************************************
;    *                      GENERATED MODIFICATION CONTROL LOG              *
;    ************************************************************************
;    *                                                                      *
;    *Mod    Date     	Engineer              Comment                       *
;    *---   ------------ -------------------- ------------------------------*
;     000  						               Initial Release 				  *
;     001 	05/19/14	 Akcia				  add change suggested by cerner		*
;****************************************************************************
;*** Generated by translate command; please verify contents before re-including in CCL ***
DROP PROGRAM   MAYO_MN_FN_UDT_FORM_HEADER : DBA  GO
CREATE PROGRAM  MAYO_MN_FN_UDT_FORM_HEADER : DBA
 
DECLARE  ADDRESS_CD  =  F8  WITH  PROTECT , CONSTANT ( UAR_GET_CODE_BY ("MEANING" ,  212 ,
"BUSINESS" ))
 
DECLARE  PHONE_CD  =  F8  WITH  PROTECT , CONSTANT ( UAR_GET_CODE_BY ("MEANING" ,  43 , "BUSINESS" )
)
 
DECLARE  STEXT  =  VC
 
DECLARE  FACILITY  =  VC
 
DECLARE  ADDY1  =  VC
 
DECLARE  ADDY2  =  VC
 
DECLARE  CITY  =  VC
 
DECLARE  STATE  =  VC
 
DECLARE  ZIP  =  VC
 
DECLARE  PHONE  =  VC
 
DECLARE  POPULATE  =  I2  WITH  NOCONSTANT ( 0 )
 
DECLARE  LEN  =  I4
 
SET  POPULATE  =  0
 
SELECT  INTO "nl:"
FROM ( ENCOUNTER  E ),
( ADDRESS  A ),
( PHONE  P )
 PLAN ( E
WHERE (E.ENCNTR_ID= REQUEST -> ENCNTR_ID ) AND (E.BEG_EFFECTIVE_DT_TM<= SYSDATE ) AND (
E.END_EFFECTIVE_DT_TM> SYSDATE ) AND (E.ACTIVE_IND= 1 ))
 AND ( A
WHERE (A.PARENT_ENTITY_ID= OUTERJOIN (E.LOC_FACILITY_CD)) AND (A.PARENT_ENTITY_NAME= OUTERJOIN (
"LOCATION" )) AND (A.ADDRESS_TYPE_CD= OUTERJOIN ( ADDRESS_CD )) AND (A.BEG_EFFECTIVE_DT_TM<=
 OUTERJOIN ( SYSDATE )) AND (A.END_EFFECTIVE_DT_TM> OUTERJOIN ( SYSDATE )) AND (A.ACTIVE_IND=
 OUTERJOIN ( 1 )))
 AND ( P
WHERE (P.PARENT_ENTITY_ID= OUTERJOIN (E.LOC_FACILITY_CD)) AND (A.PARENT_ENTITY_NAME= OUTERJOIN (
"LOCATION" )) AND (P.PHONE_TYPE_CD= OUTERJOIN ( PHONE_CD )) AND (P.BEG_EFFECTIVE_DT_TM<= OUTERJOIN (
 SYSDATE )) AND (P.END_EFFECTIVE_DT_TM> OUTERJOIN ( SYSDATE )) AND (P.ACTIVE_IND= OUTERJOIN ( 1 )))
 
 
DETAIL
 POPULATE = 1 ,
 ;001  LEN = SIZE ( UAR_GET_CODE_DESCRIPTION (E.LOC_FACILITY_CD)),
 ;001  FACILITY = SUBSTRING ( 4 ,  LEN ,  UAR_GET_CODE_DESCRIPTION (E.LOC_FACILITY_CD)),
 FACILITY = SUBSTRING ( 4 , 60 ,  UAR_GET_CODE_DESCRIPTION (E.LOC_FACILITY_CD)),		;001
 ADDY1 = TRIM (A.STREET_ADDR),
 ADDY2 = TRIM (A.STREET_ADDR2),
 CITY = TRIM (A.CITY),
 
IF ( (A.STATE_CD> 0 ) )  STATE = UAR_GET_CODE_DISPLAY (A.STATE_CD)
ELSE   STATE =A.STATE
ENDIF
,
 ZIP =A.ZIPCODE,
 PHONE = CNVTPHONE (P.PHONE_NUM, P.PHONE_FORMAT_CD),
 STEXT = CONCAT ("<html><body><tr>" ,
"<p align='center'><b><span style='font-size:14.0pt;font-family:Palatino Linotype'>" ,  FACILITY ,
"</span></b><br>" ),
; STEXT = BUILD ( STEXT ,
;"<b><span style='font-size:12.0pt;font-family:Palatino Linotype;font-style:italic'>" ,
;"Mayo Health System</span></b><br>" ),
 STEXT = BUILD ( STEXT , "<b><span style='font-size:12.0pt;font-family:Palatino Linotype'>" ,  ADDY1
, "</span></b><br>" ),
 STEXT = BUILD ( STEXT , "<b><span style='font-size:12.0pt;font-family:Palatino Linotype'>" ,  ADDY2
, "</span></b><br>" ),
 STEXT = BUILD2 ( STEXT , "<b><span style='font-size:12.0pt;font-family:Palatino Linotype'>" ,
 CITY , ", " ,  STATE , " " ,  ZIP , "</span></b><br>" ),
 STEXT = BUILD ( STEXT , "<b><span style='font-size:12.0pt;font-family:Palatino Linotype'>" ,
 PHONE , "</span></b></p>" )
 WITH  NOCOUNTER
 
IF ( ( POPULATE = 0 ) )
SET  STEXT  =  BUILD (
"<html><body><tr><p align='center'><b><span style='font-size:14.0pt;font-family:Palatino Linotype'>"
, "No Facility found" , "</span></b></p>" )
ENDIF
 
 
SET  STEXT  =  CONCAT ( STEXT , "</tr></body></html>" )
 
SET  REPLY -> TEXT  =  STEXT
 
SET  REPLY -> FORMAT  =  1
 
 CALL ECHO ( REPLY -> TEXT )
 
;SET  MOD  = "000 NT5990 12/05/2008"
 END GO
