DYNDOCStrike=function(){var m_STRIKE_COLOR="#FF0000";
var m_nIsStrikeThroughAllowed=-1;
if(typeof CKEDITOR.PreferenceHelper!=="undefined"&&typeof CKEDITOR.PreferenceHelper.Preference!=="undefined"){m_nIsStrikeThroughAllowed=!(CKEDITOR.PreferenceHelper.Preference("pvNotes.NoStrikeThrough"));
}return{m_oEditor:null,m_bStrikeOnlyFreeText:false,isCommandEnabled:function(sCmdName){var command=DYNDOCStrike.m_oEditor.getCommand(sCmdName);
if(command){if(CKEDITOR.TRISTATE_DISABLED==command.state){return false;
}}return true;
},onStrikeThrough:function(){var oSelection=DYNDOCStrike.m_oEditor.getSelection();
if(!oSelection){return;
}var oSelRange=DYNDOCStrike.m_oEditor.document.$.selection.createRange();
if(null==oSelRange){return;
}var sSelHtmlText=oSelRange.text;
if(DDCOMMON.isEmpty(sSelHtmlText)){return;
}var oStartElement=null;
if(null!=oSelection.getStartElement()){oStartElement=oSelection.getStartElement().$;
}if(null==oStartElement){return;
}var oContribution=DDCOMMON.getParentElementByClass(oStartElement,g_sCLASS_CONTRIBUTION);
if(!oContribution){return;
}DYNDOCStrike.m_oEditor.fire("saveSnapshot");
var bActive=DDCOMMON.getAttributeBoolean(oContribution,g_sATTRIBUTE_ACTIVE);
if(!bActive){var styles=new CKEDITOR.style({element:"span",styles:{color:m_STRIKE_COLOR}});
styles.apply(this.m_oEditor.document);
}},strikeElement:function(oElement){if(null==oElement){return;
}if(oElement.childNodes&&oElement.childNodes.length>0){if(typeof oElement.childNodes[0]=="object"){if(1===oElement.childNodes[0].nodeType){if(oElement.childNodes[0].nodeName=="STRIKE"||oElement.childNodes[0].nodeName=="DEL"||oElement.childNodes[0].nodeName=="S"||oElement.childNodes[0].style.textDecorationLineThrough==true){return;
}}}}var oContribution=DDCOMMON.getParentElementByClass(oElement,g_sCLASS_CONTRIBUTION);
if(!oContribution){return;
}DYNDOCStrike.m_oEditor.fire("saveSnapshot");
if(oElement.tagName.toUpperCase()==="TR"){oElement.style.textDecorationLineThrough=true;
oElement.style.color=m_STRIKE_COLOR;
}else{var sHtmlStrike=["<span style='color:",m_STRIKE_COLOR,";text-decoration:line-through'>",oElement.innerHTML,"</span>"].join("");
oElement.innerHTML=sHtmlStrike;
}DYNDOCStrike.m_oEditor.fire("saveSnapshot");
},updateStrikeThroughCmdStatus:function(){if(0==m_nIsStrikeThroughAllowed){return;
}if(!this.m_bStrikeOnlyFreeText){return;
}var oSelection=DYNDOCStrike.m_oEditor.getSelection();
if(!oSelection){return;
}if(null==this.m_oEditor.document||null==this.m_oEditor.document.$){return;
}var oSelRange=DYNDOCStrike.m_oEditor.document.$.selection.createRange();
var oRanges=oSelection.getRanges();
var oRange=oRanges[0];
var oStartElement=null;
var oEndElement=null;
if(typeof oRange!=="undefined"){oStartElement=oRange.startContainer.$;
oEndElement=oRange.endContainer.$;
var bStrikeThroughEnable=DDCOMMON.hasCommonParent(oStartElement,oEndElement,g_sCLASS_FREETEXT);
if(bStrikeThroughEnable&&DDCOMMON.m_oWin32Document.ReadOnly()==false){var cmdStrike=DYNDOCStrike.m_oEditor.getCommand(DDCMD_STRIKE);
if(cmdStrike.state!=CKEDITOR.TRISTATE_ON){DDCOMMON.enableCommand(DYNDOCStrike.m_oEditor,DDCMD_STRIKE,true);
}return;
}else{DDCOMMON.enableCommand(DYNDOCStrike.m_oEditor,DDCMD_STRIKE,false);
return;
}}}};
}();
