var CERN_EventListener=null;
var CERN_MPageComponents=null;
var CERN_TabManagers=null;
var STR_PAD_LEFT=1;
var STR_PAD_RIGHT=2;
var STR_PAD_BOTH=3;
Array.prototype.addAll=function(v){if(v&&v.length>0){for(var x=0,xl=v.length;
x<xl;
x++){this.push(v[x]);
}}};
var MP_Core=function(){return{Criterion:function(jsCrit,static_content){var m_patInfo=null;
var m_prsnlInfo=null;
var m_encntrOverride=[];
this.person_id=jsCrit.PERSON_ID;
this.encntr_id=(jsCrit.ENCNTRS.length>0)?jsCrit.ENCNTRS[0].ENCNTR_ID:0;
this.provider_id=jsCrit.PRSNL_ID;
this.executable=jsCrit.EXECUTABLE;
this.static_content=static_content;
this.position_cd=jsCrit.POSITION_CD;
this.ppr_cd=jsCrit.PPR_CD;
this.debug_ind=(jsCrit.DEBUG_IND==1)?true:false;
this.help_file_local_ind=jsCrit.HELP_FILE_LOCAL_IND;
this.category_mean=jsCrit.CATEGORY_MEAN;
this.locale_id=(this.debug_ind)?"en_us":jsCrit.LOCALE_ID;
this.device_location=jsCrit.DEVICE_LOCATION;
var encntrOR=jsCrit.ENCNTR_OVERRIDE;
if(encntrOR){for(var x=encntrOR.length;
x--;
){m_encntrOverride.push(encntrOR[x].ENCNTR_ID);
}}else{m_encntrOverride.push(this.encntr_id);
}this.setPatientInfo=function(value){m_patInfo=value;
};
this.getPatientInfo=function(){return m_patInfo;
};
this.getPersonnelInfo=function(){if(!m_prsnlInfo){m_prsnlInfo=new MP_Core.PersonnelInformation(this.provider_id,this.person_id);
}return m_prsnlInfo;
};
this.getEncounterOverride=function(){return m_encntrOverride;
};
},PatientInformation:function(){var m_dob=null;
var m_sex=null;
this.setSex=function(value){m_sex=value;
};
this.getSex=function(){return m_sex;
};
this.setDOB=function(value){m_dob=value;
};
this.getDOB=function(){return m_dob;
};
},ScriptRequest:function(component,loadTimerName){var m_comp=component;
var m_load=loadTimerName;
var m_name="";
var m_programName="";
var m_params=null;
var m_async=true;
this.getComponent=function(){return m_comp;
};
this.getLoadTimer=function(){return m_load;
};
this.setName=function(value){m_name=value;
};
this.getName=function(){return m_name;
};
this.setProgramName=function(value){m_programName=value;
};
this.getProgramName=function(){return m_programName;
};
this.setParameters=function(value){m_params=value;
};
this.getParameters=function(){return m_params;
};
this.setAsync=function(value){m_async=value;
};
this.isAsync=function(){return m_async;
};
},ScriptReply:function(component){var m_name="";
var m_status="F";
var m_err="";
var m_resp=null;
var m_comp=component;
this.setName=function(value){m_name=value;
};
this.getName=function(){return m_name;
};
this.setStatus=function(value){m_status=value;
};
this.getStatus=function(){return m_status;
};
this.setError=function(value){m_err=value;
};
this.getError=function(){return m_err;
};
this.setResponse=function(value){m_resp=value;
};
this.getResponse=function(){return m_resp;
};
this.getComponent=function(){return m_comp;
};
},PersonnelInformation:function(prsnlId,patientId){var m_prsnlId=prsnlId;
var m_viewableEncntrs=null;
var patConObj=null;
try{patConObj=window.external.DiscernObjectFactory("PVCONTXTMPAGE");
if(patConObj){m_viewableEncntrs=patConObj.GetValidEncounters(patientId);
}}catch(e){}finally{patConObj=null;
}this.getPersonnelId=function(){return m_prsnlId;
};
this.getViewableEncounters=function(){return m_viewableEncntrs;
};
},XMLCclRequestWrapper:function(component,program,paramAr,async){var timerLoadComponent=MP_Util.CreateTimer(component.getComponentLoadTimerName(),component.getCriterion().category_mean);
var i18nCore=i18n.discernabu;
var info=new XMLCclRequest();
info.onreadystatechange=function(){var countText="";
var errMsg=null;
if(this.readyState==4&&this.status==200){try{var jsonEval=JSON.parse(this.responseText);
var recordData=jsonEval.RECORD_DATA;
if(recordData.STATUS_DATA.STATUS=="Z"){countText=(component.isLineNumberIncluded()?"(0)":"");
MP_Util.Doc.FinalizeComponent(MP_Util.HandleNoDataResponse(component.getStyles().getNameSpace()),component,countText);
}else{if(recordData.STATUS_DATA.STATUS=="S"){var timerRenderComponent=MP_Util.CreateTimer(component.getComponentRenderTimerName(),component.getCriterion().category_mean);
try{var rootComponentNode=component.getRootComponentNode();
var secTitle=Util.Style.g("sec-total",rootComponentNode,"span");
secTitle[0].innerHTML=i18nCore.RENDERING_DATA+"...";
component.HandleSuccess(recordData);
}catch(err){if(timerRenderComponent){timerRenderComponent.Abort();
timerRenderComponent=null;
}throw (err);
}finally{if(timerRenderComponent){timerRenderComponent.Stop();
}}}else{errMsg=[];
var ss=null;
errMsg.push("<b>",i18nCore.DISCERN_ERROR,"</b><br /><ul><li>",i18nCore.STATUS,": ",this.status,"</li><li>",i18nCore.REQUEST,": ",this.requestText,"</li>");
var statusData=recordData.STATUS_DATA;
if(statusData.SUBEVENTSTATUS.length&&statusData.SUBEVENTSTATUS.length>0){for(var x=0,xl=statusData.SUBEVENTSTATUS.length;
x<xl;
x++){ss=statusData.SUBEVENTSTATUS[x];
errMsg.push("<li>",i18nCore.ERROR_OPERATION,": ",ss.OPERATIONNAME,"</li><li>",i18nCore.ERROR_OPERATION_STATUS,": ",ss.OPERATIONSTATUS,"</li><li>",i18nCore.ERROR_TARGET_OBJECT,": ",ss.TARGETOBJECTNAME,"</li><li>",i18nCore.ERROR_TARGET_OBJECT_VALUE,": ",ss.TARGETOBJECTVALUE,"</li>");
}}else{if(statusData.SUBEVENTSTATUS.length===undefined){ss=statusData.SUBEVENTSTATUS;
errMsg.push("<li>",i18nCore.ERROR_OPERATION,": ",ss.OPERATIONNAME,"</li><li>",i18nCore.ERROR_OPERATION_STATUS,": ",ss.OPERATIONSTATUS,"</li><li>",i18nCore.ERROR_TARGET_OBJECT,": ",ss.TARGETOBJECTNAME,"</li><li>",i18nCore.ERROR_TARGET_OBJECT_VALUE,": ",ss.TARGETOBJECTVALUE,"</li>");
}}errMsg.push("</ul>");
countText=(component.isLineNumberIncluded()?"(0)":"");
MP_Util.Doc.FinalizeComponent(MP_Util.HandleErrorResponse(component.getStyles().getNameSpace(),errMsg.join("")),component,countText);
}}}catch(err){errMsg=[];
errMsg.push("<b>",i18nCore.JS_ERROR,"</b><br /><ul><li>",i18nCore.MESSAGE,": ",err.message,"</li><li>",i18nCore.NAME,": ",err.name,"</li><li>",i18nCore.NUMBER,": ",(err.number&65535),"</li><li>",i18nCore.DESCRIPTION,": ",err.description,"</li></ul>");
MP_Util.Doc.FinalizeComponent(MP_Util.HandleErrorResponse(component.getStyles().getNameSpace(),errMsg.join("")),component,countText);
if(timerLoadComponent){timerLoadComponent.Abort();
timerLoadComponent=null;
}}finally{if(timerLoadComponent){timerLoadComponent.Stop();
}}}else{if(this.readyState==4&&this.status!=200){errMsg=[];
errMsg.push("<b>",i18nCore.DISCERN_ERROR,"</b><br /><ul><li>",i18nCore.STATUS,": ",this.status,"</li><li>",i18nCore.REQUEST,": ",this.requestText,"</li></ul>");
MP_Util.Doc.FinalizeComponent(MP_Util.HandleErrorResponse(component.getStyles().getNameSpace(),errMsg.join("")),component,"");
if(timerLoadComponent){timerLoadComponent.Abort();
}}}if(this.readyState==4){MP_Util.ReleaseRequestReference(this);
}};
info.open("GET",program,async);
info.send(paramAr.join(","));
},XMLCCLRequestCallBack:function(component,request,funcCallback){var timerLoad=MP_Util.CreateTimer(request.getLoadTimer());
var i18nCore=i18n.discernabu;
var info=new XMLCclRequest();
var reply=new MP_Core.ScriptReply(component);
reply.setName(request.getName());
info.onreadystatechange=function(){var errMsg=null;
if(this.readyState==4&&this.status==200){try{var jsonEval=JSON.parse(info.responseText);
var recordData=jsonEval.RECORD_DATA;
var status=recordData.STATUS_DATA.STATUS;
reply.setStatus(status);
if(status=="Z"){reply.setResponse(recordData);
funcCallback(reply);
}else{if(status=="S"){reply.setResponse(recordData);
funcCallback(reply);
}else{errMsg=[];
errMsg.push("<b>",i18nCore.DISCERN_ERROR,"</b><br /><ul><li>",i18nCore.STATUS,": ",this.status,"</li><li>",i18nCore.REQUEST,": ",this.requestText,"</li>");
var statusData=recordData.STATUS_DATA;
if(statusData.SUBEVENTSTATUS.length&&statusData.SUBEVENTSTATUS.length>0){for(var x=0,xl=statusData.SUBEVENTSTATUS.length;
x<xl;
x++){var ss=statusData.SUBEVENTSTATUS[x];
errMsg.push("<li>",i18nCore.ERROR_OPERATION,": ",ss.OPERATIONNAME,"</li><li>",i18nCore.ERROR_OPERATION_STATUS,": ",ss.OPERATIONSTATUS,"</li><li>",i18nCore.ERROR_TARGET_OBJECT,": ",ss.TARGETOBJECTNAME,"</li><li>",i18nCore.ERROR_TARGET_OBJECT_VALUE,": ",ss.TARGETOBJECTVALUE,"</li>");
}}else{if(statusData.SUBEVENTSTATUS.length==undefined){var ss=statusData.SUBEVENTSTATUS;
errMsg.push("<li>",i18nCore.ERROR_OPERATION,": ",ss.OPERATIONNAME,"</li><li>",i18nCore.ERROR_OPERATION_STATUS,": ",ss.OPERATIONSTATUS,"</li><li>",i18nCore.ERROR_TARGET_OBJECT,": ",ss.TARGETOBJECTNAME,"</li><li>",i18nCore.ERROR_TARGET_OBJECT_VALUE,": ",ss.TARGETOBJECTVALUE,"</li>");
}}errMsg.push("</ul>");
reply.setError(errMsg.join(""));
funcCallback(reply);
}}}catch(err){errMsg=[];
errMsg.push("<b>",i18nCore.DISCERN_ERROR,"</b><br /><ul><li>",i18nCore.STATUS,": ",this.status,"</li><li>",i18nCore.REQUEST,": ",this.requestText,"</li></ul>");
reply.setError(errMsg.join(""));
if(timerLoad){timerLoad.Abort();
timerLoad=null;
}}finally{if(timerLoad){timerLoad.Stop();
}}}else{if(info.readyState==4&&info.status!=200){errMsg=[];
errMsg.push("<b>",i18nCore.DISCERN_ERROR,"</b><br /><ul><li>",i18nCore.STATUS,": ",this.status,"</li><li>",i18nCore.REQUEST,": ",this.requestText,"</li></ul>");
reply.setError(errMsg.join(""));
if(timerLoad){timerLoad.Abort();
}funcCallback(reply);
}}if(this.readyState==4){MP_Util.ReleaseRequestReference(this);
}};
info.open("GET",request.getProgramName(),request.isAsync());
info.send(request.getParameters().join(","));
},XMLCCLRequestThread:function(name,component,request){var m_name=name;
var m_comp=component;
var m_request=request;
m_request.setName(name);
this.getName=function(){return m_name;
};
this.getComponent=function(){return m_comp;
};
this.getRequest=function(){return m_request;
};
},XMLCCLRequestThreadManager:function(callbackFunction,component,handleFinalize){var m_threads=null;
var m_replyAr=null;
var m_isData=false;
var m_isError=false;
this.addThread=function(thread){if(!m_threads){m_threads=[];
}m_threads.push(thread);
};
this.begin=function(){if(m_threads&&m_threads.length>0){for(x=m_threads.length;
x--;
){var thread=m_threads[x];
MP_Core.XMLCCLRequestCallBack(thread.getComponent(),thread.getRequest(),this.completeThread);
}}else{if(handleFinalize){var countText=(component.isLineNumberIncluded()?"(0)":"");
MP_Util.Doc.FinalizeComponent(MP_Util.HandleNoDataResponse(component.getStyles().getNameSpace()),component,countText);
}else{callbackFunction(null,component);
}}};
this.completeThread=function(reply){if(!m_replyAr){m_replyAr=[];
}if(reply.getStatus()==="S"){m_isData=true;
}else{if(reply.getStatus()==="F"){m_isError=true;
}}m_replyAr.push(reply);
if(m_replyAr.length===m_threads.length){var countText=(component.isLineNumberIncluded()?"(0)":"");
var errMsg=null;
try{if(handleFinalize){if(m_isError){errMsg=[];
for(var x=m_replyAr.length;
x--;
){var rep=m_replyAr[x];
if(rep.getStatus()==="F"){errMsg.push(rep.getError());
}}MP_Util.Doc.FinalizeComponent(MP_Util.HandleErrorResponse(component.getStyles().getNameSpace(),errMsg.join("<br />")),component,"");
}else{if(!m_isData){countText=(component.isLineNumberIncluded()?"(0)":"");
MP_Util.Doc.FinalizeComponent(MP_Util.HandleNoDataResponse(component.getStyles().getNameSpace()),component,countText);
}else{callbackFunction(m_replyAr,component);
}}}else{callbackFunction(m_replyAr,component);
}}catch(err){var i18nCore=i18n.discernabu;
errMsg=["<b>",i18nCore.JS_ERROR,"</b><br /><ul><li>",i18nCore.MESSAGE,": ",err.message,"</li><li>",i18nCore.NAME,": ",err.name,"</li><li>",i18nCore.NUMBER,": ",(err.number&65535),"</li><li>",i18nCore.DESCRIPTION,": ",err.description,"</li></ul>"];
MP_Util.Doc.FinalizeComponent(MP_Util.HandleErrorResponse(component.getStyles().getNameSpace(),errMsg.join("")),component,countText);
}}};
},MapObject:function(name,value){this.name=name;
this.value=value;
},TabItem:function(key,name,components,prefIdentifier){this.key=key;
this.name=name;
this.components=components;
this.prefIdentifier=prefIdentifier;
},TabManager:function(tabItem){var m_isLoaded=false;
var m_tabItem=tabItem;
var m_isExpandAll=false;
var m_isSelected=false;
this.toggleExpandAll=function(){m_isExpandAll=(!m_isExpandAll);
};
this.loadTab=function(){if(!m_isLoaded){m_isLoaded=true;
var components=m_tabItem.components;
if(components){for(var xl=components.length;
xl--;
){var component=components[xl];
if(component.isDisplayable()){component.InsertData();
}}}}};
this.getTabItem=function(){return m_tabItem;
};
this.getSelectedTab=function(){return m_isSelected;
};
this.setSelectedTab=function(value){m_isSelected=value;
};
},ReferenceRangeResult:function(){var m_valNLow=-1,m_valNHigh=-1,m_valCLow=-1,m_valCHigh=-1;
var m_uomNLow=null,m_uomNHigh=null,m_uomCLow=null,m_uomCHigh=null;
this.init=function(refRange,codeArray){var nf=MP_Util.GetNumericFormatter();
m_valCLow=nf.format(refRange.CRITICAL_LOW.NUMBER);
if(refRange.CRITICAL_LOW.UNIT_CD!=""){m_uomCLow=MP_Util.GetValueFromArray(refRange.CRITICAL_LOW.UNIT_CD,codeArray);
}m_valCHigh=nf.format(refRange.CRITICAL_HIGH.NUMBER);
if(refRange.CRITICAL_HIGH.UNIT_CD!=""){m_uomCHigh=MP_Util.GetValueFromArray(refRange.CRITICAL_HIGH.UNIT_CD,codeArray);
}m_valNLow=nf.format(refRange.NORMAL_LOW.NUMBER);
if(refRange.NORMAL_LOW.UNIT_CD!=""){m_uomNLow=MP_Util.GetValueFromArray(refRange.NORMAL_LOW.UNIT_CD,codeArray);
}m_valNHigh=nf.format(refRange.NORMAL_HIGH.NUMBER);
if(refRange.NORMAL_HIGH.UNIT_CD!=""){m_uomNHigh=MP_Util.GetValueFromArray(refRange.NORMAL_HIGH.UNIT_CD,codeArray);
}};
this.getNormalLow=function(){return m_valNLow;
};
this.getNormalHigh=function(){return m_valNHigh;
};
this.getNormalLowUOM=function(){return m_uomNLow;
};
this.getNormalHighUOM=function(){return m_uomNHigh;
};
this.getCriticalLow=function(){return m_valCLow;
};
this.getCriticalHigh=function(){return m_valCHigh;
};
this.getCriticalLowUOM=function(){return m_uomCLow;
};
this.getCriticalHighUOM=function(){return m_uomCHigh;
};
this.toNormalInlineString=function(){var low=(m_uomNLow)?m_uomNLow.display:"";
var high=(m_uomNHigh)?m_uomNHigh.display:"";
if(m_valNLow!=0||m_valNHigh!=0){return(m_valNLow+"&nbsp;"+low+" - "+m_valNHigh+"&nbsp;"+high);
}else{return"";
}};
this.toCriticalInlineString=function(){var low=(m_uomCLow)?m_uomCLow.display:"";
var high=(m_uomCHigh)?m_uomCHigh.display:"";
if(m_valCLow!=0||m_valCHigh!=0){return(m_valCLow+"&nbsp;"+low+" - "+m_valCHigh+"&nbsp;"+high);
}else{return"";
}};
},QuantityValue:function(){var m_val,m_precision;
var m_uom=null;
var m_refRange=null;
var m_rawValue=0;
var m_hasModifier=false;
this.init=function(result,codeArray){var quantityValue=result.QUANTITY_VALUE;
var referenceRange=result.REFERENCE_RANGE;
for(var l=0,ll=quantityValue.length;
l<ll;
l++){var numRes=quantityValue[l].NUMBER;
m_precision=quantityValue[l].PRECISION;
if(!isNaN(numRes)){m_val=MP_Util.Measurement.SetPrecision(numRes,m_precision);
m_rawValue=numRes;
}if(quantityValue[l].MODIFIER_CD!=""){var modCode=MP_Util.GetValueFromArray(quantityValue[l].MODIFIER_CD,codeArray);
if(modCode){m_val=modCode.display+m_val;
m_hasModifier=true;
}}if(quantityValue[l].UNIT_CD!=""){m_uom=MP_Util.GetValueFromArray(quantityValue[l].UNIT_CD,codeArray);
}for(var m=0,ml=referenceRange.length;
m<ml;
m++){m_refRange=new MP_Core.ReferenceRangeResult();
m_refRange.init(referenceRange[m],codeArray);
}}};
this.getValue=function(){return m_val;
};
this.getRawValue=function(){return m_rawValue;
};
this.getUOM=function(){return m_uom;
};
this.getRefRange=function(){return m_refRange;
};
this.getPrecision=function(){return m_precision;
};
this.toString=function(){if(m_uom){return(m_val+" "+m_uom.display);
}return m_val;
};
this.hasModifier=function(){return m_hasModifier;
};
},Measurement:function(){var m_eventId=0;
var m_personId=0;
var m_encntrId=0;
var m_eventCode=null;
var m_dateTime=null;
var m_updateDateTime=null;
var m_result=null;
var m_normalcy=null;
var m_status=null;
this.init=function(eventId,personId,encntrId,eventCode,dateTime,resultObj,updateDateTime){m_eventId=eventId;
m_personId=personId;
m_encntrId=encntrId;
m_eventCode=eventCode;
m_dateTime=dateTime;
m_result=resultObj;
m_updateDateTime=updateDateTime;
};
this.initFromRec=function(measObj,codeArray){var effectiveDateTime=new Date();
var updateDateTime=new Date();
m_eventId=measObj.EVENT_ID;
m_personId=measObj.PATIENT_ID;
m_encntrId=measObj.ENCOUNTER_ID;
m_eventCode=MP_Util.GetValueFromArray(measObj.EVENT_CD,codeArray);
effectiveDateTime.setISO8601(measObj.EFFECTIVE_DATE);
m_dateTime=effectiveDateTime;
m_result=MP_Util.Measurement.GetObject(measObj,codeArray);
updateDateTime.setISO8601(measObj.UPDATE_DATE);
m_updateDateTime=updateDateTime;
m_normalcy=MP_Util.GetValueFromArray(measObj.NORMALCY_CD,codeArray);
m_status=MP_Util.GetValueFromArray(measObj.STATUS_CD,codeArray);
};
this.getEventId=function(){return m_eventId;
};
this.getPersonId=function(){return m_personId;
};
this.getEncntrId=function(){return m_encntrId;
};
this.getEventCode=function(){return m_eventCode;
};
this.getDateTime=function(){return m_dateTime;
};
this.getUpdateDateTime=function(){return m_updateDateTime;
};
this.getResult=function(){return m_result;
};
this.setNormalcy=function(value){m_normalcy=value;
};
this.getNormalcy=function(){return m_normalcy;
};
this.setStatus=function(value){m_status=value;
};
this.getStatus=function(){return m_status;
};
this.isModified=function(){if(m_status){var mean=m_status.meaning;
if(mean==="MODIFIED"||mean==="ALTERED"){return true;
}}return false;
};
},MenuItem:function(){var m_name="";
var m_desc="";
var m_id=0;
this.setDescription=function(value){m_desc=value;
};
this.getDescription=function(){return m_desc;
};
this.setName=function(value){m_name=value;
};
this.getName=function(){return m_name;
};
this.setId=function(value){m_id=value;
};
this.getId=function(){return m_id;
};
},CriterionFilters:function(criterion){var m_criterion=criterion;
var m_evalAr=[];
this.addFilter=function(type,value){m_evalAr.push(new MP_Core.MapObject(type,value));
};
this.checkFilters=function(){var pass=false;
var patInfo=m_criterion.getPatientInfo();
for(var x=m_evalAr.length;
x--;
){var filter=m_evalAr[x];
var dob=null;
switch(filter.name){case MP_Core.CriterionFilters.SEX_MEANING:var sex=patInfo.getSex();
if(sex){if(filter.value==sex.meaning){continue;
}}return false;
case MP_Core.CriterionFilters.DOB_OLDER_THAN:dob=patInfo.getDOB();
if(dob){if(dob<=filter.value){continue;
}}return false;
case MP_Core.CriterionFilters.DOB_YOUNGER_THAN:dob=patInfo.getDOB();
if(dob){if(dob>=filter.value){continue;
}}return false;
default:alert("Unhandled criterion filter");
return false;
}}return true;
};
},CreateSimpleError:function(component,sMessage){var errMsg=[];
var i18nCore=i18n.discernabu;
var countText=(component.isLineNumberIncluded()?"(0)":"");
errMsg.push("<b>",i18nCore.DISCERN_ERROR,"</b><br /><ul><li>",sMessage,"</li></ul>");
MP_Util.Doc.FinalizeComponent(MP_Util.HandleErrorResponse(component.getStyles().getNameSpace(),errMsg.join("")),component,countText);
}};
}();
MP_Core.CriterionFilters.SEX_MEANING=1;
MP_Core.CriterionFilters.DOB_OLDER_THAN=2;
MP_Core.CriterionFilters.DOB_YOUNGER_THAN=3;
MP_Core.AppUserPreferenceManager=function(){var m_criterion=null;
var m_prefIdent="";
var m_jsonObject=null;
return{Initialize:function(criterion,preferenceIdentifier){m_criterion=criterion;
m_prefIdent=preferenceIdentifier;
m_jsonObject=null;
},SetPreferences:function(prefString){var jsonEval=JSON.parse(prefString);
m_jsonObject=jsonEval;
},LoadPreferences:function(){if(!m_criterion){alert("Validation Failed: the AppUserPreferenceManager must be initialized prior to usage.");
return null;
}if(m_jsonObject){return;
}else{var info=new XMLCclRequest();
info.onreadystatechange=function(){if(this.readyState==4&&this.status==200){var jsonEval=JSON.parse(this.responseText);
var recordData=jsonEval.RECORD_DATA;
if(recordData.STATUS_DATA.STATUS=="S"){m_jsonObject=JSON.parse(recordData.PREF_STRING);
}else{if(recordData.STATUS_DATA.STATUS=="Z"){return;
}else{var errAr=[];
var statusData=recordData.STATUS_DATA;
errAr.push("STATUS: "+statusData.STATUS);
for(var x=0,xl=statusData.SUBEVENTSTATUS.length;
x<xl;
x++){var ss=statusData.SUBEVENTSTATUS[x];
errAr.push(ss.OPERATIONNAME,ss.OPERATIONSTATUS,ss.TARGETOBJECTNAME,ss.TARGETOBJECTVALUE);
}window.status="Error retrieving user preferences "+errAr.join(",");
return;
}}}if(this.readyState==4){MP_Util.ReleaseRequestReference(this);
}};
info.open("GET","MP_GET_USER_PREFS",false);
var ar=["^mine^",m_criterion.provider_id+".0","^"+m_prefIdent+"^"];
info.send(ar.join(","));
return;
}},GetPreferences:function(){if(!m_criterion){alert("Validation Failed: the AppUserPreferenceManager must be initialized prior to usage.");
return null;
}if(!m_jsonObject){this.LoadPreferences();
}return m_jsonObject;
},SavePreferences:function(){var body=document.body;
var groups=Util.Style.g("col-group",body,"div");
var grpId=0;
var colId=0;
var rowId=0;
var compId=0;
var jsonObject={};
var userPrefs=jsonObject.user_prefs={};
var pagePrefs=userPrefs.page_prefs={};
var components=pagePrefs.components=[];
var cclParams=[];
for(var x=0,xl=groups.length;
x<xl;
x++){grpId=x+1;
var liqLay=Util.Style.g("col-outer1",groups[x],"div");
if(liqLay.length>0){var cols=Util.gcs(liqLay[0]);
for(var y=0,yl=cols.length;
y<yl;
y++){colId=y+1;
var rows=Util.gcs(cols[y]);
for(var z=0,zl=rows.length;
z<zl;
z++){var component=new Object();
rowId=z+1;
compId=jQuery(rows[z]).attr("id");
component.id=compId;
component.group_seq=grpId;
component.col_seq=colId;
component.row_seq=rowId;
if(jQuery(rows[z]).hasClass("closed")){component.expanded=false;
}else{component.expanded=true;
}components.push(component);
}}}}WritePreferences(jsonObject);
m_jsonObject=jsonObject;
cclParams.push("^MINE^",m_criterion.person_id+".0",m_criterion.encntr_id+".0",m_criterion.provider_id+".0",m_criterion.position_cd+".0",m_criterion.ppr_cd+".0","^"+m_criterion.executable+"^","^"+m_criterion.device_location+"^","^"+m_criterion.static_content.replace(/\\/g,"\\\\")+"^","^"+m_criterion.category_mean+"^",m_criterion.debug_ind);
CCLLINK("MP_DRIVER",cclParams.join(","),1);
},ClearPreferences:function(){WritePreferences(null);
var cclParams=["^MINE^",m_criterion.person_id+".0",m_criterion.encntr_id+".0",m_criterion.provider_id+".0",m_criterion.position_cd+".0",m_criterion.ppr_cd+".0","^"+m_criterion.executable+"^","^"+m_criterion.device_location+"^","^"+m_criterion.static_content.replace(/\\/g,"\\\\")+"^","^"+m_criterion.category_mean+"^",m_criterion.debug_ind];
CCLLINK("MP_DRIVER",cclParams.join(","),1);
},GetComponentById:function(id){if(m_jsonObject){var components=m_jsonObject.user_prefs.page_prefs.components;
for(var x=components.length;
x--;
){var component=components[x];
if(component.id==id){return component;
}}}return null;
}};
function WritePreferences(jsonObject,successMessage){var info=new XMLCclRequest();
info.onreadystatechange=function(){if(this.readyState==4&&this.status==200){var jsonEval=JSON.parse(this.responseText);
var recordData=jsonEval.RECORD_DATA;
if(recordData.STATUS_DATA.STATUS=="Z"){m_jsonObject=null;
}else{if(recordData.STATUS_DATA.STATUS=="S"){m_jsonObject=jsonObject;
if(successMessage&&successMessage.length>0){alert(successMessage);
}}else{var errAr=[];
var statusData=recordData.STATUS_DATA;
errAr.push("STATUS: "+statusData.STATUS);
for(var x=0,xl=statusData.SUBEVENTSTATUS.length;
x<xl;
x++){var ss=statusData.SUBEVENTSTATUS[x];
errAr.push(ss.OPERATIONNAME,ss.OPERATIONSTATUS,ss.TARGETOBJECTNAME,ss.TARGETOBJECTVALUE);
}window.status="Error saving user preferences: "+errAr.join(",");
}}}if(this.readyState==4){MP_Util.ReleaseRequestReference(this);
}};
info.open("GET","MP_MAINTAIN_USER_PREFS",false);
var sJson=(jsonObject!=null)?JSON.stringify(jsonObject):"";
var ar=["^mine^",m_criterion.provider_id+".0","^"+m_prefIdent+"^","^"+sJson+"^"];
info.send(ar.join(","));
}}();
var MP_Util=function(){var m_df=null;
var m_nf=null;
return{GetCriterion:function(js_criterion,static_content){var jsCrit=js_criterion.CRITERION;
var criterion=new MP_Core.Criterion(jsCrit,static_content);
var codeArray=MP_Util.LoadCodeListJSON(jsCrit.CODES);
var jsPatInfo=jsCrit.PATIENT_INFO;
var patInfo=new MP_Core.PatientInformation();
patInfo.setSex(MP_Util.GetValueFromArray(jsPatInfo.SEX_CD,codeArray));
if(jsPatInfo.DOB!=""){var dt=new Date();
dt.setISO8601(jsPatInfo.DOB);
patInfo.setDOB(dt);
}criterion.setPatientInfo(patInfo);
return criterion;
},CalcLookbackDate:function(lookbackDays){var retDate=new Date();
var hrs=retDate.getHours();
hrs-=(lookbackDays*24);
retDate.setHours(hrs);
return retDate;
},CalcWithinTime:function(dateTime){return(GetDateDiffString(dateTime,null,null,true));
},CalcAge:function(birthDt,fromDate){fromDate=(fromDate)?fromDate:new Date();
return(GetDateDiffString(birthDt,fromDate,1,false));
},DisplayDateByOption:function(component,date){var df=MP_Util.GetDateFormatter();
var dtFormatted="";
switch(component.getDateFormat()){case 1:return(df.format(date,mp_formatter.DateTimeFormatter.FULL_DATE_2YEAR));
case 2:return(df.format(date,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_2YEAR));
case 3:return(MP_Util.CalcWithinTime(date));
case 4:return("&nbsp");
default:return df.format(date,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_2YEAR);
}},DisplaySelectedTab:function(showDiv,anchorId){if(window.name=="a-tab0"){window.name="";
}else{window.name=showDiv+","+anchorId;
}var body=document.body;
var divs=Util.Style.g("div-tab-item",body);
for(var i=divs.length;
i--;
){if(divs[i].id==showDiv){divs[i].style.display="block";
}else{divs[i].style.display="none";
}}var anchors=Util.Style.g("anchor-tab-item",body);
for(var i=anchors.length;
i--;
){if(anchors[i].id==anchorId){anchors[i].className="anchor-tab-item active";
}else{anchors[i].className="anchor-tab-item inactive";
}}var custNode=_g("custView");
if(custNode!=null){custNode.href="";
custNode.innerHTML="";
}for(var yl=CERN_TabManagers.length;
yl--;
){var tabManager=CERN_TabManagers[yl];
var tabItem=tabManager.getTabItem();
if(tabItem.key==showDiv){tabManager.loadTab();
tabManager.setSelectedTab(true);
var components=tabItem.components;
if(components!=null&&components.length>0){for(var xl=components.length;
xl--;
){var component=components[xl];
MP_Util.Doc.AddCustomizeLink(component.getCriterion());
break;
}}}else{tabManager.setSelectedTab(false);
}}},OpenTab:function(compId){for(var x=0,xl=CERN_MPageComponents.length;
x<xl;
x++){var comp=CERN_MPageComponents[x];
var styles=comp.getStyles();
if(styles.getId()==compId){comp.openTab();
}}},LaunchMenuSelection:function(compId,menuItemId){for(var x=0,xl=CERN_MPageComponents.length;
x<xl;
x++){var comp=CERN_MPageComponents[x];
var crit=comp.getCriterion();
var styles=comp.getStyles();
if(styles.getId()==compId){comp.openDropDown(menuItemId);
break;
}}},LaunchMenu:function(menuId,componentId){var menu=_g(menuId);
MP_Util.closeMenuInit(menu,componentId);
if(menu!=null){if(Util.Style.ccss(menu,"menu-hide")){_g(componentId).style.zIndex=2;
Util.Style.rcss(menu,"menu-hide");
}else{_g(componentId).style.zIndex=1;
Util.Style.acss(menu,"menu-hide");
}}},closeMenuInit:function(inMenu,compId){var menuId;
var docMenuId=compId+"Menu";
if(inMenu.id==docMenuId){menuId=compId;
}if(!e){var e=window.event;
}if(window.attachEvent){Util.addEvent(inMenu,"mouseleave",function(){Util.Style.acss(inMenu,"menu-hide");
_g(menuId).style.zIndex=1;
});
}else{Util.addEvent(inMenu,"mouseout",menuLeave);
}menuLeave:function(e){if(!e){var e=window.event;
}var relTarg=e.relatedTarget||e.toElement;
if(e.relatedTarget.id==inMenu.id){Util.Style.acss(inMenu,"menu-hide");
_g(menuId).style.zIndex=1;
}e.stopPropagation();
Util.cancelBubble(e);
}},CreateTitleText:function(component,nbr,optionalText){var ar=[];
if(component.isLineNumberIncluded()){ar.push("(",nbr,")");
}if(optionalText&&optionalText!==""){ar.push(" ",optionalText);
}return ar.join("");
},GetContentClass:function(component,nbr){if(component.isScrollingEnabled()){var scrollNbr=component.getScrollNumber();
if(nbr>=scrollNbr&&scrollNbr>0){return"content-body scrollable";
}}return"content-body";
},CreateTimer:function(timerName,subTimerName,metaData1,metaData2,metaData3){try{var slaTimer=window.external.DiscernObjectFactory("SLATIMER");
}catch(err){return null;
}if(slaTimer){slaTimer.TimerName=timerName;
if(subTimerName){slaTimer.SubtimerName=subTimerName;
}if(metaData1){slaTimer.Metadata1=String(metaData1);
}if(metaData2){slaTimer.Metadata2=String(metaData2);
}if(metaData3){slaTimer.Metadata3=String(metaData3);
}slaTimer.Start();
return slaTimer;
}else{return null;
}},GetCodeSet:function(codeSet,async){var codes=new Array();
var info=new XMLCclRequest();
info.onreadystatechange=function(){if(this.readyState==4&&this.status==200){var jsonEval=JSON.parse(this.responseText);
if(jsonEval.RECORD_DATA.STATUS_DATA.STATUS=="S"){codes=MP_Util.LoadCodeListJSON(jsonEval.RECORD_DATA.CODES);
}return codes;
}if(this.readyState==4){MP_Util.ReleaseRequestReference(this);
}};
info.open("GET","MP_GET_CODESET",async);
var sendVal="^MINE^, "+codeSet+".0";
info.send(sendVal);
return codes;
},GetCodeByMeaning:function(mapCodes,meaning){for(var x=mapCodes.length;
x--;
){var code=mapCodes[x].value;
if(code.meaning==meaning){return code;
}}return null;
},GetItemFromMapArray:function(mapItems,item){for(var x=mapItems.length;
x--;
){if(mapItems[x].name==item){return mapItems[x].value;
}}},AddItemToMapArray:function(mapItems,key,value){var ar=MP_Util.GetItemFromMapArray(mapItems,key);
if(!ar){ar=[];
mapItems.push(new MP_Core.MapObject(key,ar));
}ar.push(value);
},LookBackTime:function(component){var i18nCore=i18n.discernabu;
var remainder=0;
var lookbackDays=component.getLookbackDays();
if(lookbackDays==0){return(i18nCore.SELECTED_VISIT);
}else{if(lookbackDays==1){return(i18nCore.LAST_N_HOURS.replace("{0}",lookbackDays*24));
}else{return(i18nCore.LAST_N_DAYS.replace("{0}",lookbackDays));
}}},CreateClinNoteLink:function(patient_id,encntr_id,event_id,display,docViewerType,pevent_id){var docType=(docViewerType&&docViewerType>"")?docViewerType:"STANDARD";
var doclink="";
if(event_id>0){var ar=[];
ar.push(patient_id,encntr_id,event_id,'"'+docType+'"',pevent_id);
doclink="<a onclick='javascript:MP_Util.LaunchClinNoteViewer("+ar.join(",")+"); return false;' href='#'>"+display+"</a>";
}else{doclink=display;
}return(doclink);
},LaunchClinNoteViewer:function(patient_id,encntr_id,event_id,docViewerType,pevent_id){var x=0;
var m_dPersonId=parseFloat(patient_id);
var m_dEncntrId=parseFloat(encntr_id);
var m_dPeventId=parseFloat(pevent_id);
var viewerObj=window.external.DiscernObjectFactory("PVVIEWERMPAGE");
try{switch(docViewerType){case"AP":viewerObj.CreateAPViewer();
viewerObj.AppendAPEvent(event_id,m_dPeventId);
viewerObj.LaunchAPViewer();
break;
case"DOC":viewerObj.CreateDocViewer(m_dPersonId);
if(MP_Util.IsArray(event_id)){for(var x=event_id.length;
x--;
){viewerObj.AppendDocEvent(event_id[x]);
}}else{viewerObj.AppendDocEvent(event_id);
}viewerObj.LaunchDocViewer();
break;
case"EVENT":viewerObj.CreateEventViewer(m_dPersonId);
if(MP_Util.IsArray(event_id)){for(var x=event_id.length;
x--;
){viewerObj.AppendEvent(event_id[x]);
}}else{viewerObj.AppendEvent(event_id);
}viewerObj.LaunchEventViewer();
break;
case"MICRO":viewerObj.CreateMicroViewer(m_dPersonId);
if(MP_Util.IsArray(event_id)){for(var x=event_id.length;
x--;
){viewerObj.AppendMicroEvent(event_id[x]);
}}else{viewerObj.AppendMicroEvent(event_id);
}viewerObj.LaunchMicroViewer();
break;
case"GRP":viewerObj.CreateGroupViewer();
if(MP_Util.IsArray(event_id)){for(var x=event_id.length;
x--;
){viewerObj.AppendGroupEvent(event_id[x]);
}}else{viewerObj.AppendGroupEvent(event_id);
}viewerObj.LaunchGroupViewer();
break;
case"PROC":viewerObj.CreateProcViewer(m_dPersonId);
if(MP_Util.IsArray(event_id)){for(var x=event_id.length;
x--;
){viewerObj.AppendProcEvent(event_id[x]);
}}else{viewerObj.AppendProcEvent(event_id);
}viewerObj.LaunchProcViewer();
break;
case"HLA":viewerObj.CreateAndLaunchHLAViewer(m_dPersonId,m_dEventId);
break;
case"NR":viewerObj.LaunchRemindersViewer(event_id);
break;
case"STANDARD":alert(i18n.discernabu.CAN_NOT_VIEW_RESULTS);
break;
}}catch(err){alert(i18n.discernabu.CAN_NOT_VIEW_RESULTS+"  "+i18n.discernabu.CONTACT_ADMINISTRATOR);
}},IsArray:function(input){return(typeof(input)=="object"&&(input instanceof Array));
},IsString:function(input){return(typeof(input)=="string");
},HandleNoDataResponse:function(nameSpace){var i18nCore=i18n.discernabu;
return("<h3 class='info-hd'><span class='res-normal'>"+i18nCore.NO_RESULTS_FOUND+"</span></h3><span class='res-none'>"+i18nCore.NO_RESULTS_FOUND+"</span>");
},HandleErrorResponse:function(nameSpace,errorMessage){var ar=[];
var i18nCore=i18n.discernabu;
var ns=(nameSpace&&nameSpace.length>0)?nameSpace+"-":"";
ar.push("<h3 class='info-hd'><span class='res-normal'>",i18nCore.ERROR_RETREIVING_DATA,"</span></h3>");
ar.push("<dl class='",ns,"info'><dd><span>",i18nCore.ERROR_RETREIVING_DATA,"</span></dd></dl>");
if(errorMessage!=null&&errorMessage.length>0){ar.push("<h4 class='det-hd'><span>DETAILS</span></h4><div class='hvr'><dl class='",ns,"det'><dd><span>",errorMessage,"</span></dd></dl></div>");
}return ar.join("");
},GetValueFromArray:function(name,array){if(array!=null){for(var x=0,xi=array.length;
x<xi;
x++){if(array[x].name==name){return(array[x].value);
}}}return(null);
},GetCompObjById:function(id){var comps=CERN_MPageComponents;
var cLen=comps.length;
for(var i=cLen;
i--;
){var comp=comps[i];
if(comp.m_componentId===id){return comp;
}}return(null);
},LoadCodeListJSON:function(parentElement){var codeArray=new Array();
if(parentElement!=null){for(var x=0;
x<parentElement.length;
x++){var codeObject=new Object();
codeElement=parentElement[x];
codeObject.codeValue=codeElement.CODE;
codeObject.display=codeElement.DISPLAY;
codeObject.description=codeElement.DESCRIPTION;
codeObject.codeSet=codeElement.CODE_SET;
codeObject.sequence=codeElement.SEQUENCE;
codeObject.meaning=codeElement.MEANING;
var mapObj=new MP_Core.MapObject(codeObject.codeValue,codeObject);
codeArray.push(mapObj);
}}return(codeArray);
},LoadPersonelListJSON:function(parentElement){var personnelArray=new Array();
if(parentElement!=null){for(var x=0;
x<parentElement.length;
x++){var perObject=new Object();
codeElement=parentElement[x];
perObject.id=codeElement.ID;
perObject.fullName=codeElement.PROVIDER_NAME.NAME_FULL;
perObject.firstName=codeElement.PROVIDER_NAME.NAME_FIRST;
perObject.middleName=codeElement.PROVIDER_NAME.NAME_MIDDLE;
perObject.lastName=codeElement.PROVIDER_NAME.NAME_LAST;
perObject.userName=codeElement.PROVIDER_NAME.USERNAME;
perObject.initials=codeElement.PROVIDER_NAME.INITIALS;
perObject.title=codeElement.PROVIDER_NAME.TITLE;
var mapObj=new MP_Core.MapObject(perObject.id,perObject);
personnelArray[x]=mapObj;
}}return(personnelArray);
},WriteToFile:function(sText){try{var ForAppending=8;
var TriStateFalse=0;
var fso=new ActiveXObject("Scripting.FileSystemObject");
var newFile=fso.OpenTextFile("c:\\temp\\test.txt",ForAppending,true,TriStateFalse);
newFile.write(sText);
newFile.close();
}catch(err){var strErr="Error:";
strErr+="\nNumber:"+err.number;
strErr+="\nDescription:"+err.description;
document.write(strErr);
}},CalculateAge:function(bdate){var age;
var bdate=new Date(bdate);
var byear=bdate.getFullYear();
var bmonth=bdate.getMonth();
var bday=bdate.getDate();
var bhours=bdate.getHours();
today=new Date();
year=today.getFullYear();
month=today.getMonth();
day=today.getDate();
hours=today.getHours();
if(year==byear&&(day==bday)){age=hours-bhours;
age+=" Hours";
return age;
}else{if(year==byear&&(month==bmonth)){age=day-bday;
age+=" Days";
return age;
}}if(year==byear){age=month-bmonth;
age+=" Months";
return age;
}else{if(month<bmonth){age=year-byear-1;
}else{if(month>bmonth){age=year-byear;
}else{if(month==bmonth){if(day<bday){age=year-byear-1;
}else{if(day>bday){age=year-byear;
}else{if(day==bday){age=year-byear;
}}}}}}}age+=" Years";
return age;
},pad:function(str,len,pad,dir){if(typeof(len)=="undefined"){var len=0;
}if(typeof(pad)=="undefined"){var pad=" ";
}if(typeof(dir)=="undefined"){var dir=STR_PAD_RIGHT;
}if(len+1>=str.length){switch(dir){case STR_PAD_LEFT:str=Array(len+1-str.length).join(pad)+str;
break;
case STR_PAD_BOTH:var right=Math.ceil((padlen=len-str.length)/2);
var left=padlen-right;
str=Array(left+1).join(pad)+str+Array(right+1).join(pad);
break;
default:str=str+Array(len+1-str.length).join(pad);
break;
}}return str;
},GraphResults:function(eventCd,compID,groupID){var component=MP_Util.GetCompObjById(compID);
var lookBackUnits=(component.getLookbackUnits()!=null&&component.getLookbackUnits()>0)?component.getLookbackUnits():"365";
var lookBackType=(component.getLookbackUnitTypeFlag()!=null&&component.getLookbackUnitTypeFlag()>0)?component.getLookbackUnitTypeFlag():"2";
var i18nCore=i18n.discernabu;
var subTitleText="";
var scope=component.getScope();
var lookBackText="";
var criterion=component.getCriterion();
component.setLookbackUnits(lookBackUnits);
component.setLookbackUnitTypeFlag(lookBackType);
if(scope>0){switch(lookBackType){case 1:var replaceText=i18nCore.LAST_N_HOURS.replace("{0}",lookBackUnits);
break;
case 2:var replaceText=i18nCore.LAST_N_DAYS.replace("{0}",lookBackUnits);
break;
case 3:var replaceText=i18nCore.LAST_N_WEEKS.replace("{0}",lookBackUnits);
break;
case 4:var replaceText=i18nCore.LAST_N_MONTHS.replace("{0}",lookBackUnits);
break;
case 5:var replaceText=i18nCore.LAST_N_YEARS.replace("{0}",lookBackUnits);
break;
default:var replaceText=i18nCore.LAST_N_DAYS.replace("{0}",lookBackUnits);
break;
}switch(scope){case 1:lookBackText=i18nCore.ALL_N_VISITS.replace("{0}",replaceText);
var encntrOption="0.0";
break;
case 2:lookBackText=i18nCore.SELECTED_N_VISIT.replace("{0}",replaceText);
var encntrOption=criterion.encntr_id;
break;
}}var wParams="left=0,top=0,width=1200,height=700,toolbar=no";
var sParams="^MINE^,"+criterion.person_id+","+encntrOption+","+eventCd+",^"+criterion.static_content+"\\discrete-graphing^,"+groupID+","+criterion.provider_id+","+criterion.position_cd+","+criterion.ppr_cd+","+lookBackUnits+","+lookBackType+",200,^"+lookBackText+"^";
var graphCall="javascript:CCLLINK('mp_retrieve_graph_results', '"+sParams+"',1)";
javascript:CCLNEWSESSIONWINDOW(graphCall,"_self",wParams,0,1);
Util.preventDefault();
},ReleaseRequestReference:function(reqObj){if(XMLCCLREQUESTOBJECTPOINTER){for(var id in XMLCCLREQUESTOBJECTPOINTER){if(XMLCCLREQUESTOBJECTPOINTER[id]==reqObj){delete (XMLCCLREQUESTOBJECTPOINTER[id]);
}}}},CreateAutoSuggestBoxHtml:function(component){var searchBoxHTML=[];
var compNs=component.getStyles().getNameSpace();
var compId=component.getComponentId();
searchBoxHTML.push("<div class='search-box-div'><form name='contentForm'><input type='text' id='",compNs,"contentCtrl",compId,"'"," class='search-box'></form></div>");
return searchBoxHTML.join("");
},AddAutoSuggestControl:function(component,queryHandler,selectionHandler,selectDisplayHandler){new AutoSuggestControl(component,queryHandler,selectionHandler,selectDisplayHandler);
},RetrieveAutoSuggestSearchBox:function(component){var componentNamespace=component.getStyles().getNameSpace();
var componentId=component.getComponentId();
return _g(componentNamespace+"contentCtrl"+componentId);
},CreateParamArray:function(ar,type){var returnVal=(type===1)?"0.0":"0";
if(ar&&ar.length>0){if(ar.length>1){if(type===1){returnVal="value("+ar.join(".0,")+".0)";
}else{returnVal="value("+ar.join(",")+")";
}}else{returnVal=(type===1)?ar[0]+".0":ar[0];
}}return returnVal;
},GetDateFormatter:function(){if(!m_df){m_df=new mp_formatter.DateTimeFormatter(MPAGE_LOCALE);
}return m_df;
},GetNumericFormatter:function(){if(!m_nf){m_nf=new mp_formatter.NumericFormatter(MPAGE_LOCALE);
}return m_nf;
},CalculatePrecision:function(valRes){var precision=0;
var str=(MP_Util.IsString(valRes))?valRes:valRes.toString();
var decLoc=str.search(/\.(\d)/);
if(decLoc!==-1){var strSize=str.length;
precision=strSize-decLoc-1;
}return precision;
},CreateDateParameter:function(date){var day=date.getDate();
var month="";
var rest=date.format("yyyy HH:MM:ss");
switch(date.getMonth()){case (0):month="JAN";
break;
case (1):month="FEB";
break;
case (2):month="MAR";
break;
case (3):month="APR";
break;
case (4):month="MAY";
break;
case (5):month="JUN";
break;
case (6):month="JUL";
break;
case (7):month="AUG";
break;
case (8):month="SEP";
break;
case (9):month="OCT";
break;
case (10):month="NOV";
break;
case (11):month="DEC";
break;
default:alert("unknown month");
}return(day+"-"+month+"-"+rest);
}};
function GetDateDiffString(beginDate,endDate,mathFlag,abbreviateFlag){var i18nCore=i18n.discernabu;
var timeDiff=0;
var returnVal="";
endDate=(!endDate)?new Date():endDate;
mathFlag=(!mathFlag)?0:mathFlag;
var one_minute=1000*60;
var one_hour=one_minute*60;
var one_day=one_hour*24;
var one_week=one_day*7;
var one_month=one_day*(365/12);
var one_year=one_month*12;
var valMinutes=0;
var valHours=0;
var valDays=0;
var valWeeks=0;
var valMonths=0;
var valYears=0;
timeDiff=(endDate.getTime()-beginDate.getTime());
var mathFunc=null;
var comparisonFunc=null;
if(mathFlag==0){mathFunc=function(val){return Math.ceil(val);
};
comparisonFunc=function(lowerVal,upperVal){return(lowerVal<=upperVal);
};
}else{mathFunc=function(val){return Math.floor(val);
};
comparisonFunc=function(lowerVal,upperVal){return(lowerVal<upperVal);
};
}valMinutes=mathFunc(timeDiff/one_minute);
valHours=mathFunc(timeDiff/one_hour);
valDays=mathFunc(timeDiff/one_day);
valWeeks=mathFunc(timeDiff/one_week);
valMonths=mathFunc(timeDiff/one_month);
valYears=mathFunc(timeDiff/one_year);
if(comparisonFunc(valHours,2)){returnVal=abbreviateFlag?(i18nCore.WITHIN_MINS.replace("{0}",valMinutes)):(i18nCore.X_MINUTES.replace("{0}",valMinutes));
}else{if(comparisonFunc(valDays,2)){returnVal=abbreviateFlag?(i18nCore.WITHIN_HOURS.replace("{0}",valHours)):(i18nCore.X_HOURS.replace("{0}",valHours));
}else{if(comparisonFunc(valWeeks,2)){returnVal=abbreviateFlag?(i18nCore.WITHIN_DAYS.replace("{0}",valDays)):(i18nCore.X_DAYS.replace("{0}",valDays));
}else{if(comparisonFunc(valMonths,2)){returnVal=abbreviateFlag?(i18nCore.WITHIN_WEEKS.replace("{0}",valWeeks)):(i18nCore.X_WEEKS.replace("{0}",valWeeks));
}else{if(comparisonFunc(valYears,2)){returnVal=abbreviateFlag?(i18nCore.WITHIN_MONTHS.replace("{0}",valMonths)):(i18nCore.X_MONTHS.replace("{0}",valMonths));
}else{returnVal=abbreviateFlag?(i18nCore.WITHIN_YEARS.replace("{0}",valYears)):(i18nCore.X_YEARS.replace("{0}",valYears));
}}}}}return(returnVal);
}}();
MP_Util.Doc=function(){var isExpandedAll=false;
return{InitMPageTabLayout:function(arMapObjects,title){var arItems=[];
var sc="",helpFile="",helpURL="",debugInd=false;
var bDisplayBanner=false;
var criterion=null;
var custInd=true;
var anchorArray=null;
for(var x=0,xl=arMapObjects.length;
x<xl;
x++){var key=arMapObjects[x].name;
var page=arMapObjects[x].value;
criterion=page.getCriterion();
arItems.push(new MP_Core.TabItem(key,page.getName(),page.getComponents(),criterion.category_mean));
sc=criterion.static_content;
debugInd=criterion.debug_ind;
helpFile=page.getHelpFileName();
helpURL=page.getHelpFileURL();
custInd=page.getCustomizeEnabled();
anchorArray=page.getTitleAnchors();
if(page.isBannerEnabled()){bDisplayBanner=page.isBannerEnabled();
}}MP_Util.Doc.InitTabLayout(arItems,title,sc,helpFile,helpURL,bDisplayBanner,0,criterion,custInd,anchorArray);
},InitTabLayout:function(arTabItems,title,sc,helpFile,helpURL,includeBanner,debugInd,criterion,custInd,anchorArray){var body=document.body;
var i18nCore=i18n.discernabu;
MP_Util.Doc.AddPageTitle(title,body,debugInd,custInd,anchorArray,helpFile,helpURL,criterion);
if(includeBanner){body.innerHTML+="<div id=banner></div>";
}body.innerHTML+="<div id='disclaimer'><span>"+i18nCore.DISCLAIMER+"</span></div>";
AddPageTabs(arTabItems,body);
CERN_TabManagers=[];
for(var x=0,xl=arTabItems.length;
x<xl;
x++){var tabItem=arTabItems[x];
var tabManager=new MP_Core.TabManager(tabItem);
if(x==0){tabManager.setSelectedTab(true);
}CERN_TabManagers.push(tabManager);
CreateLiquidLayout(tabItem.components,_g(arTabItems[x].key));
}MP_Util.Doc.AddCustomizeLink(criterion);
SetupExpandCollapse();
},InitLayout:function(mPage,helpFile,helpURL){var body=document.body;
var i18nCore=i18n.discernabu;
var criterion=mPage.getCriterion();
MP_Util.Doc.AddPageTitle(mPage.getName(),body,criterion.debug_ind,mPage.getCustomizeEnabled(),mPage.getTitleAnchors(),helpFile,helpURL,criterion);
if(mPage.isBannerEnabled()){body.innerHTML+="<div id=banner></div>";
}body.innerHTML+="<div id='disclaimer'><span>"+i18nCore.DISCLAIMER+"</span></div>";
CreateLiquidLayout(mPage.getComponents(),body);
MP_Util.Doc.AddCustomizeLink(criterion);
SetupExpandCollapse();
},CustomizeLayout:function(title,components,criterion){var body=document.body;
var i18nCore=i18n.discernabu;
MP_Util.Doc.AddPageTitle(title,body,0,false,null,null,null,criterion);
MP_Util.Doc.AddClearPreferences(body);
MP_Util.Doc.AddSavePreferences(body);
body.innerHTML+="<div id='disclaimer'><span>"+i18nCore.USER_CUST_DISCLAIMER+"</span></div>";
var compAr=[];
for(var x=components.length;
x--;
){var component=components[x];
if(component.getColumn()!=99){compAr.push(component);
}}CreateCustomizeLiquidLayout(compAr,body);
SetupExpandCollapse();
},GetComments:function(par,personnelArray){var com="",recDate="";
var df=new mp_formatter.DateTimeFormatter(MPAGE_LOCALE);
for(var j=0,m=par.COMMENTS.length;
j<m;
j++){if(personnelArray.length!=null){if(par.COMMENTS[j].RECORDED_BY){perCodeObj=MP_Util.GetValueFromArray(par.COMMENTS[j].RECORDED_BY,personnelArray);
}if(par.COMMENTS[j].RECORDED_DT_TM!=""){recDate=df.formatISO8601(par.COMMENTS[j].RECORDED_DT_TM,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_4YEAR);
}if(j>0){com+="<br />";
}com+=recDate+" -  "+perCodeObj.fullName+"<br />"+par.COMMENTS[j].COMMENT_TEXT;
}}return com;
},FinalizeComponent:function(contentHTML,component,countText){var styles=component.getStyles();
var rootComponentNode=component.getRootComponentNode();
var totalCount=Util.Style.g("sec-total",rootComponentNode,"span");
totalCount[0].innerHTML=countText;
var node=component.getSectionContentNode();
node.innerHTML=contentHTML;
MP_Util.Doc.InitHovers(styles.getInfo(),node,component);
MP_Util.Doc.InitSubToggles(node,"sub-sec-hd-tgl");
MP_Util.Doc.InitScrolling(Util.Style.g("scrollable",node,"div"),component.getScrollNumber(),"1.6");
},InitScrolling:function(content,num,ht){for(var k=0;
k<content.length;
k++){MP_Util.Doc.InitSectionScrolling(content[k],num,ht);
}},InitSectionScrolling:function(sec,num,ht){var th=num*ht;
var totalHeight=th+"em";
sec.style.height=totalHeight;
sec.style.overflowY="scroll";
sec.style.overflowX="hidden";
},InitHovers:function(trg,par,component){gen=Util.Style.g(trg,par,"DL");
for(var i=0,l=gen.length;
i<l;
i++){var m=gen[i];
if(m){var nm=Util.gns(Util.gns(m));
if(nm){if(Util.Style.ccss(nm,"hvr")){hs(m,nm,component);
}}}}},InitSubToggles:function(par,tog){var i18nCore=i18n.discernabu;
var toggleArray=Util.Style.g(tog,par,"span");
for(var k=0;
k<toggleArray.length;
k++){Util.addEvent(toggleArray[k],"click",MP_Util.Doc.ExpandCollapse);
var checkClosed=Util.gp(Util.gp(toggleArray[k]));
if(Util.Style.ccss(checkClosed,"closed")){toggleArray[k].innerHTML="+";
toggleArray[k].title=i18nCore.SHOW_SECTION;
}}},ExpandCollapseAll:function(){var i18nCore=i18n.discernabu;
var allSections=Util.Style.g("section");
var expNode=_g("expAll");
if(isExpandedAll){for(var i=0,asLen=allSections.length;
i<asLen;
i++){var secHandle=Util.gc(Util.gc(allSections[i]));
if(secHandle.innerHTML=="-"||secHandle.innerHTML=="+"){Util.Style.acss(allSections[i],"closed");
secHandle.innerHTML="+";
secHandle.title=i18nCore.SHOW_SECTION;
}else{var allSubSections=Util.Style.g("sub-sec",allSections[i],"div");
for(var j=0,aSubLen=allSubSections.length;
j<aSubLen;
j++){var subSecTgl=Util.gc(Util.gc(allSubSections[j]));
Util.Style.acss(allSubSections[j],"closed");
subSecTgl.innerHTML="+";
subSecTgl.title=i18nCore.SHOW_SECTION;
}}expNode.innerHTML=i18nCore.EXPAND_ALL;
}isExpandedAll=false;
}else{for(var i=0,asLen=allSections.length;
i<asLen;
i++){var secHandle=Util.gc(Util.gc(allSections[i]));
if(secHandle.innerHTML=="-"||secHandle.innerHTML=="+"){Util.Style.rcss(allSections[i],"closed");
secHandle.innerHTML="-";
secHandle.title=i18nCore.HIDE_SECTION;
}else{var allSubSections=Util.Style.g("sub-sec",allSections[i],"div");
for(var j=0,aSubLen=allSubSections.length;
j<aSubLen;
j++){var subSecTgl=Util.gc(Util.gc(allSubSections[j]));
Util.Style.rcss(allSubSections[j],"closed");
subSecTgl.innerHTML="-";
subSecTgl.title=i18nCore.HIDE_SECTION;
}}expNode.innerHTML=i18nCore.COLLAPSE_ALL;
}isExpandedAll=true;
}},AddPageTitle:function(title,bodyTag,debugInd,custInd,anchorArray,helpFile,helpURL,criterion){var i18nCore=i18n.discernabu;
var ar=[];
var imgSource=criterion.static_content+"\\images\\3865_16.gif";
if(bodyTag){bodyTag=document.body;
}ar.push("<div class='pg-hd'>");
ar.push("<h1><span class=pg-title>",title,"</span></h1><span id=pageCtrl class=page-ctrl>");
if(anchorArray!=null){for(var x=0,xl=anchorArray.length;
x<xl;
x++){ar.push(anchorArray[x]);
}}ar.push("<a id=expAll onclick='javascript:MP_Util.Doc.ExpandCollapseAll()'>",i18nCore.EXPAND_ALL,"</a>");
if(custInd){ar.push("<a id=custView></a>");
}if(criterion.help_file_local_ind===1&&helpFile&&helpFile.length>0){ar.push("<a id=helpMenu onclick='MP_Util.Doc.LaunchHelpWindow(\""+helpFile+"\")' >",i18nCore.HELP,"</a><img src='",imgSource,"'/></span></div>");
}else{if(helpURL&&helpURL.length>0){ar.push("<a id=helpMenu onclick='MP_Util.Doc.LaunchHelpWindow(\""+helpURL+"\")' >",i18nCore.HELP,"</a><img src='",imgSource,"'/></span></div>");
}}bodyTag.innerHTML+=ar.join("");
return;
},LaunchHelpWindow:function(helpURL){var wParams="left=0,top=0,width=1200,height=700,toolbar=no";
CCLNEWSESSIONWINDOW(helpURL,"_self",wParams,0,1);
Util.preventDefault();
},AddClearPreferences:function(body){var i18nCore=i18n.discernabu;
var pageCtrl=_g("pageCtrl");
var clearPrefNode=Util.cep("A",{id:"clearPrefs",onclick:"javascript:MP_Core.AppUserPreferenceManager.ClearPreferences();"});
clearPrefNode.innerHTML=i18nCore.CLEAR_PREFERENCES;
Util.ac(clearPrefNode,pageCtrl);
},AddSavePreferences:function(body){var i18nCore=i18n.discernabu;
var pageCtrl=_g("pageCtrl");
var savePrefNode=Util.cep("A",{id:"savePrefs",onclick:"javascript:MP_Core.AppUserPreferenceManager.SavePreferences();"});
savePrefNode.innerHTML=i18nCore.SAVE_PREFERENCES;
Util.ac(savePrefNode,pageCtrl);
},AddCustomizeLink:function(criterion){var i18nCore=i18n.discernabu;
var custNode=_g("custView");
if(custNode!=null){custNode.innerHTML=i18nCore.CUSTOMIZE;
var compReportIds=GetPageReportIds();
var cclParams=["^MINE^",criterion.person_id+".0",criterion.encntr_id+".0",criterion.provider_id+".0",criterion.position_cd+".0",criterion.ppr_cd+".0","^"+criterion.executable+"^","^"+criterion.device_location+"^","^"+criterion.static_content.replace(/\\/g,"\\\\")+"^","^"+criterion.category_mean+"^",criterion.debug_ind,"value("+compReportIds.join(",")+")","1"];
custNode.onclick=function(){CCLLINK("MP_DRIVER",cclParams.join(","),1);
Util.preventDefault();
};
}},RenderLayout:function(){if(CERN_TabManagers!=null){var tabManager=null;
if(window.name.length>0){var paramList=window.name.split(",");
MP_Util.DisplaySelectedTab(paramList[0],paramList[1]);
}else{tabManager=CERN_TabManagers[0];
tabManager.setSelectedTab(true);
tabManager.loadTab();
}}else{if(CERN_MPageComponents!=null){for(var x=CERN_MPageComponents.length;
x--;
){var comp=CERN_MPageComponents[x];
if(comp.isDisplayable()){comp.InsertData();
}}}}},ExpandCollapse:function(){var i18nCore=i18n.discernabu;
var gpp=Util.gp(Util.gp(this));
if(Util.Style.ccss(gpp,"closed")){Util.Style.rcss(gpp,"closed");
this.innerHTML="-";
this.title=i18nCore.HIDE_SECTION;
}else{Util.Style.acss(gpp,"closed");
this.innerHTML="+";
this.title=i18nCore.SHOW_SECTION;
}},HideHovers:function(){var hovers=Util.Style.g("hover",document.body,"DIV");
for(var i=hovers.length;
i--;
){if(Util.gp(hovers[i]).nodeName=="BODY"){hovers[i].style.display="none";
Util.de(hovers[i]);
}}},ReplaceSubTitleText:function(component,text){var compNode=component.getRootComponentNode();
var subTitle=Util.Style.g("sub-title-disp",compNode,"div");
if(subTitle){subTitle[0].innerHTML=text;
}},ReInitSubTitleText:function(component){if(component.getScope()>0){var st=Util.Style.g("sub-title-disp",component.getRootComponentNode(),"div");
st[0].innerHTML=CreateSubTitleText(component);
}}};
function GetPreferenceIdentifier(){var prefIdentifier="";
if(CERN_TabManagers!=null){for(var x=CERN_TabManagers.length;
x--;
){var tabManager=CERN_TabManagers[x];
if(tabManager.getSelectedTab()){var tabItem=tabManager.getTabItem();
return tabItem.prefIdentifier;
}}}else{if(CERN_MPageComponents!=null){for(var x=CERN_MPageComponents.length;
x--;
){var criterion=CERN_MPageComponents[x].getCriterion();
return criterion.category_mean;
}}}return prefIdentifier;
}function GetPageReportIds(){var ar=[];
if(CERN_TabManagers!=null){for(var x=CERN_TabManagers.length;
x--;
){var tabManager=CERN_TabManagers[x];
if(tabManager.getSelectedTab()){var tabItem=tabManager.getTabItem();
var components=tabItem.components;
if(components!=null&&components.length>0){for(var y=components.length;
y--;
){ar.push(components[y].getReportId());
}}break;
}}}else{if(CERN_MPageComponents!=null){for(var x=CERN_MPageComponents.length;
x--;
){ar.push(CERN_MPageComponents[x].getReportId());
}}}return ar;
}function GetComponentArray(components){var grpAr=[];
var colAr=[];
var rowAr=[];
var curCol=-1;
var curGrp=-1;
var sHTML=[];
if(components!=null){components.sort(SortMPageComponents);
for(var x=0,xl=components.length;
x<xl;
x++){var component=components[x];
if(CERN_MPageComponents==null){CERN_MPageComponents=[];
}CERN_MPageComponents.push(component);
if(component.isDisplayable()){var compGrp=component.getPageGroupSequence();
var compCol=component.getColumn();
if(compGrp!=curGrp){curCol=-1;
colAr=[];
grpAr.push(colAr);
curGrp=compGrp;
}if(compCol!=curCol){rowAr=[];
colAr.push(rowAr);
curCol=compCol;
}rowAr.push(component);
}}}return grpAr;
}function CreateCustomizeLiquidLayout(components,parentNode){var sHTML=[];
var grpAr=GetComponentArray(components);
sHTML.push("<div class=pref-columns>");
for(var x=0,xl=grpAr.length;
x<xl;
x++){colAr=grpAr[x];
sHTML.push("<div>");
var colLen=colAr.length;
sHTML.push("<div class='col-group three-col'>");
sHTML.push("<div class='col-outer2'><div class='col-outer1'>");
for(var y=0;
y<colLen;
y++){var comps=colAr[y];
var colClassName="col"+(y+1)+" cust-col";
sHTML.push("<div class='",colClassName,"'>");
for(var z=0,zl=comps.length;
z<zl;
z++){sHTML.push(CreateCompDiv(comps[z]));
}sHTML.push("</div>");
}for(var y=colLen+1;
y<=3;
y++){var colClassName="col"+(y)+" cust-col";
sHTML.push("<div class='",colClassName,"'></div>");
}sHTML.push("</div></div></div></div>");
}sHTML.push("</div>");
parentNode.innerHTML+=sHTML.join("");
}function CreateLiquidLayout(components,parentNode){var grpAr=GetComponentArray(components);
var sHTML=[];
for(var x=0,xl=grpAr.length;
x<xl;
x++){colAr=grpAr[x];
sHTML.push("<div>");
var colLen=colAr.length;
if(colLen==1){sHTML.push("<div class='col-group one-col'>");
}else{if(colLen==2){sHTML.push("<div class='col-group two-col'>");
}else{sHTML.push("<div class='col-group three-col'>");
}}sHTML.push("<div class='col-outer2'><div class='col-outer1'>");
for(var y=0;
y<colLen;
y++){var colClassName="col"+(y+1);
var comps=colAr[y];
sHTML.push("<div class='",colClassName,"'>");
for(var z=0,zl=comps.length;
z<zl;
z++){sHTML.push(CreateCompDiv(comps[z]));
}sHTML.push("</div>");
}sHTML.push("</div></div></div></div>");
}parentNode.innerHTML+=sHTML.join("");
}function SetupExpandCollapse(){var i18nCore=i18n.discernabu;
var toggleArray=Util.Style.g("sec-hd-tgl");
for(var k=0;
k<toggleArray.length;
k++){Util.addEvent(toggleArray[k],"click",MP_Util.Doc.ExpandCollapse);
var checkClosed=Util.gp(Util.gp(toggleArray[k]));
if(Util.Style.ccss(checkClosed,"closed")){toggleArray[k].innerHTML="+";
toggleArray[k].title=i18nCore.SHOW_SECTION;
}}}function CreateCompDiv(component){var i18nCore=i18n.discernabu;
var ar=[];
var style=component.getStyles();
var ns=style.getNameSpace();
var compId=style.getId();
var secClass=style.getClassName();
var tabLink=component.getLink();
var loc=component.getCriterion().static_content;
var tglCode=(!component.isAlwaysExpanded())?["<span class='",style.getHeaderToggle(),"' title='",i18nCore.HIDE_SECTION,"'>-</span>"].join(""):"";
if(!component.isExpanded()&&!component.isAlwaysExpanded()){secClass+=" closed";
}var sAnchor=(tabLink!=""&&component.getCustomizeView()==false)?CreateComponentAnchor(component):component.getLabel();
ar.push("<div id='",style.getId(),"' class='",secClass,"'>","<h2 class='",style.getHeaderClass(),"'>",tglCode,"<span class='",style.getTitle(),"'><span>",sAnchor,"</span>");
if(component.getCustomizeView()==false){ar.push("<span class='",style.getTotal(),"'>",i18nCore.LOADING_DATA+"...","</span></span>");
if(component.isPlusAddEnabled()){ar.push("<a id='",ns,"Add' class=add-plus onclick='MP_Util.OpenTab(\"",compId,"\"); return false;' href='#'><span class='add-icon'>&nbsp;</span><span class='add-text'>",i18nCore.ADD,"</span></a>");
var menuItems=component.getMenuItems();
if(menuItems!=null||menuItems>0){var menuId=compId+"Menu";
ar.push("<a id='",ns,"Drop' class='drop-Down'><img src='",loc,"\\images\\3943_16.gif' onclick='javascript:MP_Util.LaunchMenu(\"",menuId,'", "',compId,"\");'></a>");
ar.push("<div class='form-menu menu-hide' id='",menuId,"'><span>");
for(var x=0,xl=menuItems.length;
x<xl;
x++){var item=menuItems[x];
ar.push("<div>");
ar.push("<a id='lnkID",x,"' href='#' onclick='javascript:MP_Util.LaunchMenuSelection(\"",compId,'",',item.getId(),");'>",item.getDescription(),"</a>");
ar.push("</div>");
}ar.push("</span></div>");
}}}else{ar.push("</span>");
}ar.push("</h2>");
if(component.getCustomizeView()==false){if(component.getScope()>0){ar.push("<div class=sub-title-disp>",CreateSubTitleText(component),"</div>");
}}ar.push("<div id='",style.getContentId(),"' class='",style.getContentClass(),"'></div>");
var footerText=component.getFooterText();
if(footerText&&footerText!==""){ar.push("<div class=sec-footer>",footerText,"</div>");
}ar.push("</div>");
var arHtml=ar.join("");
return arHtml;
}function CreateSubTitleText(component){var i18nCore=i18n.discernabu;
var subTitleText="";
var scope=component.getScope();
var lookbackDays=component.getLookbackDays();
var lookbackUnits=(lookbackDays>0)?lookbackDays:component.getLookbackUnits();
var lookbackFlag=(lookbackDays>0)?2:component.getLookbackUnitTypeFlag();
if(scope>0){if(lookbackFlag>0&&lookbackUnits>0){var replaceText="";
switch(lookbackFlag){case 1:replaceText=i18nCore.LAST_N_HOURS.replace("{0}",lookbackUnits);
break;
case 2:replaceText=i18nCore.LAST_N_DAYS.replace("{0}",lookbackUnits);
break;
case 3:replaceText=i18nCore.LAST_N_WEEKS.replace("{0}",lookbackUnits);
break;
case 4:replaceText=i18nCore.LAST_N_MONTHS.replace("{0}",lookbackUnits);
break;
case 5:replaceText=i18nCore.LAST_N_YEARS.replace("{0}",lookbackUnits);
break;
}switch(scope){case 1:subTitleText=i18nCore.ALL_N_VISITS.replace("{0}",replaceText);
break;
case 2:subTitleText=i18nCore.SELECTED_N_VISIT.replace("{0}",replaceText);
break;
}}else{switch(scope){case 1:subTitleText=i18nCore.All_VISITS;
break;
case 2:subTitleText=i18nCore.SELECTED_VISIT;
break;
}}}return subTitleText;
}function CreateComponentAnchor(component){var i18nCore=i18n.discernabu;
var style=component.getStyles();
var criterion=component.getCriterion();
var sParms='javascript:APPLINK(0,"'+criterion.executable+'","/PERSONID='+criterion.person_id+" /ENCNTRID="+criterion.encntr_id+" /FIRSTTAB=^"+component.getLink()+'^"); return false;';
var sAnchor="<a id="+style.getLink()+" title='"+i18nCore.GO_TO_TAB.replace("{0}",component.getLink())+"' href='#' onclick='"+sParms+"'>"+component.getLabel()+"</a>";
return sAnchor;
}function AddPageTabs(items,bodyTag){var ar=[];
var divAr=[];
if(bodyTag==null){bodyTag=document.body;
}ar.push("<ul class=tabmenu>");
for(var x=0,xl=items.length;
x<xl;
x++){var item=items[x];
var activeInd=(x==0)?1:0;
ar.push(CreateTabLi(item,activeInd,x));
divAr.push("<div id='",item.key,"' class='div-tab-item'></div>");
}ar.push("</ul>");
bodyTag.innerHTML+=(ar.join("")+divAr.join(""));
}function CreateTabLi(item,activeInd,sequence){var ar=[];
var tabName="";
tabName=item.name;
ar.push("<li>");
var seqClass="a-tab"+sequence;
if(activeInd){ar.push("<a id='",seqClass,"' class='anchor-tab-item active' href='#' onclick='javascript:MP_Util.DisplaySelectedTab(\"",item.key,'","',seqClass,"\");return false;'>",tabName,"</a>");
}else{ar.push("<a id='",seqClass,"' class='anchor-tab-item inactive' href='#' onclick='javascript:MP_Util.DisplaySelectedTab(\"",item.key,'","',seqClass,"\");return false;'>",tabName,"</a>");
}ar.push("</li>");
return(ar.join(""));
}}();
MP_Util.Measurement=function(){var m_nf=null;
return{GetString:function(result,codeArray,dateMask,excludeUOM){var obj=(result instanceof MP_Core.Measurement)?result.getResult():MP_Util.Measurement.GetObject(result,codeArray);
if(obj instanceof MP_Core.QuantityValue){if(excludeUOM){return obj.getValue();
}return obj.toString();
}else{if(obj instanceof Date){return obj.format(dateMask);
}}return obj;
},GetObject:function(result,codeArray){switch(result.CLASSIFICATION.toUpperCase()){case"QUANTITY_VALUE":return GetQuantityValue(result,codeArray);
case"STRING_VALUE":return(GetStringValue(result));
case"DATE_VALUE":return(GetDateValue(result));
case"CODIFIED_VALUES":case"CODE_VALUE":return(GetCodedResult(result));
case"ENCAPSULATED_VALUE":return(GetEncapsulatedValue(result));
}},SetPrecision:function(num,dec){var nf=MP_Util.GetNumericFormatter();
return nf.format(num,"^."+dec);
},GetModifiedIcon:function(result){return(result.isModified())?"<span class='res-modified'>&nbsp;</span>":"";
},GetNormalcyClass:function(oMeasurement){var normalcy="res-normal";
var nc=oMeasurement.getNormalcy();
if(nc!=null){var normalcyMeaning=nc.meaning;
if(normalcyMeaning!=null){if(normalcyMeaning==="LOW"){normalcy="res-low";
}else{if(normalcyMeaning==="HIGH"){normalcy="res-high";
}else{if(normalcyMeaning==="CRITICAL"||normalcyMeaning==="EXTREMEHIGH"||normalcyMeaning==="PANICHIGH"||normalcyMeaning==="EXTREMELOW"||normalcyMeaning==="PANICLOW"||normalcyMeaning==="VABNORMAL"||normalcyMeaning==="POSITIVE"){normalcy="res-severe";
}else{if(normalcyMeaning==="ABNORMAL"){normalcy="res-abnormal";
}}}}}}return normalcy;
},GetNormalcyResultDisplay:function(oMeasurement,excludeUOM){var ar=["<span class='",MP_Util.Measurement.GetNormalcyClass(oMeasurement),"'><span class='res-ind'>&nbsp;</span><span class='res-value'>",GetEventViewerLink(oMeasurement,MP_Util.Measurement.GetString(oMeasurement,null,"longDateTime2",excludeUOM)),"</span>",MP_Util.Measurement.GetModifiedIcon(oMeasurement),"</span>"];
return ar.join("");
}};
function GetEventViewerLink(oMeasurement,sResultDisplay){var params=[oMeasurement.getPersonId(),oMeasurement.getEncntrId(),oMeasurement.getEventId(),'"EVENT"'];
var ar=["<a onclick='MP_Util.LaunchClinNoteViewer(",params.join(","),"); return false;' href='#'>",sResultDisplay,"</a>"];
return ar.join("");
}function GetEncapsulatedValue(result){var ar=[];
var encap=result.ENCAPSULATED_VALUE;
if(encap&&encap.length>0){for(var n=0,nl=encap.length;
n<nl;
n++){var txt=encap[n].TEXT_PLAIN;
if(txt!=null&&txt.length>0){ar.push(txt);
}}}return ar.join("");
}function GetQuantityValue(result,codeArray){var qv=new MP_Core.QuantityValue();
qv.init(result,codeArray);
return qv;
}function GetDateValue(result){for(var x=0,xl=result.DATE_VALUE.length;
x<xl;
x++){var date=result.DATE_VALUE[x];
if(date.DATE!=""){var dateTime=new Date();
dateTime.setISO8601(date.DATE);
return dateTime;
}}return null;
}function GetCodedResult(result){var cdValue=result.CODE_VALUE;
var ar=[];
for(var n=0,nl=cdValue.length;
n<nl;
n++){var values=cdValue[n].VALUES;
for(var p=0,pl=values.length;
p<pl;
p++){ar.push(values[p].SOURCE_STRING);
}var sOther=cdValue[n].OTHER_RESPONSE;
if(sOther!=""){ar.push(sOther);
}}return ar.join(", ");
}function GetStringValue(result){var strValue=result.STRING_VALUE;
var ar=[];
for(var n=0,nl=strValue.length;
n<nl;
n++){ar.push(strValue[n].VALUE);
}return ar.join(", ");
}}();
document.getElementsByClassName=function(cl,e){var retnode=[];
var clssnm=new RegExp("\\b"+cl+"\\b");
var elem=this.getElementsByTagName("*",e);
for(var u=0;
u<elem.length;
u++){var classes=elem[u].className;
if(clssnm.test(classes)){retnode.push(elem[u]);
}}return retnode;
};
Function.prototype.bind=function(object){var method=this;
return function(){return method.apply(object,arguments);
};
};
function EventListener(){this.events=[];
this.builtinEvts=[];
}EventListener.prototype.getActionIdx=function(obj,evt,action,binding){if(obj&&evt){var curel=this.events[obj][evt];
if(curel){var len=curel.length;
for(var i=len-1;
i>=0;
i--){if(curel[i].action==action&&curel[i].binding==binding){return i;
}}}else{return -1;
}}return -1;
};
EventListener.prototype.addListener=function(obj,evt,action,binding){if(this.events[obj]){if(this.events[obj][evt]){if(this.getActionIdx(obj,evt,action,binding)==-1){var curevt=this.events[obj][evt];
curevt[curevt.length]={action:action,binding:binding};
}}else{this.events[obj][evt]=[];
this.events[obj][evt][0]={action:action,binding:binding};
}}else{this.events[obj]=[];
this.events[obj][evt]=[];
this.events[obj][evt][0]={action:action,binding:binding};
}};
EventListener.prototype.removeListener=function(obj,evt,action,binding){if(this.events[obj]){if(this.events[obj][evt]){var idx=this.getActionIdx(obj,evt,action,binding);
if(idx>=0){this.events[obj][evt].splice(idx,1);
}}}};
EventListener.prototype.removeAllListeners=function(obj,binding){if(this.events[obj]){for(var el=this.events[obj].length;
el--;
){if(this.events[obj][el]){for(var ev=this.events[obj][el].length;
ev--;
){if(this.events[obj][el][ev].binding==binding){this.events[obj][el].splice(ev,1);
}}}}}};
EventListener.prototype.fireEvent=function(e,obj,evt,args){if(!e){e=window.event;
}if(obj&&this.events){var evtel=this.events[obj];
if(evtel){var curel=evtel[evt];
if(curel){for(var act=curel.length;
act--;
){var action=curel[act].action;
if(curel[act].binding){action=action.bind(curel[act].binding);
}action(e,args);
}}}}};
CERN_EventListener=new EventListener();
EventListener.EVENT_CLINICAL_EVENT=1;
EventListener.EVENT_ORDER_ACTION=2;
