function SpellCheckPluginHelper(){var WORD_BOUNDARIES=["\r","\n"," ","(",")","*","/","<","=",">","[","\\","]","{","}","-","+",";",",",".","`","!","@","#","$","%","^","&",":","+","_","?","~","|",'"'];
var WORD_BOUNDARIES_LOOKUP={};
$(WORD_BOUNDARIES).each(function(){WORD_BOUNDARIES_LOOKUP[this]=1;
});
var m_bSpellcheckEnabled=true;
var SCAYT_TIMER_TIMEOUT=2000;
var mainSuggestions={};
function checkSpelling(sWord){var spelledCorrectly=CKEDITOR.SpellCheckHelper.CheckSpelling(sWord);
return spelledCorrectly;
}function trimWord(word){if(!word){return{word:word,wordPosition:0};
}var match=/^(['"]*)(.*?)['"]*$/.exec(word);
if(match){return{word:match[2],wordPosition:match[1].length};
}else{DocHandleError("SpellCheckPluginHelper::trimWord, trim word error","DynDocCKEditor","",word);
return{word:word,wordPosition:0};
}}function getCursorPosition(oElement,oRange){var oRangePosition=DDCOMMON.getRangePosition(oElement,oRange);
if(null==oRangePosition||oRangePosition.start<-1||oRangePosition.end<-1){return -1;
}return oRange.text.length>0?oRangePosition.start:oRangePosition.end;
}function trimRangeWhitespace(range){while(range.text.length&&/\s/.test(range.text.charAt(0))){range.moveStart("character",1);
}while(range.text.length&&/\s/.test(range.text.charAt(range.text.length-1))){range.moveEnd("character",-1);
}}function getWordRangeAtCursor(element,selectedRange){var wordRange=selectedRange.duplicate();
var elementRange=selectedRange.duplicate();
elementRange.moveToElementText(element);
while(wordRange.compareEndPoints("StartToStart",elementRange)>0){wordRange.moveStart("character",-1);
if(WORD_BOUNDARIES_LOOKUP[wordRange.text.charAt(0)]){wordRange.moveStart("character",1);
break;
}}while(wordRange.compareEndPoints("EndToEnd",elementRange)<0){wordRange.moveEnd("character",1);
if(WORD_BOUNDARIES_LOOKUP[wordRange.text.charAt(wordRange.text.length-1)]){wordRange.moveEnd("character",-1);
break;
}}return wordRange;
}function replaceMisspelledWord(range,text){range.pasteHTML(text);
var rangeParent=range.parentElement();
var spellCheckSpan=DDCOMMON.hasClassName(rangeParent.className,g_sCLASS_SPELLCHECK)?rangeParent:$(rangeParent).closest(g_sCLASS_SPELLCHECK).get(0);
if(spellCheckSpan){spellCheckSpan.removeNode();
}return true;
}return{m_oEditor:null,m_nMouseDowns:0,m_lastCharPress:null,m_mapTimers:[],m_spellCheckTimeout:null,contentDomHandler:function(event){var editable=this.m_oEditor.editable();
editable.on("keyup",this.keyUpHandler,this);
editable.on("keypress",this.keyPressHandler,this);
editable.on("mousedown",this.mouseDownHandler,this);
editable.on("mouseup",this.mouseUpHandler,this);
editable.on("click",this.clickHandler,this);
editable.on("dblclick",this.doubleClickHandler,this);
},instanceReadyHandler:function(event){var body=this.m_oEditor.document.$.body;
if(!body.id){var sGUID=CKEDITOR.DocUtilsHelper.GenerateGUID();
body.id=sGUID;
}var oHelper=this;
oHelper.m_oEditor.fire("saveSnapshot");
oHelper.m_oEditor.registerXhtmlFilter(function(){var oBody=oHelper.m_oEditor.plugins.divarea?oHelper.m_oEditor.ui.space("contents").$:oHelper.m_oEditor.document.getBody().$;
var arrElements=DDCOMMON.getDescendentsByClassName(oBody,g_sCLASS_SPELLCHECK);
while(arrElements&&arrElements.length>0){arrElements.pop().removeNode();
}});
},beforeDestroyHandler:function(event){m_bSpellCheckEnabled=false;
if(this.m_oEditor.document){this.m_oEditor.document.removeListener("focusout",this.blurHandler);
}},setSpellCheckEnabled:function(bEnabled){m_bSpellcheckEnabled=bEnabled;
},keyUpHandler:function(event){var nKeyCode=event.data.$.keyCode;
var self=this;
function handleSpellCheck(){clearTimeout(self.m_spellCheckTimeout);
self.m_spellCheckTimeout=setTimeout(function(){self.m_oEditor.fire("saveSnapshot");
if(nKeyCode===g_iDD_KEYCODE_ENTER){var oBody=self.m_oEditor.plugins.divarea?self.m_oEditor.ui.space("contents").$:self.m_oEditor.document.getBody().$;
var arrElements=DDCOMMON.getDescendentsByClassName(oBody,g_sCLASS_SPELLCHECK);
while(arrElements&&arrElements.length>0){arrElements.pop().removeNode();
}}self.spellCheckCurrentFreeText(true);
self.m_oEditor.fire("updateSnapshot");
self.m_oEditor.fire("spellCheckComplete");
},500);
}if(this.m_lastCharPress&&WORD_BOUNDARIES_LOOKUP[this.m_lastCharPress]){handleSpellCheck();
}else{if(nKeyCode===g_iDD_KEYCODE_ENTER){handleSpellCheck();
}else{if(nKeyCode===g_iDD_KEYCODE_BACKSPACE||nKeyCode===g_iDD_KEYCODE_DELETE){handleSpellCheck();
}else{if(nKeyCode===g_iDD_KEYCODE_TAB){return;
}else{handleSpellCheck();
}}}}this.m_lastCharPress=null;
},keyPressHandler:function(event){var nKeyCode=event.data.$.keyCode;
this.m_lastCharPress=String.fromCharCode(nKeyCode);
},mouseDownHandler:function(event){this.m_nMouseDowns++;
},mouseUpHandler:function(event){this.m_nMouseDowns--;
},clickHandler:function(event){var self=this;
if(true==this.m_oEditor.focusManager.hasFocus){setTimeout(function(){self.spellCheckCurrentFreeText(true);
},500);
}},doubleClickHandler:function(event){if(document.documentMode&&document.documentMode<9){this.m_nMouseDowns++;
}},blurHandler:function(event){if(!m_bSpellcheckEnabled){return;
}var e=event.data.$.srcElement;
if(e){var freetextElement=this.getFreeTextElement(e);
if(freetextElement){if(freetextElement.id){CKEDITOR.tools.setTimeout(function(){if(!this.m_oEditor.document){return;
}this.spellCheckFreeText(freetextElement.id);
},0,this);
}else{DocHandleError("SpellCheckPluginHelper::blurHandler, element is missing an ID","DynDocCKEditor","","");
}this.m_lastCharPress=null;
}}},contextMenuHandler:function(element_ignore,selection,oEditor){var word=null;
if(selection==null||selection.getRanges().length==0){DocHandleError("SpellCheckPluginHelper::contextMenuHandler, selection has no ranges","DynDocCKEditor","","");
return null;
}if(selection.getRanges()[0].checkReadOnly()){return false;
}this.m_oEditor.focus();
var range=oEditor.document.$.selection.createRange();
range.expand("word");
trimRangeWhitespace(range);
word=range.text;
var selectedElement=range.parentElement();
if(!selectedElement){return null;
}var freetextElement=this.getFreeTextElement(selectedElement);
if(!freetextElement){return null;
}if(checkSpelling(word)){return null;
}var items_suggestion=CKEDITOR.SpellCheckHelper.GetSuggestedSpelling(word);
var suggestionsEnabledStatus=CKEDITOR.TRISTATE_OFF;
if(!items_suggestion||!items_suggestion.length){items_suggestion=oEditor.lang.cernscayt.noSpellingSuggestions;
suggestionsEnabledStatus=CKEDITOR.TRISTATE_DISABLED;
}items_suggestion=items_suggestion.split("\n");
for(var i in mainSuggestions){if(typeof oEditor._.menuItems!=="undefined"){delete oEditor._.menuItems[i];
}if(typeof oEditor._.commands!=="undefined"){delete oEditor._.commands[i];
}}mainSuggestions={};
var maxSuggestions=oEditor.config.scayt_maxSuggestions;
if(typeof maxSuggestions!="number"){maxSuggestions=5;
}if(!maxSuggestions){maxSuggestions=items_suggestion.length;
}for(var i=0,l=items_suggestion.length;
i<l;
i+=1){var commandName="scayt_suggestion_"+i;
var exec=(function(sTextNew,oWordRange){return{editorFocus:false,exec:function(){if(sTextNew.length>0){if(replaceMisspelledWord(oWordRange,sTextNew)){oWordRange.select();
}this.canUndo=false;
}}};
})(items_suggestion[i],range);
exec.canUndo=true;
exec.suggestedWord=items_suggestion[i];
if(i<maxSuggestions){this.addButtonCommand(items_suggestion[i],commandName,exec,"scayt_suggest",i+1);
mainSuggestions[commandName]=suggestionsEnabledStatus;
}}return mainSuggestions;
},addButtonCommand:function(sLabel,sCmdName,oCommand,ctxMenuGroup,ctxMenuOrder){this.m_oEditor.addCommand(sCmdName,oCommand);
if(this.m_oEditor.addMenuItems){this.m_oEditor.addMenuItem(sCmdName,{label:sLabel,command:sCmdName,group:ctxMenuGroup,order:ctxMenuOrder});
}},startScaytTimer:function(sFreeTextElementId){if(this.m_oEditor.mode!="wysiwyg"){return;
}if(!sFreeTextElementId){var oFreeTextElement=this.getFreeTextElementAtRange(this.m_oEditor.document.$.selection.createRange());
if(null==oFreeTextElement){return;
}sFreeTextElementId=oFreeTextElement.id;
}if(!sFreeTextElementId){return;
}var oTimer=this.m_mapTimers[sFreeTextElementId];
if(oTimer){clearTimeout(oTimer);
}this.m_mapTimers[sFreeTextElementId]=CKEDITOR.tools.setTimeout(function(){this.onScaytTimer(sFreeTextElementId);
},SCAYT_TIMER_TIMEOUT,this);
},onScaytTimer:function(sFreeTextElementId){if(!sFreeTextElementId){DocHandleError("SpellCheckPluginHelper::onScaytTimer, parameter cannot be falsey","DynDocCKEditor","","");
return;
}this.m_mapTimers[sFreeTextElementId]=null;
if(this.m_nMouseDowns>0){this.startScaytTimer();
return;
}this.spellCheckFreeText(sFreeTextElementId);
},spellCheckFreeText:function(freetextElement){if(!m_bSpellcheckEnabled||this.m_oEditor.mode!="wysiwyg"){return;
}if(!freetextElement||!this.m_oEditor.document){return;
}else{if(typeof freetextElement==="string"||freetextElement instanceof String){freetextElement=this.m_oEditor.document.$.getElementById(freetextElement);
}else{if(typeof freetextElement.nodeType==="undefined"){DocHandleError("SpellCheckPluginHelper::spellCheckFreeText, invalid freetextElement given to spellCheckFreeText","DynDocCKEditor","","");
return;
}}}if(!freetextElement){return;
}if(!freetextElement.isContentEditable){return;
}var elementId=freetextElement.id;
if(elementId){var oTimer=this.m_mapTimers[elementId];
if(oTimer){clearTimeout(oTimer);
this.m_mapTimers[elementId]=null;
}}var sHtml=freetextElement.innerHTML;
var sHtmlBefore=new String(sHtml);
try{sHtml=this.spellCheckFragment(sHtml,null);
}catch(e){DocHandleException("SpellCheckPluginHelper::spellCheckFreeText, exception from spellCheckFragment","DynDocCKEditor",e);
return;
}if(sHtml!=sHtmlBefore){CKEDITOR.dom.element.get(freetextElement).setHtml(sHtml);
}},spellCheckCurrentFreeText:function(restoreCursorPosition){if(null==this.m_oEditor||null==this.m_oEditor.document){return;
}var wasDirty=this.m_oEditor.checkDirty();
var self=this;
var selectionBookmarkArray=null;
var currentRange=this.m_oEditor.getSelection().getRanges()[0];
if(currentRange&&!currentRange.collapsed){return;
}if(restoreCursorPosition){selectionBookmarkArray=this.m_oEditor.getSelection().createBookmarks(true);
if(selectionBookmarkArray[0]&&selectionBookmarkArray[0].startNode){$("#"+selectionBookmarkArray[0].startNode).html("");
}if(selectionBookmarkArray[0]&&selectionBookmarkArray[0].endNode){$("#"+selectionBookmarkArray[0].endNode).html("");
}}var container=$(this.m_oEditor.editable().$);
container.find("p, div").each(function(){self.spellCheckFreeText(this);
});
if(restoreCursorPosition&&selectionBookmarkArray[0]){this.m_oEditor.getSelection().selectBookmarks([selectionBookmarkArray[0]]);
if(selectionBookmarkArray[0].startNode){container.find("#"+selectionBookmarkArray[0].startNode).remove();
}if(selectionBookmarkArray[0].endNode){container.find("#"+selectionBookmarkArray[0].endNode).remove();
}}if(!wasDirty&&this.m_oEditor.checkDirty()){this.m_oEditor.resetDirty();
}},spellCheckFragment:function(sHtml,nExcludeWordAt){sHtml=[WORD_BOUNDARIES[0],sHtml].join("");
for(var z=1;
z<=2;
z++){var dom=new SpellCheck.Element();
dom.parse(sHtml);
var sText=dom.getText();
if(nExcludeWordAt&&z===1&&nExcludeWordAt+1<sText.length-1){if(!WORD_BOUNDARIES_LOOKUP[sText.charAt(nExcludeWordAt+2)]){nExcludeWordAt=null;
}}var nWordEnd=sText.length;
for(var i=sText.length-1;
i>=0;
i--){if(WORD_BOUNDARIES_LOOKUP[sText.charAt(i)]||(sText.charCodeAt(i)>=128&&sText.charCodeAt(i)<=191)){if(i<nWordEnd-1){var sWord=sText.substring(i+1,nWordEnd);
var oWordTrimmed=trimWord(sWord);
var nTrimmedWordStart=i+1+oWordTrimmed.wordPosition;
var leftEndNode=dom.findNodeAt(nTrimmedWordStart);
var rightEndNode=dom.findNodeAt(nTrimmedWordStart+oWordTrimmed.word.length-1);
var rightEndNodeIsSquiggle=rightEndNode&&rightEndNode.hasClassName(g_sCLASS_SPELLCHECK);
var leftEndSquiggle=dom.findNodeWithClassAt(nTrimmedWordStart,g_sCLASS_SPELLCHECK);
if(rightEndNode&&rightEndNodeIsSquiggle&&rightEndNode.getText()!==oWordTrimmed.word){dom.unwrap(rightEndNode);
}if(leftEndSquiggle&&leftEndSquiggle.isValid()){if(leftEndSquiggle.getText()!==oWordTrimmed.word){dom.unwrap(leftEndSquiggle);
i=nWordEnd=leftEndSquiggle.nTextStart;
continue;
}}if(leftEndNode!=dom&&!leftEndNode.isValid()){i=nWordEnd=leftEndNode.textStart;
continue;
}var bCorrect=checkSpelling(oWordTrimmed.word);
if(bCorrect){if(leftEndSquiggle){dom.unwrap(leftEndSquiggle);
}}else{if(nExcludeWordAt==null||i>nExcludeWordAt+1||nWordEnd-2<nExcludeWordAt){if(!leftEndSquiggle){if(leftEndNode===rightEndNode){dom.wrapRange(nTrimmedWordStart,nTrimmedWordStart+oWordTrimmed.word.length,'<span class="'+g_sCLASS_SPELLCHECK+'">',"</span>");
}}}}}nWordEnd=i;
}}sHtml=dom.sHtml;
}return sHtml.substring(1);
},getCurrentCursorPosition:function(element,range){var tempRange=range.duplicate();
var nCursorPosition;
if(tempRange.expand("character")&&tempRange.htmlText.search(new RegExp("\\btextarea\\b","gi"))!=-1&&tempRange.htmlText.search(new RegExp("\\beditor[0-9]+\\b","gi"))!=-1){nCursorPosition=INCORRECT_CURSOR_POSITION;
}else{nCursorPosition=getCursorPosition(element,range);
}return nCursorPosition;
},getParentFreeTextElement:function(oElement){return this.m_oEditor.editable().$;
},getFreeTextElement:function(oElement){if(DDCOMMON.hasClassName(oElement.className,g_sCLASS_FREETEXT)){return oElement;
}else{return this.getParentFreeTextElement(oElement);
}},getFreeTextElementAtRange:function(range){return range.parentElement?this.getParentFreeTextElement(range.parentElement()):null;
},retrieveCursorPosition:function(element,range){if(null==element||null==range||null==element.parentElement){return -1;
}var nCursorPosition=this.getCurrentCursorPosition(element,range);
var duplRange=range.duplicate();
try{duplRange.moveToElementText(element);
}catch(e){return -1;
}duplRange.setEndPoint("EndToEnd",range);
var sHTMLText=duplRange.htmlText;
nCursorPosition-=DDCOMMON.getLineBreakCount(sHTMLText);
return nCursorPosition;
},restoreCursorPosition:function(element,range,nCursorPosition){if(null==element||null==range||null==element.parentElement){return;
}var duplRange=range.duplicate();
try{duplRange.moveToElementText(element);
}catch(e){DocHandleError("SpellCheckPluginHelper::restoreCursorPosition, exception from TextRange::moveToElementText","DynDocCKEditor","","");
return;
}duplRange.collapse(true);
duplRange.moveEnd("character",nCursorPosition);
duplRange.moveStart("character",nCursorPosition);
duplRange.select();
},nothing:null};
}