function OrgSearchControl(textBox){var selectedId=0;
var serviceDelegate=new OrgServiceDelegate();
var orgSecurityInd=0;
var orgType="";
var selectionHandler=function(newSelectedId){selectedId=newSelectedId;
};
var queryHandler=function(callback,searchString){serviceDelegate.getResults(searchString,orgType,function(results){callback.autosuggest(results);
},orgSecurityInd);
};
var autoSuggestControl=new RCMAutoSuggestControl(textBox,queryHandler,selectionHandler,ToolTipDetailsHandler);
this.getSelectedOrgId=function(){return selectedId;
};
this.setSelectedOrg=function(orgId,orgName){selectedId=orgId;
textBox.value=orgName;
autoSuggestControl.setVerified(orgId>0);
};
this.setRequired=function(required){autoSuggestControl.setRequired(required);
};
this.isVerified=function(){return autoSuggestControl.isVerified;
};
this.setOrgType=function(org){orgType=org;
};
this.addVerifyStateChangeListener=function(listener){autoSuggestControl.addVerifyStateChangeListener(listener);
};
this.removeVerifyStateChangeListener=function(listener){autoSuggestControl.removeVerifyStateChangeListener(listener);
};
var addEventHandler=function(element,event,handler){element.addEventListener?element.addEventListener(event,handler,false):element.attachEvent("on"+event,handler);
};
if(textBox.form){addEventHandler(textBox.form,"reset",function(){selectedId=0;
autoSuggestControl.setVerified(false);
});
}}