(function(){var pluginName="placeholdertext";
CKEDITOR.plugins.add(pluginName,{init:function(editor){var placeholderhtml=null;
if(!editor.config.placeholderText){return;
}placeholderhtml=['<span id="placeHolderText">',editor.config.placeholderText,"</span>"].join("");
editor.on("instanceReady",function(e){var editorInstance=e.editor,container=editorInstance.container.$,body=$(container).find(".cke_wysiwyg_div"),content=body[0].innerHTML;
var applyPlaceholderText=function(e){var editor=editorInstance;
window.setTimeout(function(){var wasDirty=editor.checkDirty();
if(editor.isFloatPanelOpened||editor.focusManager.hasFocus){return;
}var hasMixedContent=(body.find(".ddfreetext").length||body.find(".ddstructuredtext").length);
var freetextArea=hasMixedContent?body.find(".ddfreetext").first():body;
var content="";
if(hasMixedContent){content=freetextArea.text();
}else{content=editor.getData();
}if(content.replace(/^[ ]+/g,"")===""&&freetextArea.children().length<2){if(freetextArea.children().length){freetextArea.children().first().html(placeholderhtml);
}else{freetextArea.html(placeholderhtml);
}if(!wasDirty){editor.resetDirty();
}}},200);
};
var removePlaceHolderText=function(e){var wasDirty=editorInstance.checkDirty();
var removed=body.find("#placeHolderText").remove();
if(removed.length>0&&!wasDirty){editorInstance.resetDirty();
}};
editor.applyPlaceholderText=applyPlaceholderText;
editor.removePlaceHolderText=removePlaceHolderText;
applyPlaceholderText();
body.blur(applyPlaceholderText);
body.focus(removePlaceHolderText);
var firstFreetext=body.find(".ddfreetext").first();
firstFreetext.focus(removePlaceHolderText);
firstFreetext.blur(applyPlaceholderText);
body.keydown(function(e){body.find("#placeHolderText").remove();
});
editor.on("beforeCommandExec",removePlaceHolderText);
editor.on("saveSnapshot",function(e){removePlaceHolderText(e);
applyPlaceholderText(e);
});
});
editor.on("focus",function(e){if(!$(e.editor.editable().$).find(".ddfreetext").length){e.editor.focus();
}else{setTimeout(function(){$(e.editor.editable().$).find(".ddfreetext").first().focus();
},0);
}});
}});
})();
