(function(){var pasteTextCmd={canUndo:false,async:true,exec:function(editor){editor.getClipboardData({title:editor.lang.pastetext.title},function(data){data&&editor.fire("paste",{type:"text",dataValue:data.dataValue});
editor.fire("afterCommandExec",{name:"pastetext",command:pasteTextCmd,returnValue:!!data});
});
}};
CKEDITOR.plugins.add("pastetext",{requires:"clipboard",lang:"af,ar,bg,bn,bs,ca,cs,cy,da,de,el,en,en-au,en-ca,en-gb,eo,es,et,eu,fa,fi,fo,fr,fr-ca,gl,gu,he,hi,hr,hu,id,is,it,ja,ka,km,ko,ku,lt,lv,mk,mn,ms,nb,nl,no,pl,pt,pt-br,ro,ru,si,sk,sl,sq,sr,sr-latn,sv,th,tr,ug,uk,vi,zh,zh-cn",icons:"pastetext,pastetext-rtl",hidpi:true,init:function(editor){var commandName="pastetext";
editor.addCommand(commandName,pasteTextCmd);
editor.ui.addButton&&editor.ui.addButton("PasteText",{label:editor.lang.pastetext.button,command:commandName,toolbar:"clipboard,40"});
if(editor.config.forcePasteAsPlainText){editor.on("beforePaste",function(evt){if(evt.data.type!="html"){evt.data.type="text";
}});
}editor.on("pasteState",function(evt){editor.getCommand(commandName).setState(evt.data);
});
}});
})();
