CKEDITOR.plugins.add("cernbackspace",{init:function(editor){editor.on("contentDom",function(){var editable=editor.editable();
if(!editable){logger.logError("Failed to retrieve editable area from the CKEditor instance in the cernbackspace plugin");
}editable.on("keydown",function(event){var KEYCODES={BACKSPACE:8,DELETE:46};
var keyCode=event.data.getKey();
if((keyCode===KEYCODES.BACKSPACE||keyCode===KEYCODES.DELETE)&&event.data.getKeystroke()<65536){var selection=editor.getSelection();
var range=selection&&selection.getRanges()[0];
if(!range){return;
}var ierange=editor.document.$.selection.createRange();
if(!ierange.moveStart){return;
}var rangeParent=ierange.parentElement();
if(rangeParent.isContentEditable==false){return;
}if(range.collapsed){if(keyCode===KEYCODES.DELETE){ierange.moveEnd("character",1);
}else{if(keyCode===KEYCODES.BACKSPACE){ierange.moveStart("character",-1);
}}if(ierange.text.length!==1){return;
}var extendedRange=ierange.duplicate();
extendedRange.moveStart("character",-1);
extendedRange.moveEnd("character",1);
if(extendedRange.text.indexOf(" ")<0&&extendedRange.text.indexOf("\u00A0")<0){return;
}ierange.select();
selection.reset();
try{range=selection.getRanges()[0];
if(range){range.deleteContents(true);
ierange=editor.document.$.selection.createRange();
event.data.preventDefault(false);
}else{DocHandleError("cernbackspace - Unable to obtain range after selecting character","DynDocCKeditor","","");
}}finally{if(ierange.moveStart){ierange.collapse(true);
ierange.select();
selection.reset();
}}}else{range.deleteContents(true);
selection.selectRanges([range]);
ierange=editor.document.$.selection.createRange();
if(ierange.moveStart){ierange.select();
selection.reset();
}event.data.preventDefault(false);
}}},this,null,0);
});
}});
