;*** Generated by translate command; please verify contents before re-including in CCL ***
/***********************************************************************
 *                  GENERATED MODIFICATION CONTROL LOG                 *
 ***********************************************************************
 *                                                                     *
 *Mod Date     Engineer             Comment                            *
 *--- -------- -------------------- -----------------------------------*
 *000 00/00/00 Unknown              Unknown                            *
 *001 01/03/12 Rob Banks            Modify to use DB2                  *
 *002 07/29/12 Akcia                changes to improve efficiency for oracle upgrade     *
 ******************** End of Modification Log **************************/
DROP PROGRAM   1_MHS_RCMC_ESI_LOG_HL7 : dba GO
CREATE PROGRAM  1_MHS_RCMC_ESI_LOG_HL7 : dba
prompt
	"Output to File/Printer/MINE " = "MINE"
	, "Enter Contributor System (ie, RCMC_DICTAPHONE_SYS) " = "RCMC_DICTAPHONE_SYS"
	, "Enter number of days back for report to run: " = 0
 
with PROMPT1, PROMPT2, PROMPT3
 
/*** START 001 ***/
;*********************************************************************
;*** If PROD / CERT then run as 2nd oracle instance to improve
;*** efficiency. Will auto Fail-over to Instance 1 if Instance 2 down.
;*********************************************************************
IF(CURDOMAIN = "PROD")
  FREE DEFINE oraclesystem
  DEFINE oraclesystem 'v500/fullmoon@mhprbrpt'
ELSEIF(CURDOMAIN = "MHPRD")
  FREE DEFINE oraclesystem
  DEFINE oraclesystem 'v500/fullmoon@mhprbrpt'
ELSEIF(CURDOMAIN="MHCRT")
  FREE DEFINE oraclesystem
  DEFINE oraclesystem 'v500/java4t2@mhcrtrpt'
ENDIF ;CURDOMAIN
;*** Write instance ccl ran in to the log file
;SET Iname = fillstring(10," ")
;SELECT INTO value("mayo_logfiles:mayo_instance2.log")
;  run_date = format(sysdate,";;q")
; ,Iname = substring(1,7,instance_name)
;FROM v$instance
;DETAIL
;  col  1 run_date
;  col +1 curprog
;  col +1 " *Instance="
;  col +1 Iname
;with nocounter
;   , format
;****************** End of INSTANCE 2 routine ************************
/*** END 001 ***/
 
SELECT  INTO  $1
 MESSAGEDATE =E.MSH_DATE,
 APPLICATION =E.MSH_SENDING_APP,
 PATIENT =E.NAME_FULL_FORMATTED,
 ERROR =E.ERROR_TEXT,
 HL7MESSAGE = SUBSTRING ( 1 ,  650 , O.MSG_TEXT)
FROM  OEN_TXLOG  O ,
 ESI_LOG  E
 
;002  WHERE (O.TX_KEY=E.TX_KEY) AND (E.MSH_SENDING_APP= $2 ) AND (E.ERROR_STAT= "ESI_STAT_FAILURE" ) AND (
;002 E.UPDT_DT_TM>= CNVTDATETIME (( CURDATE - $3 ),  0 ))
plan e															;002
where e.create_dt_tm >= cnvtdatetime((curdate - $3),0)			;002
  and e.msh_sending_app = $2									;002
  and e.error_stat = "ESI_STAT_FAILURE"							;002
 
join o															;002
where o.tx_key = e.tx_key										;002
 
ORDER BY E.MSH_DATE DESC
 WITH  FORMAT , SEPARATOR = " " , DIO = 38
 
/*** START 001 ***/
;*** After report put back to instance 1
IF(CURDOMAIN = "PROD")
  FREE DEFINE oraclesystem
  DEFINE oraclesystem 'v500/fullmoon@mhprb1'
ELSEIF(CURDOMAIN = "MHPRD")
  FREE DEFINE oraclesystem
  DEFINE oraclesystem 'v500/fullmoon@mhprb1'
ELSEIF(CURDOMAIN="MHCRT")
  FREE DEFINE oraclesystem
  DEFINE oraclesystem 'v500/java4t2@mhcrt1'
ENDIF ;CURDOMAIN
/*** END 001 ***/
 
END
GO
