Ext.define("MPAGE.store.ROSearch", {
	extend: "univnm.ext.QueryStore",
	alias:"store.ro_search",
	model: "MPAGE.model.Group",
	sql:[
		"<tpl if=\"!query\"> ",
			"select * from dual where 1=0",
		"</tpl>",
		"<tpl if=\"query\"> ",
		"select ",
			"code_value foreign_key, ",
			"display alias, ",
			"'CernerRole' model,",
			"CASE WHEN exists ( ",
				"select ",
					"'x' ",
				"from ",
					"cust_aros ro ",
				"where ",
					"ro.model = 'CernerRole' ",
					"and ro.foreign_key=cv.code_value ",
					"and ro.parent_id = {pid} ",
			") THEN 'Yes' ELSE 'No' END previously_added",
		"from ",
			"code_value cv ",
		"where ",
			"1=1 ",
			"and lower(display) like lower('%{query}%')",
			"and code_set= 88 ",
			"and active_ind= 1 ",
		"UNION ",
		"select ",
			"person_id foreign_key, ",
			"name_full_formatted alias, ",
			"'User' model,",
			"CASE WHEN exists ( ",
				"select ",
					"'x' ",
				"from ",
					"cust_aros ro ",
				"where ",
					"ro.model = 'User' ",
					"and ro.foreign_key=p.person_id ",
					"and ro.parent_id = {pid} ",
			") THEN 'Yes' ELSE 'No' END previously_added",
		"from ",
			"prsnl p ",
		"where ",
			"1=1 ",
			"and ( ",
				"p.name_last_key like upper('{query}%') ",
				"or p.name_first_key like upper('{query}%') ",
			") ",
			"",
			"and active_ind = 1 ",
		"order by previously_added,alias ",
		"</tpl> "

	],
	extraParams:{
		pid:0
	}
})