CKEDITOR.plugins.add("removeformat",{lang:"af,ar,bg,bn,bs,ca,cs,cy,da,de,el,en,en-au,en-ca,en-gb,eo,es,et,eu,fa,fi,fo,fr,fr-ca,gl,gu,he,hi,hr,hu,is,it,ja,ka,km,ko,ku,lt,lv,mk,mn,ms,nb,nl,no,pl,pt,pt-br,ro,ru,si,sk,sl,sq,sr,sr-latn,sv,th,tr,ug,uk,vi,zh,zh-cn",icons:"removeformat",hidpi:true,init:function(editor){editor.addCommand("removeFormat",CKEDITOR.plugins.removeformat.commands.removeformat);
editor.ui.addButton&&editor.ui.addButton("RemoveFormat",{label:editor.lang.removeformat.toolbar,command:"removeFormat",toolbar:"cleanup,10"});
}});
CKEDITOR.plugins.removeformat={commands:{removeformat:{exec:function(editor){var tagsRegex=editor._.removeFormatRegex||(editor._.removeFormatRegex=new RegExp("^(?:"+editor.config.removeFormatTags.replace(/,/g,"|")+")$","i"));
var removeAttributes=editor._.removeAttributes||(editor._.removeAttributes=editor.config.removeFormatAttributes.split(","));
var filter=CKEDITOR.plugins.removeformat.filter;
var ranges=editor.getSelection().getRanges(1),iterator=ranges.createIterator(),range;
while((range=iterator.getNextRange())){if(!range.collapsed){range.enlarge(CKEDITOR.ENLARGE_ELEMENT);
}var bookmark=range.createBookmark(),startNode=bookmark.startNode,endNode=bookmark.endNode,currentNode;
var breakParent=function(node){var path=editor.elementPath(node),pathElements=path.elements;
for(var i=1,pathElement;
pathElement=pathElements[i];
i++){if(pathElement.equals(path.block)||pathElement.equals(path.blockLimit)){break;
}if(tagsRegex.test(pathElement.getName())&&filter(editor,pathElement)){node.breakParent(pathElement);
}}};
breakParent(startNode);
if(endNode){breakParent(endNode);
currentNode=startNode.getNextSourceNode(true,CKEDITOR.NODE_ELEMENT);
while(currentNode){if(currentNode.equals(endNode)){break;
}var nextNode=currentNode.getNextSourceNode(false,CKEDITOR.NODE_ELEMENT);
if(!(currentNode.getName()=="img"&&currentNode.data("cke-realelement"))&&filter(editor,currentNode)){if(tagsRegex.test(currentNode.getName())){currentNode.remove(1);
}else{currentNode.removeAttributes(removeAttributes);
editor.fire("removeFormatCleanup",currentNode);
}}currentNode=nextNode;
}}range.moveToBookmark(bookmark);
}editor.forceNextSelectionCheck();
editor.getSelection().selectRanges(ranges);
}}},filter:function(editor,element){var filters=editor._.removeFormatFilters||[];
for(var i=0;
i<filters.length;
i++){if(filters[i](element)===false){return false;
}}return true;
}};
CKEDITOR.editor.prototype.addRemoveFormatFilter=function(func){if(!this._.removeFormatFilters){this._.removeFormatFilters=[];
}this._.removeFormatFilters.push(func);
};
CKEDITOR.config.removeFormatTags="b,big,code,del,dfn,em,font,i,ins,kbd,q,s,samp,small,span,strike,strong,sub,sup,tt,u,var";
CKEDITOR.config.removeFormatAttributes="class,style,lang,width,height,align,hspace,valign";
