(function(){var TRISTATE_DISABLED=CKEDITOR.TRISTATE_DISABLED,TRISTATE_OFF=CKEDITOR.TRISTATE_OFF;
CKEDITOR.plugins.add("indent",{lang:"af,ar,bg,bn,bs,ca,cs,cy,da,de,el,en,en-au,en-ca,en-gb,eo,es,et,eu,fa,fi,fo,fr,fr-ca,gl,gu,he,hi,hr,hu,id,is,it,ja,ka,km,ko,ku,lt,lv,mk,mn,ms,nb,nl,no,pl,pt,pt-br,ro,ru,si,sk,sl,sq,sr,sr-latn,sv,th,tr,ug,uk,vi,zh,zh-cn",icons:"indent,indent-rtl,outdent,outdent-rtl",init:function(editor){var genericDefinition=CKEDITOR.plugins.indent.genericDefinition;
setupGenericListeners(editor,editor.addCommand("indent",new genericDefinition(true)));
setupGenericListeners(editor,editor.addCommand("outdent",new genericDefinition()));
if(editor.ui.addButton){editor.ui.addButton("Indent",{label:editor.lang.indent.indent,command:"indent",directional:true,toolbar:"indent,20"});
editor.ui.addButton("Outdent",{label:editor.lang.indent.outdent,command:"outdent",directional:true,toolbar:"indent,10"});
}editor.on("dirChanged",function(evt){var range=editor.createRange(),dataNode=evt.data.node;
range.setStartBefore(dataNode);
range.setEndAfter(dataNode);
var walker=new CKEDITOR.dom.walker(range),node;
while((node=walker.next())){if(node.type==CKEDITOR.NODE_ELEMENT){if(!node.equals(dataNode)&&node.getDirection()){range.setStartAfter(node);
walker=new CKEDITOR.dom.walker(range);
continue;
}var classes=editor.config.indentClasses;
if(classes){var suffix=(evt.data.dir=="ltr")?["_rtl",""]:["","_rtl"];
for(var i=0;
i<classes.length;
i++){if(node.hasClass(classes[i]+suffix[0])){node.removeClass(classes[i]+suffix[0]);
node.addClass(classes[i]+suffix[1]);
}}}var marginLeft=node.getStyle("margin-right"),marginRight=node.getStyle("margin-left");
marginLeft?node.setStyle("margin-left",marginLeft):node.removeStyle("margin-left");
marginRight?node.setStyle("margin-right",marginRight):node.removeStyle("margin-right");
}}});
}});
CKEDITOR.plugins.indent={genericDefinition:function(isIndent){this.isIndent=!!isIndent;
this.startDisabled=!this.isIndent;
},specificDefinition:function(editor,name,isIndent){this.name=name;
this.editor=editor;
this.jobs={};
this.enterBr=editor.config.enterMode==CKEDITOR.ENTER_BR;
this.isIndent=!!isIndent;
this.relatedGlobal=isIndent?"indent":"outdent";
this.indentKey=isIndent?9:CKEDITOR.SHIFT+9;
this.database={};
},registerCommands:function(editor,commands){editor.on("pluginsLoaded",function(){for(var name in commands){(function(editor,command){var relatedGlobal=editor.getCommand(command.relatedGlobal);
for(var priority in command.jobs){relatedGlobal.on("exec",function(evt){if(evt.data.done){return;
}editor.fire("lockSnapshot");
if(command.execJob(editor,priority)){evt.data.done=true;
}editor.fire("unlockSnapshot");
CKEDITOR.dom.element.clearAllMarkers(command.database);
},this,null,priority);
relatedGlobal.on("refresh",function(evt){if(!evt.data.states){evt.data.states={};
}evt.data.states[command.name+"@"+priority]=command.refreshJob(editor,priority,evt.data.path);
},this,null,priority);
}editor.addFeature(command);
})(this,commands[name]);
}});
}};
CKEDITOR.plugins.indent.genericDefinition.prototype={context:"p",exec:function(){}};
CKEDITOR.plugins.indent.specificDefinition.prototype={execJob:function(editor,priority){var job=this.jobs[priority];
if(job.state!=TRISTATE_DISABLED){return job.exec.call(this,editor);
}},refreshJob:function(editor,priority,path){var job=this.jobs[priority];
job.state=job.refresh.call(this,editor,path);
return job.state;
},getContext:function(path){return path.contains(this.context);
}};
function setupGenericListeners(editor,command){var selection,bookmarks;
command.on("refresh",function(evt){var states=[TRISTATE_DISABLED];
for(var s in evt.data.states){states.push(evt.data.states[s]);
}this.setState(CKEDITOR.tools.search(states,TRISTATE_OFF)?TRISTATE_OFF:TRISTATE_DISABLED);
},command,null,100);
command.on("exec",function(evt){selection=editor.getSelection();
bookmarks=selection.createBookmarks(1);
if(!evt.data){evt.data={};
}evt.data.done=false;
},command,null,0);
command.on("exec",function(evt){editor.forceNextSelectionCheck();
selection.selectBookmarks(bookmarks);
},command,null,100);
}})();
