CKEDITOR.plugins.add("cernscayt",{lang:"en,en-gb,de,fr,es",requires:"cerngetxhtml",m_mapHelpers:[],beforeInit:function(editor){if(-1==editor.config.menu_groups.indexOf("scayt_suggest")){editor.config.menu_groups="scayt_suggest,"+editor.config.menu_groups;
}if(typeof DDCOMMON==="undefined"){CKEDITOR.scriptLoader.load(CKEDITOR.getUrl("js/dynDocCommonFunc.js"));
}if(typeof SpellCheckPluginHelper==="undefined"){CKEDITOR.scriptLoader.load(CKEDITOR.getUrl("plugins/cernscayt/js/spellcheck.js"));
}if(typeof SpellCheck==="undefined"||typeof SpellCheck.Element==="undefined"){CKEDITOR.scriptLoader.load(CKEDITOR.getUrl("plugins/cernscayt/js/element.js"));
}var oHelper=new SpellCheckPluginHelper();
this.m_mapHelpers[editor.name]=oHelper;
oHelper.m_oEditor=editor;
},init:function(editor){var oHelper=this.m_mapHelpers[editor.name];
editor.on("contentDom",oHelper.contentDomHandler,oHelper);
editor.on("instanceReady",oHelper.instanceReadyHandler,oHelper);
editor.on("beforeDestroy",oHelper.beforeDestroyHandler,oHelper);
if(editor.contextMenu){if(editor.addMenuItems){var iScaytMenuOrder=-1;
editor.addMenuGroup("scayt_suggest",iScaytMenuOrder);
editor.contextMenu.addListener(function(element,selection){return oHelper.contextMenuHandler(element,selection,editor);
});
}}editor.on("afterCommandExec",function(event){if(event.data.name==DDCMD_CUT||event.data.name==DDCMD_PASTE){setTimeout(function(){oHelper.spellCheckCurrentFreeText(true,true);
},0);
}});
}});
