function CheckoutComponentWFStyle(){this.initByNamespace("ckout");
}CheckoutComponentWFStyle.inherits(ComponentStyle);
function CheckoutComponentWF(criterion){this.setCriterion(criterion);
this.setStyles(new CheckoutComponentWFStyle());
this.setComponentLoadTimerName("USR:MPG.CHECKOUT.O1 - load component");
this.setComponentRenderTimerName("ENG:MPG.CHECKOUT.O1 - render component");
this.m_selectedVisit=2;
this.setScope(this.m_selectedVisit);
this.checkoutI18n=i18n.discernabu.CheckoutComponentWF;
this.m_medReconciliationOn=false;
this.m_medReconciliationLabel="";
this.m_patEducationOn=false;
this.m_patEducationLabel="";
this.m_followupOn=false;
this.m_followupLabel="";
this.m_visitNoteOn=false;
this.m_visitNoteLabel="";
this.m_visitNoteLink="";
this.m_visitSummaryOn=false;
this.m_visitSummaryLabel="";
this.m_visitSummaryLink="";
this.m_visitChargeOn=false;
this.m_visitChargeLabel="";
this.m_visitChargeLinkOn=false;
this.dischargeMedCodeset=54732;
var dischargeMedCodeValueMeaning=MP_Util.GetCodeValueByMeaning("DISCHARGEMED",this.dischargeMedCodeset);
this.m_dischargeMedCd=(dischargeMedCodeValueMeaning)?dischargeMedCodeValueMeaning.codeValue:0;
}CheckoutComponentWF.prototype=new MPageComponent();
CheckoutComponentWF.prototype.constructor=MPageComponent;
CheckoutComponentWF.prototype.getDischargeMedCode=function(){return this.m_dischargeMedCd;
};
CheckoutComponentWF.prototype.setMedReconciliationSwitch=function(value){this.m_medReconciliationOn=value;
};
CheckoutComponentWF.prototype.isMedReconciliationOn=function(){return this.m_medReconciliationOn;
};
CheckoutComponentWF.prototype.setMedReconciliationLabel=function(value){this.m_medReconciliationLabel=value;
};
CheckoutComponentWF.prototype.getMedReconciliationLabel=function(){return this.m_medReconciliationLabel;
};
CheckoutComponentWF.prototype.setPatEducationSwitch=function(value){this.m_patEducationOn=value;
};
CheckoutComponentWF.prototype.isPatEducationOn=function(){return this.m_patEducationOn;
};
CheckoutComponentWF.prototype.setPatEducationLabel=function(value){this.m_patEducationLabel=value;
};
CheckoutComponentWF.prototype.getPatEducationLabel=function(){return this.m_patEducationLabel;
};
CheckoutComponentWF.prototype.setFollowupSwitch=function(value){this.m_followupOn=value;
};
CheckoutComponentWF.prototype.isFollowupOn=function(){return this.m_followupOn;
};
CheckoutComponentWF.prototype.setFollowupLabel=function(value){this.m_followupLabel=value;
};
CheckoutComponentWF.prototype.getFollowupLabel=function(){return this.m_followupLabel;
};
CheckoutComponentWF.prototype.setVisitNoteSwitch=function(value){this.m_visitNoteOn=value;
};
CheckoutComponentWF.prototype.isVisitNoteOn=function(){return this.m_visitNoteOn;
};
CheckoutComponentWF.prototype.setVisitNoteLabel=function(value){this.m_visitNoteLabel=value;
};
CheckoutComponentWF.prototype.getVisitNoteLabel=function(){return this.m_visitNoteLabel;
};
CheckoutComponentWF.prototype.setVisitNoteLink=function(value){this.m_visitNoteLink=value;
};
CheckoutComponentWF.prototype.getVisitNoteLink=function(){return this.getValidatedUrl(this.m_visitNoteLink);
};
CheckoutComponentWF.prototype.setVisitSummarySwitch=function(value){this.m_visitSummaryOn=value;
};
CheckoutComponentWF.prototype.isVisitSummaryOn=function(){return this.m_visitSummaryOn;
};
CheckoutComponentWF.prototype.setVisitSummaryLabel=function(value){this.m_visitSummaryLabel=value;
};
CheckoutComponentWF.prototype.getVisitSummaryLabel=function(){return this.m_visitSummaryLabel;
};
CheckoutComponentWF.prototype.setVisitSummaryLink=function(value){this.m_visitSummaryLink=value;
};
CheckoutComponentWF.prototype.getVisitSummaryLink=function(){return this.getValidatedUrl(this.m_visitSummaryLink);
};
CheckoutComponentWF.prototype.setVisitChargeSwitch=function(value){this.m_visitChargeOn=value;
};
CheckoutComponentWF.prototype.isVisitChargeOn=function(){return this.m_visitChargeOn;
};
CheckoutComponentWF.prototype.setVisitChargeLabel=function(value){this.m_visitChargeLabel=value;
};
CheckoutComponentWF.prototype.getVisitChargeLabel=function(){return this.m_visitChargeLabel;
};
CheckoutComponentWF.prototype.setVisitChargeLinkSwitch=function(value){this.m_visitChargeLinkOn=value;
};
CheckoutComponentWF.prototype.isLinkToChargeOn=function(){return this.m_visitChargeLinkOn;
};
CheckoutComponentWF.prototype.loadFilterMappings=function(){this.addFilterMappingObject("WF_CHECKOUT_MEDREC",{setFunction:this.setMedReconciliationSwitch,type:"BOOLEAN",field:"FREETEXT_DESC"});
this.addFilterMappingObject("WF_CHECKOUT_MEDREC_LABEL",{setFunction:this.setMedReconciliationLabel,type:"STRING",field:"FREETEXT_DESC"});
this.addFilterMappingObject("WF_CHECKOUT_PATED",{setFunction:this.setPatEducationSwitch,type:"BOOLEAN",field:"FREETEXT_DESC"});
this.addFilterMappingObject("WF_CHECKOUT_PATED_LABEL",{setFunction:this.setPatEducationLabel,type:"STRING",field:"FREETEXT_DESC"});
this.addFilterMappingObject("WF_CHECKOUT_FOLLOWUP",{setFunction:this.setFollowupSwitch,type:"BOOLEAN",field:"FREETEXT_DESC"});
this.addFilterMappingObject("WF_CHECKOUT_FOLLOWUP_LABEL",{setFunction:this.setFollowupLabel,type:"STRING",field:"FREETEXT_DESC"});
this.addFilterMappingObject("WF_CHECKOUT_NOTE",{setFunction:this.setVisitNoteSwitch,type:"BOOLEAN",field:"FREETEXT_DESC"});
this.addFilterMappingObject("WF_CHECKOUT_NOTE_LABEL",{setFunction:this.setVisitNoteLabel,type:"STRING",field:"FREETEXT_DESC"});
this.addFilterMappingObject("WF_CHECKOUT_NOTE_LINK",{setFunction:this.setVisitNoteLink,type:"STRING",field:"FREETEXT_DESC"});
this.addFilterMappingObject("WF_CHECKOUT_SUMMARY",{setFunction:this.setVisitSummarySwitch,type:"BOOLEAN",field:"FREETEXT_DESC"});
this.addFilterMappingObject("WF_CHECKOUT_SUMM_LABEL",{setFunction:this.setVisitSummaryLabel,type:"STRING",field:"FREETEXT_DESC"});
this.addFilterMappingObject("WF_CHECKOUT_SUMM_LINK",{setFunction:this.setVisitSummaryLink,type:"STRING",field:"FREETEXT_DESC"});
this.addFilterMappingObject("WF_CHECKOUT_CHARGE",{setFunction:this.setVisitChargeSwitch,type:"BOOLEAN",field:"FREETEXT_DESC"});
this.addFilterMappingObject("WF_CHECKOUT_CHARGE_LABEL",{setFunction:this.setVisitChargeLabel,type:"STRING",field:"FREETEXT_DESC"});
this.addFilterMappingObject("WF_CHECKOUT_CHARGE_LINK",{setFunction:this.setVisitChargeLinkSwitch,type:"BOOLEAN",field:"FREETEXT_DESC"});
};
CheckoutComponentWF.prototype.retrieveComponentData=function(){var criterion=this.getCriterion();
var groups=this.getGroups();
var events=(groups&&groups.length>0)?groups[0].getEventSets():null;
var checkoutComponent=[];
if(this.isMedReconciliationOn()){checkoutComponent.push("'MED_REC'");
}if(this.isPatEducationOn()){checkoutComponent.push("'WF_PFE'");
}if(this.isFollowupOn()){checkoutComponent.push("'WF_FOLLOWUP'");
}if(this.isVisitNoteOn()){checkoutComponent.push("'VISIT_NOTE'");
}if(this.isVisitSummaryOn()){checkoutComponent.push("'VISIT_SUMMARY'");
}if(this.isVisitChargeOn()){checkoutComponent.push("'WF_CHARGES'");
}if(checkoutComponent&&checkoutComponent.length>0){var sendArray=["^MINE^",criterion.person_id+".0",criterion.encntr_id+".0",criterion.provider_id+".0",criterion.position_cd+".0",criterion.ppr_cd+".0",MP_Util.CreateParamArray(events,1),1,"value("+checkoutComponent.join(",")+")"];
MP_Core.XMLCclRequestWrapper(this,"MP_GET_CHECKOUT_STATUS",sendArray,true);
}else{var errorHtml=MP_Core.generateUserMessageHTML("error",this.checkoutI18n.NOT_CONFIGURED_BEDROCK_ERR,"","ckout-request-alert-msg ckout-request-msg ckout-request-blue-cross-image");
MP_Util.Doc.FinalizeComponent(errorHtml,this,"");
}};
CheckoutComponentWF.prototype.renderComponent=function(reply){try{var compId=this.getComponentId();
var container=[];
var sHTML="";
var self=this;
var dataRow=[];
var dataRowString="";
var maxLabelLength=30;
var medReconciliationLabel=this.getMedReconciliationLabel();
var patientEduLabel=this.getPatEducationLabel();
var followupLabel=this.getFollowupLabel();
var visitNoteLabel=this.getVisitNoteLabel();
var visitSummaryLabel=this.getVisitSummaryLabel();
var visitChargeLabel=this.getVisitChargeLabel();
CERN_EventListener.addListener(this,EventListener.EVENT_NAVIGATOR_ERR,this.onCheckoutNavigationErr,this);
var checkoutStatus=this.setCheckoutIndicators(reply);
container.push("<div class='",MP_Util.GetContentClass(this,"1"),"'>");
dataRow.push("<div align='center' class='ckout-container'>");
if(this.isMedReconciliationOn()){var medRecLengthFormattedLabel=this.getLengthFormattedLabel(medReconciliationLabel);
var medRecFaceupLabel=this.getValidatedLabel(medRecLengthFormattedLabel);
if(CERN_Platform.inMillenniumContext()){dataRow.push("<div class='ckout-comp ",(checkoutStatus.isMedReconciliationComplete)?"ckout-complete-bgcolour ":"ckout-incomplete-bgcolour","'><div class='",(checkoutStatus.isMedReconciliationComplete)?"ckout-complete":"ckout-incomplete","'></div><div id= '","medRecon"+compId,"' title ='",(medReconciliationLabel.length>maxLabelLength)?this.getValidatedLabel(medReconciliationLabel):"","'><span class='ckout-text'>",medRecFaceupLabel,"</span></div></div>");
}else{dataRow.push("<div class='ckout-comp ",(checkoutStatus.isMedReconciliationComplete)?"ckout-complete-bgcolour ":"ckout-incomplete-bgcolour","'><div class='",(checkoutStatus.isMedReconciliationComplete)?"ckout-complete":"ckout-incomplete","'></div><div title ='",(medReconciliationLabel.length>maxLabelLength)?this.getValidatedLabel(medReconciliationLabel):"","' ><span>",medRecFaceupLabel,"</span></div></div>");
}}if(this.isPatEducationOn()){var patientEduLengthFormattedLabel=this.getLengthFormattedLabel(patientEduLabel);
var patEduFaceupLabel=this.getValidatedLabel(patientEduLengthFormattedLabel);
dataRow.push("<div class='ckout-comp ",(checkoutStatus.isPatEducationComplete)?"ckout-complete-bgcolour ":"ckout-incomplete-bgcolour","'><div class='",(checkoutStatus.isPatEducationComplete)?"ckout-complete ":"ckout-incomplete","'></div><div id= '","patSum"+compId,"' title ='",(patientEduLabel.length>maxLabelLength)?this.getValidatedLabel(patientEduLabel):"","'><span class='ckout-text'>",patEduFaceupLabel,"</span></div></div>");
}if(this.isFollowupOn()){var FollowupLengthFormattedLabel=this.getLengthFormattedLabel(followupLabel);
var followupFaceupLabel=this.getValidatedLabel(FollowupLengthFormattedLabel);
dataRow.push("<div class='ckout-comp ",(checkoutStatus.isFollowupComplete)?"ckout-complete-bgcolour ":"ckout-incomplete-bgcolour","'><div class='",(checkoutStatus.isFollowupComplete)?"ckout-complete":"ckout-incomplete","'></div><div id='","followUp"+compId,"' nameSpace='fu-o2' title ='",(followupLabel.length>maxLabelLength)?this.getValidatedLabel(followupLabel):"","'><span class='ckout-text' >",followupFaceupLabel,"</span></div></div>");
}if(this.isVisitNoteOn()){var visitNoteLengthFormattedLabel=this.getLengthFormattedLabel(visitNoteLabel);
var visitNoteFaceupLabel=this.getValidatedLabel(visitNoteLengthFormattedLabel);
if(CERN_Platform.inMillenniumContext()){dataRow.push("<div class='ckout-comp ",(checkoutStatus.isVisitNoteComplete)?"ckout-complete-bgcolour ":"ckout-incomplete-bgcolour","'><div class='",(checkoutStatus.isVisitNoteComplete)?"ckout-complete":"ckout-incomplete","'></div><div  id= '","visitNote"+compId,"' title='",(visitNoteLabel.length>maxLabelLength)?this.getValidatedLabel(visitNoteLabel):"","'><span class='ckout-text' >",visitNoteFaceupLabel,"</span></div></div>");
}else{dataRow.push("<div class='ckout-comp ",(checkoutStatus.isVisitNoteComplete)?"ckout-complete-bgcolour ":"ckout-incomplete-bgcolour","'><div class='",(checkoutStatus.isVisitNoteComplete)?"ckout-complete":"ckout-incomplete","'></div><div title='",(visitNoteLabel.length>maxLabelLength)?this.getValidatedLabel(visitNoteLabel):"","'><span>",visitNoteFaceupLabel,"</span></div></div>");
}}if(this.isVisitSummaryOn()){var VisitSummLengthFormattedLabel=this.getLengthFormattedLabel(visitSummaryLabel);
var visitSummaryFaceupLabel=this.getValidatedLabel(VisitSummLengthFormattedLabel);
if(CERN_Platform.inMillenniumContext()){dataRow.push("<div class='ckout-comp ",(checkoutStatus.isVisitSummaryComplete)?"ckout-complete-bgcolour ":"ckout-incomplete-bgcolour","'><div class='",(checkoutStatus.isVisitSummaryComplete)?"ckout-complete":"ckout-incomplete","'></div><div id='","visitSum"+compId,"' title='",(visitSummaryLabel.length>maxLabelLength)?this.getValidatedLabel(visitSummaryLabel):"","'><span class='ckout-text' >",visitSummaryFaceupLabel,"</span></div></div>");
}else{dataRow.push("<div class='ckout-comp ",(checkoutStatus.isVisitSummaryComplete)?"ckout-complete-bgcolour ":"ckout-incomplete-bgcolour","'><div class='",(checkoutStatus.isVisitSummaryComplete)?"ckout-complete":"ckout-incomplete","'></div><div title='",(visitSummaryLabel.length>maxLabelLength)?this.getValidatedLabel(visitSummaryLabel):"","'><span>",visitSummaryFaceupLabel,"</span></div></div>");
}}if(this.isVisitChargeOn()){var VisitChargeLengthFormattedLabel=this.getLengthFormattedLabel(visitChargeLabel);
var visitChargeFaceupLabel=this.getValidatedLabel(VisitChargeLengthFormattedLabel);
dataRow.push("<div class='ckout-comp ",(checkoutStatus.isVisitChargeComplete)?"ckout-complete-bgcolour ":"ckout-incomplete-bgcolour","'><div class='",(checkoutStatus.isVisitChargeComplete)?"ckout-complete":"ckout-incomplete","'></div><div id='","charge"+compId,"' title='",(visitChargeLabel.length>maxLabelLength)?this.getValidatedLabel(visitChargeLabel):"","'><span class='ckout-text' >",visitChargeFaceupLabel,"</span></div></div>");
}dataRowString=dataRow.join("");
container.push(dataRowString,"</div>");
sHTML=container.join("");
MP_Util.Doc.FinalizeComponent(sHTML,this,"");
$("#patSum"+compId).on("click",{nameSpace:"pe-o2",self:this},this.handleClick);
$("#followUp"+compId).on("click",{nameSpace:"fu-o2",self:this},this.handleClick);
$("#charge"+compId).on("click",{nameSpace:"charge",self:this},this.handleClick);
$("#medRecon"+compId).on("click",{nameSpace:"medRecon",self:this},this.handleClick);
$("#visitNote"+compId).on("click",{nameSpace:"visitNote",self:this},this.handleClick);
$("#visitSum"+compId).on("click",{nameSpace:"visitSum",self:this},this.handleClick);
}catch(err){MP_Util.LogJSError(this,err,"checkout-o1.js","renderComponent");
}finally{}};
CheckoutComponentWF.prototype.setCheckoutIndicators=function(reply){var scriptReplyComponent=reply.COMPONENTS;
var checkout={isFollowupComplete:false,isPatEducationComplete:false,isMedReconciliationComplete:false,isVisitNoteComplete:false,isVisitSummaryComplete:false,isVisitChargeComplete:false};
if(scriptReplyComponent){for(var x=scriptReplyComponent.length;
x--;
){switch(scriptReplyComponent[x].MEANING){case"WF_FOLLOWUP":checkout.isFollowupComplete=(scriptReplyComponent[x].STATUS_FLAG===1)?true:false;
break;
case"WF_PFE":checkout.isPatEducationComplete=(scriptReplyComponent[x].STATUS_FLAG===1)?true:false;
break;
case"MED_REC":checkout.isMedReconciliationComplete=(scriptReplyComponent[x].STATUS_FLAG===1)?true:false;
break;
case"VISIT_NOTE":checkout.isVisitNoteComplete=(scriptReplyComponent[x].STATUS_FLAG===1)?true:false;
break;
case"VISIT_SUMMARY":checkout.isVisitSummaryComplete=(scriptReplyComponent[x].STATUS_FLAG===1)?true:false;
break;
case"WF_CHARGES":checkout.isVisitChargeComplete=(scriptReplyComponent[x].STATUS_FLAG===1)?true:false;
break;
default:alert("No components used within the Checkout Component are mapped to this view.");
}}}return checkout;
};
CheckoutComponentWF.prototype.handleClick=function(event){var nameSpace=event.data.nameSpace;
var self=event.data.self;
var criterion=self.getCriterion();
switch(nameSpace){case"pe-o2":case"fu-o2":CERN_EventListener.fireEvent(self,self,EventListener.EVENT_SCROLL,nameSpace);
break;
case"charge":var nameSpce=(self.isLinkToChargeOn())?"charges":"noe2";
CERN_EventListener.fireEvent(self,self,EventListener.EVENT_SCROLL,nameSpce);
break;
case"medRecon":var medReconciliationObject={};
try{MP_Util.LogDiscernInfo(self,"ORDERS","checkout.js","handleClick");
medReconciliationObject=window.external.DiscernObjectFactory("ORDERS");
medReconciliationObject.PersonId=criterion.person_id;
medReconciliationObject.EncntrId=criterion.encntr_id;
medReconciliationObject.reconciliationMode=3;
medReconciliationObject.defaultVenue=self.getDischargeMedCode();
medReconciliationObject.LaunchOrdersMode(2,0,0);
}catch(err){MP_Util.LogJSError(err,null,"checkout.js","handleClick");
}break;
case"visitNote":APPLINK(0,"powerchart.exe","/PERSONID="+criterion.person_id+" /ENCNTRID="+criterion.encntr_id+"/FIRSTTAB=^"+self.getVisitNoteLink()+"^");
break;
case"visitSum":APPLINK(0,"powerchart.exe","/PERSONID="+criterion.person_id+" /ENCNTRID="+criterion.encntr_id+"/FIRSTTAB=^"+self.getVisitSummaryLink()+"^");
break;
case"default":break;
}};
CheckoutComponentWF.prototype.onCheckoutNavigationErr=function(component,args){var componentLabel="";
switch(args){case"pe-o2":componentLabel=this.getPatEducationLabel();
break;
case"fu-o2":componentLabel=this.getFollowupLabel();
break;
case"charges":case"noe2":componentLabel=this.getVisitChargeLabel();
break;
default:componentLabel="";
}try{var errorMessage=this.checkoutI18n.NOT_CONFIGURED_NAVIGATOR_ERR.replace("{0}",this.getValidatedLabel(componentLabel));
var errorModal=MP_ModalDialog.retrieveModalDialogObject("errorModal");
if(!errorModal){errorModal=MP_Util.generateModalDialogBody("errorModal","error",errorMessage,"");
errorModal.setHeaderTitle(i18n.ERROR_OCCURED);
var closeButton=new ModalButton("closeButton");
closeButton.setText(i18n.CLOSE).setCloseOnClick(true);
errorModal.addFooterButton(closeButton);
}else{errorModal=MP_Util.generateModalDialogBody("errorModal","error",errorMessage,"");
}MP_ModalDialog.updateModalDialogObject(errorModal);
MP_ModalDialog.showModalDialog("errorModal");
}catch(err){MP_Util.LogJSError(this,err,"checkout-o1.js","onCheckoutNavigationErr");
}};
CheckoutComponentWF.prototype.getValidatedLabel=function(label){var tempObj=null;
if(label&&typeof label==="string"){tempObj=$("<div>").html(label);
return tempObj.html();
}else{throw new TypeError("Invalid input Label!");
}};
CheckoutComponentWF.prototype.getLengthFormattedLabel=function(label){var componentLabel=label;
var maxLabelLength=30;
if(label&&typeof label==="string"){if(label.length>maxLabelLength){componentLabel=label.substr(0,maxLabelLength)+"...";
}return componentLabel;
}else{throw new TypeError("Invalid input Label! ");
}};
CheckoutComponentWF.prototype.getValidatedUrl=function(label){var tempObj=null;
if(label&&typeof label==="string"){tempObj=$("<div>").html(label);
return tempObj.html().replace("&amp;","&").replace("&lt;","<").replace("&gt;",">");
}else{throw new TypeError("Invalid input Label! ");
}};
MP_Util.setObjectDefinitionMapping("WF_CHECKOUT",CheckoutComponentWF);
