(function(){window.DocumentationUtils={};
DocumentationUtils.getDocUtilsHelper=function(){var utilContainer=CKEDITOR?CKEDITOR:window;
if(!utilContainer.DocUtilsHelper){utilContainer.DocUtilsHelper=CERN_Platform.getDiscernObject("DOCUTILSHELPER");
}return utilContainer.DocUtilsHelper;
};
DocumentationUtils.cleanHtml=function(html){var DocUtilsHelper=DocumentationUtils.getDocUtilsHelper();
var sanitizedHtml="";
if(typeof DocUtilsHelper!=="undefined"&&typeof DocUtilsHelper.CleanHtml!=="undefined"){sanitizedHtml=DocUtilsHelper.CleanHtml("<div>"+html+"</div>",true);
}else{throw new Error("DocUtilsHelper or DocUtilsHelper.CleanHtml undefined");
}return sanitizedHtml;
};
DocumentationUtils.getXHtml=function(html){return'<?xml version="1.0"?><html><head><title></title></head><body>'+html+"</body></html>";
};
DocumentationUtils.getSelectedHtml=(function(){var srcDocument;
var srcWindow;
function getComputedElementStyle(element,styleName){var style;
if(srcWindow.getSelection){style=srcWindow.getComputedStyle(element);
return style.getPropertyValue(styleName);
}else{style=element.currentStyle;
return style[styleName];
}}var getDefaultStyle=(function(){var defaultsCache={};
return function(tagName,styleName){tagName=tagName.toLowerCase();
styleName=styleName.toLowerCase();
var tagDefaults=defaultsCache[tagName];
if(tagDefaults&&tagDefaults.hasOwnProperty(styleName)){return tagDefaults[styleName];
}var dummy=srcDocument.createElement(tagName);
if(srcDocument.documentMode&&srcDocument.documentMode<9){$(dummy).css({position:"absolute",visibility:"hidden",top:0,left:0}).appendTo(srcDocument.body);
}var def=getComputedElementStyle(dummy,styleName);
$(dummy).remove();
if(!tagDefaults){tagDefaults=defaultsCache[tagName]={};
}tagDefaults[styleName]=def;
return def;
};
})();
var isStyleOk=(function(){var STYLE_WHITELIST=["color","text-decoration","text-align","vertical-align","box-sizing","direction","kerning","letter-spacing","word-spacing","line-break","word-break","line-height","white-space","table-layout","text-transform"];
var STYLE_WHITELIST_OTHER_REGEX=/(?:^font)|(?:^border)|(?:^margin)|(?:^padding)/i;
var STYLE_WHITELIST_LOOKUP={};
var whitelistLength=STYLE_WHITELIST.length;
for(var i=0;
i<whitelistLength;
i++){var styleName=STYLE_WHITELIST[i];
STYLE_WHITELIST_LOOKUP[styleName]=1;
var altName=styleName.replace(/-([a-z])/g,function(match,p1){return p1.charAt(0).toUpperCase();
});
STYLE_WHITELIST_LOOKUP[altName]=1;
}return function(styleName){styleName=styleName.toLowerCase();
return STYLE_WHITELIST_LOOKUP[styleName]||STYLE_WHITELIST_OTHER_REGEX.test(styleName);
};
})();
function copyStyles(src,dest){var style;
var styleName;
var styleValue;
var styleCnt;
if(srcWindow.getSelection){style=srcWindow.getComputedStyle(src);
styleCnt=style.length;
for(var propIndex=0;
propIndex<styleCnt;
propIndex++){styleName=style[propIndex];
if(!isStyleOk(styleName)){continue;
}styleValue=style.getPropertyValue(styleName);
if(getDefaultStyle(dest.tagName,styleName)===styleValue){continue;
}dest.style.setProperty(styleName,styleValue,"");
}}else{style=src.currentStyle;
for(styleName in style){if(!isStyleOk(styleName)){continue;
}styleValue=style[styleName];
if(getDefaultStyle(dest.tagName,styleName)===styleValue){continue;
}dest.style.setAttribute(styleName,styleValue);
}}}function getSelectedHtml(){var html="";
var container=srcDocument.createElement("div");
var parentElem;
var selectionRangeCount;
if(typeof srcWindow.getSelection!="undefined"&&srcWindow.getSelection().toString()!==""&&(!srcDocument.documentMode||srcDocument.documentMode>=9)){var sel=srcWindow.getSelection();
selectionRangeCount=sel.rangeCount;
if(selectionRangeCount){for(var i=0,len=selectionRangeCount;
i<len;
++i){parentElem=sel.getRangeAt(i).commonAncestorContainer;
while(parentElem.nodeType!==1){parentElem=parentElem.parentNode;
}copyStyles(parentElem,container);
container.appendChild(sel.getRangeAt(i).cloneContents());
}html=container.outerHTML;
}}else{if(typeof srcDocument.selection!=="undefined"&&srcDocument.selection.type==="Text"&&srcDocument.selection.createRange().text!==""&&srcDocument.documentMode<9){parentElem=srcDocument.selection.createRange().parentElement();
while(parentElem.nodeType!==1){parentElem=parentElem.parentNode;
}copyStyles(parentElem,container);
container.innerHTML=srcDocument.selection.createRange().htmlText;
html=container.outerHTML;
}}return html;
}return function(sourceDocument,sourceWindow){srcWindow=sourceWindow;
srcDocument=sourceDocument;
return getSelectedHtml();
};
})();
})();
