function DocumentationGenComponentStyle(){this.initByNamespace("documentation-gen");
}DocumentationGenComponentStyle.prototype=new ComponentStyle();
function DocumentationGenComponent(criterion){this.setCriterion(criterion);
this.setStyles(new DocumentationGenComponentStyle());
this.setDocumentationTimerName("MPG.DOCUMENTATION_GEN.O1");
this.setComponentLoadTimerName("USR:"+this.getDocumentationTimerName()+"_load_component");
this.setComponentRenderTimerName("ENG:"+this.getDocumentationTimerName()+"_render_component");
this.setIncludeLineNumber(true);
this.setConceptType("");
this.setPlaceholderText("");
}DocumentationGenComponent.prototype=new DocumentationBaseComponent();
DocumentationGenComponent.prototype.constructor=DocumentationBaseComponent;
DocumentationGenComponent.prototype.preProcessing=function(){DocumentationBaseComponent.prototype.preProcessing.call(this);
this.setPlusAddEnabled(false);
};
DocumentationGenComponent.prototype.loadFilterMappings=function(){this.addFilterMappingObject("WF_GDD_CKI_1",{setFunction:this.setConceptCKI,type:"STRING",field:"FREETEXT_DESC"});
this.addFilterMappingObject("WF_GDD_CKI_2",{setFunction:this.setConceptCKI,type:"STRING",field:"FREETEXT_DESC"});
this.addFilterMappingObject("WF_GDD_CKI_3",{setFunction:this.setConceptCKI,type:"STRING",field:"FREETEXT_DESC"});
};
MP_Util.setObjectDefinitionMapping("WF_GDD_COMP_1",DocumentationGenComponent);
MP_Util.setObjectDefinitionMapping("WF_GDD_COMP_2",DocumentationGenComponent);
MP_Util.setObjectDefinitionMapping("WF_GDD_COMP_3",DocumentationGenComponent);
