function GoalsComponentO1Style(){this.initByNamespace("goals");
}GoalsComponentO1Style.inherits(ComponentStyle);
function GoalsComponentO1(criterion){this.setCriterion(criterion);
this.setStyles(new GoalsComponentO1Style());
this.setComponentLoadTimerName("USR:MPG.RehabGoals.O1 - load component");
this.setComponentRenderTimerName("ENG:MPG.RehabGoals.O1 - render component");
this.setIncludeLineNumber(true);
GoalsComponentO1.method("InsertData",function(){CERN_RehabGoalsO1.GetRehabGoalsO1Table(this);
});
GoalsComponentO1.method("HandleSuccess",function(recordData){CERN_RehabGoalsO1.RenderComponent(this,recordData);
});
GoalsComponentO1.method("setNursingGoals",function(value){this.m_nursingGoals=value;
});
GoalsComponentO1.method("getNursingGoals",function(){return this.m_nursingGoals;
});
GoalsComponentO1.method("setOTShortTermGoalDocumented",function(value){this.m_OTShortTermGoalDocumented=value;
});
GoalsComponentO1.method("getOTShortTermGoalDocumented",function(){return this.m_OTShortTermGoalDocumented;
});
GoalsComponentO1.method("setOTLongTermGoalDocumented",function(value){this.m_OTLongTermGoalDocumented=value;
});
GoalsComponentO1.method("getOTLongTermGoalDocumented",function(){return this.m_OTLongTermGoalDocumented;
});
GoalsComponentO1.method("setPTShortTermGoalDocumented",function(value){this.m_PTShortTermGoalDocumented=value;
});
GoalsComponentO1.method("getPTShortTermGoalDocumented",function(){return this.m_PTShortTermGoalDocumented;
});
GoalsComponentO1.method("setPTLongTermGoalDocumented",function(value){this.m_PTLongTermGoalDocumented=value;
});
GoalsComponentO1.method("getPTLongTermGoalDocumented",function(){return this.m_PTLongTermGoalDocumented;
});
GoalsComponentO1.method("setSLPShortTermGoalDocumented",function(value){this.m_SLPShortTermGoalDocumented=value;
});
GoalsComponentO1.method("getSLPShortTermGoalDocumented",function(){return this.m_SLPShortTermGoalDocumented;
});
GoalsComponentO1.method("setSLPLongTermGoalDocumented",function(value){this.m_SLPLongTermGoalDocumented=value;
});
GoalsComponentO1.method("getSLPLongTermGoalDocumented",function(){return this.m_SLPLongTermGoalDocumented;
});
GoalsComponentO1.method("setOTShortTermGoalDocumentedDG",function(value){this.m_OTShortTermGoalDocumentedDG=value;
});
GoalsComponentO1.method("getOTShortTermGoalDocumentedDG",function(){return this.m_OTShortTermGoalDocumentedDG;
});
GoalsComponentO1.method("setOTLongTermGoalDocumentedDG",function(value){this.m_OTLongTermGoalDocumentedDG=value;
});
GoalsComponentO1.method("getOTLongTermGoalDocumentedDG",function(){return this.m_OTLongTermGoalDocumentedDG;
});
GoalsComponentO1.method("setPTShortTermGoalDocumentedDG",function(value){this.m_PTShortTermGoalDocumentedDG=value;
});
GoalsComponentO1.method("getPTShortTermGoalDocumentedDG",function(){return this.m_PTShortTermGoalDocumentedDG;
});
GoalsComponentO1.method("setPTLongTermGoalDocumentedDG",function(value){this.m_PTLongTermGoalDocumentedDG=value;
});
GoalsComponentO1.method("getPTLongTermGoalDocumentedDG",function(){return this.m_PTLongTermGoalDocumentedDG;
});
GoalsComponentO1.method("setSLPShortTermGoalDocumentedDG",function(value){this.m_SLPShortTermGoalDocumentedDG=value;
});
GoalsComponentO1.method("getSLPShortTermGoalDocumentedDG",function(){return this.m_SLPShortTermGoalDocumentedDG;
});
GoalsComponentO1.method("setSLPLongTermGoalDocumentedDG",function(value){this.m_SLPLongTermGoalDocumentedDG=value;
});
GoalsComponentO1.method("getSLPLongTermGoalDocumentedDG",function(){return this.m_SLPLongTermGoalDocumentedDG;
});
GoalsComponentO1.method("openTab",function(){var criterion=this.getCriterion();
var paramString=criterion.person_id+"|"+criterion.encntr_id+"|"+0+"|0|0";
MP_Util.LogMpagesEventInfo(this,"POWERFORM",paramString,"goals.js","openTab");
javascript:MPAGES_EVENT("POWERFORM",paramString);
});
GoalsComponentO1.method("openDropDown",function(formID){var criterion=this.getCriterion();
var paramString=criterion.person_id+"|"+criterion.encntr_id+"|"+formID+"|0|0";
MP_Util.LogMpagesEventInfo(this,"POWERFORM",paramString,"goals.js","openDropDown");
javascript:MPAGES_EVENT("POWERFORM",paramString);
});
}GoalsComponentO1.inherits(MPageComponent);
GoalsComponentO1.prototype.loadFilterMappings=function(){this.addFilterMappingObject("NURSE_GOAL_DOC",{setFunction:this.setNursingGoals,type:"Array",field:"PARENT_ENTITY_ID"});
this.addFilterMappingObject("OT_STG_DOC",{setFunction:this.setOTShortTermGoalDocumented,type:"Array",field:"PARENT_ENTITY_ID"});
this.addFilterMappingObject("OT_LTG_DOC",{setFunction:this.setOTLongTermGoalDocumented,type:"Array",field:"PARENT_ENTITY_ID"});
this.addFilterMappingObject("PT_STG_DOC",{setFunction:this.setPTShortTermGoalDocumented,type:"Array",field:"PARENT_ENTITY_ID"});
this.addFilterMappingObject("PT_LTG_DOC",{setFunction:this.setPTLongTermGoalDocumented,type:"Array",field:"PARENT_ENTITY_ID"});
this.addFilterMappingObject("SLP_STG_DOC",{setFunction:this.setSLPShortTermGoalDocumented,type:"Array",field:"PARENT_ENTITY_ID"});
this.addFilterMappingObject("SLP_LTG_DOC",{setFunction:this.setSLPLongTermGoalDocumented,type:"Array",field:"PARENT_ENTITY_ID"});
this.addFilterMappingObject("OT_STG_DOC_DG",{setFunction:this.setOTShortTermGoalDocumentedDG,type:"Array",field:"PARENT_ENTITY_ID"});
this.addFilterMappingObject("OT_LTG_DOC_DG",{setFunction:this.setOTLongTermGoalDocumentedDG,type:"Array",field:"PARENT_ENTITY_ID"});
this.addFilterMappingObject("PT_STG_DOC_DG",{setFunction:this.setPTShortTermGoalDocumentedDG,type:"Array",field:"PARENT_ENTITY_ID"});
this.addFilterMappingObject("PT_LTG_DOC_DG",{setFunction:this.setPTLongTermGoalDocumentedDG,type:"Array",field:"PARENT_ENTITY_ID"});
this.addFilterMappingObject("SLP_STG_DOC_DG",{setFunction:this.setSLPShortTermGoalDocumentedDG,type:"Array",field:"PARENT_ENTITY_ID"});
this.addFilterMappingObject("SLP_LTG_DOC_DG",{setFunction:this.setSLPLongTermGoalDocumentedDG,type:"Array",field:"PARENT_ENTITY_ID"});
};
var CERN_RehabGoalsO1=function(){return{GetRehabGoalsO1Table:function(component){var sendAr=[];
var criterion=component.getCriterion();
var goalsO1_lookbackUnits=0;
var goalsO1_lookbackType=0;
goalsO1_encntr=(component.getScope()==1)?"0.0":(criterion.encntr_id+".0");
goalsO1_lookbackUnits=(component.getLookbackUnits())?component.getLookbackUnits():"0";
goalsO1_lookbackType=(component.getLookbackUnitTypeFlag())?component.getLookbackUnitTypeFlag():"-1";
sendAr.push("^MINE^",criterion.person_id+".0",goalsO1_encntr,goalsO1_lookbackUnits,goalsO1_lookbackType);
sendAr.push(MP_Util.CreateParamArray(component.getNursingGoals(),1));
sendAr.push(MP_Util.CreateParamArray(component.getOTShortTermGoalDocumented(),1));
sendAr.push(MP_Util.CreateParamArray(component.getOTLongTermGoalDocumented(),1));
sendAr.push(MP_Util.CreateParamArray(component.getPTShortTermGoalDocumented(),1));
sendAr.push(MP_Util.CreateParamArray(component.getPTLongTermGoalDocumented(),1));
sendAr.push(MP_Util.CreateParamArray(component.getSLPShortTermGoalDocumented(),1));
sendAr.push(MP_Util.CreateParamArray(component.getSLPLongTermGoalDocumented(),1));
sendAr.push(MP_Util.CreateParamArray(component.getOTShortTermGoalDocumentedDG(),1));
sendAr.push(MP_Util.CreateParamArray(component.getOTLongTermGoalDocumentedDG(),1));
sendAr.push(MP_Util.CreateParamArray(component.getPTShortTermGoalDocumentedDG(),1));
sendAr.push(MP_Util.CreateParamArray(component.getPTLongTermGoalDocumentedDG(),1));
sendAr.push(MP_Util.CreateParamArray(component.getSLPShortTermGoalDocumentedDG(),1));
sendAr.push(MP_Util.CreateParamArray(component.getSLPLongTermGoalDocumentedDG(),1));
MP_Core.XMLCclRequestWrapper(component,"mp_reh_get_goals",sendAr,true);
},RenderComponent:function(component,recordData){try{var m_rootComponentNode=null;
m_rootComponentNode=component.getRootComponentNode();
var compId=component.getStyles().getId();
var jsGoalsO1HTML=[];
var numberOfFixedRows=6;
var totalResultCount=0;
var criterion=component.getCriterion();
var dateTime=new Date();
var patResult="";
var totNurs=0;
var totOT=0;
var totPT=0;
var totSLP=0;
var nursingContent=[];
var otContent=[];
var ptContent=[];
var slpContent=[];
var otContentDG=[];
var ptContentDG=[];
var slpContentDG=[];
var i;
var j;
var g;
var t;
var r;
jsGoalsO1HTML.push("<div class = 'reh_goals_scrollable'>");
for(i=0;
i<recordData.TYPE_CNT;
i++){switch(recordData.TYPES[i].SECTION_IND){case 1:nursingContent.push("<div id='nursingGoals",compId,"'>");
for(j=0;
j<recordData.TYPES[i].CNT;
j++){if(recordData.TYPES[i].GOALS[j].MET_IND==1){nursingContent.push("<dl class='goals-hide' id='goals-met",compId,"'><dt class='goals-dt'>",recordData.TYPES[i].GOALS[j].TITLE,"</dt><dd class='goals-info-dd'>",recordData.TYPES[i].GOALS[j].DATE,"</dd><dd class='goals-ico-dd'><span class='goals-img-met'>&nbsp;</span></dd></dl>");
}else{nursingContent.push("<dl class='goals-info' id='goals-notmet",compId,"'><dt class='goals-dt'>",recordData.TYPES[i].GOALS[j].TITLE,"</dt><dd class='goals-info-dd'>",recordData.TYPES[i].GOALS[j].DATE,"</dd><dd class='goals-ico-dd'></dd></dl>");
totNurs++;
}}nursingContent.push("</div>");
nursingContent=nursingContent.join("");
break;
case 2:otContent.push("<div id='otGoals",compId,"'>");
for(j=0;
j<recordData.TYPES[i].CNT;
j++){if(recordData.TYPES[i].GOALS[j].TYPE_IND==1){otContent.push("<dl class='goals-info goals-stg'><dt class='goals-dt'>",recordData.TYPES[i].GOALS[j].TITLE,"</dt><dd class='goals-info-dd'>",recordData.TYPES[i].GOALS[j].RESULT,"</dd>");
otContent.push("<dd class='goals-ico-dd'>STG</dd></dl>");
totOT++;
}}for(j=0;
j<recordData.TYPES[i].CNT;
j++){if(recordData.TYPES[i].GOALS[j].TYPE_IND==2){otContent.push("<dl class='goals-hide goals-ltg'><dt class='goals-dt'>",recordData.TYPES[i].GOALS[j].TITLE,"</dt><dd class='goals-info-dd'>",recordData.TYPES[i].GOALS[j].RESULT,"</dd>");
otContent.push("<dd class='goals-ico-dd'>LTG</dd></dl>");
}}otContent.push("</div>");
otContent=otContent.join("");
break;
case 3:ptContent.push("<div id='ptGoals",compId,"'>");
for(j=0;
j<recordData.TYPES[i].CNT;
j++){if(recordData.TYPES[i].GOALS[j].TYPE_IND==1){ptContent.push("<dl class='goals-info goals-stg'><dt class='goals-dt'>",recordData.TYPES[i].GOALS[j].TITLE,"</dt><dd class='goals-info-dd'>",recordData.TYPES[i].GOALS[j].RESULT,"</dd>");
ptContent.push("<dd class='goals-ico-dd'>STG</dd></dl>");
totPT++;
}}for(j=0;
j<recordData.TYPES[i].CNT;
j++){if(recordData.TYPES[i].GOALS[j].TYPE_IND==2){ptContent.push("<dl class='goals-hide goals-ltg'><dt class='goals-dt'>",recordData.TYPES[i].GOALS[j].TITLE,"</dt><dd class='goals-info-dd'>",recordData.TYPES[i].GOALS[j].RESULT,"</dd>");
ptContent.push("<dd class='goals-ico-dd'>LTG</dd></dl>");
}}ptContent.push("</div>");
ptContent=ptContent.join("");
break;
case 4:slpContent.push("<div id='slpGoals",compId,"'>");
for(j=0;
j<recordData.TYPES[i].CNT;
j++){if(recordData.TYPES[i].GOALS[j].TYPE_IND==1){slpContent.push("<dl class='goals-info goals-stg'><dt class='goals-dt'>",recordData.TYPES[i].GOALS[j].TITLE,"</dt><dd class='goals-info-dd'>",recordData.TYPES[i].GOALS[j].RESULT,"</dd>");
slpContent.push("<dd class='goals-ico-dd'>STG</dd></dl>");
totSLP++;
}}for(j=0;
j<recordData.TYPES[i].CNT;
j++){if(recordData.TYPES[i].GOALS[j].TYPE_IND==2){slpContent.push("<dl class='goals-hide goals-ltg'><dt class='goals-dt'>",recordData.TYPES[i].GOALS[j].TITLE,"</dt><dd class='goals-info-dd'>",recordData.TYPES[i].GOALS[j].RESULT,"</dd>");
slpContent.push("<dd class='goals-ico-dd'>LTG</dd></dl>");
}}slpContent.push("</div>");
slpContent=slpContent.join("");
break;
}}for(g=0;
g<recordData.DYNAMIC_GROUPS.OT_STG.GROUP_CNT;
g++){otContentDG.push("<div class='sub-sec rehab-sec'><h3 class='sub-sec-hd'>","<dl class='goals-info goals-stg'><dt class='goals-dt'>",recordData.DYNAMIC_GROUPS.OT_STG.GROUP[g].NAME,"</dt></dl></h3><div class='content-body'><div class='sub-sec-content'><h3 class='goals-info-hd'><span>patResult</span></h3>");
for(t=0;
t<recordData.DYNAMIC_GROUPS.OT_STG.GROUP[g].TYPE_CNT;
t++){otContentDG.push("<div class='sub-sec rehab-sec'><h3 class='sub-sec-hd'>","<dl class='goals-info goals-stg'><dt class='goals-dt'>&nbsp;&nbsp",recordData.DYNAMIC_GROUPS.OT_STG.GROUP[g].TYPE[t].NAME,"</dt></dl></h3><div class='content-body'><div class='sub-sec-content'><h3 class='goals-info-hd'><span>patResult</span></h3>");
for(r=0;
r<recordData.DYNAMIC_GROUPS.OT_STG.GROUP[g].TYPE[t].RESULT_CNT;
r++){otContentDG.push("<dl class='goals-info goals-stg'><dt class='goals-dt'>",recordData.DYNAMIC_GROUPS.OT_STG.GROUP[g].TYPE[t].RESULT_SET[r].LABEL,"</dt><dd class='goals-info-dd'>",recordData.DYNAMIC_GROUPS.OT_STG.GROUP[g].TYPE[t].RESULT_SET[r].RESULT,"</dd>");
otContentDG.push("<dd class='goals-ico-dd'>STG</dd></dl>");
}}}for(g=0;
g<recordData.DYNAMIC_GROUPS.OT_LTG.GROUP_CNT;
g++){otContentDG.push("<div class='sub-sec rehab-sec'><h3 class='sub-sec-hd'>","<dl class='goals-ltg goals-hide'><dt class='goals-dt'>",recordData.DYNAMIC_GROUPS.OT_LTG.GROUP[g].NAME,"</dt></dl></h3><div class='content-body'><div class='sub-sec-content'><h3 class='goals-info-hd'><span>patResult</span></h3>");
for(t=0;
t<recordData.DYNAMIC_GROUPS.OT_LTG.GROUP[g].TYPE_CNT;
t++){otContentDG.push("<div class='sub-sec rehab-sec'><h3 class='sub-sec-hd'>","<dl class='goals-ltg goals-hide'><dt class='goals-dt'>&nbsp;&nbsp",recordData.DYNAMIC_GROUPS.OT_LTG.GROUP[g].TYPE[t].NAME,"</dt></dl></h3><div class='content-body'><div class='sub-sec-content'><h3 class='goals-info-hd'><span>patResult</span></h3>");
for(r=0;
r<recordData.DYNAMIC_GROUPS.OT_LTG.GROUP[g].TYPE[t].RESULT_CNT;
r++){otContentDG.push("<dl class='goals-ltg goals-hide'><dt class='goals-dt'>",recordData.DYNAMIC_GROUPS.OT_LTG.GROUP[g].TYPE[t].RESULT_SET[r].LABEL,"</dt><dd class='goals-info-dd'>",recordData.DYNAMIC_GROUPS.OT_LTG.GROUP[g].TYPE[t].RESULT_SET[r].RESULT,"</dd>");
otContentDG.push("<dd class='goals-ico-dd'>LTG</dd></dl>");
}}}otContentDG=otContentDG.join("");
for(g=0;
g<recordData.DYNAMIC_GROUPS.PT_STG.GROUP_CNT;
g++){ptContentDG.push("<div class='sub-sec rehab-sec'><h3 class='sub-sec-hd'>","<dl class='goals-info goals-stg'><dt class='goals-dt'>",recordData.DYNAMIC_GROUPS.PT_STG.GROUP[g].NAME,"</dt></dl></h3><div class='content-body'><div class='sub-sec-content'><h3 class='goals-info-hd'><span>patResult</span></h3>");
for(t=0;
t<recordData.DYNAMIC_GROUPS.PT_STG.GROUP[g].TYPE_CNT;
t++){ptContentDG.push("<div class='sub-sec rehab-sec'><h3 class='sub-sec-hd'>","<dl class='goals-info goals-stg'><dt class='goals-dt'>&nbsp;&nbsp",recordData.DYNAMIC_GROUPS.PT_STG.GROUP[g].TYPE[t].NAME,"</dt></dl></h3><div class='content-body'><div class='sub-sec-content'><h3 class='goals-info-hd'><span>patResult</span></h3>");
for(r=0;
r<recordData.DYNAMIC_GROUPS.PT_STG.GROUP[g].TYPE[t].RESULT_CNT;
r++){ptContentDG.push("<dl class='goals-info goals-stg'><dt class='goals-dt'>",recordData.DYNAMIC_GROUPS.PT_STG.GROUP[g].TYPE[t].RESULT_SET[r].LABEL,"</dt><dd class='goals-info-dd'>",recordData.DYNAMIC_GROUPS.PT_STG.GROUP[g].TYPE[t].RESULT_SET[r].RESULT,"</dd>");
ptContentDG.push("<dd class='goals-ico-dd'>STG</dd></dl>");
}}}for(g=0;
g<recordData.DYNAMIC_GROUPS.PT_LTG.GROUP_CNT;
g++){ptContentDG.push("<div class='sub-sec rehab-sec'><h3 class='sub-sec-hd'>","<dl class='goals-ltg goals-hide'><dt class='goals-dt'>",recordData.DYNAMIC_GROUPS.PT_LTG.GROUP[g].NAME,"</dt></dl></h3><div class='content-body'><div class='sub-sec-content'><h3 class='goals-info-hd'><span>patResult</span></h3>");
for(t=0;
t<recordData.DYNAMIC_GROUPS.PT_LTG.GROUP[g].TYPE_CNT;
t++){ptContentDG.push("<div class='sub-sec rehab-sec'><h3 class='sub-sec-hd'>","<dl class='goals-ltg goals-hide'><dt class='goals-dt'>&nbsp;&nbsp",recordData.DYNAMIC_GROUPS.PT_LTG.GROUP[g].TYPE[t].NAME,"</dt></dl></h3><div class='content-body'><div class='sub-sec-content'><h3 class='goals-info-hd'><span>patResult</span></h3>");
for(r=0;
r<recordData.DYNAMIC_GROUPS.PT_LTG.GROUP[g].TYPE[t].RESULT_CNT;
r++){ptContentDG.push("<dl class='goals-ltg goals-hide'><dt class='goals-dt'>",recordData.DYNAMIC_GROUPS.PT_LTG.GROUP[g].TYPE[t].RESULT_SET[r].LABEL,"</dt><dd class='goals-info-dd'>",recordData.DYNAMIC_GROUPS.PT_LTG.GROUP[g].TYPE[t].RESULT_SET[r].RESULT,"</dd>");
ptContentDG.push("<dd class='goals-ico-dd'>LTG</dd></dl>");
}}}ptContentDG=ptContentDG.join("");
for(g=0;
g<recordData.DYNAMIC_GROUPS.SLP_STG.GROUP_CNT;
g++){slpContentDG.push("<div class='sub-sec rehab-sec'><h3 class='sub-sec-hd'>","<dl class='goals-info goals-stg'><dt class='goals-dt'>",recordData.DYNAMIC_GROUPS.SLP_STG.GROUP[g].NAME,"</dt></dl></h3><div class='content-body'><div class='sub-sec-content'><h3 class='goals-info-hd'><span>patResult</span></h3>");
for(t=0;
t<recordData.DYNAMIC_GROUPS.SLP_STG.GROUP[g].TYPE_CNT;
t++){slpContentDG.push("<div class='sub-sec rehab-sec'><h3 class='sub-sec-hd'>","<dl class='goals-info goals-stg'><dt class='goals-dt'>&nbsp;&nbsp",recordData.DYNAMIC_GROUPS.SLP_STG.GROUP[g].TYPE[t].NAME,"</dt></dl></h3><div class='content-body'><div class='sub-sec-content'><h3 class='goals-info-hd'><span>patResult</span></h3>");
for(r=0;
r<recordData.DYNAMIC_GROUPS.SLP_STG.GROUP[g].TYPE[t].RESULT_CNT;
r++){slpContentDG.push("<dl class='goals-info goals-stg'><dt class='goals-dt'>",recordData.DYNAMIC_GROUPS.SLP_STG.GROUP[g].TYPE[t].RESULT_SET[r].LABEL,"</dt><dd class='goals-info-dd'>",recordData.DYNAMIC_GROUPS.SLP_STG.GROUP[g].TYPE[t].RESULT_SET[r].RESULT,"</dd>");
slpContentDG.push("<dd class='goals-ico-dd'>STG</dd></dl>");
}}}for(g=0;
g<recordData.DYNAMIC_GROUPS.SLP_LTG.GROUP_CNT;
g++){slpContentDG.push("<div class='sub-sec rehab-sec'><h3 class='sub-sec-hd'>","<dl class='goals-ltg goals-hide'><dt class='goals-dt'>",recordData.DYNAMIC_GROUPS.SLP_LTG.GROUP[g].NAME,"</dt></dl></h3><div class='content-body'><div class='sub-sec-content'><h3 class='goals-info-hd'><span>patResult</span></h3>");
for(t=0;
t<recordData.DYNAMIC_GROUPS.SLP_LTG.GROUP[g].TYPE_CNT;
t++){slpContentDG.push("<div class='sub-sec rehab-sec'><h3 class='sub-sec-hd'>","<dl class='goals-ltg goals-hide'><dt class='goals-dt'>&nbsp;&nbsp",recordData.DYNAMIC_GROUPS.SLP_LTG.GROUP[g].TYPE[t].NAME,"</dt></dl></h3><div class='content-body'><div class='sub-sec-content'><h3 class='goals-info-hd'><span>patResult</span></h3>");
for(r=0;
r<recordData.DYNAMIC_GROUPS.SLP_LTG.GROUP[g].TYPE[t].RESULT_CNT;
r++){slpContentDG.push("<dl class='goals-ltg goals-hide'><dt class='goals-dt'>",recordData.DYNAMIC_GROUPS.SLP_LTG.GROUP[g].TYPE[t].RESULT_SET[r].LABEL,"</dt><dd class='goals-info-dd'>",recordData.DYNAMIC_GROUPS.SLP_LTG.GROUP[g].TYPE[t].RESULT_SET[r].RESULT,"</dd>");
slpContentDG.push("<dd class='goals-ico-dd'>LTG</dd></dl>");
}}}slpContentDG=slpContentDG.join("");
jsGoalsO1HTML.push("<div class='sub-sec rehab-sec'><h3 class='sub-sec-hd'><span class='sub-sec-hd-tgl' title='",patResult,"'>-</span>","<span class='sub-sec-title' id='totNurs",compId,"'>Nursing (",totNurs,")</span></h3><div class='sub-sec-content'><h3 class='goals-info-hd'><span>patResult</span></h3>");
jsGoalsO1HTML.push("<div class ='goals-info-hdr'><dl><dt class ='goals-dt'><span>Filter Nursing Goals by:</span></dt><dd class ='goals-info-dd'><select class='goals-fltr' id='nursgoalfltr",compId,"' onchange='CERN_RehabGoalsO1.fltrNursing(\"",compId,"\");'><option value='both'>Both</option><option selected='yes' value='notmet'>Not Met</option><option value='met'>Met</option></select></dd></dl></div>");
jsGoalsO1HTML.push(nursingContent);
jsGoalsO1HTML.push("</div></div>");
jsGoalsO1HTML.push("<div><dl class ='goals-info-hdr'><dt class ='goals-dt'><span>Filter Therapy Goals by:</span></dt><dd class ='goals-info-dd'><select class='goals-fltr' id='othergoalfltr",compId,"' onchange='CERN_RehabGoalsO1.fltrOther(\"",compId,"\");'><option value='both'>Both</option><option selected='yes' value='stg'>Short-term</option><option value='ltg'>Long-term</option></select></dd></dl></div>");
jsGoalsO1HTML.push("<div class='sub-sec rehab-sec'><h3 class='sub-sec-hd'><span class='sub-sec-hd-tgl' title='",patResult,"'>-</span>","<span class='sub-sec-title' id='totOT",compId,"'>OT</span></h3><div class='content-body'><div class='sub-sec-content'><h3 class='goals-info-hd'><span>patResult</span></h3>");
jsGoalsO1HTML.push(otContent);
jsGoalsO1HTML.push(otContentDG);
jsGoalsO1HTML.push("</div></div></div>");
jsGoalsO1HTML.push("<div class='sub-sec rehab-sec'><h3 class='sub-sec-hd'><span class='sub-sec-hd-tgl' title='",patResult,"'>-</span>","<span class='sub-sec-title' id='totPT",compId,"'>PT</span></h3><div class='content-body'><div class='sub-sec-content'><h3 class='goals-info-hd'><span>patResult</span></h3>");
jsGoalsO1HTML.push(ptContent);
jsGoalsO1HTML.push(ptContentDG);
jsGoalsO1HTML.push("</div></div></div>");
jsGoalsO1HTML.push("<div class='sub-sec rehab-sec'><h3 class='sub-sec-hd'><span class='sub-sec-hd-tgl' title='",patResult,"'>-</span>","<span class='sub-sec-title' id='totSLP",compId,"'>SLP</span></h3><div class='content-body'><div class='sub-sec-content'><h3 class='goals-info-hd'><span>patResult</span></h3>");
jsGoalsO1HTML.push(slpContent);
jsGoalsO1HTML.push(slpContentDG);
jsGoalsO1HTML.push("</div></div></div>");
jsGoalsO1HTML=jsGoalsO1HTML.join("");
MP_Util.Doc.FinalizeComponent(jsGoalsO1HTML,component,"");
totalResultCount=totNurs+totOT+totPT+totSLP+numberOfFixedRows;
if(component.isScrollingEnabled()){if(component.getScrollNumber()<totalResultCount){MP_Util.Doc.InitScrolling(Util.Style.g("reh_goals_scrollable",m_rootComponentNode,"div"),component.getScrollNumber(),"1.6");
}}}catch(err){throw (err);
}finally{}},fltrNursing:function(compId){var nurFilters=_g("nursgoalfltr"+compId);
var nurDiv=_g("nursingGoals"+compId);
var totNur=_g("totNurs"+compId);
var curFilter=nurFilters.options.selectedIndex;
var curVal=nurFilters.options.value;
var nurDL=[];
var cnt=0;
var i;
nurDL=Util.gcs(nurDiv);
switch(curVal){case"both":for(i=nurDL.length;
i--;
){Util.Style.rcss(nurDL[i],"goals-hide");
Util.Style.acss(nurDL[i],"goals-info");
}totNur.innerHTML="Nursing ("+nurDL.length+")";
break;
case"notmet":for(i=nurDL.length;
i--;
){if(nurDL[i].id===("goals-met"+compId)){Util.Style.rcss(nurDL[i],"goals-info");
Util.Style.acss(nurDL[i],"goals-hide");
}else{if(nurDL[i].id===("goals-notmet"+compId)){Util.Style.rcss(nurDL[i],"goals-hide");
Util.Style.acss(nurDL[i],"goals-info");
cnt++;
}}}totNur.innerHTML="Nursing ("+cnt+")";
break;
case"met":for(i=nurDL.length;
i--;
){if(nurDL[i].id===("goals-met"+compId)){Util.Style.rcss(nurDL[i],"goals-hide");
Util.Style.acss(nurDL[i],"goals-info");
cnt++;
}else{if(nurDL[i].id===("goals-notmet"+compId)){Util.Style.rcss(nurDL[i],"goals-info");
Util.Style.acss(nurDL[i],"goals-hide");
}}}totNur.innerHTML="Nursing ("+cnt+")";
break;
}},fltrOther:function(compId){var compContentDiv=_g(compId);
var otherFilters=_g("othergoalfltr"+compId);
var curFilter=otherFilters.options.selectedIndex;
var otGoals=_g("otGoals"+compId);
var ptGoals=_g("ptGoals"+compId);
var slpGoals=_g("slpGoals"+compId);
var curVal=otherFilters.options.value;
var stgDL=Util.Style.g("goals-stg",compContentDiv,"DL");
var ltgDL=Util.Style.g("goals-ltg",compContentDiv,"DL");
var totOT=_g("totOT"+compId);
var totPT=_g("totPT"+compId);
var totSLP=_g("totSLP"+compId);
var i;
var cnt=0;
var otGoalsArr=[];
var ptGoalsArr=[];
var slpGoalsArr=[];
otGoalsArr=otGoals.childNodes;
ptGoalsArr=ptGoals.childNodes;
slpGoalsArr=slpGoals.childNodes;
switch(curVal){case"both":if(stgDL){for(i=stgDL.length;
i--;
){Util.Style.rcss(stgDL[i],"goals-hide");
Util.Style.acss(stgDL[i],"goals-info");
}}if(ltgDL){for(i=ltgDL.length;
i--;
){Util.Style.rcss(ltgDL[i],"goals-hide");
Util.Style.acss(ltgDL[i],"goals-info");
}}break;
case"stg":if(stgDL){for(i=stgDL.length;
i--;
){Util.Style.rcss(stgDL[i],"goals-hide");
Util.Style.acss(stgDL[i],"goals-info");
}}if(ltgDL){for(i=ltgDL.length;
i--;
){Util.Style.rcss(ltgDL[i],"goals-info");
Util.Style.acss(ltgDL[i],"goals-hide");
}}break;
case"ltg":if(stgDL){for(i=stgDL.length;
i--;
){Util.Style.rcss(stgDL[i],"goals-info");
Util.Style.acss(stgDL[i],"goals-hide");
}}if(ltgDL){for(i=ltgDL.length;
i--;
){Util.Style.rcss(ltgDL[i],"goals-hide");
Util.Style.acss(ltgDL[i],"goals-info");
}}break;
}for(i=otGoalsArr.length;
i--;
){if(Util.Style.ccss(otGoalsArr[i],"goals-info")){cnt++;
}}totOT.innerHTML="OT ("+cnt+")";
cnt=0;
for(i=ptGoalsArr.length;
i--;
){if(Util.Style.ccss(ptGoalsArr[i],"goals-info")){cnt++;
}}totPT.innerHTML="PT ("+cnt+")";
cnt=0;
for(i=slpGoalsArr.length;
i--;
){if(Util.Style.ccss(slpGoalsArr[i],"goals-info")){cnt++;
}}totSLP.innerHTML="SLP ("+cnt+")";
cnt=0;
}};
}();
