function CpmPreviewPane(){this.m_id="";
this.m_itemsList=null;
}CpmPreviewPane.prototype.getItemsList=function(){if(!this.m_itemsList){this.m_itemsList=[];
}return this.m_itemsList;
};
function DiagramCPMComponentStyle(){this.initByNamespace("diagCPM");
}DiagramCPMComponentStyle.prototype=new ComponentStyle();
DiagramCPMComponentStyle.prototype.constructor=ComponentStyle;
function DiagramCPMComponent(criterion){this.loadTimer=new RTMSTimer("USR:MPG.IMAGE.CPM - load component");
this.renderTimer=new RTMSTimer("ENG:MPG.IMAGE.CPM - render component");
this.setCriterion(criterion);
this.setStyles(new DiagramCPMComponentStyle());
this.setScope(1);
this.m_diagramName="";
this.m_diagramList=null;
this.setConceptGroupMeanings(["REFIMAGE","DIAGRAM"]);
}DiagramCPMComponent.prototype=new MPageComponent();
DiagramCPMComponent.prototype.constructor=DiagramCPMComponent;
CPMMPageComponent.attachMethods(DiagramCPMComponent);
DiagramCPMComponent.CSS_MAPPINGS={DIABETES_THUMB:"diagram-cpm-diabetes-thumb",DIABETES_FULL:"diagram-cpm-diabetes-full",DIABETES_URL:"diabetes_diagram.png"};
DiagramCPMComponent.prototype.getRefUrls=function(){if(!this.m_refUrls){this.m_refUrls=[];
}return this.m_refUrls;
};
DiagramCPMComponent.prototype.getDiagramList=function(){if(!this.m_diagramList){this.m_diagramList=[];
}return this.m_diagramList;
};
DiagramCPMComponent.prototype.setDiagramList=function(list){this.m_diagramList=list;
};
DiagramCPMComponent.prototype.getLoadTimer=function(){return this.loadTimer;
};
DiagramCPMComponent.prototype.getRenderTimer=function(){return this.renderTimer;
};
DiagramCPMComponent.prototype.processComponentConfig=function(componentConfig,conceptGroupConfig){try{this.loadTimer.start();
CPMMPageComponent.prototype.processComponentConfig.call(this,componentConfig,conceptGroupConfig);
if((!componentConfig||!componentConfig.length)&&(!conceptGroupConfig||!conceptGroupConfig.length)){return;
}var detail=null;
var cLen;
var i;
var diagramList=this.getDiagramList();
var diagram={};
if(componentConfig&&componentConfig.length){cLen=componentConfig.length;
for(i=0;
i<cLen;
i++){detail=componentConfig[i];
if(detail.DETAIL_RELTN_CD_MEAN==="DIAGRAM"){this.m_diagramName=detail.ENTITY_NAME;
}if(detail.DETAIL_RELTN_CD_MEAN==="REFIMAGE"){diagram.TITLE=detail.ENTITY_IDENT;
diagram.URL=detail.ENTITY_TEXT;
diagramList.push(diagram);
}}}if(conceptGroupConfig&&conceptGroupConfig.length){cLen=conceptGroupConfig.length;
for(i=0;
i<cLen;
i++){if(conceptGroupConfig[i].CONCEPT_GROUP_CD_MEAN=="DIAGRAM"||conceptGroupConfig[i].CONCEPT_GROUP_CD_MEAN=="REFIMAGE"){var detailList=conceptGroupConfig[i].CG_DTL_LIST;
for(var x=0,xl=detailList.length;
x<xl;
x++){detail=detailList[x];
diagram={};
diagram.TITLE=detail.CONCEPT_ENTITY_IDENT;
diagram.URL=detail.CONCEPT_ENTITY_TEXT;
diagramList.push(diagram);
}}}}}catch(err){this.loadTimer.fail();
}finally{this.loadTimer.stop();
}};
DiagramCPMComponent.prototype.populateDiagramMenu=function(){try{this.renderTimer.start();
var diagConceptCd=this.getConceptCd();
var diagramMenuItem="cpmTabDiagramsMenu"+diagConceptCd;
var concept=this.m_diagramName;
var diagramList=this.getDiagramList();
var dLen=diagramList.length;
var i;
var url=this.getCustomContentLocation();
url+="img/"+DiagramCPMComponent.CSS_MAPPINGS[concept+"_URL"];
if(diagramList&&dLen>0){MP_MenuManager.getMenuObject(diagramMenuItem).setIsDisabled(false);
MP_MenuManager.getMenuObject(diagramMenuItem).setTypeClass("");
$("#chxTabsMenu"+diagConceptCd).removeClass("cpm-tab-menu-inactive").addClass("cpm-tab-menu-active");
$("#chxTabsMenu"+diagConceptCd).unbind("click").click(function(){if(MP_MenuManager.getMenuObject("cpmTabMenu"+diagConceptCd).isActive()){MP_MenuManager.closeMenuStack(true);
}else{MP_MenuManager.showMenu("cpmTabMenu"+diagConceptCd);
}});
}for(i=0;
i<dLen;
i++){var diagram=diagramList[i];
var menuItem=new MenuSelection("diagramsMenuSelection_"+i);
menuItem.setCloseOnClick(true);
menuItem.setLabel(diagram.TITLE);
menuItem.setIsDisabled(false);
menuItem.setClickFunction(function(selectedDiagram){return function(){window.open(selectedDiagram.URL,"_blank","");
};
}(diagram));
MP_MenuManager.getMenuObject(diagramMenuItem).addMenuItem(menuItem);
}}catch(err){this.renderTimer.fail();
}finally{this.renderTimer.stop();
}};
DiagramCPMComponent.prototype.retrieveComponentData=function(){this.renderComponent();
};
DiagramCPMComponent.prototype.renderComponent=function(){var diagramList=this.getDiagramList();
var diagram,html="",x,y;
for(x=0,y=diagramList.length;
x<y;
x++){diagram=diagramList[x];
if(diagram.hasOwnProperty("URL")){if(diagram.URL.indexOf(".pdf")>-1){html+="<div class='diag-cpm-container'><object class='diag-cpm-contents' type='application/pdf' data='"+diagram.URL+"' /></div>";
}else{if(diagram.URL.indexOf(".png")>-1||diagram.URL.indexOf(".jpg")>-1||diagram.URL.indexOf(".gif")>-1){html+="<div class='diag-cpm-thumb-cont'><a href='"+diagram.URL+"' target='_blank'><img class='diag-cpm-img' src='"+diagram.URL+"' title='"+diagram.TITLE+"' /></a></div>";
}else{html+="<div class='diag-cpm-container'><iframe class='diag-cpm-contents' src='"+diagram.URL+"'></iframe></div>";
}}}}this.finalizeComponent(html,"");
};
CPMController.prototype.addComponentMapping("DIAGRAM",DiagramCPMComponent);
MP_Util.setObjectDefinitionMapping("PW_DIAGRAM_PARAM",DiagramCPMComponent);
