var g_MediaGadgetXMLHttpRequestObj=new XMLHttpRequest();
function MediaGalleryComponentStyle(){this.initByNamespace("mmfgal-o1");
}MediaGalleryComponentStyle.inherits(ComponentStyle);
function MediaGalleryComponent(criterion){this.m_baseServiceURL="";
this.m_sURLParams="";
this.m_mediaStash=null;
this.m_personId=0;
this.m_viewableImageIds=[];
this.setCriterion(criterion);
this.setLookBackDropDown(true);
this.setStyles(new MediaGalleryComponentStyle());
this.clearTimeoutCount=750;
this.activelyHovering=false;
this.docTimeout=null;
this.m_MediaViewerURL="";
this.m_menuGroupBy=0;
this.m_docData=[];
this.m_contentTypeFilterList=[];
this.rootNode$={};
this.setComponentLoadTimerName("USR:MPG.MMF.GALLERY.01 _ load component");
this.setComponentRenderTimerName("ENG:MPG.MMF.GALLERY.01 _ render component");
this.setIncludeLineNumber(true);
MediaGalleryComponent.method("openTab",function(){var criterion=this.getCriterion();
var sParms="/PERSONID="+criterion.person_id+" /ENCNTRID="+criterion.encntr_id+" /FIRSTTAB=^"+this.getLink()+"+^";
APPLINK(0,criterion.executable,sParms);
});
MediaGalleryComponent.method("getPrefJson",function(){var json={GROUP_BY_PREF:this.m_menuGroupBy};
return json;
});
this.mediaGalleryo1PrefObj={MEDIA_GALLERY_PREFS:{}};
}MediaGalleryComponent.prototype=new MPageComponent();
MediaGalleryComponent.prototype.constructor=MPageComponent;
MediaGalleryComponent.inherits(MPageComponent);
MediaGalleryComponent.prototype.getPreferencesObj=function(){return MPageComponent.prototype.getPreferencesObj.call(this,null);
};
MediaGalleryComponent.prototype.setURLParams=function(sURLParams){this.m_sURLParams=sURLParams;
};
MediaGalleryComponent.prototype.getURLParams=function(){return this.m_sURLParams;
};
MediaGalleryComponent.prototype.getBaseURL=function(){return this.m_baseServiceURL;
};
MediaGalleryComponent.prototype.setMediaStash=function(media){this.m_mediaStash=media;
};
MediaGalleryComponent.prototype.getMediaStash=function(){return this.m_mediaStash;
};
MediaGalleryComponent.prototype.setPersonId=function(personId){this.m_personId=personId;
};
MediaGalleryComponent.prototype.getPersonId=function(){return this.m_personId;
};
MediaGalleryComponent.prototype.imageRecord=function(imageId,description,serviceDate,contentType,imageURL,mimeType,groupId){return{imageId:imageId,description:description,serviceDate:serviceDate,contentType:contentType,imageURL:imageURL,mimeType:mimeType,groupId:groupId};
};
MediaGalleryComponent.prototype.setContentTypes=function(contentTypes){this.m_contentTypes=contentTypes;
};
MediaGalleryComponent.prototype.getContentTypes=function(){return this.m_contentTypes;
};
MediaGalleryComponent.prototype.setContentTypeFilterList=function(contentTypeFilterList){this.m_contentTypeFilterList=contentTypeFilterList;
};
MediaGalleryComponent.prototype.getContentTypeFilterList=function(){return this.m_contentTypeFilterList;
};
MediaGalleryComponent.prototype.loadFilterMappings=function(){this.addFilterMappingObject("MG_CONTENT_TYPE",{setFunction:this.setContentTypes,type:"ARRAY",field:"PARENT_ENTITY_ID"});
};
MediaGalleryComponent.prototype.retrieveComponentData=function(){var criterion=this.getCriterion();
var sendAr=null;
this.setPersonId(criterion.person_id);
var searchScope=this.getScope();
var lookBackUnits=this.getLookbackUnits();
var lookBackUnitType=this.getLookbackUnitTypeFlag();
var sUrlParam="";
if(searchScope==1){sUrlParam="media?personId="+criterion.person_id;
}else{sUrlParam="media?encounterId="+criterion.encntr_id;
}if(lookBackUnits>0){var searchDate=new Date();
switch(lookBackUnitType){case 1:searchDate.setHours(searchDate.getHours()-lookBackUnits);
break;
case 2:searchDate.setDate(searchDate.getDate()-lookBackUnits);
break;
case 3:searchDate.setDate(searchDate.getDate()-lookBackUnits*7);
break;
case 4:searchDate.setMonth(searchDate.getMonth()-lookBackUnits);
break;
case 5:searchDate.setFullYear(searchDate.getFullYear()-lookBackUnits);
break;
}var sUrlDateParam="&beginDate="+Math.round(searchDate.getTime()/1000);
sUrlParam=sUrlParam+sUrlDateParam;
}this.setURLParams(sUrlParam);
sendAr=["^MINE^",criterion.person_id+".0",MP_Util.CreateParamArray(this.getContentTypes(),1)];
MP_Core.XMLCclRequestWrapper(this,"MP_MEDIA_GALLERY",sendAr,true);
};
MediaGalleryComponent.prototype.doSelect=function(compId){var tmp=this;
if(tmp.getAttribute("class")=="mmf-thumb mmf-selected"){tmp.setAttribute("class","mmf-thumb");
if($(".mmf-thumb.mmf-selected").length===0){MediaGalleryComponent.prototype.disableActions.apply(this,[compId]);
}}else{tmp.setAttribute("class","mmf-thumb mmf-selected");
MediaGalleryComponent.prototype.enableActions.apply(this,[compId]);
}};
MediaGalleryComponent.prototype.launchMediaViewer=function(viewerURL,subTimerName,imageId){var mmfI18n=i18n.discernabu.mediaGallery_o1;
var viewMediaAuthenticated=false;
var slaTimer=MP_Util.CreateTimer("CAP:MPG_Media_Gallery_o1_Launch_Media_Viewer");
if(slaTimer){slaTimer.SubtimerName=subTimerName;
slaTimer.Stop();
}if(typeof(imageId)!=="undefined"){viewerURL=viewerURL+imageId;
}else{$(".mmf-thumb.mmf-selected").each(function(i,obj){viewerURL=viewerURL+"&identifier={"+obj.getAttribute("id")+"}";
});
}try{g_MediaGadgetXMLHttpRequestObj.open("GET",viewerURL,false);
window.location="javascript:MPAGES_SVC_AUTH(g_MediaGadgetXMLHttpRequestObj)";
g_MediaGadgetXMLHttpRequestObj.send();
if(g_MediaGadgetXMLHttpRequestObj.status==200){viewMediaAuthenticated=true;
}else{MP_Util.LogInfo("mediagallery-o1.js: launchMediaViewer: Failed to get Media Viewer Authenticated:"+g_MediaGadgetXMLHttpRequestObj.status);
}}catch(err){MP_Util.LogJSError(this,err,"mediagallery-o1.js","launchMediaViewer");
throw (err);
}if(viewMediaAuthenticated===true){var modalId="MediaGalleryComponent";
var mDialog=new ModalDialog(modalId);
mDialog.setHeaderCloseFunction(function(){MP_ModalDialog.closeModalDialog(modalId);
MP_ModalDialog.deleteModalDialogObject(modalId);
});
mDialog.setBodyDataFunction(function(modalObj){modalObj.setBodyHTML('<iframe class="mmf-media-viewer-modal-dialog" src="'+viewerURL+'" ></iframe>');
});
mDialog.setHeaderTitle(mmfI18n.MEDIA_VIEWER);
MP_ModalDialog.addModalDialogObject(mDialog);
MP_ModalDialog.showModalDialog(modalId);
}};
MediaGalleryComponent.prototype.clearMediaSelection=function(compId){$(".mmf-thumb.mmf-selected").removeClass("mmf-selected");
MediaGalleryComponent.prototype.disableActions.apply(this,[compId]);
};
MediaGalleryComponent.prototype.findImages=function(){var patientImages=[];
var imageObject=null;
var tempMedia=this.getMediaStash();
var imageIdList=[];
if(tempMedia){try{for(var i=0;
i<tempMedia.length;
i++){var obj=tempMedia[i];
if(typeof obj.name==="undefined"){obj.name="";
}if(typeof obj.contentTypeDisplay==="undefined"){obj.contentTypeDisplay="";
}if(this.m_menuGroupBy===0){if((obj.groupIdentifier&&obj.groupIdentifier!==obj.identifier)||(obj.groupIdentifier===undefined)){imageObject=this.imageRecord(obj.identifier,obj.name,obj.serviceDate,obj.contentTypeDisplay,this.getBaseURL()+"thumbnail/"+obj.identifier+"?size=4&generic=1",obj.mimeType,obj.groupIdentifier);
patientImages.push(imageObject);
imageIdList.push('"'+obj.identifier+'"');
}}else{imageObject=this.imageRecord(obj.identifier,obj.name,obj.serviceDate,obj.contentTypeDisplay,this.getBaseURL()+"thumbnail/"+obj.identifier+"?size=4&generic=1",obj.mimeType,obj.groupIdentifier);
patientImages.push(imageObject);
imageIdList.push('"'+obj.identifier+'"');
}}}catch(err){throw (err);
}}this.m_viewableImageIds=imageIdList;
return patientImages;
};
MediaGalleryComponent.prototype.imageGroup=function(displayImages){var component=this;
var sImageGrpListHTML=[];
var ordArray=[];
function imageDateSorter(a,b){var aDate=a.serviceDate;
var bDate=b.serviceDate;
if(aDate>bDate){return 1;
}else{if(aDate<bDate){return -1;
}else{return 0;
}}}function imageContentTypeSorter(a,b){var aContentTypeDisplay=a.contentType.toUpperCase();
var bContentTypeDisplay=b.contentType.toUpperCase();
if(aContentTypeDisplay>bContentTypeDisplay){return 1;
}else{if(aContentTypeDisplay<bContentTypeDisplay){return -1;
}else{return 0;
}}}function imageDescriptionSorter(a,b){var aName=a.description.toUpperCase();
var bName=b.description.toUpperCase();
if(aName>bName){return 1;
}else{if(aName<bName){return -1;
}else{return 0;
}}}function imageGroupIdSorter(a,b){var aGroupIdentifier=a.groupId;
var bGroupIdentifier=b.groupId;
if(aGroupIdentifier>bGroupIdentifier){return 1;
}else{if(aGroupIdentifier<bGroupIdentifier){return -1;
}else{return 0;
}}}function generateHTMLdisplayImage(tempImage){var ImageId=tempImage.imageId;
var imageIdStr=ImageId.substring(1,ImageId.length-1);
var sImageListHTML=[];
var mmfI18n=i18n.discernabu.mediaGallery_o1;
var serviceDateObj=new Date(tempImage.serviceDate*1000);
var sServiceDate=serviceDateObj.toLocaleDateString();
var sServiceTime=serviceDateObj.toLocaleTimeString();
sImageListHTML.push("<div class='mmf-image' image-name = \"",tempImage.description,'">');
sImageListHTML.push("<div class='mmf-imgContain'>");
sImageListHTML.push('<dl class ="mmfgal-o1-info result-info">');
sImageListHTML.push("<img class='mmf-thumb' id=",imageIdStr," alt= '",tempImage.description,"' src= '",tempImage.imageURL,"'/>");
sImageListHTML.push("<div class='mmf-iconHolder'></div>");
sImageListHTML.push("</dl>");
sImageListHTML.push("<h4 class='det-hd'>media detail hover</h4>");
sImageListHTML.push('<div class="hvr">');
sImageListHTML.push('<dl class="mmf-det"><dt><span>',mmfI18n.CONTENT_TYPE,":</span></dt><dd><span>",tempImage.contentType,"</span></dd><dt><span>",mmfI18n.NAME,":</span></dt><dd><span>",tempImage.description,"</span></dd><dt><span>",mmfI18n.SERVICE_DATE_TIME,":</span></dt><dd><span>",sServiceDate,"&nbsp;",sServiceTime,"</span></dd></dl>");
sImageListHTML.push("</div>");
sImageListHTML.push("</div>");
if(tempImage.description){sImageListHTML.push("<div class='mmf-media-name' ><span><span class='mmf-imageLaunchViewer' name='&identifier=",tempImage.imageId,"' title=\"",tempImage.description,'" >',tempImage.description,"</span></span></div>");
}else{sImageListHTML.push("<div class='mmf-media-name'><span><span class='mmf-imageLaunchViewer' name='&identifier=",tempImage.imageId,"' >[",mmfI18n.VIEW,"]</span></span></div>");
}sImageListHTML.push("</div>");
return sImageListHTML;
}function displayDateGroup(imagesGroup){var i=0;
var imageDateObj=new Date(imagesGroup[i].serviceDate*1000);
var sHyperLinkGroupId="";
var sSectionHeaderHTML=[];
var sImageListHTML=[];
var options={weekday:"short",year:"numeric",month:"short",day:"numeric"};
var imageDate=imageDateObj.toLocaleDateString(options);
for(i=0;
i<imagesGroup.length;
i++){var tempImage=imagesGroup[i];
sHyperLinkGroupId=sHyperLinkGroupId+"&identifier="+tempImage.imageId;
var sImageHTML=generateHTMLdisplayImage(tempImage);
sImageListHTML.push(sImageHTML.join(""));
}sSectionHeaderHTML.push("<div class='sub-sec'><h3 class='sub-sec-hd'><span class='sub-sec-hd-tgl' title='","Collapse","'>-</span><span class='mmf-dateLinkLaunchViewer' name='",sHyperLinkGroupId,"'><span class='sub-sec-title'><span class = 'mmf-grp-hdr'>",imageDate,"</span> (<span class = 'mmf-grp-cnt'>",imagesGroup.length,"</span>)","</span></span></h3>","<div class='sub-sec-content'>");
ordArray.push(sSectionHeaderHTML.join(""));
ordArray.push(sImageListHTML.join(""));
ordArray.push("</div></div>");
}function displaySubGroup(imagesGroup){var i=0;
var sHyperLinkGroupId="&identifier="+imagesGroup[0].groupId;
var sImageListHTML=[];
for(i=0;
i<imagesGroup.length;
i++){var tempImage=imagesGroup[i];
var arrayHTML=generateHTMLdisplayImage(tempImage);
sImageListHTML.push(arrayHTML.join(""));
}var arrayHTMLandLink=[];
arrayHTMLandLink.push(sImageListHTML,sHyperLinkGroupId);
return arrayHTMLandLink;
}function displayContentTypeGroup(imagesGroup,imagesInSubGroups){var i=0;
var imageDateObj=new Date(imagesGroup[i].serviceDate*1000);
var sHyperLinkGroupId="";
var sSectionHeaderHTML=[];
var sImageListHTML=[];
var imgCnt=0;
var sContentTypeDisplay=imagesGroup[0].contentType;
var mmfI18n=i18n.discernabu.mediaGallery_o1;
for(i=0;
i<imagesGroup.length;
i++){var tempImage=imagesGroup[i];
if(tempImage.groupId===undefined){sHyperLinkGroupId=sHyperLinkGroupId+"&identifier="+tempImage.imageId;
var arrayHTMLandLink=generateHTMLdisplayImage(tempImage);
sImageListHTML.push(arrayHTMLandLink.join(""));
imgCnt=imgCnt+1;
}else{var groupId=tempImage.groupId;
var groupIdStr=groupId.substring(1,groupId.length-1);
var sGroupHeaderHTML=[];
var subGroupLen=0;
var arrayHTMLandLink=[];
var sSubGroupHyperLinkId="";
var serviceDateObj=new Date(tempImage.serviceDate*1000);
var sServiceDate=serviceDateObj.toLocaleDateString();
var sServiceTime=serviceDateObj.toLocaleTimeString();
for(var idx=0;
idx<imagesInSubGroups.length;
idx++){var imgInSubGroup=[];
imgInSubGroup=imagesInSubGroups[idx];
if(groupId===imgInSubGroup[0].groupId){subGroupLen=imgInSubGroup.length;
arrayHTMLandLink=displaySubGroup(imgInSubGroup);
imgCnt=imgCnt+subGroupLen;
break;
}}if(arrayHTMLandLink.length>0){sSubGroupHyperLinkId=arrayHTMLandLink[1];
sHyperLinkGroupId=sHyperLinkGroupId+sSubGroupHyperLinkId;
}sGroupHeaderHTML.push("<div class='sub-sec  mmf-group'>");
sGroupHeaderHTML.push("<dl class ='mmfgal-o1-info result-info'>");
sGroupHeaderHTML.push("<h3 class='sub-sec-hd'><span class='sub-sec-hd-tgl' title='","Collapse","'>-</span><span class='mmf-dateLinkLaunchViewer' name='",sSubGroupHyperLinkId,"'><span class='sub-sec-title'><span class = 'mmf-grp-hdr'>",tempImage.description,"</span> (<span class = 'mmf-grp-cnt'>",subGroupLen,"</span>)","</span></span></h3>");
sGroupHeaderHTML.push("</dl>");
sGroupHeaderHTML.push("<h4 class='det-hd'>group detail hover</h4>");
sGroupHeaderHTML.push('<div class="hvr">');
sGroupHeaderHTML.push('<dl class="mmf-det"><dt><span>',mmfI18n.CONTENT_TYPE,":</span></dt><dd><span>",tempImage.contentType,"</span></dd><dt><span>",mmfI18n.NAME,":</span></dt><dd><span>",tempImage.description,"</span></dd><dt><span>",mmfI18n.SERVICE_DATE_TIME,":</span></dt><dd><span>",sServiceDate,"&nbsp;",sServiceTime,"</span></dd></dl>");
sGroupHeaderHTML.push("</div>");
sGroupHeaderHTML.push("<div class='sub-sec-content' id ='",groupIdStr,"'>");
sImageListHTML.push(sGroupHeaderHTML.join(""));
if(arrayHTMLandLink.length>0){sImageListHTML.push(arrayHTMLandLink[0].join(""));
}sImageListHTML.push("</div></div>");
}}sSectionHeaderHTML.push("<div class='sub-sec'><h3 class='sub-sec-hd'><span class='sub-sec-hd-tgl' title='","Collapse","'>-</span><span class='mmf-dateLinkLaunchViewer' name='",sHyperLinkGroupId,"'><span class='sub-sec-title'><span class = 'mmf-grp-hdr'>",sContentTypeDisplay,"</span> (<span class = 'mmf-grp-cnt'>",imgCnt,"</span>)","</span></span></h3>","<div class='sub-sec-content'>");
ordArray.push(sSectionHeaderHTML.join(""));
ordArray.push(sImageListHTML.join(""));
ordArray.push("</div></div>");
}function groupByContentType(displayImages){var i=0;
var imgGrouping=[];
var imgContentTypeDisplay="";
var arryImgSubGrouping=[];
while(i<displayImages.length){imgContentTypeDisplay=displayImages[i].contentType;
for(i=i;
i<displayImages.length;
i++){var tempImage=displayImages[i];
var sCompContentTypeDisplay=tempImage.contentType;
if(imgContentTypeDisplay!=sCompContentTypeDisplay){break;
}imgGrouping.push(tempImage);
}var contentTypleList=[];
var imgObj=null;
var groupList=[];
for(var idx=0;
idx<imgGrouping.length;
idx++){imgObj=imgGrouping[idx];
if((imgObj.groupId&&imgObj.groupId===imgObj.imageId)||(imgObj.groupId===undefined)){contentTypleList.push(imgObj);
}else{groupList.push(imgObj);
}}contentTypleList.sort(imageDescriptionSorter);
if(groupList.length>1){groupList.sort(imageGroupIdSorter);
arryImgSubGrouping=groupBySubGroup(groupList);
}else{if(groupList.length===1){arryImgSubGrouping.push(groupList);
}}displayContentTypeGroup(contentTypleList,arryImgSubGrouping);
imgGrouping.length=0;
}}function groupBySubGroup(groupList){var i=0;
var arryImgSubGrouping=[];
var groupListLen=groupList.length;
if(groupListLen>1){while(i<groupListLen){var imgSubGrouping=[];
var groupId=groupList[i].groupId;
for(i=i;
i<groupListLen;
i++){var tempImage=groupList[i];
if(groupId!=tempImage.groupId){break;
}imgSubGrouping.push(tempImage);
}if(imgSubGrouping.length>1){imgSubGrouping.sort(imageDescriptionSorter);
}arryImgSubGrouping.push(imgSubGrouping);
}}return arryImgSubGrouping;
}if(component.m_menuGroupBy===0){displayImages.sort(imageDateSorter);
var i=displayImages.length-1;
var imageDateObj=null;
var imageDate="";
var imgGrouping=[];
while(i>-1){imageDateObj=new Date(displayImages[i].serviceDate*1000);
imageDate=imageDateObj.toLocaleDateString();
for(i=i;
i>=0;
i--){var tempImage=displayImages[i];
var compDate=new Date(tempImage.serviceDate*1000);
var sCompDate=compDate.toLocaleDateString();
if(imageDate!=sCompDate){break;
}imgGrouping.push(tempImage);
}displayDateGroup(imgGrouping);
imgGrouping.length=0;
}}else{displayImages.sort(imageContentTypeSorter);
groupByContentType(displayImages);
}return ordArray;
};
MediaGalleryComponent.prototype.enableActions=function(compId){_g("mgViewBtn"+compId).disabled=false;
_g("mgClearBtn"+compId).disabled=false;
};
MediaGalleryComponent.prototype.disableActions=function(compId){_g("mgViewBtn"+compId).disabled=true;
_g("mgClearBtn"+compId).disabled=true;
};
MediaGalleryComponent.prototype.getCAMMURL=function(url){var CAMM_URL="";
try{g_MediaGadgetXMLHttpRequestObj.open("GET",url,false);
window.location="javascript:MPAGES_SVC_AUTH(g_MediaGadgetXMLHttpRequestObj)";
g_MediaGadgetXMLHttpRequestObj.send();
if(g_MediaGadgetXMLHttpRequestObj.status==200){var Links=JSON.parse(g_MediaGadgetXMLHttpRequestObj.responseText);
CAMM_URL=Links.link;
MP_Util.LogInfo("MMF Media Gallery :getCAMMURL: "+CAMM_URL);
}else{MP_Util.LogInfo("mediagallery-o1.js: getCAMMURL: Failed to retrieve the CAMM URL from Service Directory:"+g_MediaGadgetXMLHttpRequestObj.status);
}}catch(err){MP_Util.LogJSError(this,err,"mediagallery-o1.js","getCAMMURL");
throw (err);
}return(CAMM_URL);
};
MediaGalleryComponent.prototype.retrieveMedia=function(url){MP_Util.LogInfo("MMF Media Gallery:retrieveMedia:URL:"+url);
if(g_MediaGadgetXMLHttpRequestObj){try{g_MediaGadgetXMLHttpRequestObj.open("GET",url,false);
window.location="javascript:MPAGES_SVC_AUTH(g_MediaGadgetXMLHttpRequestObj)";
g_MediaGadgetXMLHttpRequestObj.send();
}catch(err){MP_Util.LogJSError(this,err,"mediagallery-o1.js","retrieveMedia");
throw (err);
}if(g_MediaGadgetXMLHttpRequestObj.status==200){var vartest=g_MediaGadgetXMLHttpRequestObj.responseText;
try{this.setMediaStash(JSON.parse(vartest));
MP_Util.LogInfo("MMF Media Gallery:retrieveMedia:responseText:"+vartest);
}catch(err){MP_Util.LogJSError(this,err,"mediagallery-o1.js","retrieveMedia");
throw (err);
}}else{var errMgs="RetrieveMedia returned unsuccessful status: "+g_MediaGadgetXMLHttpRequestObj.status;
MP_Util.LogError(errMgs);
throw errMgs;
}}};
MediaGalleryComponent.prototype.renderComponent=function(recordData){var compId=this.getComponentId();
var countText="";
var imageSum=0;
var ordArray=[];
var SERVICE_DIR_KEY="/keys/urn:cerner:api:mmf-camm-mpage-app-service-1.0.json";
var mmfI18n=i18n.discernabu.mediaGallery_o1;
var catName=this.getCriterion().category_mean;
var component=this;
var contentTypeKeys=[];
this.rootNode$=$(component.getRootComponentNode());
try{var url=recordData.SERVICE_DIRECTORY_URL+SERVICE_DIR_KEY;
var CAMMURL=this.getCAMMURL(url);
this.m_baseServiceURL=CAMMURL;
this.setMenuShowRelatedDocsInd(0);
this.m_MediaViewerURL=recordData.URL;
this.setContentTypeFilterList(recordData.CONTENT_TYPES);
var contentTypeFilterList=this.getContentTypeFilterList();
var contentTypeListLen=contentTypeFilterList.length;
if(contentTypeListLen>0){for(var idx=0;
idx<contentTypeListLen;
idx++){var filterObj=contentTypeFilterList[idx];
contentTypeKeys.push(filterObj.CONTENT_TYPE_KEY);
}contentTypeKeys.toString();
}if(CAMMURL){var sParams=this.getURLParams();
if(contentTypeKeys.length>0){sParams=sParams+"&contentType="+contentTypeKeys;
}this.retrieveMedia(CAMMURL+sParams);
}var savedUserPrefs=this.getPreferencesObj();
if(savedUserPrefs!==null&&savedUserPrefs.media_gallery_prefs!==null){this.m_menuGroupBy=savedUserPrefs.media_gallery_prefs.GROUP_BY_PREF;
}if(recordData.CONTENT_TYPES.length>0){this.displayFilterApplied();
}this.displayBodyContent();
this.addComponentMenu();
if(this.m_menuGroupBy===1){var menuGroupByContentType=$("#mnuMediaGalleryo1GroupByContentType"+compId);
var menuGroupByContentTypeHtml=menuGroupByContentType.html();
menuGroupByContentTypeHtml=menuGroupByContentTypeHtml+"<span class='mmf-opt-mnu-grp-by-content-type'></span>";
menuGroupByContentType.html(menuGroupByContentTypeHtml);
}}catch(err){MP_Util.LogJSError(this,err,"mediagallery-o1.js","renderComponent");
throw (err);
}};
MediaGalleryComponent.prototype.displayBodyContent=function(){var compId=this.getComponentId();
var countText="";
var imageSum=0;
var ordArray=[];
var mmfI18n=i18n.discernabu.mediaGallery_o1;
var component=this;
var imageListing=[];
var imageListingLen=0;
ordArray.push("<div class='mmf-viewselection-row' id='mgbuttonViewRow",compId,"'><div class= 'mmf-btn-section'><button class='mmf-viewselection-btn' id='mgViewBtn",compId,"' disabled='true' title='",mmfI18n.VIEW_SELECTION,"'>",mmfI18n.VIEW_SELECTION,"</button>","<button class='mmf-clear-selection-btn' id='mgClearBtn",compId,"' disabled='true' title='",mmfI18n.CLEAR_SELECTION,"'>",mmfI18n.CLEAR_SELECTION,"</button>",'</div><div class = "mmf-search-section"><div class="mmf-search-box">',MP_Util.CreateAutoSuggestBoxHtml(this),"</div></div>");
if(this.getMediaStash()!==null){imageListing=this.findImages();
imageListingLen=imageListing.length;
}if(imageListingLen===0){ordArray.push("<div class='mmf-content-body'> ");
ordArray.push("<div><span class = 'res-none'>",mmfI18n.NO_RESULTS_FOUND,"</span></div>");
}else{var nBedrockScrollNumber=this.getScrollNumber();
var sMaxHeight="";
if(nBedrockScrollNumber>0){nBedrockScrollNumber=(nBedrockScrollNumber*100)+150;
sMaxHeight=nBedrockScrollNumber+"px";
}if(nBedrockScrollNumber===0){ordArray.push("<div class='mmf-content-body'> ");
}else{ordArray.push("<div class='mmf-content-body' style = 'max-height: ",sMaxHeight," ; overflow-y: auto;'> ");
}for(var i=0;
i<imageListingLen;
i++){var obj=imageListing[i];
if((obj.groupId&&obj.groupId!==obj.imageId)||(obj.groupId===undefined)){imageSum=imageSum+1;
}}var imgGrpHTML=this.imageGroup(imageListing);
ordArray.push(imgGrpHTML.join(""));
}ordArray.push("</div>");
countText=MP_Util.CreateTitleText(this,imageSum);
this.applyTemplate("list-as-table");
MP_Util.Doc.FinalizeComponent(ordArray.join(""),this,countText);
this.rootNode$.off("click",".mmf-thumb");
this.rootNode$.on("click",".mmf-thumb",function(){MediaGalleryComponent.prototype.doSelect.apply(this,[compId]);
});
var name=this.getCriterion().category_mean;
this.rootNode$.off("click",".mmf-viewselection-btn");
this.rootNode$.on("click",".mmf-viewselection-btn",function(){MediaGalleryComponent.prototype.launchMediaViewer.apply(this,[component.m_MediaViewerURL,name]);
});
this.rootNode$.off("click",".mmf-clear-selection-btn");
this.rootNode$.on("click",".mmf-clear-selection-btn",function(){MediaGalleryComponent.prototype.clearMediaSelection.apply(this,[compId]);
});
var searchBox=_g(this.getStyles().getNameSpace()+"ContentCtrl"+compId);
var searchBoxTimeOut=0;
searchBox.value=mmfI18n.SEARCH;
searchBox.className+=" placeholder";
searchBox.onkeyup=function(event){var textBox=this;
event=event||window.event;
var iKeyCode=event.keyCode;
clearTimeout(searchBoxTimeOut);
searchBoxTimeOut=setTimeout(function(){if(iKeyCode===8||iKeyCode===46){component.searchImages(event,textBox,component);
}else{if(iKeyCode<32||(iKeyCode>=33&&iKeyCode<46)||(iKeyCode>=112&&iKeyCode<=123)){}else{component.searchImages(event,textBox,component);
}}},500);
};
searchBox.onblur=function(event){if(this.value===""){this.value=mmfI18n.SEARCH;
$(this).addClass("placeholder");
}};
searchBox.onfocus=function(event){if(this.value===mmfI18n.SEARCH){this.value="";
$(this).removeClass("placeholder");
}};
CERN_EventListener.fireEvent(this,this,EventListener.EVENT_COUNT_UPDATE,{count:imageSum});
};
MediaGalleryComponent.prototype.searchImages=function(callback,textBox,component){var searchString=textBox.value.toUpperCase();
var rootNode=component.getRootComponentNode();
var imageMainNode=$(rootNode).find(".mmf-content-body").children();
var imageCnt=-1;
var hiddenImageCnt=-1;
var subGrpImageCnt=-1;
var subGrpHiddenImageCnt=-1;
var subfolderSearchMatch=false;
var headerText="";
var imageName="";
$(imageMainNode).each(function(index,item){imageCnt=$(item).find(".mmf-image").length;
$(item).find(".mmf-image").each(function(imgIndex,imgNode){var imageName=$(imgNode).attr("image-name").toUpperCase();
if(imageName.indexOf(searchString)==-1){$(imgNode).addClass("mmf-force-hidden");
}else{$(imgNode).removeClass("mmf-force-hidden");
}});
$(item).find(".mmf-group").each(function(imgIndex,subNode){headerText=$(subNode).find(".mmf-grp-hdr").text().toUpperCase();
subfolderSearchMatch=(headerText.indexOf(searchString)==-1)?false:true;
if(subfolderSearchMatch){$(subNode).find(".mmf-force-hidden").removeClass("mmf-force-hidden");
}subGrpImageCnt=$(subNode).find(".mmf-image").length;
subGrpHiddenImageCnt=$(subNode).find(".mmf-image.mmf-force-hidden").length;
if(subGrpImageCnt===subGrpHiddenImageCnt){$(subNode).addClass("mmf-force-hidden");
}else{$(subNode).removeClass("mmf-force-hidden");
$(subNode).find(".sub-sec-hd").find(".mmf-grp-cnt").text(subGrpImageCnt-subGrpHiddenImageCnt);
}});
hiddenImageCnt=$(item).find(".mmf-image.mmf-force-hidden").length;
if(imageCnt===hiddenImageCnt&&imageCnt!==0){$(item).addClass("mmf-force-hidden");
}else{if(imageCnt!==0){$(item).removeClass("mmf-force-hidden");
$(item).children(".sub-sec-hd").find(".mmf-grp-cnt").text(imageCnt-hiddenImageCnt);
}}});
if(searchString.length===0){$(imageMainNode).each(function(index,item){$(item).find(".mmf-force-hidden").removeClass("mmf-force-hidden");
});
}};
MediaGalleryComponent.prototype.displayFilterApplied=function(){var namespace=this.getStyles().getId();
var lbContainer="lookbackContainer"+namespace;
var filterMsgHTML="";
var contentTypeDisplays=[];
var idx=0;
var mmfI18n=i18n.discernabu.mediaGallery_o1;
var contentTypeFilterList=this.getContentTypeFilterList();
var filterContentTypesLen=contentTypeFilterList.length;
if(filterContentTypesLen>0){for(idx=0;
idx<filterContentTypesLen;
idx++){var filterObj=contentTypeFilterList[idx];
contentTypeDisplays.push(filterObj.DISPLAY);
}var filterMegObj=document.getElementById("filterMessage"+namespace);
if(!filterMegObj){filterMsgHTML='<span id="filterMessage'+namespace+'" title="'+mmfI18n.CONTENT_TYPES+": "+contentTypeDisplays.join(", ")+'" class="mmf-filter-applied-message"> '+mmfI18n.FILTER_APPLIED+"</span>";
$("#"+lbContainer).append(filterMsgHTML);
}}};
MediaGalleryComponent.prototype.addComponentMenu=function(){var compId=this.getComponentId();
var mmfI18n=i18n.discernabu.mediaGallery_o1;
var component=this;
var menuShowRelatedDocsSelected=component.getMenuShowRelatedDocsInd();
this.addMenuOption("mnuMediaGalleryo1GroupByContentType","mnuMediaGalleryo1GroupByContentType"+compId,mmfI18n.GROUP_BY_CONTENT_TYPE,false,"click",function(){component.displayGroupByContentType();
});
this.addMenuOption("mnuMediaGalleryo1ShowRelatedDocs","mnuMediaGalleryo1ShowRelatedDocs"+compId,mmfI18n.SHOW_RELATED_DOCUMENTS,false,"click",function(){if(component.getMenuShowRelatedDocsInd()===0){component.setMenuShowRelatedDocsInd(1);
var menuShowRelatedDocs=$("#mnuMediaGalleryo1ShowRelatedDocs"+compId);
var menuShowRelatedDocsHtml=menuShowRelatedDocs.html();
menuShowRelatedDocsHtml=menuShowRelatedDocsHtml+"<span class='mmf-gal-opt-mnu-show-related-docs'></span>";
menuShowRelatedDocs.html(menuShowRelatedDocsHtml);
component.getRelatedDocs();
}else{component.setMenuShowRelatedDocsInd(0);
$("#mnuMediaGalleryo1ShowRelatedDocs"+compId+">span").removeClass();
component.removeShowRelatedDocsIcon();
}});
this.createMenu();
};
MediaGalleryComponent.prototype.displayGroupByContentType=function(){var compId=this.getComponentId();
if(this.m_menuGroupBy===0){this.m_menuGroupBy=1;
var menuGroupByContentType=$("#mnuMediaGalleryo1GroupByContentType"+compId);
var menuGroupByContentTypeHtml=menuGroupByContentType.html();
menuGroupByContentTypeHtml=menuGroupByContentTypeHtml+"<span class='mmf-opt-mnu-grp-by-content-type'></span>";
menuGroupByContentType.html(menuGroupByContentTypeHtml);
}else{this.m_menuGroupBy=0;
$("#mnuMediaGalleryo1GroupByContentType"+compId+">span").removeClass();
}this.displayBodyContent();
this.postProcessing();
if(this.m_menuShowRelatedDocsInd===1){this.generateHTMLShowRelatedDocsIcon();
}this.mediaGalleryo1PrefObj.media_gallery_prefs=this.getPrefJson();
this.setPreferencesObj(this.mediaGalleryo1PrefObj);
this.savePreferences(true);
};
MediaGalleryComponent.prototype.getMenuShowRelatedDocsInd=function(){return this.m_menuShowRelatedDocsInd;
};
MediaGalleryComponent.prototype.setMenuShowRelatedDocsInd=function(menuShowRelatedDocsInd){this.m_menuShowRelatedDocsInd=menuShowRelatedDocsInd;
};
MediaGalleryComponent.prototype.getRelatedDocs=function(){var criterion=this.getCriterion();
var request=null;
var self=this;
var encntrs=null;
var encntrStr="";
encntrs=criterion.getPersonnelInfo().getViewableEncounters();
encntrStr=(encntrs)?"value("+encntrs+")":"0";
var imageIdList="value("+this.m_viewableImageIds+")";
var sendAr=["^MINE^",criterion.person_id+".0",encntrStr,imageIdList,criterion.provider_id+".0",criterion.ppr_cd+".0"];
request=new MP_Core.ScriptRequest(this,"ENG:MPG.MMF.GALLERY.01 _ Get Related Docs");
request.setProgramName("MP_MEDIA_GALLERY_GET_DOCS");
request.setParameters(sendAr);
request.setAsync(true);
MP_Core.XMLCCLRequestCallBack(this,request,function(reply){self.displayShowRelatedDocsIcon(reply);
});
};
MediaGalleryComponent.prototype.displayShowRelatedDocsIcon=function(reply){var component=this;
var replyData=null;
var replyStatus="";
replyStatus=reply.getStatus();
if(replyStatus!=="S"){if(replyStatus==="F"){var errMgs="getRelatedDocs returned unsuccessful status: "+replyStatus;
MP_Util.LogError(errMgs);
alert(i18n.ERROR_RETREIVING_DATA);
}else{MP_Util.LogInfo("MMF Media Gallery:getRelatedDocs:No results found");
}return;
}replyData=reply.getResponse();
this.m_docData=replyData.DOCS;
this.generateHTMLShowRelatedDocsIcon();
};
MediaGalleryComponent.prototype.generateHTMLShowRelatedDocsIcon=function(){var component=this;
if(this.m_menuShowRelatedDocsInd===1&&component.m_docData){component.rootNode$.find(".mmf-iconHolder").each(function(){var imgMenuId=$(this).prev().attr("id");
var docsObject=[];
var docCnt=0;
var docsLen=component.m_docData.length;
if(docsLen){for(var i=0;
i<docsLen;
i++){var curDoc=component.m_docData[i];
var thumbnailId=curDoc.IMAGE_ID;
var thumbnailIdStr=thumbnailId.substring(1,thumbnailId.length-1);
if(thumbnailIdStr===imgMenuId){docsObject[docCnt]=curDoc;
docCnt=docCnt+1;
}}}if(docCnt>0){$(this).addClass("mmf-show-related-docs-icon");
$(this).click(function(){component.displayDocumentsMenu(imgMenuId,docsObject);
$(".hvr.hover").hide();
});
$(this).mouseenter(function(){this.activelyHovering=true;
});
$(this).mouseleave(function(){this.activelyHovering=false;
});
}});
}};
MediaGalleryComponent.prototype.removeShowRelatedDocsIcon=function(){if(this.m_menuShowRelatedDocsInd===0){this.rootNode$.find(".mmf-show-related-docs-icon").removeClass("mmf-show-related-docs-icon");
}};
MediaGalleryComponent.prototype.displayDocumentsMenu=function(imgMenuId,objDocs){var component=this;
if(this.docTimeout!==null){this.hideDocumentMenu(this,true);
}this.setEditMode(true);
var docsHTML="";
var compId=this.getComponentId();
var docsLen=objDocs.length;
this.docTimeout=setTimeout(function(){component.hideDocumentMenu(component);
},this.clearTimeoutCount);
this.activelyHovering=true;
if(docsLen){for(var i=0;
i<docsLen;
i++){var curDoc=objDocs[i];
var patId=curDoc.PERSON_ID;
var enctrId=curDoc.ENCNTR_ID;
var evntId=curDoc.EVENT_ID;
var doc=curDoc.EVENT_CD_DISP;
var viewerType=curDoc.VIEWER_TYPE;
var parentEventId=curDoc.PARENT_EVENT_ID;
var docDt=null;
var dateTime=new Date();
if(curDoc.EFFECTIVE_DATE){dateTime.setISO8601(curDoc.EFFECTIVE_DATE);
docDt=MP_Util.DisplayDateByOption(component,dateTime);
}else{docDt=i18n.UNKNOWN;
}docsHTML+="<div class='mmf-doc-item-opt'><span><span>"+docDt+"<span  class ='mmf-doc-item-name' title = '"+doc+"'>"+MP_Util.CreateClinNoteLink(patId,enctrId,evntId,doc,viewerType,parentEventId)+"</span></span></div>";
}var docsMnu=Util.cep("div",{className:"mmf-docs-menu",id:"docsMnu"+compId});
docsMnu.innerHTML=docsHTML;
$(docsMnu).bind("mouseenter",{self:this},function(event){var self=event.data.self;
self.activelyHovering=true;
self.docTimeout=setTimeout(function(){self.hideDocumentMenu(self);
},self.clearTimeoutCount);
});
$(docsMnu).bind("mouseleave",{self:this},function(event){var self=event.data.self;
self.activelyHovering=false;
event.stopPropagation();
});
$(".mmf-show-related-docs-icon").bind("mouseleave",{self:this},function(event){var self=event.data.self;
self.activelyHovering=false;
event.stopPropagation();
});
var imageMenuId=component.rootNode$.find("#"+imgMenuId).parent();
imageMenuId.append(docsMnu);
Util.cancelBubble();
}};
MediaGalleryComponent.prototype.hideDocumentMenu=function(component,bypassCheck){if(this.activelyHovering===false||typeof(bypassCheck)!=="undefined"){this.docTimeout=null;
$(".mmf-docs-menu").remove();
this.setEditMode(false);
}else{this.docTimeout=setTimeout(function(){component.hideDocumentMenu(component);
},this.clearTimeoutCount);
}};
MediaGalleryComponent.prototype.postProcessing=function(){var $self,$scopeObj,$allHyperLinkImages,$currentImageObj;
var catName=this.getCriterion().category_mean;
$self=this;
$scopeObj=$("#"+this.m_rootComponentNode.id);
$allHyperLinkImages=$scopeObj.find(".mmf-imageLaunchViewer, .mmf-dateLinkLaunchViewer");
for(var i=0;
i<$allHyperLinkImages.length;
i++){$currentImageObj=$allHyperLinkImages[i];
var currentImgAttr=$($currentImageObj).attr("name");
if(currentImgAttr!==null){$($currentImageObj).click({component:$self,imageIdStr:currentImgAttr},function(event){var eData=event.data;
eData.component.launchMediaViewer(eData.component.m_MediaViewerURL,catName,eData.imageIdStr);
});
}}$self.rootNode$.off("click",".mmfgal-o1-info.result-info .sub-sec-hd-tgl");
$self.rootNode$.on("click",".mmfgal-o1-info.result-info .sub-sec-hd-tgl",function(event){$(event.target).closest(".sub-sec.mmf-group").toggleClass("closed");
});
};
MP_Util.setObjectDefinitionMapping("MMF_MED_GAL",MediaGalleryComponent);
