var MPageComponents=MPageComponents?MPageComponents:{};
(function(){var attribute=MPageObjectOriented.createAttribute;
MPageComponents.NewOrderEntry=function(){this.setTabGroup(new MPageControls.TabGroup());
this.setOrderSearchControl(null);
this.setFaceUpSuggestionLimit(50);
this.tabs={};
};
var NewOrderEntry=MPageComponents.NewOrderEntry;
NewOrderEntry.Venues={INPATIENT:1,AMBULATORY:2};
NewOrderEntry.NewOrderPref={NOT_CONFIGURED:0,ALLOW:1,REJECT:2,WARN:3};
NewOrderEntry.MessageType={WARNING:1,INFORMATION:2};
attribute(NewOrderEntry,"Templates");
attribute(NewOrderEntry,"TargetElementId");
attribute(NewOrderEntry,"ComponentId");
attribute(NewOrderEntry,"TabGroup");
attribute(NewOrderEntry,"OrderSearchElementId");
attribute(NewOrderEntry,"OrderSearchControl");
attribute(NewOrderEntry,"OrderSearchEnabled");
attribute(NewOrderEntry,"Criterion");
attribute(NewOrderEntry,"SuggestionLimit");
attribute(NewOrderEntry,"FaceUpSuggestionLimit");
attribute(NewOrderEntry,"EncounterTypeCd");
attribute(NewOrderEntry,"FacilityId");
attribute(NewOrderEntry,"SearchIndicators");
attribute(NewOrderEntry,"SearchVenueType");
attribute(NewOrderEntry,"VenueType");
attribute(NewOrderEntry,"LegacyComponent");
attribute(NewOrderEntry,"LegacyNamespace");
attribute(NewOrderEntry,"TabInstances");
attribute(NewOrderEntry,"RecordData");
attribute(NewOrderEntry,"I18n");
attribute(NewOrderEntry,"DefaultTab");
attribute(NewOrderEntry,"TimerNames");
attribute(NewOrderEntry,"NewOrderPrefMsgElemId");
attribute(NewOrderEntry,"FutureOrderMessagePref");
attribute(NewOrderEntry,"DischNewOrderPref");
attribute(NewOrderEntry,"OrderSentencesEnabled");
attribute(NewOrderEntry,"ShowOrderSentenceDetailUserPref");
var prot=MPageComponents.NewOrderEntry.prototype;
prot.init=function(){var template=null;
if(!this.getTabGroup().getControls().length){throw new Error(i18n.discernabu.CONFIG_INCOMPLETE+"&nbsp;"+i18n.CONTACT_ADMINISTRATOR);
}var futureOrderPref=this.getFutureOrderMessagePref();
if(futureOrderPref!==NewOrderEntry.NewOrderPref.REJECT||futureOrderPref===NewOrderEntry.NewOrderPref.NOT_CONFIGURED){template=TemplateBuilder.buildTemplate(this.getTemplates().main);
$("#"+this.getTargetElementId()).html(template.render(this.makeRenderParams()));
this.createOrderSearchControl();
this.createTabs();
}else{var newOrderPrefDiv=$("#noeNewOrderMessage"+this.getLegacyComponent().getComponentId());
if(!newOrderPrefDiv.length){template=TemplateBuilder.buildTemplate(this.getTemplates().newOrderPref);
$("#"+this.getTargetElementId()).html(template.render(this.makeRenderParams()));
}}this.createNewOrderPrefMessage();
this.setOrderSentencesEnabled(true);
};
prot.makeRenderParams=function(){return{component:this,compId:this.getLegacyComponent().getComponentId(),i18n:this.getI18n(),warningMessage:this.getMessage(1),informationMessage:this.getMessage(2)};
};
prot.getMessage=function(msgType){var msg="";
var i18n=this.getI18n();
if(this.getDischNewOrderPref()>1){msg+=msgType===NewOrderEntry.MessageType.WARNING?i18n.VIEWING_DISCHARGE_ENCOUNTER_MSG:i18n.PLACE_PRESCRIPTIONS_ONLY;
}else{if(this.getFutureOrderMessagePref()>=1){msg+=msgType===NewOrderEntry.MessageType.WARNING?i18n.VIEWING_FUTURE_ENCOUNTER_MSG:i18n.CANNOT_PLACE_ORDER;
}}return msg;
};
prot.createOrderSearchControl=function(){if(!this.getOrderSearchEnabled()){return;
}var self=this;
this.getLegacyNamespace().ApplySearchSettings(this.getLegacyComponent());
this.setOrderSearchElementId("noeSearchBox"+this.getLegacyComponent().getComponentId());
var element=$("#"+this.getOrderSearchElementId());
var control=new MPageControls.OrderSearch(element);
this.setOrderSearchControl(control);
control.getTextbox().click(function(){self.fireCapTimer(self.getTimerNames().SEARCH);
});
this.loadOrderSearchAttributes();
control.activateCaption();
control.setOnEnter(function(){self.getTabGroup().selectSingle(self.tabs.searchresults);
self.tabs.searchresults.showLoading();
control.close();
control.setSuggestionLimit(self.getFaceUpSuggestionLimit());
control.searchOrders(function(response){self.tabs.searchresults.onLoad();
self.loadSearchResults(response);
});
control.setSuggestionLimit(self.getSuggestionLimit());
});
control.getList().setOnSelect(function(){control.close();
self.addOrderToScratchpad(control.getList().getSelectedItem());
control.activateCaption();
});
control.getList().setOnEnter(function(){control.close();
self.addOrderToScratchpad(control.getList().getSelectedItem());
control.setValue("");
});
};
prot.loadOrderSearchAttributes=function(){var control=this.getOrderSearchControl();
control.setCriterion(this.getCriterion());
control.setSuggestionLimit(this.getSuggestionLimit());
control.setEncounterTypeCd(this.getEncounterTypeCd());
control.setFacilityId(this.getFacilityId());
control.setSearchIndicators(this.getSearchIndicators());
control.setVenueType(this.getSearchVenueType());
control.setCaption(this.getI18n().SEARCH_ORDER);
};
prot.createTabs=function(){var tabgroup=this.getTabGroup();
var compId=this.getComponentId();
tabgroup.setButtonsContainerId("noeTabButtons"+compId);
tabgroup.setContentsContainerId("noeTabContent"+compId);
tabgroup.setDefaultButtonTemplate(this.getTemplates().tabButtons);
tabgroup.render();
if(this.getDefaultTab()!==undefined){tabgroup.selectSingle(this.getDefaultTab());
}};
prot.loadLegacyComponent=function(instance,namespace,i18n){this.setComponentId(instance.getComponentId());
this.setFacilityId(instance.getFacilityId());
this.setSearchIndicators(instance.getSearchIndicators());
this.setEncounterTypeCd(instance.getEncntrTypeCd());
this.setVenueType(instance.getVenueType());
this.setLegacyComponent(instance);
this.setLegacyNamespace(namespace);
this.setCriterion(instance.getCriterion());
this.setOrderSearchEnabled(instance.isOrderSearchInd());
this.setSearchVenueType(instance.getEncntrVenueInd());
this.setI18n(i18n);
if(this.shouldHomeTabBeDisplayed(instance)){this.addTab(NewOrderEntry.HomeTab);
}if(instance.isUserFavEnabled()){this.addTab(NewOrderEntry.MineTab);
}if(instance.isPublicFavEnabled()){this.addTab(NewOrderEntry.PublicTab);
}if(instance.isSharedFavEnabled()){this.addTab(NewOrderEntry.SharedTab);
}if(this.getOrderSearchEnabled()){this.addTab(NewOrderEntry.SearchTab);
}if(this.getOrderSearchControl()){this.loadOrderSearchAttributes();
}};
prot.shouldHomeTabBeDisplayed=function(instance){return instance.isHomeFavEnabled&&instance.isHomeFavEnabled()&&(instance.isUserFavEnabled()||instance.isPublicFavEnabled()||instance.isSharedFavEnabled());
};
prot.addTab=function(TabClass){var tabName=TabClass.ALIAS.toLowerCase();
if(this.tabs[tabName]!==undefined){this.tabs[tabName].setLoaded(false);
return;
}var tab=new TabClass(this);
this.tabs[tabName]=tab;
this.getTabGroup().add(tab);
if(this.getDefaultTab()===undefined&&tab!=this.tabs.searchresults){this.setDefaultTab(tab);
}};
prot.loadSearchResults=function(jsonResponse){this.tabs.searchresults.setResultsJson(jsonResponse);
this.getTabGroup().selectSingle(this.tabs.searchresults);
};
prot.refreshRecordData=function(excludeTabFromRefresh){var self=this;
var currentTabMask=this.getTabGroup().getCurrent().getTabMask();
$.each(this.getTabGroup().getControls(),function(){if(this==excludeTabFromRefresh){return;
}this.showLoading();
});
this.requestRecordData(function(response,component){self.setRecordData(response.getResponse());
self.refreshTabs();
self.refreshSearchIndicators();
if(self.getTabGroup().getCurrent()!=excludeTabFromRefresh){self.getTabGroup().getCurrent().onLoad();
}},currentTabMask);
};
prot.refreshSearchIndicators=function(){var recordData=this.getRecordData();
var component=this.getLegacyComponent();
if(recordData.VIEWPLORDERS!==undefined){component.setDispOnlyProductLevelMeds(recordData.VIEWPLORDERS);
}this.getLegacyNamespace().ApplySearchSettings(component);
};
prot.onVenueChange=function(){if(this.getTabGroup().getCurrent()==this.tabs.searchresults){this.refreshRecordData(this.tabs.searchresults);
return;
}this.refreshRecordData();
};
prot.refreshTabs=function(){$.each(this.getTabGroup().getControls(),function(){this.setLoaded(false);
});
};
prot.showLoading=function(){$.each(this.getTabGroup().getControls(),function(){this.showLoading();
});
};
prot.addOrderToScratchpad=function(order){var Order=MPageComponents.NewOrderEntry.Order;
var favType=Order.Types.ORDER;
if(order.PATH_CAT_ID){favType=Order.Types.POWERPLAN;
}else{if(order.ORDERABLE_TYPE_FLAG==6){favType=Order.Types.CARESET;
}}this.getLegacyNamespace().AddSearchItemToScratchPad(order,this.getLegacyComponent(),favType);
};
prot.fireCapTimer=function(name){var slaTimer=MP_Util.CreateTimer(name);
if(slaTimer){slaTimer.SubtimerName=this.getCriterion().category_mean;
slaTimer.Start();
slaTimer.Stop();
}};
prot.fireOrderTimer=function(synonymID){if(!this.getTabGroup().getCurrent()){return;
}if(!(isFinite(parseFloat(synonymID)))){synonymID="";
}var elementId=$("#"+this.getOrderSearchElementId());
var inputElementLength=elementId.find("input[type=text]").length;
if(elementId&&inputElementLength){searchText=elementId.find("input[type=text]").val();
}else{return;
}var tabAlias=this.getTabGroup().getCurrent().getAlias().toUpperCase();
var timerNames=this.getTimerNames().ORDER;
if(tabAlias in timerNames){this.fireCapTimer(timerNames[tabAlias]);
}if("ORDER_ADDTOSCRATCHPAD" in this.getTimerNames()){timerNames=this.getTimerNames().ORDER_ADDTOSCRATCHPAD;
if(tabAlias in timerNames){var orderAddToScratchpadCAPTimer=new CapabilityTimer(timerNames[tabAlias],this.getCriterion().category_mean);
orderAddToScratchpadCAPTimer.addMetaData("rtms.legacy.metadata.1",searchText);
orderAddToScratchpadCAPTimer.addMetaData("rtms.legacy.metadata.2",synonymID);
orderAddToScratchpadCAPTimer.capture();
}}};
prot.fireOrderTimerFromSearch=function(synonymID){var elementId=$("#"+this.getOrderSearchElementId());
var inputElementLength=elementId.find("input[type=text]").length;
if(elementId&&inputElementLength){searchText=elementId.find("input[type=text]").val();
}else{return;
}var timerName=this.getTimerNames().ORDER.SEARCHRESULTS;
var clickOrderFromSearchCAPTimer=new CapabilityTimer(timerName,this.getCriterion().category_mean);
if(!(isFinite(parseFloat(synonymID)))){synonymID="";
}clickOrderFromSearchCAPTimer.addMetaData("rtms.legacy.metadata.1",searchText);
clickOrderFromSearchCAPTimer.addMetaData("rtms.legacy.metadata.2",synonymID);
clickOrderFromSearchCAPTimer.capture();
timerName=this.getTimerNames().ORDER_ADDTOSCRATCHPAD.SEARCHRESULTS;
var orderAddToScratchpadFromSearchCAPTimer=new CapabilityTimer(timerName,this.getCriterion().category_mean);
orderAddToScratchpadFromSearchCAPTimer.capture();
};
prot.createNewOrderPrefMessage=function(){var template=null;
var element=null;
var message=null;
var control=null;
var messageType=null;
var futureNewOrderPref=this.getFutureOrderMessagePref();
var dschNewOrderPref=this.getDischNewOrderPref();
var component=this.getLegacyComponent();
if(futureNewOrderPref===undefined||futureNewOrderPref===NewOrderEntry.NewOrderPref.NOT_CONFIGURED&&(dschNewOrderPref===undefined||dschNewOrderPref===NewOrderEntry.NewOrderPref.NOT_CONFIGURED||dschNewOrderPref===NewOrderEntry.NewOrderPref.ALLOW)){return;
}this.setNewOrderPrefMsgElemId("noeNewOrderPrefMessage"+this.getLegacyComponent().getComponentId());
element=$("#"+this.getNewOrderPrefMsgElemId());
template=MPageControls.getDefaultTemplates().messageBar;
if(futureNewOrderPref===NewOrderEntry.NewOrderPref.WARN||futureNewOrderPref===NewOrderEntry.NewOrderPref.ALLOW||dschNewOrderPref===NewOrderEntry.NewOrderPref.WARN){messageTemplate=this.getTemplates().warningMessage;
messageType=MPageControls.AlertMessage.MessageTypes.WARNING;
}else{if(futureNewOrderPref===NewOrderEntry.NewOrderPref.REJECT||dschNewOrderPref===NewOrderEntry.NewOrderPref.REJECT){messageTemplate=this.getTemplates().informationMessage;
messageType=MPageControls.AlertMessage.MessageTypes.INFORMATION;
}}message=TemplateBuilder.buildTemplate(messageTemplate);
control=new MPageControls.AlertMessage(element,template,messageType);
control.render(message.render(this.makeRenderParams()));
};
prot.createDisabledVenue=function(venue){var component=this.getLegacyComponent();
var venueHtml=[];
var componentId=this.getComponentId();
var m_contentNode=component.getRootComponentNode();
if(m_contentNode){var m_contentNodeHd=_gbt("H2",m_contentNode)[0];
var venueTypeEle=Util.cep("div",{id:"noeHdVenueType"+componentId});
venueHtml.push("<span class='noe-disabled-venue'>",venue.DISPLAY,"</span>");
Util.ia(venueTypeEle,m_contentNodeHd);
$("#noeHdVenueType"+componentId).html(venueHtml.join(""));
}};
prot.requestRecordData=function(callback,tabMask){var component=this.getLegacyComponent();
var criterion=this.getCriterion();
var componentId=this.getComponentId();
var venueType=this.getVenueType();
var orderMask=0;
var virtualViewMask=0;
var orderSearchMask=0;
var planSearchMask=0;
var productLevelMask=0;
var sharedPlanMask=0;
var tabs=this.tabs;
var favsRequest=new MP_Core.ScriptRequest(component,component.getComponentLoadTimerName());
if(venueType===1){component.setDispOnlyProductLevelMeds(0);
productLevelMask=0;
}else{component.setDispOnlyProductLevelMeds(1);
productLevelMask=16;
}if(tabs.mine||tabs["public"]||tabs.shared){planSearchMask=(component.isPowerPlanEnabled()?8:0);
sharedPlanMask=(component.isPowerPlanEnabled()?32:0);
orderSearchMask=tabMask===4?0:4;
}virtualViewMask=(component.isVirtViewOrders()||component.isVirtViewRxOrders()?3:0);
orderMask=virtualViewMask+planSearchMask+productLevelMask+sharedPlanMask+orderSearchMask+tabMask;
var sendAr=["^MINE^",criterion.person_id+".0",criterion.encntr_id+".0",criterion.provider_id+".0","0.0","^FAVORITES^",criterion.position_cd+".0",criterion.ppr_cd+".0",orderMask,venueType,1];
favsRequest.setProgramName("mp_get_powerorder_favs_json");
favsRequest.setParameters(sendAr);
favsRequest.setAsync(true);
MP_Core.XMLCCLRequestCallBack(component,favsRequest,callback);
};
prot.renderFormularyInfo=function(uid,noeOrderList,tabName){var baseComponent=this;
if(uid){var component=baseComponent.getLegacyComponent();
var recordData=this.getRecordData();
var ckiList=this.retrieveCKIFromReply(noeOrderList);
var namespace=component.getStyles().getNameSpace();
var currentTab=baseComponent.tabs[tabName];
if(currentTab){var element=currentTab.getElement();
this.retrieveEligibilityInfo(uid,ckiList,element);
}}};
prot.renderFormularySearch=function(uid,orderList){var baseComponent=this;
if(uid){var component=baseComponent.getLegacyComponent();
var ckiList=this.retrieveCKIFromSearchReply(orderList);
var currentTab=baseComponent.tabs.searchresults;
if(currentTab){var element=currentTab.getElement();
this.retrieveEligibilityInfo(uid,ckiList,element);
}}};
prot.retrieveCKIFromSearchReply=function(searchList){var ckiList=[];
var uniqueCKIObj={};
var order;
var cki;
var orderCnt=searchList.length;
for(var i=0;
i<orderCnt;
i++){order=searchList[i];
cki=order.CKI;
if(cki){if(!uniqueCKIObj[cki]){uniqueCKIObj[cki]=true;
}}}for(cki in uniqueCKIObj){ckiList.push(cki);
}return ckiList;
};
prot.retrieveCKIFromReply=function(noeOrdersJSON){var ckiList=[];
var uniqueCKIObj={};
var noeFolder;
var noeChildList;
var noeChild;
var cki;
var noeFolderCnt=noeOrdersJSON.length;
for(var i=0;
i<noeFolderCnt;
i++){noeFolder=noeOrdersJSON[i];
noeChildList=noeFolder.CHILD_LIST;
noeChildCnt=noeChildList.length;
for(var j=0;
j<noeChildCnt;
j++){noeChild=noeChildList[j];
cki=noeChild.CKI;
if(cki){if(!uniqueCKIObj[cki]){uniqueCKIObj[cki]=true;
}}}}for(cki in uniqueCKIObj){ckiList.push(cki);
}return ckiList;
};
prot.refreshEligibilityInfo=function(uid){var uniqueCKIObj={};
var ckiList=[];
var component=this.getLegacyComponent();
var rootNode=component.getRootComponentNode();
var namespace=component.getStyles().getNameSpace();
this.clearEligibilityIcons(rootNode);
$("."+namespace+"-info",rootNode).each(function(index,element){var cki=$(this).data("cki");
if(cki){if(!uniqueCKIObj[cki]){uniqueCKIObj[cki]=true;
}}});
for(cki in uniqueCKIObj){ckiList.push(cki);
}this.retrieveEligibilityInfo(uid,ckiList,rootNode);
};
prot.retrieveEligibilityInfo=function(uid,ckiList,element){var self=this;
var wrappedCallback=function(ckiMap){self.renderEligibilityInformation(ckiMap,element);
};
if(uid&&ckiList){SharedPlanEligibilityInfo.retrieveEligibilityInfo(uid,ckiList,wrappedCallback);
}};
prot.clearEligibilityIcons=function(element){var component=this.getLegacyComponent();
var namespace=component.getStyles().getNameSpace();
$("."+namespace+"-info",element).find("."+namespace+"-eligibility-info").empty();
};
prot.renderEligibilityInformation=function(ckiMap,element){var component=this.getLegacyComponent();
var namespace=component.getStyles().getNameSpace();
var rootNode;
$("."+namespace+"-info",element).each(function(index,element){var cki=$(this).data("cki");
var eligibilityElement=$(this).find("."+namespace+"-eligibility-info");
var eligibilityInfo;
var annotatedText;
var benefitRating;
var formularyDetails;
if(cki){eligibilityInfo=ckiMap[cki];
if(eligibilityInfo){benefitRating=eligibilityInfo.BENEFIT_RATING;
annotatedText=eligibilityInfo.ANNOTATED_TEXT||"";
formularyDetails=eligibilityInfo.FORMATTED_DETAILS;
HealthPlanEligibilityInfo.generateIconHtml(eligibilityElement,benefitRating,annotatedText,formularyDetails);
}else{eligibilityElement.empty();
}}});
};
prot.getOrderSentenceDetails=function(ageFilter,weightFilter,pmaFilter){var filterDetailStrings=[];
var noei18n=this.getI18n();
if(!ageFilter&&!weightFilter&&!pmaFilter){return filterDetailStrings;
}var addSentenceFilterDetails=function(min,max,unit){var details="";
if(min&&max){details=(min+" "+noei18n.ORDER_SENT_BETWEEN+" "+max+" "+unit);
}else{if(max){details=(noei18n.ORDER_SENT_LESS_THAN+" "+max+" "+unit);
}else{if(min){details=(noei18n.ORDER_SENT_GREATER_THAN_EQUAL+" "+min+" "+unit);
}}}return details;
};
filterDetailStrings.push(" [");
if(ageFilter){filterDetailStrings.push(addSentenceFilterDetails(ageFilter.AGE_MINIMUM,ageFilter.AGE_MAXIMUM,ageFilter.AGE_UNIT));
}if(ageFilter&&weightFilter){filterDetailStrings.push(" "+noei18n.AND+" ");
}if(weightFilter){filterDetailStrings.push(addSentenceFilterDetails(weightFilter.WEIGHT_MINIMUM,weightFilter.WEIGHT_MAXIMUM,weightFilter.WEIGHT_UNIT));
}if((ageFilter&&pmaFilter)||(weightFilter&&pmaFilter)){filterDetailStrings.push(" "+noei18n.AND+" ");
}if(pmaFilter){filterDetailStrings.push(noei18n.PMA+" "+addSentenceFilterDetails(pmaFilter.AGE_MINIMUM,pmaFilter.AGE_MAXIMUM,pmaFilter.AGE_UNIT));
}filterDetailStrings.push("]");
return filterDetailStrings;
};
})();
MPageComponents.NewOrderEntry.Templates={option1:{header:'<div id="noeSearchBox${componentId}"></div><div id="searchHeader${componentId}"></div>',main:"<div class ='message-container' id='noeNewOrderPrefMessage${compId}' /><div class = 'message-container' id='noeEligibilityMessage${compId}' /><div id='noeSearchBox${compId}' /><div class='noe-hd hdr'><div id='noeTabButtons${compId}' class='noe-buttons' /></div><div id='noeTabContent${compId}' class='noe-body' /><div id='noeScratchPadCont${compId}' class='sub-sec hidden'><h3 class='sub-sec-hd'><span class='sub-sec-title'>${i18n.ORDERS_FOR_SIGNATURE} (<span id='noeScratchPadCount${compId}'>0</span>)</span></h3><div id='noeScratchPad${compId}' class='sub-sec-content noe-scratch'><span class='res-none'>${i18n.NO_ORDERS_FOR_SIGNATURE}</span></div><div class='noe-scr-submit hdr'><input id='btnDx${compId}' type='button' class='noe-btn' value='${i18n.DX_TABLE}' /><input id='btnModify${compId}' type='button' class='noe-btn' value='${i18n.MODIFY}' /><input id='btnSign${compId}' type='button' class='noe-btn' value='${i18n.SIGN}' /></div></div>",tabButtons:"<div class='noe-seg-cont-center' id='${tabButtonId}'>${tab.getTitle()}</div>",searchTab:"<div id='searchHeader${compId}' class='sub-sec-hd'></div><div id='folderContentsSearchResults${compId}' class='noe-search-results'></div>",loading:"<div class='noe2-preloader-icon'></div>",newOrderPref:"<div class ='message-container' id='noeNewOrderPrefMessage${compId}' />",warningMessage:"<span class='noe-future-warning'>${warningMessage}</span> ${i18n.APPLY_TO_ENCOUNTER}",informationMessage:"<span class='noe-future-warning'>${informationMessage}</span>"},option2:{main:"<div class='noe2-hd hdr'><div id='noeTabButtons${compId}' class='noe2-tab-container'></div><div id='noeSearchBox${compId}'></div></div><div id='noeTabContent${compId}' class='noe2-body'></div>",tabButtons:"<div class='noe2-seg-cont-center' id='${tabButtonId}'><span>${tab.getTitle()}</span></div>",homeTabButton:"<div class='noe2-seg-cont-center home' id='${tabButtonId}'><span class='noe2-home-icon'></span></div>",searchTab:"<div class='noe2-search-results-sec'><div id='searchHeader${compId}' class='sub-sec-hd'></div><div id='folderContentsSearchResults${compId}' class='noe2-main-container noe-search-results''></div></div>"}};
MPageComponents.NewOrderEntry.Templates.option2.loading=MPageComponents.NewOrderEntry.Templates.option1.loading;
MPageComponents.NewOrderEntry.Templates.option2.warningMessage=MPageComponents.NewOrderEntry.Templates.option1.warningMessage;
MPageComponents.NewOrderEntry.Templates.option2.informationMessage=MPageComponents.NewOrderEntry.Templates.option1.informationMessage;
MPageComponents.NewOrderEntry.Templates.option2.newOrderPref=MPageComponents.NewOrderEntry.Templates.option1.newOrderPref;
(function(){var attribute=MPageObjectOriented.createAttribute;
var inherits=MPageObjectOriented.inherits;
var ns=MPageComponents.NewOrderEntry;
ns.NoeTab=function(component){MPageControls.Tab.call(this);
var self=this;
this.setOnSelect(function(){self.performSelect();
});
this.setComponent(component);
this.setLoaded(false);
};
inherits(ns.NoeTab,MPageControls.Tab);
attribute(ns.NoeTab,"Component");
attribute(ns.NoeTab,"Loaded");
attribute(ns.NoeTab,"Alias");
attribute(ns.NoeTab,"RecordData");
attribute(ns.NoeTab,"TabMask");
var prot=ns.NoeTab.prototype;
prot.performSelect=function(){if(typeof(FavoriteModeless)!="undefined"&&FavoriteModeless.current){FavoriteModeless.closeModeless();
}if(!this.getLoaded()){this.onLoad();
this.setLoaded(true);
}this.onSelect();
};
prot.showLoading=function(){this.setLoaded(true);
var template=TemplateBuilder.buildTemplate(this.getComponent().getTemplates().loading);
$("#"+this.getContentId()).html(template.render({}));
};
prot.getRecordDataArr=function(){return null;
};
prot.onSelect=function(){};
prot.onLoad=function(){var self=this;
var recordData=this.getComponent().getRecordData();
this.showLoading();
if(this.getRecordDataArr().length){this.setRecordData(recordData);
this.renderTabBody();
}else{this.updateScriptRequest(this.getTabMask());
}};
prot.renderTabBody=function(){};
prot.updateScriptRequest=function(tabMask){var tab=this;
this.getComponent().requestRecordData(function(recordData){tab.setRecordData(recordData.getResponse());
tab.renderTabBody();
},tabMask);
};
})();
(function(){var attribute=MPageObjectOriented.createAttribute;
var inherits=MPageObjectOriented.inherits;
var ns=MPageComponents.NewOrderEntry;
ns.MineTab=function(component){ns.NoeTab.call(this,component);
var legacyComponent=this.getComponent().getLegacyComponent();
this.setTitle(legacyComponent.getUserFavLabel()?legacyComponent.getUserFavLabel():this.getComponent().getI18n().MINE);
this.setAlias(ns.MineTab.ALIAS);
this.setTabMask(4);
};
ns.MineTab.ALIAS="Mine";
inherits(ns.MineTab,ns.NoeTab);
var prot=ns.MineTab.prototype;
prot.ALIAS=ns.MineTab.ALIAS;
prot.getRecordDataArr=function(){return this.getComponent().getRecordData().USER_FAV;
};
prot.renderTabBody=function(){var baseComponent=this.getComponent();
var namespace=this.getComponent().getLegacyNamespace();
var component=this.getComponent().getLegacyComponent();
var recordData=this.getRecordData();
var html=namespace.RenderMineTab(component,recordData);
$("#"+this.getContentId()).html(html);
baseComponent.renderFormularyInfo(component.getUid(),recordData.USER_FAV,"mine");
namespace.CreateMineTabEvents(component,recordData);
};
prot.onSelect=function(){var namespace=this.getComponent().getLegacyNamespace();
var componentNamespace=this.getComponent().getLegacyComponent().getStyles().getNameSpace();
if(componentNamespace==="noe2"){var mineTabSelectCAPTimer=new CapabilityTimer("CAP:MPG NEW ORDER ENTRY O2 SELECT MINE TAB",this.getComponent().getCriterion().category_mean);
mineTabSelectCAPTimer.capture();
}if(this.getRecordData()&&typeof namespace.ResizeColumns!=="undefined"){namespace.ResizeColumns(this.getRecordData(),this.getAlias(),this.getComponent().getLegacyComponent());
}};
})();
(function(){var inherits=MPageObjectOriented.inherits;
var ns=MPageComponents.NewOrderEntry;
var attribute=MPageObjectOriented.createAttribute;
ns.PublicTab=function(component){ns.NoeTab.call(this,component);
var legacyComponent=this.getComponent().getLegacyComponent();
this.setTitle(legacyComponent.getPublicFavLabel()?legacyComponent.getPublicFavLabel():this.getComponent().getI18n().PUBLIC);
this.setAlias(ns.PublicTab.ALIAS);
this.setTabMask(320);
};
ns.PublicTab.ALIAS="Public";
inherits(ns.PublicTab,ns.NoeTab);
attribute(ns.PublicTab,"LoadedVenue");
var prot=ns.PublicTab.prototype;
prot.getRecordDataArr=function(){return this.getComponent().getRecordData().PUBLIC_FAV;
};
prot.renderTabBody=function(){var baseComponent=this.getComponent();
var namespace=this.getComponent().getLegacyNamespace();
var component=this.getComponent().getLegacyComponent();
var recordData=this.getRecordData();
var html=namespace.RenderPublicTab(component,recordData);
$("#"+this.getContentId()).html(html);
namespace.CreatePublicTabEvents(component,recordData);
baseComponent.renderFormularyInfo(component.getUid(),recordData.PUBLIC_FAV,"public");
this.setLoadedVenue(this.getComponent().getVenueType());
};
prot.onSelect=function(){var namespace=this.getComponent().getLegacyNamespace();
var componentNamespace=this.getComponent().getLegacyComponent().getStyles().getNameSpace();
if(componentNamespace==="noe2"){var publicTabSelectCAPTimer=new CapabilityTimer("CAP:MPG NEW ORDER ENTRY O2 SELECT PUBLIC TAB",this.getComponent().getCriterion().category_mean);
publicTabSelectCAPTimer.capture();
}if(this.getRecordData()&&typeof namespace.ResizeColumns!=="undefined"){namespace.ResizeColumns(this.getRecordData(),this.getAlias(),this.getComponent().getLegacyComponent());
}};
})();
(function(){var attribute=MPageObjectOriented.createAttribute;
var inherits=MPageObjectOriented.inherits;
var ns=MPageComponents.NewOrderEntry;
ns.SharedTab=function(component){ns.NoeTab.call(this,component);
var legacyComponent=this.getComponent().getLegacyComponent();
this.setTitle(legacyComponent.getSharedFavLabel()?legacyComponent.getSharedFavLabel():this.getComponent().getI18n().SHARED);
this.setAlias(ns.SharedTab.ALIAS);
};
ns.SharedTab.ALIAS="Shared";
inherits(ns.SharedTab,ns.NoeTab);
attribute(ns.SharedTab,"RecordData");
var prot=ns.SharedTab.prototype;
prot.onLoad=function(){var component=this.getComponent().getLegacyComponent();
var namespace=this.getComponent().getLegacyNamespace();
var html=namespace.RenderSharedTab(component);
$("#"+this.getContentId()).html(html);
namespace.CreateSharedTabEvents(component);
};
prot.onSelect=function(){var namespace=this.getComponent().getLegacyNamespace();
if(this.getRecordData()&&typeof namespace.ResizeColumns!=="undefined"){namespace.ResizeColumns(this.getRecordData(),this.getAlias(),this.getComponent().getLegacyComponent());
}};
})();
(function(){var inherits=MPageObjectOriented.inherits;
var attribute=MPageObjectOriented.createAttribute;
var ns=MPageComponents.NewOrderEntry;
ns.SearchTab=function(legacyComponent,namespace,i18n){ns.NoeTab.call(this,legacyComponent,namespace);
this.setButtonTemplate("");
this.setTitle("");
this.setAlias(ns.SearchTab.ALIAS);
};
ns.SearchTab.ALIAS="SearchResults";
inherits(ns.SearchTab,ns.NoeTab);
attribute(ns.SearchTab,"ResultsJson");
var prot=ns.SearchTab.prototype;
prot.onLoad=function(){var comp=this.getComponent();
var templateStr=comp.getTemplates().searchTab;
var template=TemplateBuilder.buildTemplate(templateStr);
$("#"+this.getContentId()).html(template.render(comp.makeRenderParams()));
};
prot.onSelect=function(){var comp=this.getComponent();
if(this.getResultsJson()===undefined){return;
}comp.getLegacyNamespace().LoadSearchResults(JSON.parse(this.getResultsJson()),comp.getLegacyComponent());
};
})();
(function(){var attribute=MPageObjectOriented.createAttribute;
var inherits=MPageObjectOriented.inherits;
var ns=MPageComponents.NewOrderEntry;
ns.HomeTab=function(component){ns.NoeTab.call(this,component);
var legacyComponent=this.getComponent().getLegacyComponent();
this.setTitle(legacyComponent.getUserFavLabel()?legacyComponent.getUserFavLabel():this.getComponent().getI18n().MINE);
this.setAlias(ns.HomeTab.ALIAS);
this.setButtonTemplate(this.getComponent().getTemplates().homeTabButton);
this.setTabMask(384);
};
ns.HomeTab.ALIAS="Home";
inherits(ns.HomeTab,ns.NoeTab);
var prot=ns.HomeTab.prototype;
prot.ALIAS=ns.HomeTab.ALIAS;
prot.getRecordDataArr=function(){return this.getComponent().getRecordData().HOME_FAV;
};
prot.renderTabBody=function(){var baseComponent=this.getComponent();
var namespace=this.getComponent().getLegacyNamespace();
var component=this.getComponent().getLegacyComponent();
var recordData=this.getRecordData();
var html=namespace.RenderHomeTab(component,recordData);
$("#"+this.getContentId()).html(html);
baseComponent.renderFormularyInfo(component.getUid(),recordData.HOME_FAV,"home");
namespace.CreateHomeTabEvents(component,recordData);
};
prot.onSelect=function(){var namespace=this.getComponent().getLegacyNamespace();
if(this.getRecordData()&&typeof namespace.ResizeColumns!=="undefined"){namespace.ResizeColumns(this.getRecordData(),this.getAlias(),this.getComponent().getLegacyComponent());
}};
})();
(function(){MPageComponents.NewOrderEntry.Order=function(){this.synonym=null;
this.sentence=null;
this.synId=null;
this.senId=null;
this.type=null;
};
var Order=MPageComponents.NewOrderEntry.Order;
Order.Types={ORDER:0,CARESET:1,POWERPLAN:2};
})();
