function OncologyStagingComponentWFStyle(){this.initByNamespace("staging-o1");
}OncologyStagingComponentWFStyle.prototype=new ComponentStyle();
OncologyStagingComponentWFStyle.prototype.constructor=ComponentStyle;
function OncologyStagingComponentWF(criterion){this.setCriterion(criterion);
this.setComponentLoadTimerName("USR:MPG.STAGING.O1 - load component");
this.setComponentRenderTimerName("ENG:MPG.STAGING.O1 - render component");
this.setStyles(new OncologyStagingComponentWFStyle());
this.stgwfI18n=i18n.discernabu.stg_wf;
this.setPlusAddCustomInd(true);
this.m_iNumberofStagedForms=0;
this.m_ViewName="Staging";
this.m_isInitialScriptCalled=false;
}OncologyStagingComponentWF.prototype=new MPageComponent();
OncologyStagingComponentWF.prototype.constructor=MPageComponent;
MP_Util.setObjectDefinitionMapping("WF_ONC_STG",OncologyStagingComponentWF);
OncologyStagingComponentWF.prototype.setViewName=function(viewName){this.m_ViewName=viewName;
};
OncologyStagingComponentWF.prototype.getViewName=function(){return this.m_ViewName;
};
OncologyStagingComponentWF.prototype.setFormCount=function(formCnt){this.m_iNumberofStagedForms=formCnt;
};
OncologyStagingComponentWF.prototype.getFormCount=function(){return this.m_iNumberofStagedForms;
};
OncologyStagingComponentWF.prototype.retrieveComponentData=function(){var criterion=this.criterion;
var scriptRequest=new ComponentScriptRequest();
var viewCatagoryMean=this.criterion.category_mean;
var loadTimer=new RTMSTimer(this.getComponentLoadTimerName(),viewCatagoryMean);
var renderTimer=new RTMSTimer(this.getComponentRenderTimerName(),viewCatagoryMean);
scriptRequest.setProgramName("onc_get_form_data_wrapper");
scriptRequest.setParameterArray(["^MINE^",parseInt(criterion.person_id,10)+".0",parseInt(criterion.position_cd,10)+".0",parseInt(criterion.encntr_id,10)+".0","0"]);
scriptRequest.setComponent(this);
scriptRequest.setLoadTimer(loadTimer);
scriptRequest.setRenderTimer(renderTimer);
scriptRequest.performRequest();
};
OncologyStagingComponentWF.prototype.renderComponent=function(replyJSONObject){var layoutHtml="";
var recordData=replyJSONObject;
var compId=this.getComponentId();
var saveStagingTimerObj=null;
var timerMPage=MP_Util.CreateTimer("CAP:MPG Launch Oncology Staging");
if(timerMPage){timerMPage.Stop();
}if(replyJSONObject.STATUS_DATA.STATUS==="S"){this.setFormCount(recordData.QUAL.length);
this.setViewName(recordData.PREF_VIEW_NAME);
this.m_isInitialScriptCalled=false;
if(recordData.QUAL.length){layoutHtml+="<div class='stg-faceup-content' id='stg-faceup-content-"+compId+"-0'><div class='stg-form-header' id='stg-form-header-"+compId+"-0'></div></div>";
layoutHtml+=this.createBasicFormHTML(recordData);
layoutHtml+=this.createLinkButtons(recordData.FORM_COUNTS);
}else{layoutHtml+=this.createAddNewSatagingHTML(recordData);
}layoutHtml+="<div class='stg-details-content' id='stg-details-content-faceup"+compId+"'></div>";
MP_Util.Doc.FinalizeComponent(layoutHtml,this,"");
if(recordData.QUAL.length){this.createStagingOptionsHTML(recordData,0);
}$("#stg-details-content-faceup"+compId).hide();
$("#stg-show-details-form-section"+compId).hide();
this.attachListeners();
}};
OncologyStagingComponentWF.prototype.createAddNewSatagingHTML=function(recordData){var layoutHtml="";
var compId=this.getComponentId();
layoutHtml+="<div class='stg-faceup-content' id='stg-empty-faceup-content"+compId+"'><div class='stg-empty-form-img'></div><div class='stg-empty-msg'><p>"+this.stgwfI18n.NO_STAGING+"<span class='stg-add-form'><a id='stg-add-new-form' actionTypeId='ADDSTAGING' viewName='"+recordData.PREF_VIEW_NAME+"'>"+this.stgwfI18n.ADDSTG+"</a></span></p></div></div>";
return layoutHtml;
};
OncologyStagingComponentWF.prototype.createLinkButtons=function(numOfFormsAvailable){var layoutHtml="";
var compId=this.getComponentId();
layoutHtml+="<div class='stg-show-form-msg'><span class='stg-showall-form' id = 'stg-showall-form-section"+compId+"'><a id='stg-all-form"+compId+"' numOfFormsAvailable = '"+numOfFormsAvailable+"'actionTypeId='SHOWALL'>"+this.stgwfI18n.SHOW_ALL_STG+"("+numOfFormsAvailable+")</a></span><span class='stg-showall-form' id = 'stg-show-recent-form-section"+compId+"' style='display:none'><a id='stg-rcnt-form"+compId+"' numOfFormsAvailable = '"+numOfFormsAvailable+"'actionTypeId='SHOWRECENT'>"+this.stgwfI18n.SHOW_RECENT_STG+"</a></span><span class='stg-showall-form' id = 'stg-show-details-form-section"+compId+"'><a id='stg-all-rcnt-form"+compId+"' formCount = '"+numOfFormsAvailable+"'actionTypeId='SHOWFORM'>"+this.stgwfI18n.SHOW_RECENT_STG+"</a></span></div>";
return layoutHtml;
};
OncologyStagingComponentWF.prototype.createBasicFormHTML=function(recordData){var layoutHtml="";
var compId=this.getComponentId();
for(var formIndex=1;
formIndex<recordData.FORM_COUNTS;
formIndex++){layoutHtml+="<div class='stg-faceup-content-hide' id='stg-faceup-content-"+compId+"-"+formIndex+"'><div class='stg-form-header'  id='stg-form-header-"+compId+"-"+formIndex+"'></div></div>";
}return layoutHtml;
};
OncologyStagingComponentWF.prototype.createStagingOptionsHTML=function(recordData,begCount){var endCount=(begCount===0)?1:recordData.QUAL.length-1;
var lastEditDtz="";
var startDate=new Date();
var compId=this.getComponentId();
for(var formIndex=0;
formIndex<endCount;
formIndex++){var index=(begCount===0)?0:formIndex+1;
var layoutHtml="";
var staginedFormData=recordData.QUAL[formIndex];
var preRecurFormIds=[];
var preRecuredFormFlag=false;
var formIdsObj={};
for(var y=0;
y<recordData.PRERECUR.length;
y++){if(recordData.PRERECUR[y].ID){formIdsObj[recordData.PRERECUR[y].ID]=true;
}}preRecuredFormFlag=typeof formIdsObj[staginedFormData.FORM_ACTIVITY_ID]!=="undefined"?true:false;
var stgHeaderElement="#stg-form-header-"+compId+"-"+index;
var stgInformationElement="#stg-faceup-content-"+compId+"-"+index;
layoutHtml="";
var stagingInfo=this.getStagingFormInfo(staginedFormData);
layoutHtml+="<div class='stg-form-Info' id='stg-form-Info-"+compId+"-"+index+"'>"+stagingInfo[0]+"</div>";
$(stgInformationElement).append(layoutHtml);
layoutHtml="";
var problemName=(staginedFormData.PROBLEM_NAME===""||staginedFormData.PROBLEM_ID===0)?" ":(staginedFormData.PROBLEM_NAME+this.stgwfI18n.DELIMIT);
if(stagingInfo[1]){problemName+=this.stgwfI18n.RECURRENT+","+staginedFormData.FORM_STATUS_DISP;
}else{problemName+=staginedFormData.FORM_STATUS_DISP;
}layoutHtml+="<div class='stg-prblm-name'><p class ='stg-prblm-text' id='stg-prblm-text-"+compId+"-"+index+"'>"+problemName+"</p></div>";
startDate.setISO8601(staginedFormData.VALID_FROM_DT_TM);
lastEditDtz=this.stgwfI18n.LSTEDTD+this.stgwfI18n.DELIMIT+startDate.format("shortDate2")+this.stgwfI18n.AT+startDate.format("shortTime");
layoutHtml+="<div class='stg-last-dttm'><p class ='stg-lstdttm-text' id='stg-lstdttm-text-"+compId+"-"+index+"'>"+lastEditDtz+"</p></div>";
layoutHtml+="<div class='stg-btn-section'>";
layoutHtml+=this.createActionButtons(staginedFormData,index,preRecuredFormFlag,stagingInfo[1],recordData);
layoutHtml+="</div>";
$(stgHeaderElement).append(layoutHtml);
layoutHtml="";
var filteredDtas=this.filterDtas(recordData,formIndex);
layoutHtml+=this.createDtaSection(recordData,filteredDtas);
$(stgInformationElement).append(layoutHtml);
}};
OncologyStagingComponentWF.prototype.getStagingFormInfo=function(staginedFormData){var stgInformationText=[];
var isRecurredForm=0;
var startDate=new Date();
var dateTm=staginedFormData.RECURRENCE_DT_TM;
dateTm=dateTm.slice(6,16);
startDate.setISO8601(staginedFormData.ONSET_DT_TM);
var stagingInformation=this.stgwfI18n.STG_SYSTEM+this.stgwfI18n.DELIMIT+staginedFormData.ONC_DOCSETREF_CAT_ID_DISP+" | "+this.stgwfI18n.STG_FORM+this.stgwfI18n.DELIMIT+staginedFormData.DOC_SET_REF_DESC;
if(staginedFormData.PRE_RECURRENCE_FORM_ACT_ID.toFixed()==="0"){stagingInformation+=" | "+this.stgwfI18n.ONSETDATE+":"+startDate.format("shortDate2");
}else{stagingInformation+=" | "+this.stgwfI18n.ONSETDATE+":"+startDate.format("shortDate2");
if(dateTm!=="0000-00-00"){startDate.setISO8601(staginedFormData.RECURRENCE_DT_TM);
stagingInformation+=" | "+this.stgwfI18n.RECURDATE+":"+startDate.format("shortDate2");
}isRecurredForm=1;
}stgInformationText[0]=stagingInformation;
stgInformationText[1]=isRecurredForm;
return stgInformationText;
};
OncologyStagingComponentWF.prototype.createActionButtons=function(staginedFormData,index,recuredForm,rPrefix,recordData){var layoutHtml="";
var isDetailsDisabled=false;
var isFormInProgress=false;
var compId=this.getComponentId();
if(staginedFormData.FORM_STATUS_CD===recordData.PROGRESS){isFormInProgress=true;
}if(!staginedFormData.TEXTUAL_RENDITION_EVENT_ID){layoutHtml+="<button  disabled class='stg-details-modify-buttons' id='stg-details-button-"+compId+"-"+index+"'action = 'DETAILS'numOfForms = '"+index+"'recuredForm='"+rPrefix+"'eventId='"+staginedFormData.EVENT_ID+"'docSetRefId ='"+staginedFormData.DOC_SET_REF_ID+"'count='"+index+"'>"+this.stgwfI18n.DETAILS+"</button>";
}else{layoutHtml+="<button class='stg-details-modify-buttons' id='stg-details-button-"+compId+"-"+index+"'action = 'DETAILS'numOfForms = '"+index+"'recuredForm='"+rPrefix+"'eventId='"+staginedFormData.EVENT_ID+"'docSetRefId ='"+staginedFormData.DOC_SET_REF_ID+"'count='"+index+"'>"+this.stgwfI18n.DETAILS+"</button>";
}if(recuredForm){layoutHtml+="<button disabled class='stg-details-modify-buttons' id='stg-modify-button-"+compId+"-"+index+"'action = 'MODIFY_RECUR'enctrId = '"+recordData.ENCNTR_ID+"'numOfForms = '"+index+"'formActId = '"+staginedFormData.FORM_ACTIVITY_ID+"'actnType = '2'>"+this.stgwfI18n.MODIFY+"</button><button  disabled class='stg-details-modify-buttons' id='stg-recur-button-"+compId+"-"+index+"'action = 'MODIFY_RECUR'enctrId = '"+recordData.ENCNTR_ID+"'numOfForms = '"+index+"'formActId = '"+staginedFormData.FORM_ACTIVITY_ID+"'actnType = '3'>"+this.stgwfI18n.RECUR+"</button>";
}else{layoutHtml+="<button  class='stg-details-modify-buttons' id='stg-modify-button-"+compId+"-"+index+"'action = 'MODIFY_RECUR'enctrId = '"+recordData.ENCNTR_ID+"'numOfForms = '"+index+"'formActId = '"+staginedFormData.FORM_ACTIVITY_ID+"'actnType = '2'>"+this.stgwfI18n.MODIFY+"</button>";
if(isFormInProgress){layoutHtml+="<button disabled class='stg-details-modify-buttons' id='stg-recur-button-"+compId+"-"+index+"'action = 'MODIFY_RECUR'enctrId = '"+recordData.ENCNTR_ID+"'numOfForms = '"+index+"'formActId = '"+staginedFormData.FORM_ACTIVITY_ID+"'actnType = '3'>"+this.stgwfI18n.RECUR+"</button>";
}else{layoutHtml+="<button  class='stg-details-modify-buttons' id='stg-recur-button-"+compId+"-"+index+"'action = 'MODIFY_RECUR'enctrId = '"+staginedFormData.ENCNTR_ID+"'numOfForms = '"+index+"'formActId = '"+staginedFormData.FORM_ACTIVITY_ID+"'actnType = '3'>"+this.stgwfI18n.RECUR+"</button>";
}}return layoutHtml;
};
OncologyStagingComponentWF.prototype.createDtaSection=function(staginedFormData,filteredDtas){var layoutHtml="";
var stgClinicalData=filteredDtas[0];
var stgPathologicalData=filteredDtas[1];
var stgOtherDtaData=filteredDtas[2];
var isStgClinDataPresnt=false;
var isStgPathDataPresnt=false;
var isStgOthrDataPresnt=false;
for(var i=0;
i<stgClinicalData.length;
i++){if(stgClinicalData[i]!=="NA"){isStgClinDataPresnt=true;
}if(stgPathologicalData[i]!=="NA"){isStgPathDataPresnt=true;
}}if(stgOtherDtaData.length){isStgOthrDataPresnt=true;
}if(isStgClinDataPresnt){layoutHtml+="<div class='stg-clin-rslt-section'><p>"+this.stgwfI18n.CLIN_RESULT+"</p><div class='stg-line'></div>";
layoutHtml+=this.createClinicalPathDataSection(0,stgClinicalData.length,stgClinicalData);
layoutHtml+="</div>";
}if(isStgPathDataPresnt){layoutHtml+="<div class='stg-path-rslt-section'><p>"+this.stgwfI18n.PATH_RESULT+"</p><div class='stg-line'></div>";
layoutHtml+=this.createClinicalPathDataSection(0,stgPathologicalData.length,stgPathologicalData);
layoutHtml+="</div>";
}if(isStgOthrDataPresnt){var strOthrDataArry=["NA","NA","NA","NA","NA","NA","NA","NA","NA","NA","NA","NA","NA","NA","NA","NA"];
var iOtherDtaLength=strOthrDataArry.length;
for(var k=0;
k<stgOtherDtaData.length;
k++){strOthrDataArry[k]=stgOtherDtaData[k];
}if(isStgClinDataPresnt===false&&isStgPathDataPresnt===false){layoutHtml+="<div class='stg-clin-rslt-section'><div class='stg-rslt-heading'><div class='stg-rslt-string'><p>"+this.stgwfI18n.ITEM+'</p></div><div class="stg-rslt-data"><p>'+this.stgwfI18n.RESULT+"</p></div></div>";
layoutHtml+=this.createClinicalPathDataSection(0,stgClinicalData.length,strOthrDataArry);
layoutHtml+="</div>";
if(stgOtherDtaData.length>stgClinicalData.length){layoutHtml+="<div class='stg-path-rslt-section'><div class='stg-rslt-heading'><div class='stg-rslt-string'><p>"+this.stgwfI18n.ITEM+'</p></div><div class="stg-rslt-data"><p>'+this.stgwfI18n.RESULT+"</p></div></div>";
layoutHtml+=this.createClinicalPathDataSection(stgClinicalData.length,iOtherDtaLength,strOthrDataArry);
layoutHtml+="</div>";
}}}return layoutHtml;
};
OncologyStagingComponentWF.prototype.showAllStagingForm=function(compId){$("#stg-details-content-faceup"+compId).hide();
$("#stg-showall-form-section"+compId).hide();
$("#stg-show-recent-form-section"+compId).show();
if(this.m_isInitialScriptCalled===false){this.m_isInitialScriptCalled=true;
this.getAllStagingFormData();
}else{$(".stg-faceup-content-hide").show();
}};
OncologyStagingComponentWF.prototype.getAllStagingFormData=function(){var self=this;
var criterion=this.criterion;
var viewCatagoryMean=criterion.category_mean;
var timerEngShowAllStg=MP_Util.CreateTimer("ENG:MPG.STAGING.O1 - show all staging");
var timerUSRShowAllStg=MP_Util.CreateTimer("USR:MPG.STAGING.O1 - show all staging");
var scriptRequest=new ComponentScriptRequest();
scriptRequest.setProgramName("onc_get_form_data_wrapper");
scriptRequest.setParameterArray(["^MINE^",parseInt(criterion.person_id,10)+".0",parseInt(criterion.position_cd,10)+".0",parseInt(criterion.encntr_id,10)+".0","1"]);
scriptRequest.setComponent(self);
scriptRequest.setResponseHandler(function(scriptReply){if(scriptReply.getResponse().STATUS_DATA.STATUS==="S"){self.createStagingOptionsHTML(scriptReply.getResponse(),1);
$(".stg-faceup-content-hide").show();
self.attachListeners();
if(timerEngShowAllStg){timerEngShowAllStg.Stop();
}if(timerUSRShowAllStg){timerUSRShowAllStg.Stop();
}}});
scriptRequest.performRequest();
};
OncologyStagingComponentWF.prototype.attachListeners=function(){var rootNode=this.getRootComponentNode();
$(rootNode).find("button").on("click",{self:this},this.actionButtons);
$(rootNode).find("a").on("click",{self:this},this.attachShowActions);
};
OncologyStagingComponentWF.prototype.actionButtons=function(event){var element=$(event.target);
var self=event.data.self;
switch(element.attr("action")){case"DETAILS":self.onViewDetails(element.attr("numOfForms"),element.attr("recuredForm"),element.attr("eventId"),element.attr("docSetRefId"),element.attr("count"));
break;
case"MODIFY_RECUR":self.onNavigationBtn(element.attr("formActId"),element.attr("actnType"),self.getViewName());
break;
}};
OncologyStagingComponentWF.prototype.attachShowActions=function(event){var self=event.data.self;
var element=$(event.target);
var compId=self.getComponentId();
switch(element.attr("actionTypeId")){case"SHOWALL":self.showAllStagingForm(compId);
break;
case"SHOWRECENT":self.showRecentStagingForm(compId);
break;
case"SHOWFORM":self.showAllStagingFormDetails(compId);
break;
case"ADDSTAGING":self.onNavigationBtn(0,1,element.attr("viewName"));
break;
}};
OncologyStagingComponentWF.prototype.createClinicalPathDataSection=function(begIndex,endIndex,stgFormData){var layoutHtml="";
for(var x=begIndex;
x<endIndex;
x+=2){if(stgFormData[x]!=="NA"){layoutHtml+='<div class="stg-rslt-row" ><div class="stg-rslt-string" ><p class="stg-ellipsis">'+stgFormData[x]+'</p></div><div class="stg-rslt-data" ><p class="stg-ellipsis">'+stgFormData[x+1]+"</p></div></div>";
}}return layoutHtml;
};
OncologyStagingComponentWF.prototype.filterDtas=function(recordData,formCount){var stgClinicalData=["NA","NA","NA","NA","NA","NA","NA","NA"];
var stgPathologicalData=["NA","NA","NA","NA","NA","NA","NA","NA"];
var stgOtherDtaData=[];
var filteredDtas=[];
for(var iREP1000011Cnt=0;
iREP1000011Cnt<recordData.QUAL[formCount].REP1000011.length;
iREP1000011Cnt++){for(var iREP4102032Cnt=0;
iREP4102032Cnt<recordData.QUAL[formCount].REP4102032.length;
iREP4102032Cnt++){if(recordData.QUAL[formCount].REP1000011[iREP1000011Cnt].TASK_ASSAY_CD.toFixed()===recordData.QUAL[formCount].REP4102032[iREP4102032Cnt].TASK_ASSAY_CD.toFixed()){var bNoTokenMeaning=true;
if(recordData.QUAL[formCount].REP4102032[iREP4102032Cnt].TOKEN_MEANING==="CT"){stgClinicalData=this.filterSectionDTAs(stgClinicalData,recordData,formCount,iREP1000011Cnt,"c",0);
bNoTokenMeaning=false;
}else{if(recordData.QUAL[formCount].REP4102032[iREP4102032Cnt].TOKEN_MEANING==="PT"){stgPathologicalData=this.filterSectionDTAs(stgPathologicalData,recordData,formCount,iREP1000011Cnt,"p",0);
bNoTokenMeaning=false;
}}if(recordData.QUAL[formCount].REP4102032[iREP4102032Cnt].TOKEN_MEANING==="CN"){stgClinicalData=this.filterSectionDTAs(stgClinicalData,recordData,formCount,iREP1000011Cnt,"c",2);
bNoTokenMeaning=false;
}else{if(recordData.QUAL[formCount].REP4102032[iREP4102032Cnt].TOKEN_MEANING==="PN"){stgPathologicalData=this.filterSectionDTAs(stgPathologicalData,recordData,formCount,iREP1000011Cnt,"p",2);
bNoTokenMeaning=false;
}}if(recordData.QUAL[formCount].REP4102032[iREP4102032Cnt].TOKEN_MEANING==="CM"){stgClinicalData=this.filterSectionDTAs(stgClinicalData,recordData,formCount,iREP1000011Cnt,"c",4);
bNoTokenMeaning=false;
}else{if(recordData.QUAL[formCount].REP4102032[iREP4102032Cnt].TOKEN_MEANING==="PM"){stgPathologicalData=this.filterSectionDTAs(stgPathologicalData,recordData,formCount,iREP1000011Cnt,"p",4);
bNoTokenMeaning=false;
}}if(recordData.QUAL[formCount].REP4102032[iREP4102032Cnt].TOKEN_MEANING==="CS"){stgClinicalData=this.filterSectionDTAs(stgClinicalData,recordData,formCount,iREP1000011Cnt," ",6);
bNoTokenMeaning=false;
}else{if(recordData.QUAL[formCount].REP4102032[iREP4102032Cnt].TOKEN_MEANING==="PS"){stgPathologicalData=this.filterSectionDTAs(stgPathologicalData,recordData,formCount,iREP1000011Cnt," ",6);
bNoTokenMeaning=false;
}}}}}for(var iREP1000011Cnt=0;
iREP1000011Cnt<recordData.QUAL[formCount].REP1000011.length;
iREP1000011Cnt++){var bOtherDataExists=false;
for(var iREP4102032Cnt=0;
iREP4102032Cnt<recordData.QUAL[formCount].REP4102032.length;
iREP4102032Cnt++){if(recordData.QUAL[formCount].REP1000011[iREP1000011Cnt].TASK_ASSAY_CD.toFixed()===recordData.QUAL[formCount].REP4102032[iREP4102032Cnt].TASK_ASSAY_CD.toFixed()){bOtherDataExists=true;
}}if(bOtherDataExists===false){stgOtherDtaData.push(recordData.QUAL[formCount].REP1000011[iREP1000011Cnt].EVENT_TITLE_TEXT);
stgOtherDtaData.push(recordData.QUAL[formCount].REP1000011[iREP1000011Cnt].EVENT_TAG);
}}var yClinicalFlag=false;
var yPathologicalFlag=false;
var rPrefixFlag=false;
var aPrefixFlag=false;
var mSuffixFlag=false;
if(recordData.QUAL[formCount].PRE_RECURRENCE_FORM_ACT_ID!==0){rPrefixFlag=true;
}for(var iOtherDtaCount=0;
iOtherDtaCount<stgOtherDtaData.length;
iOtherDtaCount++){if(stgOtherDtaData[iOtherDtaCount]==="y clinical"&&stgOtherDtaData[iOtherDtaCount+1]==="Yes"){yClinicalFlag=true;
}else{if(stgOtherDtaData[iOtherDtaCount]==="y pathologic"&&stgOtherDtaData[iOtherDtaCount+1]==="Yes"){yPathologicalFlag=true;
}else{if(stgOtherDtaData[iOtherDtaCount]==="r prefix"&&stgOtherDtaData[iOtherDtaCount+1]==="Yes"){rPrefixFlag=true;
}else{if(stgOtherDtaData[iOtherDtaCount]==="a prefix"&&stgOtherDtaData[iOtherDtaCount+1]==="Yes"){aPrefixFlag=true;
}else{if(stgOtherDtaData[iOtherDtaCount]==="m suffix"&&stgOtherDtaData[iOtherDtaCount+1]==="Yes"){mSuffixFlag=true;
}}}}}iOtherDtaCount=iOtherDtaCount+1;
}if(yClinicalFlag){if(stgClinicalData[1]!=="NA"){stgClinicalData[1]="y"+stgClinicalData[1];
}if(stgClinicalData[3]!=="NA"){stgClinicalData[3]="y"+stgClinicalData[3];
}if(stgClinicalData[5]!=="NA"){stgClinicalData[5]="y"+stgClinicalData[5];
}}if(yPathologicalFlag){if(stgPathologicalData[1]!=="NA"){stgPathologicalData[1]="y"+stgPathologicalData[1];
}if(stgPathologicalData[3]!=="NA"){stgPathologicalData[3]="y"+stgPathologicalData[3];
}if(stgPathologicalData[5]!=="NA"){stgPathologicalData[5]="y"+stgPathologicalData[5];
}}if(rPrefixFlag){if(stgClinicalData[1]!=="NA"){stgClinicalData[1]="r"+stgClinicalData[1];
}if(stgClinicalData[3]!=="NA"){stgClinicalData[3]="r"+stgClinicalData[3];
}if(stgClinicalData[5]!=="NA"){stgClinicalData[5]="r"+stgClinicalData[5];
}if(stgPathologicalData[1]!=="NA"){stgPathologicalData[1]="r"+stgPathologicalData[1];
}if(stgPathologicalData[3]!=="NA"){stgPathologicalData[3]="r"+stgPathologicalData[3];
}if(stgPathologicalData[5]!=="NA"){stgPathologicalData[5]="r"+stgPathologicalData[5];
}}if(aPrefixFlag){if(stgClinicalData[1]!=="NA"){stgClinicalData[1]="a"+stgClinicalData[1];
}if(stgClinicalData[3]!=="NA"){stgClinicalData[3]="a"+stgClinicalData[3];
}if(stgClinicalData[5]!=="NA"){stgClinicalData[5]="a"+stgClinicalData[5];
}if(stgPathologicalData[1]!=="NA"){stgPathologicalData[1]="a"+stgPathologicalData[1];
}if(stgPathologicalData[3]!=="NA"){stgPathologicalData[3]="a"+stgPathologicalData[3];
}if(stgPathologicalData[5]!=="NA"){stgPathologicalData[5]="a"+stgPathologicalData[5];
}}if(mSuffixFlag){if(stgClinicalData[1]!=="NA"){stgClinicalData[1]=stgClinicalData[1]+"(m)";
}if(stgPathologicalData[1]!=="NA"){stgPathologicalData[1]=stgPathologicalData[1]+"(m)";
}}filteredDtas.push(stgClinicalData);
filteredDtas.push(stgPathologicalData);
filteredDtas.push(stgOtherDtaData);
return filteredDtas;
};
OncologyStagingComponentWF.prototype.filterSectionDTAs=function(stgDtaData,recordData,formIndex,dtaIndex,modifierValue,dtaCnt){stgDtaData[dtaCnt]=recordData.QUAL[formIndex].REP1000011[dtaIndex].EVENT_TITLE_TEXT;
if(recordData.QUAL[formIndex].REP1000011[dtaIndex].RESULT_DISP_CD.toFixed()===recordData.MODIFIED.toFixed()){if(modifierValue!==" "){stgDtaData[dtaCnt+1]=(modifierValue+recordData.QUAL[formIndex].REP1000011[dtaIndex].EVENT_TAG+"(c)");
}else{stgDtaData[dtaCnt+1]=(recordData.QUAL[formIndex].REP1000011[dtaIndex].EVENT_TAG+"(c)");
}}else{stgDtaData[dtaCnt+1]=(modifierValue+recordData.QUAL[formIndex].REP1000011[dtaIndex].EVENT_TAG);
}return stgDtaData;
};
OncologyStagingComponentWF.prototype.onViewDetails=function(formIndex,recuredForm,eventId,docSetRefId,numOfForms){var compId=this.getComponentId();
$("#stg-details-content-faceup"+compId).show();
$(".stg-faceup-content").hide();
$(".stg-faceup-content-hide").hide();
$(".stg-details-content-show").hide();
$("#stg-showall-form-section"+compId).hide();
$("#stg-show-recent-form-section"+compId).hide();
$("#stg-show-details-form-section"+compId).show();
this.fetchFormDetails(formIndex,recuredForm,eventId,docSetRefId);
};
OncologyStagingComponentWF.prototype.fetchFormDetails=function(formId,isRecuredForm,eventId,docSetRefId){var self=this;
var criterion=this.criterion;
var recurdForm=0;
var viewCatagoryMean=criterion.category_mean;
var timerMPage=MP_Util.CreateTimer("CAP:MPG View Oncology Staging");
if(timerMPage){timerMPage.Stop();
}var scriptRequest=new ComponentScriptRequest();
scriptRequest.setProgramName("onc_stg_get_form_details");
scriptRequest.setParameterArray(["^MINE^",isRecuredForm+".0",eventId+".0",docSetRefId+".0"]);
scriptRequest.setComponent(this);
scriptRequest.setResponseHandler(function(scriptReply){if(scriptReply.getResponse().STATUS_DATA.STATUS==="S"){self.displayFormDetails(formId,scriptReply.getResponse());
}});
scriptRequest.performRequest();
};
OncologyStagingComponentWF.prototype.displayFormDetails=function(formId,recordData){var compId=this.getComponentId();
var layoutHtml="";
var $componentDom=$("#stg-details-content-faceup"+compId);
var lastDtStrList=$("#stg-lstdttm-text-"+compId+"-"+formId).text();
var stgInfText=$("#stg-form-Info-"+compId+"-"+formId).text();
var problemList=$("#stg-prblm-text-"+compId+"-"+formId).text();
var eventTitle=[];
var eventTag=[];
var eventDtTm=[];
var dtaDate=new Date();
for(var ki=0;
ki<recordData.AVAILABLEDTA;
ki++){eventTitle.push("NA");
eventTag.push("NA");
eventDtTm.push("NA");
}for(var ti=0;
ti<recordData.DTAINFO.length;
ti++){eventTitle[ti]=recordData.DTAINFO[ti].EVENT_TITLE_TEXT;
eventTag[ti]=recordData.DTAINFO[ti].EVENT_TAG;
dtaDate.setISO8601(recordData.DTAINFO[ti].ACTION_DT_TM);
var df=new mp_formatter.DateTimeFormatter(MPAGE_LOCALE);
eventDtTm[ti]=df.format(dtaDate,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_4YEAR);
}layoutHtml+="<div class='stg-details-content-show' style='display:none;' id='stg-details-content-faceup"+formId+"-"+compId+"'><div class='stg-form-header' ><div class='stg-prblm-name'><p class ='stg-prblm-text'>"+problemList+"</p></div><div class='stg-modify-content'><p class ='stg-lstdttm-text'>"+lastDtStrList+"</p></div></div><div class='stg-form-Info'>"+stgInfText+"</div>";
layoutHtml+=this.createResultSection(formId,eventTitle,eventTag,eventDtTm,0,recordData.CLINDTA);
if(recordData.DTAINFO.length>recordData.PATHDTA){layoutHtml+=this.createResultSection(formId,eventTitle,eventTag,eventDtTm,recordData.PATHDTA,recordData.AVAILABLEDTA);
}$componentDom.append(layoutHtml);
var showdetailsdiv="#stg-details-content-faceup"+formId+"-"+compId;
$(showdetailsdiv).show();
};
OncologyStagingComponentWF.prototype.showAllStagingFormDetails=function(compId){$("#stg-details-content-faceup"+compId).hide();
$("#stg-showall-form-section"+compId).show();
$("#stg-show-recent-form-section"+compId).hide();
$("#stg-show-details-form-section"+compId).hide();
$(".stg-faceup-content").hide();
$("#stg-faceup-content-"+compId+"-0").show();
};
OncologyStagingComponentWF.prototype.showRecentStagingForm=function(compId){$(".stg-details-content").hide();
$(".stg-faceup-content-hide").hide();
$("#stg-showall-form-section"+compId).show();
$("#stg-show-recent-form-section"+compId).hide();
$(".stg-faceup-content").hide();
$("#stg-faceup-content-"+compId+"-0").show();
};
OncologyStagingComponentWF.prototype.onNavigationBtn=function(formActivityId,actionType,stgViewName){var criterion=this.criterion;
var compId=this.getComponentId();
if(criterion.encntr_id){var timerMPage=MP_Util.CreateTimer("CAP:MPG Modify Oncology Staging");
if(timerMPage){timerMPage.Stop();
}var sendAr=[];
var request=new ScriptRequest();
request.setProgramName("onc_set_formactivityid");
request.setParameterArray(["^MINE^",criterion.person_id+".0",criterion.encntr_id+".0",actionType+".00",formActivityId+".0"]);
request.setResponseHandler(function(recordReply){if(recordReply.getResponse().STATUS_DATA.STATUS!=="S"){var errorModal=MP_Util.generateModalDialogBody("noMode"+compId,"error","",i18n.discernabu.stg_wf.NO_MODE);
errorModal.setHeaderTitle(i18n.discernabu.stg_wf.ERROR_OCCURED);
var closeButton=new ModalButton("noModeCloseButton"+compId);
closeButton.setText(i18n.discernabu.stg_wf.CLOSE).setCloseOnClick(true);
errorModal.addFooterButton(closeButton);
MP_ModalDialog.updateModalDialogObject(errorModal);
MP_ModalDialog.showModalDialog("noMode"+compId);
}});
request.performRequest();
APPLINK(0,"powerchart.exe","/PERSONID="+criterion.person_id+" /ENCNTRID="+criterion.encntr_id+" /FIRSTTAB="+stgViewName+"");
}else{var errorModal=MP_Util.generateModalDialogBody("noEnconuterError"+compId,"error","",i18n.discernabu.stg_wf.NO_ENCOUNTER);
errorModal.setHeaderTitle(i18n.discernabu.stg_wf.ERROR_OCCURED);
var closeButton=new ModalButton("closeButton"+compId);
closeButton.setText(i18n.discernabu.stg_wf.CLOSE).setCloseOnClick(true);
errorModal.addFooterButton(closeButton);
MP_ModalDialog.updateModalDialogObject(errorModal);
MP_ModalDialog.showModalDialog("noEnconuterError"+compId);
}};
OncologyStagingComponentWF.prototype.createResultSection=function(formIndex,eventTitle,eventTag,eventDtTm,bgnCount,endCount){var layoutHtml="";
layoutHtml+="<div class='stg-show-more-details-section' id='stg-show-more-details-section"+formIndex+'\' ><div class="stg-rslt-heading"><div class="stg-rslt-item"><p class="stg-ellipsis">'+i18n.discernabu.stg_wf.ITEM+'</p></div><div class="stg-rslt"><p class="stg-ellipsis">'+i18n.discernabu.stg_wf.RESULT+'</p></div><div class="stg-rslt-dttm"><p class="stg-ellipsis">'+i18n.discernabu.stg_wf.RESULT_DT_TM+"</p></div></div>";
for(var x=bgnCount;
x<endCount;
x++){if(eventTitle[x]!=="NA"){layoutHtml+='<div class="stg-rslt-row"><div class="stg-rslt-item"><p class="stg-ellipsis" >'+eventTitle[x]+'</p></div><div class="stg-rslt" ><p class="stg-ellipsis" >'+eventTag[x]+'</p></div><div class="stg-rslt-dttm" ><p class="stg-ellipsis" >'+eventDtTm[x]+"</p></div></div>";
}}layoutHtml+="</div>";
return layoutHtml;
};
OncologyStagingComponentWF.prototype.openTab=function(){this.onNavigationBtn(0,1,this.getViewName());
};
