function OrdersOpt2ComponentStyle(){this.initByNamespace("ord2");
}OrdersOpt2ComponentStyle.inherits(ComponentStyle);
function OrdersOpt2Component(criterion){this.m_catalogCodes=[];
this.m_orderStatuses=[];
this.setCriterion(criterion);
this.setStyles(new OrdersOpt2ComponentStyle());
this.setComponentLoadTimerName("USR:MPG.ORDERS.O2 - load component");
this.setComponentRenderTimerName("ENG:MPG.ORDERS.O2 - render component");
this.setIncludeLineNumber(true);
this.setAlwaysExpanded(true);
CERN_EventListener.addListener(this,EventListener.EVENT_ORDER_ACTION,this.retrieveComponentData,this);
}OrdersOpt2Component.prototype=new MPageComponent();
OrdersOpt2Component.prototype.constructor=MPageComponent;
OrdersOpt2Component.prototype.setCatalogCodes=function(catalogCodes){this.m_catalogCodes=catalogCodes;
};
OrdersOpt2Component.prototype.getCatalogCodes=function(){return this.m_catalogCodes;
};
OrdersOpt2Component.prototype.setOrderStatuses=function(orderStatuses){this.m_orderStatuses=orderStatuses;
};
OrdersOpt2Component.prototype.getOrderStatuses=function(){return this.m_orderStatuses;
};
OrdersOpt2Component.prototype.resizeComponent=function(){MPageComponent.prototype.resizeComponent.call(this,null);
var sectionNode=this.getSectionContentNode();
var contentBody=$(sectionNode).find(".content-body");
if(contentBody.length){var maxHeight=parseInt($(contentBody).css("max-height").replace("px",""),10);
if(!isNaN(maxHeight)){var totalHeightOfAllElements=0;
$(contentBody).find(".ord2-info").each(function(){totalHeightOfAllElements+=$(this).height();
});
if(totalHeightOfAllElements>=maxHeight){$(sectionNode).find(".content-hdr").addClass("ord2-hdr-shifted");
}else{$(sectionNode).find(".content-hdr").removeClass("ord2-hdr-shifted");
}}}};
OrdersOpt2Component.prototype.loadFilterMappings=function(){this.addFilterMappingObject("WF_INCOMPLETE_ORDERS_CAT_TYPE",{setFunction:this.setCatalogCodes,type:"ARRAY",field:"PARENT_ENTITY_ID"});
this.addFilterMappingObject("WF_INCOMPLETE_ORDERS_STATUS",{setFunction:this.setOrderStatuses,type:"ARRAY",field:"PARENT_ENTITY_ID"});
};
OrdersOpt2Component.prototype.retrieveComponentData=function(){var criterion=null;
var encntrOption="0.0";
var request=null;
var self=this;
var sendAr=null;
criterion=this.getCriterion();
encntrOption=(this.getScope()==2)?(criterion.encntr_id+".0"):"0.0";
sendAr=["^MINE^",criterion.person_id+".0",encntrOption,criterion.provider_id+".0",this.getLookbackUnits(),this.getLookbackUnitTypeFlag(),MP_Util.CreateParamArray(this.getCatalogCodes(),1),MP_Util.CreateParamArray(this.getOrderStatuses(),1),criterion.ppr_cd+".0"];
request=new MP_Core.ScriptRequest(this,this.getComponentLoadTimerName());
request.setProgramName("MP_GET_OUTSTANDING_ORDERS");
request.setParameters(sendAr);
request.setAsync(true);
MP_Core.XMLCCLRequestCallBack(this,request,function(reply){self.renderComponent(reply);
});
};
OrdersOpt2Component.prototype.renderComponent=function(reply){var compId=this.getComponentId();
var countText="";
var dateTime=new Date();
var errMsg=[];
var j=0;
var ordArray=[];
var ordDateTime="";
var orderLen=0;
var orders=null;
var ordI18n=i18n.discernabu.orders_o2;
var ordLongDateTime="";
var recordData=null;
var replyStatus="";
var strtLongDateTime="";
var timerRenderComponent=null;
var zebraStripe="";
try{timerRenderComponent=MP_Util.CreateTimer(this.getComponentRenderTimerName());
replyStatus=reply.getStatus();
if(replyStatus!=="S"){if(replyStatus=="F"){errMsg.push(reply.getError());
this.finalizeComponent(MP_Util.HandleErrorResponse(this.getStyles().getNameSpace(),errMsg.join("<br />")),"");
}else{this.finalizeComponent(MP_Util.HandleNoDataResponse(this.getStyles().getNameSpace()),"(0)");
}CERN_EventListener.fireEvent(this,this,EventListener.EVENT_COUNT_UPDATE,{count:0});
return;
}ordArray.push("<div class='content-hdr'><dl class='result-info ord2-info-hdr hdr'><dd class='ord2-nm-hd'>&nbsp;</dd><dd class='ord2-st-hd'>",ordI18n.STATUS,"</dd><dd class='ord2-dt-hd'>",ordI18n.ORDERED,"</dd></dl></div>");
recordData=reply.getResponse();
ordArray.push("<div class='content-body'>");
orderLen=recordData.ORDERS.length;
for(j=0;
j<orderLen;
j++){orders=recordData.ORDERS[j];
dateTime.setISO8601(orders.ORIG_ORDER_DT_TM);
ordDateTime=dateTime.format("longDateTime2");
ordLongDateTime=dateTime.format("longDateTime3");
dateTime.setISO8601(orders.CURRENT_START_DT_TM);
strtLongDateTime=dateTime.format("longDateTime3");
zebraStripe=(j%2)?"odd":"even";
ordArray.push("<h3 class='info-hd'>",i18n.RESULT,"</h3><dl class='result-info ord2-info ",zebraStripe,"'><dd class='ord2-name'>",orders.NAME,"</dd><dd class='ord2-status'>",orders.STATUS,"</dd><dd class='ord2-date date-time'>",ordDateTime,"</dd></dl><div class='result-details'><dl class='ord2-det'><dt><span>",ordI18n.ORDER_NAME,":</span></dt><dd><span>",orders.HOVER_NAME,"</span></dd><dt><span>",ordI18n.ORDER_DETAILS,":</span></dt><dd><span>",orders.CLINICAL_DISPLAY_LINE,"</span></dd><dt><span>",ordI18n.ORDER_COMMENTS,":</span></dt><dd><span>",orders.ORDER_COMMENT.replace(/\n/g,"<br />"),"</span></dd><dt><span>",ordI18n.ORDER_DATE,":</span></dt><dd><span>",ordLongDateTime,"</span></dd><dt><span>",ordI18n.START_DT_TM,":</span></dt><dd><span>",strtLongDateTime,"</span></dd><dt><span>",ordI18n.ORDER_STATUS,":</span></dt><dd><span>",orders.STATUS,"</span></dd><dt><span>",ordI18n.ORDER_PHYS,":</span></dt><dd><span>",orders.RESPONSIBLE_PROVIDER,"</span></dd></dl></div>");
}ordArray.push("</div>");
countText=MP_Util.CreateTitleText(this,orderLen);
this.applyTemplate("list-as-table");
this.finalizeComponent(ordArray.join(""),countText);
CERN_EventListener.fireEvent(this,this,EventListener.EVENT_COUNT_UPDATE,{count:orderLen});
}catch(err){if(timerRenderComponent){timerRenderComponent.Abort();
timerRenderComponent=null;
}MP_Util.LogJSError(this,err,"orders-o2.js","renderComponent");
throw (err);
}finally{if(timerRenderComponent){timerRenderComponent.Stop();
}}};
MP_Util.setObjectDefinitionMapping("WF_INCOMPLETE_ORDERS",OrdersOpt2Component);
