function PartogramContractComponentWFStyle(){this.initByNamespace("parto-contract-wf");
}PartogramContractComponentWFStyle.prototype=new ComponentStyle();
PartogramContractComponentWFStyle.prototype.constructor=ComponentStyle;
function PartogramContractComponentWF(criterion){this.setCriterion(criterion);
this.setStyles(new PartogramContractComponentWFStyle());
this.setComponentLoadTimerName("USR:MPG.PARTOGRAMCONTRACT.O2 - load component");
this.setComponentRenderTimerName("ENG:MPG.PARTOGRAMCONTRACT.O2 - render component");
this.setImageFolderPath(criterion.static_content+"/images/");
this.NOMEN_MAPPING={};
this.setRefreshEnabled(false);
this.setResourceRequired(true);
this.groupNameMap={};
this.contractionI18n=i18n.discernabu.partogramcontract_o2;
this.strongIntensityLabel=this.contractionI18n.STRONG;
this.weakIntensityLabel=this.contractionI18n.MILD;
this.notPalpableIntensityLabel=this.contractionI18n.NOT_PALPABLE;
this.moderateIntensityLabel=this.contractionI18n.MODERATE;
this.loadTimer=null;
}PartogramContractComponentWF.prototype=new MPageComponent();
PartogramContractComponentWF.prototype.constructor=MPageComponent;
MP_Util.setObjectDefinitionMapping("WF_PARTO_CONTRACT",PartogramContractComponentWF);
PartogramContractComponentWF.prototype.HOVER_KEY="CONTRACTIONS";
PartogramContractComponentWF.prototype.getImageFolderPath=function(){return this.imageFolderPath;
};
PartogramContractComponentWF.prototype.setImageFolderPath=function(path){this.imageFolderPath=path;
};
PartogramContractComponentWF.prototype.getRecordData=function(){return this.recordData;
};
PartogramContractComponentWF.prototype.setRecordData=function(data){this.recordData=data;
};
PartogramContractComponentWF.prototype.getPlot=function(){return this.plot;
};
PartogramContractComponentWF.prototype.setPlot=function(plot){this.plot=plot;
};
PartogramContractComponentWF.prototype.getGraphElement=function(){return this.graphElement;
};
PartogramContractComponentWF.prototype.setGraphElement=function(el){this.graphElement=el;
};
PartogramContractComponentWF.prototype.loadFilterMappings=function(){this.addFilterMappingObject("WF_PARTO_CONTRACT_STR_NOMEN",{setFunction:this.setStrongIntensityNomen,type:"ARRAY",field:"NOMEN"});
this.addFilterMappingObject("WF_PARTO_CONTRACT_MOD_NOMEN",{setFunction:this.setModerateIntensityNomen,type:"ARRAY",field:"NOMEN"});
this.addFilterMappingObject("WF_PARTO_CONTRACT_WK_NOMEN",{setFunction:this.setWeakIntensityNomen,type:"ARRAY",field:"NOMEN"});
this.addFilterMappingObject("WF_PARTO_CONTRACT_NP_NOMEN",{setFunction:this.setNotPalpIntensityNomen,type:"ARRAY",field:"NOMEN"});
this.addFilterMappingObject("WF_PARTO_CONTRACT_STR_LABEL",{setFunction:this.setStrongIntensityLabel,type:"STRING",field:"FREETEXT_DESC"});
this.addFilterMappingObject("WF_PARTO_CONTRACT_NP_LABEL",{setFunction:this.setNotPalpIntensityLabel,type:"STRING",field:"FREETEXT_DESC"});
this.addFilterMappingObject("WF_PARTO_CONTRACT_WK_LABEL",{setFunction:this.setWeakIntensityLabel,type:"STRING",field:"FREETEXT_DESC"});
this.addFilterMappingObject("WF_PARTO_CONTRACT_MOD_LABEL",{setFunction:this.setModerateIntensityLabel,type:"STRING",field:"FREETEXT_DESC"});
};
PartogramContractComponentWF.prototype.setStrongIntensityLabel=function(value){this.strongIntensityLabel=value;
};
PartogramContractComponentWF.prototype.setWeakIntensityLabel=function(value){this.weakIntensityLabel=value;
};
PartogramContractComponentWF.prototype.setModerateIntensityLabel=function(value){this.moderateIntensityLabel=value;
};
PartogramContractComponentWF.prototype.setNotPalpIntensityLabel=function(value){this.notPalpableIntensityLabel=value;
};
PartogramContractComponentWF.prototype.setStrongIntensityNomen=function(value){this.NOMEN_MAPPING.STRONG=value;
};
PartogramContractComponentWF.prototype.setModerateIntensityNomen=function(value){this.NOMEN_MAPPING.MODERATE=value;
};
PartogramContractComponentWF.prototype.setWeakIntensityNomen=function(value){this.NOMEN_MAPPING.WEAK=value;
};
PartogramContractComponentWF.prototype.setNotPalpIntensityNomen=function(value){this.NOMEN_MAPPING.NOT_PALP=value;
};
PartogramContractComponentWF.prototype.RetrieveRequiredResources=function(){if(PartogramBaseComponent.prototype.getPartogramViewID()!==this.getCriterion().category_mean){var messageHTML="<span class='res-none'>"+i18n.discernabu.partogrambaseutil_o2.NOT_PARTOGRAM_VIEW+"</span>";
this.finalizeComponent(messageHTML,"");
return;
}var partogramInfoSR=MP_Resources.getSharedResource("partogramInfo");
if(partogramInfoSR&&partogramInfoSR.isResourceAvailable()&&!jQuery.isEmptyObject(partogramInfoSR.getResourceData())){this.retrieveComponentData();
}else{CERN_EventListener.addListener(this,"partogramInfoAvailable",this.retrieveComponentData,this);
}};
PartogramContractComponentWF.prototype.retrieveComponentData=function(){try{var criterion=this.getCriterion();
if(PartogramBaseComponent.prototype.getPartogramViewID()!==criterion.category_mean){var messageHTML="<span class='res-none'>"+i18n.discernabu.partogrambaseutil_o2.NOT_PARTOGRAM_VIEW+"</span>";
this.finalizeComponent(messageHTML,"");
return;
}this.loadTimer=new RTMSTimer(this.getComponentLoadTimerName());
var renderTimer=new RTMSTimer(this.getComponentRenderTimerName());
var groups=this.getGroups();
var groupsLength=groups.length;
if(groupsLength===2&&!jQuery.isEmptyObject(this.NOMEN_MAPPING)){var sendAr=[],i;
var partogramInfoSR=MP_Resources.getSharedResource("partogramInfo");
var partogramStartDate=partogramInfoSR.getResourceData().getPartogramStartDate();
partogramStartDate=MP_Util.CreateDateParameter(partogramStartDate);
sendAr.push("^MINE^",criterion.person_id+".0",criterion.provider_id+".0",criterion.ppr_cd+".0",criterion.encntr_id+".0");
var groupNames=["WF_PARTO_CONTRACT_FREQUENCY","WF_PARTO_CONTRACT_INTENSITY"];
for(i=0;
i<groupNames.length;
i++){this.groupNameMap[groupNames[i]]=[0];
}for(i=0;
i<groupsLength;
i++){var group=groups[i];
if(group instanceof MPageEventCodeGroup){this.groupNameMap[group.m_groupName]=group.getEventCodes();
}}for(i=0;
i<groupNames.length;
i++){sendAr.push(MP_Util.CreateParamArray(this.groupNameMap[groupNames[i]],1));
}sendAr.push("^"+partogramStartDate+"^");
var scriptRequest=new ComponentScriptRequest();
scriptRequest.setProgramName("MP_GET_PARTOGRAM_CONTRACT");
scriptRequest.setParameterArray(sendAr);
scriptRequest.setComponent(this);
scriptRequest.setLoadTimer(this.loadTimer);
scriptRequest.setRenderTimer(renderTimer);
scriptRequest.performRequest();
}else{var noEventCodeMappedMessage="<span class='res-none'> "+i18n.discernabu.partogrambaseutil_o2.NOT_CONFIGURED_BEDROCK_ERR+"</span>";
this.finalizeComponent(noEventCodeMappedMessage,"");
}}catch(err){MP_Util.LogJSError(err,this,"partogramcontract.js","retrieveComponentData");
}};
PartogramContractComponentWF.prototype.isPartOfIntensity=function(intensityArr,val){var len=intensityArr.length;
for(var i=0;
i<len;
i++){if(intensityArr[i].nomen_id===val){return true;
}}return false;
};
PartogramContractComponentWF.prototype.getPlotLines=function(){var recordData=this.getRecordData();
var frequencyKey=recordData.FREQUENCY_EVENT_CODE_NAME;
var intensityKey=recordData.INTENSITY_EVENT_CODE_NAME;
var plotLines=[[],[],[],[],[]];
var dataLen=recordData.CNT;
var i;
var stateMap={STRONG:0,MODERATE:1,WEAK:2,NOT_PALP:3,NO_INTEN_DOC:4};
var stateNameMap={STRONG:this.strongIntensityLabel,MODERATE:this.moderateIntensityLabel,WEAK:this.weakIntensityLabel,NOT_PALP:this.notPalpableIntensityLabel,NO_INTEN_DOC:this.contractionI18n.NO_INTENSITY_DOC};
var stateImageMap={STRONG:"partoContractSprite partoContractStrong",MODERATE:"partoContractSprite partoContractMod",WEAK:"partoContractSprite partoContractWeak",NOT_PALP:"partoContractSprite partoContractNotPalp",NO_INTEN_DOC:"partoContractSprite partoContractNoInten"};
var buildFrequencyValue=function(contractionsPoint){var resultValue=contractionsPoint.FREQUENCY;
var NO_UNIT="";
var normalcyClass=PARTO_GRAPH_BASE.getNormalcyClass(contractionsPoint.RESULT_NORMALCY);
var modifiedInd=contractionsPoint.RESULT_MODIFIED_IND_FREQ;
return PARTO_GRAPH_BASE.getResultIndHTML(resultValue,NO_UNIT,normalcyClass,modifiedInd);
};
var buildIntensityValue=function(contractionsPoint,intensityName){var resultValue=intensityName;
var NO_UNIT="";
var normalcyClass=PARTO_GRAPH_BASE.getNormalcyClass(contractionsPoint.RESULT_NORMALCY);
var modifiedInd=contractionsPoint.RESULT_MODIFIED_IND_INTEN;
return PARTO_GRAPH_BASE.getResultIndHTML(resultValue,NO_UNIT,normalcyClass,modifiedInd);
};
PARTO_GRAPH_BASE.clearHoverMap(this.HOVER_KEY);
recordData.CONTRACTION.sort(function(a,b){return new Date(a.RESULT_DATE)-new Date(b.RESULT_DATE);
});
var intensityHoverValue="";
var imageHTML="";
for(i=0;
i<dataLen;
i++){var contraction=recordData.CONTRACTION[i];
if(contraction.FREQUENCY&&contraction.FREQUENCY.length>0){var frequencyVal=parseInt(contraction.FREQUENCY,10);
var arr=contraction.INTENSITY.split(";");
var timestamp=PARTO_GRAPH_BASE.getLocalDateTime(contraction.RESULT_DATE);
var frequencyHoverValue=buildFrequencyValue(contraction);
if(arr.length<2){plotLines[stateMap.NO_INTEN_DOC].push([timestamp,frequencyVal]);
PARTO_GRAPH_BASE.insertSeriesIntoHoverMap(this.HOVER_KEY,timestamp,"",frequencyKey,frequencyHoverValue);
continue;
}var nomenID=parseInt($.trim(arr[1]),10);
if(this.NOMEN_MAPPING.STRONG){if(this.isPartOfIntensity(this.NOMEN_MAPPING.STRONG,nomenID)){intensityHoverValue=buildIntensityValue(contraction,stateNameMap.STRONG);
imageHTML='<div class="'+stateImageMap.STRONG+'"><div>';
plotLines[stateMap.STRONG].push([timestamp,frequencyVal]);
PARTO_GRAPH_BASE.insertSeriesIntoHoverMap(this.HOVER_KEY,timestamp,"",frequencyKey,frequencyHoverValue);
PARTO_GRAPH_BASE.insertSeriesIntoHoverMap(this.HOVER_KEY,timestamp,imageHTML,intensityKey,intensityHoverValue);
}}if(this.NOMEN_MAPPING.MODERATE){if(this.isPartOfIntensity(this.NOMEN_MAPPING.MODERATE,nomenID)){intensityHoverValue=buildIntensityValue(contraction,stateNameMap.MODERATE);
imageHTML='<div class="'+stateImageMap.MODERATE+'"><div>';
plotLines[stateMap.MODERATE].push([timestamp,frequencyVal]);
PARTO_GRAPH_BASE.insertSeriesIntoHoverMap(this.HOVER_KEY,timestamp,"",frequencyKey,frequencyHoverValue);
PARTO_GRAPH_BASE.insertSeriesIntoHoverMap(this.HOVER_KEY,timestamp,imageHTML,intensityKey,intensityHoverValue);
}}if(this.NOMEN_MAPPING.WEAK){if(this.isPartOfIntensity(this.NOMEN_MAPPING.WEAK,nomenID)){intensityHoverValue=buildIntensityValue(contraction,stateNameMap.WEAK);
imageHTML='<div class="'+stateImageMap.WEAK+'"><div>';
plotLines[stateMap.WEAK].push([timestamp,frequencyVal]);
PARTO_GRAPH_BASE.insertSeriesIntoHoverMap(this.HOVER_KEY,timestamp,"",frequencyKey,frequencyHoverValue);
PARTO_GRAPH_BASE.insertSeriesIntoHoverMap(this.HOVER_KEY,timestamp,imageHTML,intensityKey,intensityHoverValue);
}}if(this.NOMEN_MAPPING.NOT_PALP){if(this.isPartOfIntensity(this.NOMEN_MAPPING.NOT_PALP,nomenID)){intensityHoverValue=buildIntensityValue(contraction,stateNameMap.NOT_PALP);
imageHTML='<div class="'+stateImageMap.NOT_PALP+'"><div>';
plotLines[stateMap.NOT_PALP].push([timestamp,frequencyVal]);
PARTO_GRAPH_BASE.insertSeriesIntoHoverMap(this.HOVER_KEY,timestamp,"",frequencyKey,frequencyHoverValue);
PARTO_GRAPH_BASE.insertSeriesIntoHoverMap(this.HOVER_KEY,timestamp,imageHTML,intensityKey,intensityHoverValue);
}}}}if(plotLines[0].length===0){plotLines[0].push([null]);
}return plotLines;
};
PartogramContractComponentWF.prototype.getComponentHTML=function(){var compID=this.getStyles().getContentId();
var compHTML='<div class="partogram-container">';
compHTML+='<div class="partogram-container-col-1">';
compHTML+=this.getLegendHTML();
compHTML+="</div>";
compHTML+='<div class="partogram-container-col-2">';
compHTML+=PARTO_GRAPH_BASE.createTopBar(this.getImageFolderPath(),"GRAPH");
compHTML+='<div id="partogram-contract-graph-container'+compID+'"><div id="partogram-contract-graph-'+compID+'" class="partogramGraphDiv"></div></div>';
compHTML+="</div>";
compHTML+="</div>";
return compHTML;
};
PartogramContractComponentWF.prototype.getLegendHTML=function(){var layoutHTML="",imageClassName;
var compID=this.getComponentId();
layoutHTML+='<div class="partogram-legend" id="partogram-legend-'+compID+'">';
var labelArr=[this.strongIntensityLabel,this.moderateIntensityLabel,this.weakIntensityLabel,this.notPalpableIntensityLabel,this.contractionI18n.NO_INTENSITY_DOC];
var stateMap=["STRONG","MODERATE","WEAK","NOT_PALP"];
var imageClassNames=["partoContractStrong","partoContractMod","partoContractWeak","partoContractNotPalp","partoContractNoInten"];
for(var i=0;
i<4;
i++){if(this.NOMEN_MAPPING[stateMap[i]]){imageClassName="partoContractSprite "+imageClassNames[i];
layoutHTML+='<div class="partogram-contract-legend-item">';
layoutHTML+='<div class="partogram-contract-legend-img">';
layoutHTML+='<div class="'+imageClassName+'"></div>';
layoutHTML+="</div>";
layoutHTML+='<div title="'+labelArr[i]+'" class="partogram-contract-legend-item-name"><span>'+labelArr[i]+"</span></div>";
layoutHTML+="</div>";
}}imageClassName="partoContractSprite "+imageClassNames[4];
layoutHTML+='<div class="partogram-contract-legend-item">';
layoutHTML+='<div class="partogram-contract-legend-img">';
layoutHTML+='<div class="'+imageClassName+'"></div>';
layoutHTML+="</div>";
layoutHTML+='<div title="'+labelArr[4]+'" class="partogram-contract-legend-item-name"><span>'+labelArr[4]+"</span></div>";
layoutHTML+="</div>";
layoutHTML+="</div>";
return layoutHTML;
};
PartogramContractComponentWF.prototype.graphToolTipContent=function(){var component=this;
var tooltipFunction=function(str,seriesIndex,pointIndex,plot){PARTO_GRAPH_BASE.setToolTipLocation(plot,seriesIndex,pointIndex);
var data=plot.data[seriesIndex][pointIndex];
var time=data[0];
return PARTO_GRAPH_BASE.getHoverHTML(component.HOVER_KEY,time);
};
return tooltipFunction;
};
PartogramContractComponentWF.prototype.plotGraph=function(){var contentID=this.getStyles().getContentId();
var compHTML=this.getComponentHTML();
jQuery("#"+contentID).append(compHTML);
var contractPlots=this.getPlotLines();
var options=this.generateGraphOptions();
var widthOffset=PARTO_GRAPH_BASE.getWidthOffsetForGraph();
var currentWidth=parseInt($("#partogram-contract-graph-"+contentID).css("width"),10);
$("#partogram-contract-graph-"+contentID).css("width",currentWidth-widthOffset);
var plot=$.jqplot("partogram-contract-graph-"+contentID,contractPlots,options);
this.setPlot(plot);
this.setGraphElement(document.getElementById("partogram-contract-graph-"+contentID));
PARTO_GRAPH_BASE.setGraphsCommonCSS();
if(!PARTO_GRAPH_BASE.topBarGraphHTML){PARTO_GRAPH_BASE.refreshTopbar(contentID);
}};
PartogramContractComponentWF.prototype.getSeriesObjects=function(){var seriesArray=[];
var contractNPImage=new Image();
contractNPImage.src=this.getImageFolderPath()+"partoContractNotPalp.png";
var highlighterOption={tooltipContentEditor:this.graphToolTipContent(),showTooltip:true,tooltipLocation:"n"};
var series=function(colorVal){return{markerOptions:{show:true,style:"filledSquare",shadow:false},showLine:false,xaxis:"x2axis",yaxis:"yaxis",lineWidth:1,color:colorVal,highlighter:highlighterOption};
};
var colorVals=["#ca0813","#fc6621","#ffc20a","#ffffff","#505050"];
seriesArray.push(series(colorVals[0]));
seriesArray.push(series(colorVals[1]));
seriesArray.push(series(colorVals[2]));
seriesArray.push({markerRenderer:$.jqplot.ImageMarkerRenderer,markerOptions:{show:true,imageElement:contractNPImage,xOffset:-5.5,yOffset:-5,shadow:false},showLine:false,xaxis:"x2axis",yaxis:"yaxis",color:"#505050",highlighter:highlighterOption});
seriesArray.push(series(colorVals[4]));
return seriesArray;
};
PartogramContractComponentWF.prototype.getGraphOptions=function(startDt,endDt,hourticks,quarterticks,seriesObjs,canvasOverlayObjs){return{graphName:"partogram-contract-graph-"+this.getStyles().getId(),series:seriesObjs,seriesDefaults:{showMarker:false,pointLabels:{show:false},hoverable:false,highlightMouseDown:true,shadow:false},axes:{yaxis:{min:0,max:10,tickInterval:1,tickOptions:{showMark:false,showLabel:true,formatString:"%d"},ticks:(function(){var labels=[["-1",""]];
for(var i=0;
i<=10;
i++){labels.push(i+"");
}return labels;
})()},xaxis:{renderer:$.jqplot.DateAxisRenderer,show:true,tickOptions:{show:true,showLabel:false,showMark:false},min:startDt,max:endDt,ticks:quarterticks},x2axis:{renderer:$.jqplot.DateAxisRenderer,tickOptions:{showMark:false,showLabel:false,formatString:"%R"},min:startDt,max:endDt,ticks:hourticks}},axesDefaults:{tickOptions:{textColor:PARTO_GRAPH_BASE.COLOR_DARK_GRAY,fontSize:"11px"}},canvasOverlay:{show:true,objects:canvasOverlayObjs},grid:{drawGridLines:true,hoverable:false,shadow:false,background:PARTO_GRAPH_BASE.GRID_BACKGROUND_COLOR,gridLineWidth:1,gridLineColor:PARTO_GRAPH_BASE.MINOR_GRID_LINE_COLOR,drawBorder:false},cursor:{showTooltip:false,show:false}};
};
PartogramContractComponentWF.prototype.generateGraphOptions=function(){var endDt=PARTO_GRAPH_BASE.getEndDate();
var canvasOverlayObjs=[];
canvasOverlayObjs=canvasOverlayObjs.concat(PARTO_GRAPH_BASE.getMajorGridLines());
canvasOverlayObjs=canvasOverlayObjs.concat(PARTO_GRAPH_BASE.getOxytocinVerticalLines());
canvasOverlayObjs=canvasOverlayObjs.concat(PARTO_GRAPH_BASE.getEpiduralVerticalLines());
if(endDt>=PARTO_GRAPH_BASE.getPartogramLastLoadTime()){canvasOverlayObjs=canvasOverlayObjs.concat(PARTO_GRAPH_BASE.getTodayVerticalBar());
}var hourticks=PARTO_GRAPH_BASE.getHourTicks();
var quarterticks=PARTO_GRAPH_BASE.getQuarterTicks();
var seriesObjs=this.getSeriesObjects();
var options=this.getGraphOptions(PARTO_GRAPH_BASE.getStartDate(),endDt,hourticks,quarterticks,seriesObjs,canvasOverlayObjs);
return options;
};
PartogramContractComponentWF.prototype.renderComponent=function(recordData){var timerRenderComponent=MP_Util.CreateTimer(this.getComponentRenderTimerName(),this.getCriterion().category_mean);
var renderingCAPTimer=new CapabilityTimer("CAP:MPG.PARTOGRAMCONTRACT.O2 - rendering component",this.getCriterion().category_mean);
if(renderingCAPTimer){renderingCAPTimer.capture();
}try{var basei18n=i18n.discernabu.partogrambaseutil_o2;
var noDataHTML="<span class='res-none'>"+basei18n.NO_RESULTS_FOUND+"</span>";
var resultsCount=recordData.CNT;
this.loadTimer.addMetaData("component.resultcount",resultsCount);
if(resultsCount>0){PARTO_GRAPH_BASE.addSubscriber(this);
recordData.FREQUENCY_EVENT_CODE_NAME=PARTO_GRAPH_BASE.removeColonEndOfString(recordData.FREQUENCY_EVENT_CODE_NAME);
recordData.INTENSITY_EVENT_CODE_NAME=PARTO_GRAPH_BASE.removeColonEndOfString(recordData.INTENSITY_EVENT_CODE_NAME);
this.finalizeComponent("",MP_Util.CreateTitleText(this,""));
this.setRecordData(recordData);
this.plotGraph();
PARTO_GRAPH_BASE.addTimeScaleButtons(this.getStyles().getId());
}else{this.finalizeComponent(noDataHTML,MP_Util.CreateTitleText(this,""));
}$("#"+this.getStyles().getId()).css("margin-bottom",PARTO_GRAPH_BASE.getComponentBottomPadding());
}catch(err){MP_Util.LogJSError(err,this,"partogramcontract.js","RenderComponent");
if(timerRenderComponent){timerRenderComponent.Abort();
timerRenderComponent=null;
}}finally{if(timerRenderComponent){timerRenderComponent.Stop();
}}};
