function PregAssessment2StyleWF(){this.initByNamespace("pa2-wf");
}PregAssessment2StyleWF.inherits(ComponentStyle);
function PregAssessment2ComponentWF(criterion){this.setCriterion(criterion);
this.setLookBackDropDown(true);
this.setStyles(new PregAssessment2StyleWF());
this.setComponentLoadTimerName("USR:MPG.SECONDARYASSESSMENT.O2 - load component");
this.setComponentRenderTimerName("ENG:MPG.SECONDARYASSESSMENT.O2 - render component");
this.setPregnancyLookbackInd(true);
this.setResourceRequired(true);
this.assessmentSection=2;
CERN_EventListener.addListener(this,"pregnancyInfoAvailable",this.retrieveComponentData,this);
}PregAssessment2ComponentWF.prototype=new MPageComponent();
PregAssessment2ComponentWF.prototype.constructor=MPageComponent;
MP_Util.setObjectDefinitionMapping("WF_PREG_SA",PregAssessment2ComponentWF);
PregAssessment2ComponentWF.prototype.preProcessing=function(){var criterion=this.getCriterion();
var compMenu=this.getMenu();
var compId=this.getComponentId();
var pai18n=i18n.discernabu.pregassessmentbase_o2;
var fundalGraphItem=new MenuSelection("fundalGraph"+compId);
var laborGraphItem=new MenuSelection("laborGraph"+compId);
var patientGenderInfo=criterion.getPatientInfo().getSex();
var self=this;
if(!this.isDisplayable()||!compMenu){return;
}if(patientGenderInfo===null||patientGenderInfo.meaning===null||patientGenderInfo.meaning!=="FEMALE"){return;
}fundalGraphItem.setLabel(pai18n.FUNDAL_HEIGHT);
fundalGraphItem.setClickFunction(function(clickEvent){clickEvent.id="fundal"+compId;
self.menuItemOnClickHandler(clickEvent);
});
laborGraphItem.setLabel(pai18n.LABOR_GRAPH);
laborGraphItem.setClickFunction(function(clickEvent){clickEvent.id="labor"+compId;
self.menuItemOnClickHandler(clickEvent);
});
compMenu.addMenuItem(fundalGraphItem);
compMenu.addMenuItem(laborGraphItem);
MP_MenuManager.updateMenuObject(compMenu);
};
PregAssessment2ComponentWF.prototype.menuItemOnClickHandler=function(clickEvent){var criterion=this.getCriterion();
var pai18n=i18n.discernabu.pregassessmentbase_o2;
var eventId=clickEvent.id;
var compId=this.getComponentId();
var pregInfoSR=null;
var pregInfoObj=null;
var pregDiscernObject=null;
pregInfoSR=MP_Resources.getSharedResource("pregnancyInfo");
if(pregInfoSR&&pregInfoSR.isResourceAvailable()){pregInfoObj=pregInfoSR.getResourceData();
}else{return;
}try{pregDiscernObject=window.external.DiscernObjectFactory("PREGNANCY");
MP_Util.LogDiscernInfo(this,"PREGNANCY","pregnancyassessment2-o2.js","menuItemOnClickHandler");
if(eventId==="fundal"+compId){pregDiscernObject.LaunchFundalHeightGraph(window,criterion.person_id,pregInfoObj.getPregnancyId());
}else{if(eventId==="labor"+compId){pregDiscernObject.LaunchLaborGraph(window,criterion.person_id,pregInfoObj.getPregnancyId());
}}}catch(discernErr){MP_Util.LogJSError(discernErr,this,"pregnancyassessment2-o2.js","menuItemOnClickHandler");
return;
}pregDiscernObject=null;
};
PregAssessment2ComponentWF.prototype.removeMenuOptions=function(){var menuComp=this.getMenu();
var compId=this.getComponentId();
var menuItems=menuComp.getMenuItemArray();
var menuId="";
var fundalGraphItem="fundalGraph"+compId;
for(i=0;
i<menuItems.length;
i++){menuId=menuItems[i].m_menuItemId;
if(menuId===fundalGraphItem){menuComp.removeMenuItem(menuItems[i]);
break;
}}var laborGraphItem="laborGraph"+compId;
for(i=0;
i<menuItems.length;
i++){menuId=menuItems[i].m_menuItemId;
if(menuId===laborGraphItem){menuComp.removeMenuItem(menuItems[i]);
break;
}}if(menuItems.length===0){$("#"+menuComp.getAnchorElementId()).addClass("opts-menu-empty").unbind("click");
}};
PregAssessment2ComponentWF.prototype.RetrieveRequiredResources=function(){var pregInfoObj=null;
pregInfoObj=MP_Resources.getSharedResource("pregnancyInfo");
if(pregInfoObj&&pregInfoObj.isResourceAvailable()){this.retrieveComponentData();
}else{PREGNANCY_BASE_UTIL_O1.LoadPregnancyData(this.getCriterion());
}};
PregAssessment2ComponentWF.prototype.retrieveComponentData=function(){var sendAr=[];
var criterion=this.getCriterion();
var encntrOption=0;
var messageHTML="";
var pai18n=i18n.discernabu.pregassessmentbase_o2;
var pregInfoObj=null;
var pregInfoSR=MP_Resources.getSharedResource("pregnancyInfo");
var pregnancyId=0;
var lookBackUnits=this.getLookbackUnits();
var lookBackUnitTypeFlag=this.getLookbackUnitTypeFlag();
var df=MP_Util.GetDateFormatter();
var countText="";
var current_encntr=criterion.encntr_id;
encntrOption=this.getScope();
var patientGenderInfo=criterion.getPatientInfo().getSex();
if(patientGenderInfo===null||patientGenderInfo.meaning===null||patientGenderInfo.meaning!=="FEMALE"){messageHTML="<h3 class='info-hd'><span class='res-normal'>"+pai18n.NOT_FEMALE+"</span></h3><span class='res-none'>"+pai18n.NOT_FEMALE+"</span>";
this.finalizeComponent(messageHTML,countText);
return;
}else{if(pregInfoSR&&pregInfoSR.isResourceAvailable()){pregInfoObj=pregInfoSR.getResourceData();
pregnancyId=pregInfoObj.getPregnancyId();
if(pregnancyId===-1){this.removeMenuOptions();
messageHTML="<h3 class='info-hd'><span class='res-normal'>";
messageHTML+=pai18n.PREG_DATA_ERROR+"</span></h3><span class='res-none'>";
messageHTML+=pai18n.PREG_DATA_ERROR+"</span>";
this.finalizeComponent(messageHTML,countText);
return;
}else{if(!pregnancyId){this.removeMenuOptions();
messageHTML="<h3 class='info-hd'><span class='res-normal'>"+pai18n.NO_ACTIVE_PREG+"</span></h3><span class='res-none'>"+pai18n.NO_ACTIVE_PREG+"</span>";
this.finalizeComponent(messageHTML,countText);
return;
}else{sendAr.push("^MINE^",criterion.person_id+".0",criterion.provider_id+".0",criterion.position_cd+".0",criterion.ppr_cd+".0",pregInfoObj.getLookBack(),this.assessmentSection,"0.0");
var groups=this.getGroups();
for(var i=0;
i<groups.length;
i++){var group=groups[i];
if(group instanceof MPageEventSetGroup){sendAr.push(MP_Util.CreateParamArray(group.getEventSets(),1));
}}sendAr.push(lookBackUnits,lookBackUnitTypeFlag,current_encntr,encntrOption);
MP_Core.XMLCclRequestWrapper(this,"MP_GET_PREG_ASSESSMENT",sendAr,true);
}}}}};
PregAssessment2ComponentWF.prototype.renderComponent=function(recordData){var criterion=this.getCriterion();
var slaTimer=MP_Util.CreateTimer("CAP:MPG.SECONDARYASSESSMENT.O2- rendering component");
if(slaTimer){slaTimer.SubtimerName=criterion.category_mean;
slaTimer.Stop();
}CERN_PREG_ASSESSMENT_BASE_O2.RenderAssessmentSection(this,recordData,this.assessmentSection);
};
