function QuickVisitStyle(){this.initByNamespace("qv");
}QuickVisitStyle.prototype=new ComponentStyle();
QuickVisitStyle.prototype.constructor=ComponentStyle;
function QuickVisit(criterion){this.setCriterion(criterion);
this.setStyles(new QuickVisitStyle());
this.setComponentLoadTimerName("USR:MPG.QUICKVISIT.O2 - load component");
this.setComponentRenderTimerName("ENG:MPG.QUICKVISIT.O2 - render component");
this.setPlusAddCustomInd(false);
this.i18n=i18n.discernabu.quickVisit;
this.searchControl={};
this.specialityBundles=[];
this.allBundles=[];
this.completedReceipts=[];
this.specialityGrp=[];
this.activeTabName="SPECIALITY";
this.bundleLauncher=new QuickVisit.LaunchBundle(criterion,this.getComponentId());
}QuickVisit.prototype=new MPageComponent();
QuickVisit.prototype.constructor=MPageComponent;
MP_Util.setObjectDefinitionMapping("WF_QUICK_VISIT",QuickVisit);
QuickVisit.prototype.setActiveTabName=function(tabName){if(typeof tabName!=="string"||tabName.length===0){throw new Error("Invalid tab name");
}this.activeTabName=tabName.toUpperCase();
};
QuickVisit.prototype.getActiveTabName=function(){return this.activeTabName;
};
QuickVisit.prototype.setSearchControl=function(obj){if(!(obj instanceof MPageControls.AutoSuggest)){throw new Error("setsearchControl expected an object of type MPagesControls.AutoSuggest");
}this.searchControl=obj;
};
QuickVisit.prototype.getSearchControl=function(){return this.searchControl;
};
QuickVisit.prototype.setAllBundleData=function(data){if(!Array.isArray(data)){throw new Error("Speciality Bundles data is not an array");
}this.allBundles=data;
};
QuickVisit.prototype.getAllBundleData=function(){return this.allBundles;
};
QuickVisit.prototype.setSpecialityBundleData=function(data){if(!Array.isArray(data)){throw new Error("Speciality Bundles data is not an array");
}this.specialityBundles=data;
};
QuickVisit.prototype.getSpecialityBundleData=function(){return this.specialityBundles;
};
QuickVisit.prototype.setCompletedReceipts=function(data){if(!Array.isArray(data)){throw new Error("Completed Receipts data is not an array");
}this.completedReceipts=data;
};
QuickVisit.prototype.getCompletedReceipts=function(){return this.completedReceipts;
};
QuickVisit.prototype.getBundleLauncher=function(){return this.bundleLauncher;
};
QuickVisit.prototype.setSpecialityGroups=function(specialityGrp){this.specialityGrp=specialityGrp;
};
QuickVisit.prototype.getSpecialityGroups=function(){return this.specialityGrp;
};
QuickVisit.prototype.loadFilterMappings=function(){this.addFilterMappingObject("WF_QUICK_VISIT_SPECIALITY",{setFunction:this.setSpecialityGroups,type:"ARRAY",field:"PARENT_ENTITY_ID"});
};
QuickVisit.prototype.getContentByType=function(contentType){switch(contentType.toUpperCase()){case"ALL":return this.getAllBundleData();
case"SPECIALITY":return this.getSpecialityBundleData();
default:throw new Error("Incorrect parameter to getContentByType");
}};
QuickVisit.prototype.setContentByType=function(contentType,content){switch(contentType.toUpperCase()){case"ALL":this.setAllBundleData(content);
break;
case"SPECIALITY":this.setSpecialityBundleData(content);
break;
default:throw new Error("Incorrect parameter to getContentByType");
}};
QuickVisit.prototype.refreshComponent=function(){this.searchControl={};
this.specialityBundles=[];
this.allBundles=[];
this.completedReceipts=[];
MPageComponent.prototype.refreshComponent.call(this);
};
QuickVisit.prototype.retrieveComponentData=function(){var criterion=this.getCriterion();
var specialityGrps=this.getSpecialityGroups();
var loadTimer=new RTMSTimer(this.getComponentLoadTimerName(),criterion.category_mean);
var renderTimer=new RTMSTimer(this.getComponentRenderTimerName(),criterion.category_mean);
var scriptRequest=new ComponentScriptRequest();
if(specialityGrps.length>0){scriptRequest.setProgramName("MP_QV_GET_BUNDLE_BY_GROUP");
scriptRequest.setParameterArray(["^MINE^",MP_Util.CreateParamArray(specialityGrps,1)]);
scriptRequest.setComponent(this);
scriptRequest.setLoadTimer(loadTimer);
scriptRequest.setRenderTimer(renderTimer);
scriptRequest.performRequest();
}else{this.renderComponent({LIST:[]});
this.postProcessing();
}};
QuickVisit.prototype.renderComponent=function(recordData){var layoutHtml="";
var compId=this.getComponentId();
try{this.setContentByType("speciality",recordData.LIST);
layoutHtml="<div id='quickVisit"+compId+"'>"+this.createCompSkeleton()+"</div>";
this.finalizeComponent(layoutHtml,"");
}catch(err){logger.logError(err);
throw (err);
}};
QuickVisit.prototype.createHeaderTabs=function(){return"<div class='qv-tab-div qv-speciality-tab qv-active-tab'><button class = 'qv-tab'> "+this.i18n.specialityTab+" </button></div><div class='qv-tab-div qv-all-tab'><button class = 'qv-tab'> "+this.i18n.allTab+" </button></div>";
};
QuickVisit.prototype.createTabsContentSections=function(){return"<div class = 'qv-speciality-content'>"+this.createTabContent("speciality")+"</div><div class = 'qv-all-content hidden'></div>";
};
QuickVisit.prototype.createTabContent=function(tabName){var html="";
var bundleData=this.getContentByType(tabName);
var cnt=0;
for(cnt=0;
cnt<bundleData.length;
cnt++){html+=this.createRow(bundleData[cnt]);
}return html;
};
QuickVisit.prototype.createRow=function(details){return"<div title = '"+details.QV_BUNDLE_NAME+"' class = 'qv-bundle-row' bundle_id = '"+details.CP_PATHWAY_ID+"'><div class = 'qv-bundle'><span>"+details.QV_BUNDLE_NAME+"</span></div><div class = 'qv-buttons'><input type = 'button' class = 'qv-bundle-button' value = '"+this.i18n.open+"'></div></div>";
};
QuickVisit.prototype.createCompletedReceipts=function(){var html="";
var completedReceipts=this.getCompletedReceipts();
var cnt=0;
for(cnt=0;
cnt<completedReceipts.length;
cnt++){html+="<div>TODO</div>";
}return html;
};
QuickVisit.prototype.createCompSkeleton=function(){return"<div class = 'qv-sections qv-left'><div class = 'qv-search-header'><div class='qv-tabs-sec'>"+this.createHeaderTabs()+"</div><div class = 'qv-search'><form onsubmit = 'return false'><div id = 'qvSearch"+this.getComponentId()+"'></div></form></div></div><div class = 'qv-search-content'>"+this.createTabsContentSections()+"</div></div><div style='display: none;' class = 'qv-sections qv-right'><div class = 'qv-receipt-container'><div class = 'qv-completed-receipt'><div class = 'qv-completed-headers'><div>"+this.i18n.completedReceiptsLbl+"</div></div><div class = 'qv-completed-body'>"+this.createCompletedReceipts()+"<div></div></div></div>";
};
QuickVisit.prototype.postProcessing=function(){var rootNode=$(this.getSectionContentNode());
var compId=this.getComponentId();
var searchControl=null;
searchControl=new MPageControls.AutoSuggest($("#qvSearch"+compId));
searchControl.setCaption(this.i18n.search);
searchControl.activateCaption();
searchControl.processTextboxKeyDown=function(e){if(searchControl.getValue()===""){this.searchBundles(searchControl.getValue());
}MPageControls.AutoSuggest.prototype.processTextboxKeyDown.call(searchControl,e);
}.bind(this);
searchControl.setOnDelay(function(){this.searchBundles(searchControl.getValue());
}.bind(this));
searchControl.setOnClose(function(){this.searchBundles("");
}.bind(this));
this.setSearchControl(searchControl);
rootNode.find(".qv-tabs-sec").on("click",".qv-tab-div",{self:this},this.handleTabChange);
rootNode.find(".qv-search-content").on("click",".qv-bundle-button",{self:this},this.handleAddBundleClick);
};
QuickVisit.prototype.handleAddBundleClick=function(event){var self=event.data.self;
var rowParentNode=$(this).parent().parent();
self.getBundleLauncher().launchBundle(rowParentNode.attr("bundle_id"),rowParentNode.attr("title"));
};
QuickVisit.prototype.handleTabChange=function(event){var self=event.data.self;
var rootNode=$(self.getSectionContentNode());
self.getSearchControl().activateCaption();
self.searchBundles("");
if($(this).hasClass("qv-speciality-tab")){rootNode.find(".qv-speciality-content").removeClass("hidden");
rootNode.find(".qv-all-content").addClass("hidden");
$(this).addClass("qv-active-tab");
rootNode.find(".qv-all-tab").removeClass("qv-active-tab");
self.tabChangeActionHandler("SPECIALITY");
}else{rootNode.find(".qv-speciality-content").addClass("hidden");
rootNode.find(".qv-all-content").removeClass("hidden");
rootNode.find(".qv-speciality-tab").removeClass("qv-active-tab");
$(this).addClass("qv-active-tab");
self.tabChangeActionHandler("ALL");
}};
QuickVisit.prototype.tabChangeActionHandler=function(tabName){var tabData=[];
switch(tabName.toUpperCase()){case"ALL":tabData=this.getAllBundleData();
this.setActiveTabName("ALL");
if(tabData.length===0){this.addSpinnerToActiveTabContent();
this.retrieveAllBundle(this.updateTabContent);
}break;
case"SPECIALITY":this.setActiveTabName("SPECIALITY");
break;
}};
QuickVisit.prototype.addSpinnerToActiveTabContent=function(){var activeTabName=this.getActiveTabName();
var className=this.getContentClassByTabName(activeTabName);
var contentNode=$(this.getSectionContentNode()).find(className);
contentNode.html("<div class='loading-spinner'>&nbsp;</div>");
};
QuickVisit.prototype.removeSpinnerFromActiveTabContent=function(){var activeTabName=this.getActiveTabName();
var className=this.getContentClassByTabName(activeTabName);
var contentNode=$(this.getSectionContentNode()).find(className);
contentNode.children().remove(".loading-spinner");
};
QuickVisit.prototype.getContentClassByTabName=function(tabName){var className="";
switch(tabName.toUpperCase()){case"ALL":className=".qv-all-content";
break;
case"SPECIALITY":className=".qv-speciality-content";
break;
}return className;
};
QuickVisit.prototype.updateTabContent=function(tabName,tabData){var rootNode=$(this.getSectionContentNode());
this.removeSpinnerFromActiveTabContent();
switch(tabName.toUpperCase()){case"ALL":this.setContentByType(tabName,tabData);
rootNode.find(".qv-all-content").html(this.createTabContent(tabName));
break;
}};
QuickVisit.prototype.retrieveAllBundle=function(callback){var scriptRequest=new ScriptRequest();
scriptRequest.setProgramName("MP_QV_GET_BUNDLE_BY_GROUP");
scriptRequest.setParameterArray(["^MINE^","0.0"]);
scriptRequest.setResponseHandler(function(scriptReply){if(scriptReply.getStatus()==="S"){callback.call(this,"all",scriptReply.getResponse().LIST);
}else{logger.LogScriptCallError(this,"MP_QV_GET_BUNDLE_BY_GROUP","QuickVisit.js","retrieveAllBundle");
}}.bind(this));
scriptRequest.performRequest();
};
QuickVisit.prototype.searchBundles=function(searchText){var activeTabName=this.getActiveTabName();
var bundleData=this.getContentByType(activeTabName);
var indexesToHide=[];
if(searchText!==""){searchText=searchText.toUpperCase();
indexesToHide=bundleData.reduce(function(indexesCollection,bundle,idx){if(bundle.QV_BUNDLE_NAME.toUpperCase().indexOf(searchText)>-1){indexesCollection.push(idx);
}return indexesCollection;
},indexesToHide);
this.searchDomUpdate(indexesToHide,false);
}else{this.searchDomUpdate(indexesToHide,true);
}};
QuickVisit.prototype.searchDomUpdate=function(indexesToHide,showAllBundles){var searchContentNode=$(this.getSectionContentNode()).find(".qv-search-content");
var activeTabName=this.getActiveTabName();
var contentNode=null;
var className=this.getContentClassByTabName(activeTabName);
contentNode=searchContentNode.find(className).detach();
if(!showAllBundles){contentNode.children().each(function(idx){if(indexesToHide.indexOf(idx)>-1){$(this).removeClass("hidden");
}else{$(this).addClass("hidden");
}});
}else{contentNode.children().each(function(){$(this).removeClass("hidden");
});
}searchContentNode.append(contentNode);
};
QuickVisit.LaunchBundle=function(criterion,compId){this.criterion=criterion;
this.compId=compId;
this.modalObj=null;
};
QuickVisit.LaunchBundle.prototype.getCriterion=function(){return this.criterion;
};
QuickVisit.LaunchBundle.prototype.getCompId=function(){return this.compId;
};
QuickVisit.LaunchBundle.prototype.getModalDialog=function(){if(!this.modalObj){this.modalObj=new ModalDialog("qvModal"+this.getCompId());
this.modalObj.setHeaderTitle("Quick Visit");
this.modalObj.setHeaderCloseFunction(function(){this.closeModal();
}.bind(this));
MP_ModalDialog.addModalDialogObject(this.modalObj);
}return this.modalObj;
};
QuickVisit.LaunchBundle.prototype.launchBundle=function(bundleId,bundleName){this.renderModal(bundleId,bundleName);
};
QuickVisit.LaunchBundle.prototype.renderModal=function(bundleId,bundleName){var modalObj=this.getModalDialog();
var modalId=modalObj.getId();
var id="qv-"+this.getCompId()+"-"+parseInt(bundleId,10);
modalObj.setHeaderTitle(bundleName);
MP_ModalDialog.showModalDialog(modalId);
modalObj.setBodyHTML("<div class = 'qv-bundle-area' id = '"+id+"' style='height:100%;'><div class='qv-overlay-div'><span class='qv-img-spinner'></span></div></div>");
this.retrieveBundleData(bundleId,function(reply){this.toggleSpinner(false);
this.bundleCreate(id,reply);
}.bind(this));
};
QuickVisit.LaunchBundle.prototype.retrieveBundleData=function(bundleId,callback){var request=new ScriptRequest();
var criterion=this.getCriterion();
request.setProgramName("MP_QV_GET_BUNDLE");
request.setParameterArray(["MINE",parseInt(bundleId,10)+".0",criterion.encntr_id+".0",criterion.ppr_cd+".0"]);
request.setResponseHandler(function(scriptReply){callback(scriptReply.getResponse());
});
request.performRequest();
};
QuickVisit.LaunchBundle.prototype.closeModal=function(){MP_ModalDialog.closeModalDialog(this.getModalDialog().getId());
};
QuickVisit.LaunchBundle.prototype.toggleSpinner=function(toShow){var spinnerElem=$("#"+this.getModalDialog().getBodyElementId()).find(".qv-overlay-div").first();
if(toShow){spinnerElem.show();
}else{spinnerElem.hide();
}};
QuickVisit.LaunchBundle.prototype.bundleCreate=function(id,cclReply){var bundleForm;
var data={orders:cclReply.ORDERS,charges:cclReply.CHARGES,prescriptions:cclReply.PRESCRIPTIONS,education:cclReply.PAT_EDU,followup:cclReply.FOLLOW_UP,diagnosis:cclReply.NOMENCLATURE,id:cclReply.CP_PATHWAY_ID,preloadedTitle:cclReply.QV_BUNDLE_NAME};
var options={header:"",preloadData:data,isComponentMode:true,isEditMode:false,callBackFunc:{self:this,saveFunc:this.submitBundle.bind(this),closeFunc:this.closeModal.bind(this)}};
bundleForm=new BundleForm(id,options);
bundleForm.render();
};
QuickVisit.LaunchBundle.prototype.submitBundle=function(compRef,bundleData){if(!this.isBundleEmpty(bundleData)){if(this.isBundleDataHasOrders(bundleData)){this.toggleSpinner(true);
this.submitOrders(bundleData);
this.toggleSpinner(false);
}this.submitBundleData(bundleData);
}};
QuickVisit.LaunchBundle.prototype.getNomenclatureIdFromBundleData=function(bundleData){var selectedNomenclatureId=0;
bundleData.diagnosis.forEach(function(diag){if(diag.selected_ind===1){selectedNomenclatureId=diag.nomenclature_id;
}});
return selectedNomenclatureId;
};
QuickVisit.LaunchBundle.prototype.isItemSelected=function(item){return item.selected_ind===1;
};
QuickVisit.LaunchBundle.prototype.isBundleDataHasOrders=function(bundleData){return bundleData.orders.some(this.isItemSelected)||bundleData.charges.some(this.isItemSelected)||bundleData.prescriptions.some(this.isItemSelected);
};
QuickVisit.LaunchBundle.prototype.isBundleEmpty=function(bundleData){return !this.isBundleDataHasOrders(bundleData)&&!bundleData.education.some(this.isItemSelected)&&!bundleData.followup.some(this.isItemSelected)&&this.getNomenclatureIdFromBundleData(bundleData)===0;
};
QuickVisit.LaunchBundle.prototype.submitBundleData=function(bundleData){var criterion=this.getCriterion();
var request=new ScriptRequest();
var paramJson="";
var recData={person_id:criterion.person_id,encntr_id:criterion.encntr_id,ppr_cd:criterion.ppr_cd,nomenclature_id:!this.isBundleDataHasOrders(bundleData)?this.getNomenclatureIdFromBundleData(bundleData):0,pat_edu:[],follow_up:[]};
bundleData.education.reduce(function(patEdCollection,patEd){if(patEd.selected_ind===1){patEdCollection.push({key_doc_ident:patEd.key_doc_ident,doc_lang_id:patEd.doc_lang_id,domain_cd:patEd.domain_cd,pat_ed_reltn_id:patEd.pat_ed_reltn_id});
}return patEdCollection;
},recData.pat_edu);
bundleData.followup.reduce(function(followUpColl,data){if(data.selected_ind===1){followUpColl.push({follow_up_id:data.follow_up_id,is_quick_pick:data.is_quick_pick===true?1:0});
}return followUpColl;
},recData.follow_up);
paramJson=JSON.stringify({submit_bundle:recData}).replace(/"/g,"'");
paramJson=paramJson.replace(/:([0-9]+)/g,":$1.0");
request.setProgramName("MP_QV_SUBMIT_BUNDLE");
request.setParameterArray(["MINE","^"+paramJson+"^"]);
request.setResponseHandler(function(scriptReply){this.toggleSpinner(false);
this.closeModal();
}.bind(this));
this.toggleSpinner(true);
request.performRequest();
};
QuickVisit.LaunchBundle.prototype.submitOrders=function(bundleData){var criterion=this.getCriterion();
var params=[criterion.person_id+".0|",criterion.encntr_id+".0|"];
var selectedNomenclatureId=this.getNomenclatureIdFromBundleData(bundleData);
function getSentenceIdForSynonym(order){if(order.sentence_list.length>0){return order.sentence_list[0].sentence_id;
}return 0;
}function addToOrderParam(order){if(order.selected_ind===1){params.push("{ORDER|"+order.synonym_id+"|0|"+getSentenceIdForSynonym(order)+"|"+selectedNomenclatureId+"|1}");
}}bundleData.orders.forEach(addToOrderParam);
bundleData.charges.forEach(addToOrderParam);
bundleData.prescriptions.forEach(addToOrderParam);
params.push("|24|{2|127}{3|127}|32|1");
logger.logMPagesEventInfo(null,"ORDERS",params.join(""),"QuickVisit.js","QuickVisit");
MPAGES_EVENT("ORDERS",params.join(""));
};
var BundleForm=function(id,options){options=options||{};
this.i18n=i18n.quickVisit;
this.domId=id;
this.selections={};
this.header=options.header?options.header:"";
this.preloadData=options.preloadData?options.preloadData:{};
this.setCallBackFunc(options.callBackFunc);
this.isEditMode=options.isEditMode?options.isEditMode:false;
this.isComponentMode=options.isComponentMode?options.isComponentMode:false;
};
BundleForm.prototype.getComponentMode=function(){return this.isComponentMode;
};
BundleForm.prototype.getEditMode=function(){return this.isEditMode;
};
BundleForm.prototype.setCallBackFunc=function(callBackObj){if(callBackObj&&(typeof callBackObj.saveFunc!=="function")){throw new Error("BundleForm.prototype.setCallBackFunc expects at least a save function and a reference to the calling class.");
}if(callBackObj&&callBackObj.closeFunc&&(typeof callBackObj.closeFunc!=="function")){throw new Error("BundleForm.prototype.setCallBackFunc expects at least a close function and a reference to the calling class.");
}this.callBackFunc=callBackObj;
};
BundleForm.prototype.getCallBackFunc=function(){return this.callBackFunc;
};
BundleForm.prototype.getSelections=function(){return this.selections;
};
BundleForm.prototype.setSelections=function(obj){this.selections=obj;
};
BundleForm.prototype.getDomId=function(){return this.domId;
};
BundleForm.prototype.setDomId=function(id){this.domId=id;
};
BundleForm.prototype.setHeader=function(header){this.header=header;
};
BundleForm.prototype.getHeader=function(){return this.header;
};
BundleForm.prototype.setPreloadData=function(data){this.preloadData=data;
};
BundleForm.prototype.getPreloadData=function(){return this.preloadData;
};
BundleForm.prototype.render=function(){this.loadBundle();
return this;
};
BundleForm.prototype.closeModal=function(){$("body").find("#overlay").remove();
};
BundleForm.prototype.createTitle=function(){var html="";
var prealoedTitle=this.getPreloadData().preloadedTitle;
var title=prealoedTitle?prealoedTitle:"";
var titleHtml="<div class='title-name'><span class='form-required-field'>* </span>"+this.i18n.nameLocLbl+": </div><div class='title-input'><input type='text' value='"+title+"'></div>";
titleHtml=this.getComponentMode()?"":titleHtml;
html="<div class='bundle-title'>"+titleHtml+"</div>";
return html;
};
BundleForm.prototype.loadBundle=function(){var html="";
var orders;
var charges;
var prescriptions;
var followup;
var education;
var diagnosis;
var data=this.getPreloadData();
var id=data.id;
var isEditMode=this.getEditMode();
var saveLbl=isEditMode?this.i18n.saveLbl:this.i18n.submitLbl;
var ordersArr=data.orders;
var chargesArr=data.charges;
var prescriptionsArr=data.prescriptions;
var followupArr=data.followup;
var educationArr=data.education;
var diagnosisArr=data.diagnosis;
var headerHtml="";
id=id?id:0;
headerHtml="<div class='bundle-new-hdr'><div class='bundle-new-title'>"+this.getHeader()+"</div><div class='bundle-new-close'></div></div>";
headerHtml=this.getComponentMode()?"":headerHtml;
html+="<div class='bundle-new' bundleId='"+id+"'>"+headerHtml+"<div class='bundle-title-error hide'></div><div class='bundle-new-content'><div class='bundle-new-sec form-order-title'>"+this.createTitle()+"</div><div class='bundle-new-selection'><div class='bundle-new-sec form-diagnosis-sec'></div><div class='bundle-new-sec form-order-sec'></div><div class='bundle-new-sec form-charge-sec'></div><div class='bundle-new-sec form-prescription-sec'></div><div class='bundle-new-sec form-followup-sec'></div><div class='bundle-new-sec form-education-sec'></div></div></div><div class='bundle-new-footer'><div class='footer-btn'><div class='create-new-bundle'><input type='button' value='"+saveLbl+"' class='button save-bundle-new-btn'></div><div class='close-new-bundle'><input type='button' value='"+this.i18n.closeLbl+"' class='button cancel-bundle-new-btn'></div></div></div></div>";
$("#"+this.getDomId()).append(html);
if(isEditMode||(!isEditMode&&ordersArr&&ordersArr.length>0)){orders=new OrdersGrouper({header:this.i18n.ordersLbl,isPlusAddEnabled:isEditMode,preloadData:ordersArr,target:".form-order-sec",searchBoxCaption:this.i18n.searchLbl+" "+this.i18n.ordersLbl,type:"orders"});
orders.render();
}if(isEditMode||(!isEditMode&&chargesArr&&chargesArr.length>0)){charges=new OrdersGrouper({header:this.i18n.chargesLbl,isPlusAddEnabled:isEditMode,preloadData:chargesArr,target:".form-charge-sec",searchBoxCaption:this.i18n.searchLbl+" "+this.i18n.chargesLbl,type:"charges"});
charges.render();
}if(isEditMode||(!isEditMode&&prescriptionsArr&&prescriptionsArr.length>0)){prescriptions=new OrdersGrouper({header:this.i18n.prescriptionLbl,isPlusAddEnabled:isEditMode,preloadData:prescriptionsArr,target:".form-prescription-sec",searchBoxCaption:this.i18n.searchLbl+" "+this.i18n.prescriptionLbl,type:"prescriptions"});
prescriptions.render();
}if(isEditMode||(!isEditMode&&followupArr&&followupArr.length>0)){followup=new FollowupGrouper({header:this.i18n.followUpLbl,isPlusAddEnabled:isEditMode,preloadData:followupArr,target:".form-followup-sec",searchBoxCaption:this.i18n.searchLbl+" "+this.i18n.followUpLbl});
followup.render();
}if(isEditMode||(!isEditMode&&educationArr&&educationArr.length>0)){education=new EducationGrouper({header:this.i18n.educationLbl,isPlusAddEnabled:isEditMode,preloadData:educationArr,target:".form-education-sec",searchBoxCaption:this.i18n.searchLbl+" "+this.i18n.educationLbl});
education.render();
}if(isEditMode||(!isEditMode&&diagnosisArr&&diagnosisArr.length>0)){diagnosis=new DiagnosisGrouper({header:this.i18n.diagnosisLbl,isPlusAddEnabled:isEditMode,preloadData:diagnosisArr,target:".form-diagnosis-sec",searchBoxCaption:this.i18n.searchLbl+" "+this.i18n.diagnosisLbl});
diagnosis.render();
}this.setSelections({title:"",preloadedTitle:"",orders:orders,charges:charges,prescriptions:prescriptions,followup:followup,education:education,diagnosis:diagnosis,pathwayId:id});
this.postProcessing();
};
BundleForm.prototype.displayError=function(message){var alertBanner=new MPageUI.AlertBanner();
alertBanner.setType(MPageUI.ALERT_OPTIONS.TYPE.ERROR);
alertBanner.setPrimaryText(message.primaryMsg);
alertBanner.setSecondaryText(message.secondaryMsg);
$("#"+this.getDomId()+" .bundle-title-error").empty().removeClass("hide").append(alertBanner.render());
switch(message.field){case"title":$("#"+this.getDomId()+" .bundle-title input[type=text]").focus();
break;
default:break;
}};
BundleForm.prototype.removeError=function(){$("#"+this.getDomId()+" .bundle-title-error").addClass("hide");
};
BundleForm.prototype.postProcessing=function(){var self=this;
$("#"+this.getDomId()+" .bundle-new").on("click",".bundle-new-close",function(){var closeFunc=self.getCallBackFunc().closeFunc;
var parentSelf=self.getCallBackFunc().self;
if(!self.getCallBackFunc().closeFunc){self.closeModal();
return;
}closeFunc(parentSelf);
});
$("#"+this.getDomId()+" .close-new-bundle").on("click","input",function(){var closeFunc=self.getCallBackFunc().closeFunc;
var parentSelf=self.getCallBackFunc().self;
if(!self.getCallBackFunc().closeFunc){self.closeModal();
return;
}closeFunc(parentSelf);
});
$("#"+this.getDomId()+" .create-new-bundle").on("click","input",function(){var selections=self.getSelections();
var id=self.getPreloadData().id;
var preTitle=self.getPreloadData().preloadedTitle;
var formattedSelection={orders:selections.orders?selections.orders.getSelection():[],prescriptions:selections.prescriptions?selections.prescriptions.getSelection():[],charges:selections.charges?selections.charges.getSelection():[],followup:selections.followup?selections.followup.getSelection():[],education:selections.education?selections.education.getSelection():[],diagnosis:selections.diagnosis?selections.diagnosis.getSelection():[],pathwayId:id?parseInt(id,10):0,preloadedTitle:preTitle?preTitle:""};
var validateFunc=self.getCallBackFunc().saveFunc;
var parentSelf=self.getCallBackFunc().self;
var message={field:"title",primaryMsg:self.i18n.noTitleErr+".",secondaryMsg:self.i18n.emptyTitleErrMsg+"."};
formattedSelection.title=$("#"+self.getDomId()+" .bundle-title input[type=text]").val();
formattedSelection.title=formattedSelection.title?formattedSelection.title.toString().replace(/['"^]+/g,"").trim():"";
if(!formattedSelection.title&&self.getEditMode()){self.displayError(message);
return;
}if(!formattedSelection.orders.length&&!formattedSelection.prescriptions.length&&!formattedSelection.charges.length&&!formattedSelection.followup.length&&!formattedSelection.education.length&&!formattedSelection.diagnosis.length){message.field="bundle";
message.secondaryMsg=self.i18n.emptyBundleErrMsg+".";
self.displayError(message);
return;
}validateFunc(parentSelf,formattedSelection);
});
};
if(typeof GLOBAL_ORDER_POPUP==="undefined"){var GLOBAL_ORDER_POPUP={popup:null};
}var DiagnosisGrouper=function(options){options=options||{};
this.isPlusAddEnabled=!!options.isPlusAddEnabled;
this.header=options.header?options.header:"";
this.preloadData=options.preloadData?options.preloadData:[];
this.target=options.target?options.target:"";
this.caption=options.searchBoxCaption?options.searchBoxCaption:"";
this.type=options.type?options.type:"";
this.popup=null;
this.suggestionList=[];
this.selectedDiag=[];
this.grouper=null;
this.vocabularyCd=[];
this.selectedVocabs=[];
this.i18n=i18n.quickVisit;
this.control=null;
};
DiagnosisGrouper.prototype.setControl=function(obj){this.control=obj;
};
DiagnosisGrouper.prototype.getControl=function(){return this.control;
};
DiagnosisGrouper.prototype.getVocabularyCd=function(){return this.vocabularyCd;
};
DiagnosisGrouper.prototype.setVocabularyCd=function(arr){if(!Array.isArray(arr)){throw new Error("DiagnosisGrouper.prototype.setVocabularyCd expects an array.");
}this.vocabularyCd=arr;
};
DiagnosisGrouper.prototype.getSelectedVocabs=function(){return this.selectedVocabs;
};
DiagnosisGrouper.prototype.setSelectedVocabs=function(arr){if(!Array.isArray(arr)){throw new Error("DiagnosisGrouper.prototype.setSelectedVocabs expects an array.");
}this.selectedVocabs=arr;
};
DiagnosisGrouper.prototype.getSelectedDiag=function(){return this.selectedDiag;
};
DiagnosisGrouper.prototype.addToSelectedDiag=function(item){var arrLen=this.selectedDiag.length;
this.selectedDiag.push(item);
if(this.getGrouper()){this.updateHeaderCount();
}return arrLen;
};
DiagnosisGrouper.prototype.updateHeaderCount=function(){this.getGrouper().updateHeader(this.getHeader()+" ("+this.getSelection().length+")");
};
DiagnosisGrouper.prototype.getSuggestionList=function(){return this.suggestionList;
};
DiagnosisGrouper.prototype.setSuggestionList=function(arr){if(!Array.isArray(arr)){throw new Error("DiagnosisGrouper.prototype.setSuggestionList expects an array.");
}this.suggestionList=arr;
};
DiagnosisGrouper.prototype.setPopup=function(obj){this.popup=obj;
};
DiagnosisGrouper.prototype.getPopup=function(){return this.popup;
};
DiagnosisGrouper.prototype.setGrouper=function(obj){this.grouper=obj;
};
DiagnosisGrouper.prototype.getGrouper=function(){return this.grouper;
};
DiagnosisGrouper.prototype.getType=function(){return this.type;
};
DiagnosisGrouper.prototype.getCaption=function(){return this.caption;
};
DiagnosisGrouper.prototype.getPlusAddEnabled=function(){return this.isPlusAddEnabled;
};
DiagnosisGrouper.prototype.getHeader=function(){return this.header;
};
DiagnosisGrouper.prototype.getPreloadData=function(){return this.preloadData;
};
DiagnosisGrouper.prototype.getTarget=function(){return $(this.target);
};
DiagnosisGrouper.prototype.updateSelectedDiag=function(action,index,valueId){switch(action){case"diagnosis":this.selectedDiag[index]=valueId;
break;
case"checked":this.selectedDiag.forEach(function(element){if(element&&element.SELECTED_IND===1){element.SELECTED_IND=0;
}});
this.selectedDiag[index].SELECTED_IND=parseInt(valueId,10);
break;
default:throw new Error("DiagnosisGrouper.prototype.updateSelectedDiag expect at least one argument");
}this.updateHeaderCount();
};
DiagnosisGrouper.prototype.getSelection=function(){var diagnosis=this.getSelectedDiag();
var diagCnt=0;
var selectedDiag=[];
var diag=null;
for(diagCnt=0;
diagCnt<diagnosis.length;
diagCnt++){diag=diagnosis[diagCnt];
if(diag){selectedDiag.push({selected_ind:diag.SELECTED_IND?diag.SELECTED_IND:0,nomenclature_id:diag.NOMENCLATURE_ID});
}}return selectedDiag;
};
DiagnosisGrouper.prototype.fetchVocabulariesFromCode=function(){var self=this;
self.generateDropDown();
MP_Util.GetCodeSetAsync(400,function(response){self.setVocabularyCd(response.sort());
self.generateDropDownContent(response.sort());
});
};
DiagnosisGrouper.prototype.generateDropDown=function(){var html="";
var $popup=$("#"+this.getPopup().getId());
html+="<label>"+this.i18n.selectTerm+": </label><select data-placeholder='"+this.i18n.loadinglbl+"... ' class='diagnosis-vocab-select'></select>";
$popup.find(".qv-diagnosis-vocab-list").empty().append(html);
$popup.find(".diagnosis-vocab-select").attr("disabled",true).chosen({no_results_text:this.i18n.notFound});
};
DiagnosisGrouper.prototype.generateDropDownContent=function(arr){var count=0;
var html="";
var $popup=$("#"+this.getPopup().getId());
var self=this;
html+="<option value></option>";
for(count=0;
count<arr.length;
count++){html+="<option desc='"+arr[count].DESCRIPTION+"' value='"+arr[count].CODE+"'>"+arr[count].DISPLAY+"</option>";
}$popup.find(".diagnosis-vocab-select").empty().attr({disabled:false,"data-placeholder":this.i18n.selectTerm}).append(html).trigger("chosen:updated");
$popup.find(".diagnosis-vocab-select").on("change",function(){var vocabCdArr=[];
$.each($(this).find("option:selected"),function(i,val){vocabCdArr[i]=$(val).val();
});
self.setSelectedVocabs(vocabCdArr);
self.getControl().setVocabularyList(self.getSelectedVocabs());
if(self.getSelectedVocabs().length<1){$popup.find("#qvDiagnosisPopupSearch input[type='text']").attr("disabled",true);
self.getControl().setCaption(self.i18n.selectTermFirst);
}else{$popup.find("#qvDiagnosisPopupSearch input[type='text']").attr("disabled",false);
self.getControl().setCaption(self.getCaption());
}self.getControl().activateCaption();
});
};
DiagnosisGrouper.prototype.render=function(){var $target=this.getTarget();
$target.empty().append("<div class='qv-form-diagnosis-sec'>"+this.createDiagSec()+"</div>");
this.getGrouper().attachEvents();
this.updateHeaderCount();
this.postProcessing();
return this;
};
DiagnosisGrouper.prototype.createDiagSec=function(){var preloadData=this.getPreloadData();
var plusAddCss=this.getPlusAddEnabled()?"quick-visit-add-icon":"";
var isCollapsed=preloadData.length===0;
var grouper=new MPageUI.Grouper();
var contentHtml="";
this.setGrouper(grouper);
contentHtml="<div class='diagnosis-sec-detail'>"+this.createDiagDetails(preloadData)+"</div>";
grouper.setHeader(this.getHeader());
grouper.setBody(contentHtml);
grouper.setIsCollapsed(isCollapsed);
grouper.setAddIconCssClass(plusAddCss);
return grouper.render();
};
DiagnosisGrouper.prototype.createDiagDetails=function(data){var html="";
var count=0;
var checkedAttr="";
var dataLen=data.length;
var removeIconHtml="";
var arrIndex=0;
removeIconHtml=this.getPlusAddEnabled()?"<div class='diagnosis-remove remove-icon'></div>":"";
for(count=0;
count<dataLen;
count++){arrIndex=this.addToSelectedDiag(data[count]);
checkedAttr=data[count].SELECTED_IND?"checked":"";
html+="<div class='selected-form-items diagnosis-item' id='diagnosis-item-"+arrIndex+"' index='"+arrIndex+"'><label class='diagnosis-label'><input type='radio' name='diagnosisRadio' value='diagnosis-check-"+data[count].NOMENCLATURE_ID+"' class='diagnosis-item-radio' "+checkedAttr+"><span>"+data[count].DESCRIPTION+"</span></label>"+removeIconHtml+"</div>";
}return html;
};
DiagnosisGrouper.prototype.removeDiagnosisDetails=function(index){this.updateSelectedDiag("diagnosis",index,null);
this.getTarget().find("#diagnosis-item-"+index).remove();
};
DiagnosisGrouper.prototype.generatePopup=function(anchor){var popup=null;
var control=null;
var html="";
var self=this;
var $popup=null;
$("#orderAdd").attr("id","");
$(anchor).attr("id","orderAdd");
popup=new MPageUI.Popup();
popup.setAnchorId("orderAdd");
html="<div id='qvDiagnosisPopupHeader'><span>"+this.getCaption()+":</span></div>";
popup.setHeader(html);
html="<div id='qvDiagnosisPopup' class='"+this.getType()+"-popup-type'><div class='qv-diagnosis-vocab-list'></div><div id='qvDiagnosisPopupSearch'></div><div class='qv-diagnosis-suggest-list'></div></div>";
popup.setBodyContent(html);
html="<div id='qvDiagnosisPopupFooter'><div class='close-btn'><input type='button' value='"+this.i18n.closeLbl+"'></div></div>";
popup.setFooter(html);
popup.setWidth(400);
popup.setPosition(MPageUI.POPUP_OPTIONS.POSITION.BOTTOM_LEFT);
popup.setScrollableParent(".bundle-new-content");
popup.hideOnScroll(true);
popup.attachEvents();
popup.toggle();
$("#qvDiagnosisPopup").parent().addClass("qv-popup-body");
GLOBAL_ORDER_POPUP.popup=popup;
this.setPopup(popup);
$popup=$("#"+popup.getId());
control=new MPageControls.DiagnosisSearch($("#qvDiagnosisPopupSearch"));
control.setCaption(this.i18n.selectTermFirst);
control.setProgramName("mp_search_qo_diagnosis");
control.activateCaption();
control.setOnEnter(function(){var selections=control.getList().m_Items?control.getList().m_Items:[];
self.loadSearchResults(selections);
});
control.getList().setOnSelect(function(){control.close();
control.activateCaption();
self.handleDiagnosisSelection(control.getList().getSelectedItem());
});
control.getList().setOnEnter(function(){control.close();
control.activateCaption();
self.handleDiagnosisSelection(control.getList().getSelectedItem());
});
this.setControl(control);
$popup.find("#qvDiagnosisPopupSearch input[type='text']").attr("disabled",true);
};
DiagnosisGrouper.prototype.loadSearchResults=function(diagnosisArr){var html="";
var popup=this.getPopup();
var diagnosisCnt=0;
this.setSuggestionList(diagnosisArr);
for(diagnosisCnt=0;
diagnosisCnt<diagnosisArr.length;
diagnosisCnt++){html+="<div class='qv-diagnosis-suggest-item' index='"+diagnosisCnt+"'><span>"+diagnosisArr[diagnosisCnt].DESCRIPTION+"</span></div>";
}$("#"+popup.getId()+" .qv-diagnosis-suggest-list").empty().append(html);
};
DiagnosisGrouper.prototype.handleDiagnosisSelection=function(item){var $diagSec=this.getTarget().find(".diagnosis-sec-detail");
var deepClone=$.extend(true,{},item);
var selection=this.getSelection();
var diagLen=selection.length;
var diagCnt=0;
var grouper=this.getGrouper();
for(diagCnt=0;
diagCnt<diagLen;
diagCnt++){if(parseInt(item.NOMENCLATURE_ID,10)===parseInt(selection[diagCnt].nomenclature_id,10)){this.showAlert(true);
return;
}}$diagSec.append(this.createDiagDetails([deepClone]));
this.showAlert(false);
if(this.getTarget().find(".collapse").hasClass("collapsed")){grouper.expand();
}};
DiagnosisGrouper.prototype.showAlert=function(isAlertShowed){var $popup=$("#"+this.getPopup().getId());
var alertBanner;
if(isAlertShowed&&!$popup.find(".alert-msg").length){alertBanner=new MPageUI.AlertBanner();
alertBanner.setType(MPageUI.ALERT_OPTIONS.TYPE.ERROR);
alertBanner.setPrimaryText(this.i18n.dupSelectionErr+".");
alertBanner.setSecondaryText(this.i18n.dupSelectionErrMsg+".");
$popup.prepend(alertBanner.render());
return;
}if(!isAlertShowed){$popup.find(".alert-msg").remove();
}};
DiagnosisGrouper.prototype.postProcessing=function(){var $target=this.getTarget();
var self=this;
var $popup=null;
if(this.getPopup()){$popup=$("#"+this.getPopup().getId());
}$target.find(".quick-visit-add-icon").click(function(){if(self.getPopup()&&self.getPopup().isOpen()){self.getPopup().destroy();
self.setPopup(null);
}else{if(GLOBAL_ORDER_POPUP.popup){GLOBAL_ORDER_POPUP.popup.destroy();
}self.generatePopup(this);
self.fetchVocabulariesFromCode();
}if(self.getPopup()){$popup=$("#"+self.getPopup().getId());
$popup.on("click",".qv-diagnosis-suggest-item",function(){var index=$(this).attr("index");
self.handleDiagnosisSelection(self.getSuggestionList()[index]);
}).on("click",".auto-suggest .close-btn",function(){self.setSuggestionList([]);
$popup.find(".qv-diagnosis-suggest-list").empty();
});
$("#qvDiagnosisPopupFooter").on("click",".close-btn",function(){self.getPopup().destroy();
self.setPopup(null);
});
}});
$target.find(".diagnosis-sec-detail").on("click",".diagnosis-remove",function(){self.removeDiagnosisDetails($(this).closest(".diagnosis-item").attr("index"));
});
$target.find(".diagnosis-sec-detail").on("change",".diagnosis-item-radio",function(){var index=$(this).closest(".diagnosis-item").attr("index");
if($(this).prop("checked")){self.updateSelectedDiag("checked",index,1);
}else{self.updateSelectedDiag("checked",index,0);
}});
};
if(typeof GLOBAL_ORDER_POPUP==="undefined"){var GLOBAL_ORDER_POPUP={popup:null};
}var EducationGrouper=function(options){options=options||{};
this.isPlusAddEnabled=!!options.isPlusAddEnabled;
this.header=options.header?options.header:"";
this.preloadData=options.preloadData?options.preloadData:[];
this.target=options.target?$(options.target):"";
this.caption=options.searchBoxCaption?options.searchBoxCaption:"";
this.popup=null;
this.suggestionList=[];
this.selectedEdus=[];
this.grouper=null;
this.control=null;
this.languagesList=[];
this.domainsList=[];
this.language={};
this.domain={};
this.i18n=i18n.quickVisit;
};
EducationGrouper.prototype.getSelectedEdus=function(){return this.selectedEdus;
};
EducationGrouper.prototype.addToSelectedEdus=function(item){var arrLen=this.selectedEdus.length;
this.selectedEdus.push(item);
if(this.getGrouper()){this.updateHeaderCount();
}return arrLen;
};
EducationGrouper.prototype.updateHeaderCount=function(){this.getGrouper().updateHeader(this.getHeader()+" ("+this.getSelection().length+")");
};
EducationGrouper.prototype.updateSelectedEdus=function(action,index,valueId){switch(action){case"education":this.selectedEdus[index]=valueId;
break;
case"checked":this.selectedEdus[index].SELECTED_IND=parseInt(valueId,10);
break;
default:throw new Error("EducationGrouper.prototype.updateSelectedEdus expect at least one argument");
}this.updateHeaderCount();
};
EducationGrouper.prototype.getSelection=function(){var edus=this.getSelectedEdus();
var eduCnt=0;
var selectedEdus=[];
var edu=null;
for(eduCnt=0;
eduCnt<edus.length;
eduCnt++){edu=edus[eduCnt];
if(edu){selectedEdus.push({selected_ind:edu.SELECTED_IND?edu.SELECTED_IND:0,key_doc_ident:edu.KEY_DOC_IDENT,doc_lang_id:edu.DOC_LANG_ID,domain_cd:edu.DOMAIN_CD,prsnl_id:edu.PRSNL_ID,pat_ed_reltn_desc_key:edu.PAT_ED_RELTN_DESC_KEY,pat_ed_reltn_id:edu.PAT_ED_RELTN_ID});
}}return selectedEdus;
};
EducationGrouper.prototype.getSuggestionList=function(){return this.suggestionList;
};
EducationGrouper.prototype.setSuggestionList=function(arr){if(arr.constructor!==Array){throw new Error("EducationGrouper.prototype.setSuggestionList expects an array.");
}this.suggestionList=arr;
};
EducationGrouper.prototype.setGrouper=function(obj){this.grouper=obj;
};
EducationGrouper.prototype.getGrouper=function(){return this.grouper;
};
EducationGrouper.prototype.setControl=function(obj){this.control=obj;
};
EducationGrouper.prototype.getControl=function(){return this.control;
};
EducationGrouper.prototype.setPopup=function(obj){this.popup=obj;
};
EducationGrouper.prototype.getPopup=function(){return this.popup;
};
EducationGrouper.prototype.setCaption=function(str){if(typeof str!=="string"){throw new Error("EducationGrouper.prototype.setCaption expects a string.");
}this.caption=str;
};
EducationGrouper.prototype.getCaption=function(){return this.caption;
};
EducationGrouper.prototype.setPlusAddEnabled=function(bool){if(typeof bool!=="boolean"){throw new Error("EducationGrouper.prototype.setPlusAddEnabled expects a boolean.");
}this.isPlusAddEnabled=bool;
};
EducationGrouper.prototype.getPlusAddEnabled=function(){return this.isPlusAddEnabled;
};
EducationGrouper.prototype.setHeader=function(header){if(typeof header!=="string"){throw new Error("EducationGrouper.prototype.setHeader expects a string.");
}this.header=header;
};
EducationGrouper.prototype.getHeader=function(){return this.header;
};
EducationGrouper.prototype.setPreloadData=function(data){this.preloadData=data;
};
EducationGrouper.prototype.getPreloadData=function(){return this.preloadData;
};
EducationGrouper.prototype.setTarget=function(target){if(typeof target!=="string"){throw new Error("EducationGrouper.prototype.setTarget expects a string.");
}this.target=$(target);
};
EducationGrouper.prototype.getTarget=function(){return this.target;
};
EducationGrouper.prototype.setLanguage=function(language){if(typeof language!=="object"){throw new Error("EducationGrouper.prototype.setLanguage expects an object.");
}this.language=language;
};
EducationGrouper.prototype.getLanguage=function(){return this.language;
};
EducationGrouper.prototype.setDomain=function(domain){if(typeof domain!=="object"){throw new Error("EducationGrouper.prototype.setDomain expects an object.");
}this.domain=domain;
};
EducationGrouper.prototype.getDomain=function(){return this.domain;
};
EducationGrouper.prototype.setLanguagesList=function(languagesList){if(languagesList.constructor!==Array){throw new Error("EducationGrouper.prototype.setLanguagesList expects an array.");
}this.languagesList=languagesList;
};
EducationGrouper.prototype.getLanguagesList=function(){return this.languagesList;
};
EducationGrouper.prototype.setDomainsList=function(domainsList){if(domainsList.constructor!==Array){throw new Error("EducationGrouper.prototype.setDomainsList expects an array.");
}this.domainsList=domainsList;
};
EducationGrouper.prototype.getDomainsList=function(){return this.domainsList;
};
EducationGrouper.prototype.render=function(){var $target=this.getTarget();
$target.empty().append("<div class='qv-form-education-sec'>"+this.createEdusSec()+"</div>");
this.getGrouper().attachEvents();
this.updateHeaderCount();
this.postProcessing();
return this;
};
EducationGrouper.prototype.createEdusSec=function(){var preloadData=this.getPreloadData();
var plusCSSClass=this.getPlusAddEnabled()?"quick-visit-add-icon":"";
var isCollapsed=preloadData.length===0;
var contentHtml="";
var grouper=new MPageUI.Grouper();
this.setGrouper(grouper);
contentHtml="<div class='education-sec-detail'>"+this.createEduDetails(preloadData)+"</div>";
grouper.setHeader(this.getHeader());
grouper.setBody(contentHtml);
grouper.setIsCollapsed(isCollapsed);
grouper.setAddIconCssClass(plusCSSClass);
return grouper.render();
};
EducationGrouper.prototype.createEduDetails=function(displayData){var html="";
var count=0;
var checkedAttr="";
var dataLen=displayData.length;
var removeIconHtml="";
var arrIndex=0;
var name="";
removeIconHtml=this.getPlusAddEnabled()?"<div class='education-remove remove-icon'></div>":"";
for(count=0;
count<dataLen;
count++){name=displayData[count].NAME?displayData[count].NAME:displayData[count].DESCRIPTION;
displayData[count].DOMAIN_CD=displayData[count].DOMAIN_CD?displayData[count].DOMAIN_CD:this.getDomain().CODE;
arrIndex=this.addToSelectedEdus(displayData[count]);
checkedAttr=displayData[count].SELECTED_IND?"checked":"";
html+="<div class='selected-form-items education-item' id='education-item-"+arrIndex+"' index='"+arrIndex+"'><label class='education-label'><input type='checkbox' value='education-check-"+displayData[count].KEY_DOC_IDENT+"' class='education-item-checkbox' "+checkedAttr+"><span>"+name+"</span></label>"+removeIconHtml+"</div>";
}return html;
};
EducationGrouper.prototype.removeEduDetails=function(index){this.updateSelectedEdus("education",index,null);
this.getTarget().find(" #education-item-"+index).remove();
};
EducationGrouper.prototype.fetchLanguagesFromDomain=function(domainCd){var self=this;
var getLanguageRequest=new ScriptRequest();
var isLoading=this.i18n.loadinglbl+"... ";
var $popup=$("#"+this.getPopup().getId());
var control=this.getControl();
$popup.find(".languageSelectBox").empty().attr({"data-placeholder":isLoading}).trigger("chosen:updated");
$popup.find("#qvEducationPopupSearch input[type='text']").prop("disabled",true);
control.setCaption(this.i18n.selectLangFirst);
control.activateCaption();
getLanguageRequest.setProgramName("mp_get_lang_by_domaincd");
getLanguageRequest.setParameterArray(["^MINE^",domainCd+".0"]);
getLanguageRequest.setAsyncIndicator(true);
getLanguageRequest.setResponseHandler(function(dataReply){var response=dataReply.getResponse().LIST;
if(response&&dataReply.getStatus()==="S"){self.setLanguagesList(response);
self.generateDropDownContent("language",response);
}else{if(dataReply.getStatus()==="Z"){logger.logError("Nothing retrieved for domainCd:"+domainCd);
}else{logger.logError("There was an error retrieving data, domainCd: "+domainCd);
}}});
getLanguageRequest.performRequest();
};
EducationGrouper.prototype.fetchDomainsFromCode=function(){var self=this;
var popup=this.getPopup();
MP_Util.GetCodeSetAsync(24849,function(response){self.setDomainsList(response);
self.generateDropDownContent("domain",response);
$("#"+popup.getId()).find(".domainSelectBox").val("");
});
};
EducationGrouper.prototype.generateDropDown=function(item){var html="";
var label=item==="domain"?this.i18n.addDomLbl:this.i18n.addLangLbl;
var isLoading=item==="domain"?this.i18n.loadinglbl+"... ":this.i18n.addLangLbl;
var $popup=$("#"+this.getPopup().getId());
html="<label>"+label+": </label><select name='"+item+"' class='"+item+"SelectBox' data-placeholder='"+isLoading+"'></select>";
$popup.find("#qv"+item+"Select").empty().append(html);
$popup.find("."+item+"SelectBox").prop("disabled",true);
$popup.find("."+item+"SelectBox").chosen({no_results_text:this.i18n.notFound,max_selected_option:1});
};
EducationGrouper.prototype.generateDropDownContent=function(item,itemList){var html="";
var count=0;
var $popup=$("#"+this.getPopup().getId());
var label=item==="domain"?this.i18n.addDomLbl:this.i18n.addLangLbl;
var isDisabled=false;
var control=this.getControl();
html+="<option value></option>";
if(item==="language"){if(itemList.length===0){label=this.i18n.noPatEduAvail;
isDisabled=true;
}else{itemList.push({DISPLAY:this.i18n.allLangLbl,DOC_LANG_ID:0});
}}for(count=itemList.length-1;
count>=0;
count--){if(count===itemList.length-1&&item==="language"){html+="<option selected value='"+(itemList[count].CODE||itemList[count].DOC_LANG_ID)+"'>"+itemList[count].DISPLAY+"</option>";
$popup.find("#qvEducationPopupSearch input[type='text']").prop("disabled",false);
control.setCaption(this.getCaption());
control.activateCaption();
}else{html+="<option value='"+(itemList[count].CODE||itemList[count].DOC_LANG_ID)+"'>"+itemList[count].DISPLAY+"</option>";
}}$popup.find("."+item+"SelectBox").empty().append(html).attr({disabled:isDisabled,"data-placeholder":label}).trigger("chosen:updated");
};
EducationGrouper.prototype.generatePopup=function(anchor){var popup=null;
var html="";
var self=this;
var control=null;
$("#orderAdd").attr("id","");
$(anchor).attr("id","orderAdd");
popup=new MPageUI.Popup();
popup.setAnchorId("orderAdd");
html="<div id='qvEducationPopupHeader'><span>"+this.getCaption()+":</span></div>";
popup.setHeader(html);
html="<div id='qvEducationPopup' class='education-popup-type'><div class='qvEducationDropDown'><div id='qvdomainSelect' class='dropDownItem'></div><div id='qvlanguageSelect' class='dropDownItem'></div></div><div id='qvEducationPopupSearch'></div><div class='qv-education-suggest-list'></div></div>";
popup.setBodyContent(html);
html="<div id='qvEducationPopupFooter'><div class='close-btn'><input type='button' value='"+this.i18n.closeLbl+"'></div></div>";
popup.setFooter(html);
popup.setWidth(400);
popup.setPosition(MPageUI.POPUP_OPTIONS.POSITION.BOTTOM_LEFT);
popup.setScrollableParent(".bundle-new-content");
popup.hideOnScroll(true);
popup.attachEvents();
popup.toggle();
GLOBAL_ORDER_POPUP.popup=popup;
this.setPopup(popup);
this.generateDropDown("domain");
this.generateDropDown("language");
this.fetchDomainsFromCode();
control=new MPageControls.PatientEducationSearch($("#qvEducationPopupSearch"));
control.setCaption(this.getCaption());
control.activateCaption();
control.setLanguageId(0);
control.setDomainCd(0);
this.setControl(control);
control.setOnEnter(function(){var selections=control.getList().m_Items?control.getList().m_Items:[];
self.loadSearchResults(selections);
});
control.getList().setOnSelect(function(){control.close();
control.activateCaption();
self.handleEduSelection(control.getList().getSelectedItem());
});
control.getList().setOnEnter(function(){control.close();
control.activateCaption();
self.handleEduSelection(control.getList().getSelectedItem());
});
$("#"+popup.getId()).find("#qvEducationPopupSearch input[type='text']").prop("disabled",true);
control.setCaption(self.i18n.selectLangFirst);
control.activateCaption();
};
EducationGrouper.prototype.loadSearchResults=function(eduArr){var html="";
var popup=this.getPopup();
var eduCnt=0;
this.setSuggestionList(eduArr);
for(eduCnt=0;
eduCnt<eduArr.length;
eduCnt++){html+="<div class='qv-education-suggest-item' index='"+eduCnt+"'><span>"+eduArr[eduCnt].content+"</span></div>";
}$("#"+popup.getId()).find(".qv-education-suggest-list").empty().append(html);
};
EducationGrouper.prototype.handleEduSelection=function(item){var $eduSec=this.getTarget().find(" .education-sec-detail");
var deepClone=$.extend(true,{},item);
var grouper=this.getGrouper();
var selection=this.getSelection();
var eduLen=selection.length;
var eduCnt=0;
var domainCD=this.getDomain().CODE;
for(eduCnt=0;
eduCnt<eduLen;
eduCnt++){if(parseInt(item.PRSNL_ID,10)===parseInt(selection[eduCnt].prsnl_id,10)&&parseInt(domainCD,10)===parseInt(selection[eduCnt].domain_cd,10)&&item.KEY_DOC_IDENT.toLowerCase()===selection[eduCnt].key_doc_ident.toLowerCase()&&parseInt(item.DOC_LANG_ID,10)===parseInt(selection[eduCnt].doc_lang_id,10)&&item.PAT_ED_RELTN_DESC_KEY.toLowerCase()===selection[eduCnt].pat_ed_reltn_desc_key.toLowerCase()){this.showAlert(true);
return;
}}$eduSec.append(this.createEduDetails([deepClone]));
this.showAlert(false);
if(this.getTarget().find(".collapse").hasClass("collapsed")){grouper.expand();
}};
EducationGrouper.prototype.showAlert=function(isAlertShowed){var $popup=$("#"+this.getPopup().getId());
var alertBanner;
if(isAlertShowed&&!$popup.find(".alert-msg").length){alertBanner=new MPageUI.AlertBanner();
alertBanner.setType(MPageUI.ALERT_OPTIONS.TYPE.ERROR);
alertBanner.setPrimaryText(this.i18n.dupSelectionErr+".");
alertBanner.setSecondaryText(this.i18n.dupSelectionErrMsg+".");
$popup.prepend(alertBanner.render());
return;
}if(!isAlertShowed){$popup.find(".alert-msg").remove();
}};
EducationGrouper.prototype.postProcessing=function(){var $target=this.getTarget();
var self=this;
var $popup=null;
if(this.getPopup()){$popup=$("#"+this.getPopup().getId());
}$target.find(".quick-visit-add-icon").click(function(){if(self.getPopup()&&self.getPopup().isOpen()){self.getPopup().destroy();
self.setPopup(null);
}else{if(GLOBAL_ORDER_POPUP.popup){GLOBAL_ORDER_POPUP.popup.destroy();
}self.generatePopup(this);
}if(self.getPopup()){$popup=$("#"+self.getPopup().getId());
$popup.on("click",".qv-education-suggest-item",function(){var index=$(this).attr("index");
self.handleEduSelection(self.getSuggestionList()[index]);
}).on("click",".auto-suggest .close-btn",function(){self.setSuggestionList([]);
$popup.find(".qv-education-suggest-list").empty();
});
$popup.find(".qvEducationDropDown").on("change",".languageSelectBox",function(){var id=parseInt($(".languageSelectBox").val(),10);
var control=self.getControl();
var count=0;
var languages=self.getLanguagesList();
var language={};
for(count=0;
count<languages.length;
count++){if(parseInt(languages[count].DOC_LANG_ID,10)===id){language=languages[count];
break;
}}self.setLanguage(language);
control.setLanguageId(id);
$popup.find("#qvEducationPopupSearch input[type='text']").prop("disabled",false);
control.setCaption(self.getCaption());
control.activateCaption();
});
$popup.find(".qvEducationDropDown").on("change",".domainSelectBox",function(){var code=parseInt($(".domainSelectBox").val(),10);
var control=self.getControl();
var count=0;
var domains=self.getDomainsList();
var domain={};
for(count=0;
count<domains.length;
count++){if(parseInt(domains[count].CODE,10)===code){domain=domains[count];
break;
}}self.setDomain(domain);
control.setDomainCd(code);
self.fetchLanguagesFromDomain(code);
});
$("#qvEducationPopupFooter").on("click",".close-btn",function(){self.setDomainsList([]);
self.setLanguagesList([]);
self.setDomain({});
self.setLanguage({});
self.getPopup().destroy();
self.setPopup(null);
});
}});
$target.find(".education-sec-detail").on("click",".remove-icon",function(){self.removeEduDetails($(this).closest(".education-item").attr("index"));
});
$target.find(".education-sec-detail").on("change",".education-item-checkbox",function(){var index=$(this).closest(".education-item").attr("index");
if($(this).prop("checked")){self.updateSelectedEdus("checked",index,1);
}else{self.updateSelectedEdus("checked",index,0);
}});
};
if(typeof GLOBAL_ORDER_POPUP==="undefined"){var GLOBAL_ORDER_POPUP={popup:null};
}var FollowupGrouper=function(options){options=options||{};
this.isPlusAddEnabled=!!options.isPlusAddEnabled;
this.header=options.header?options.header:"";
this.preloadData=options.preloadData?options.preloadData:[];
this.target=options.target?$(options.target):"";
this.caption=options.searchBoxCaption?options.searchBoxCaption:"";
this.popup=null;
this.suggestionList=[];
this.selectedFolUps=[];
this.grouper=null;
this.i18n=i18n.quickVisit;
};
FollowupGrouper.prototype.getSelectedFolUps=function(){return this.selectedFolUps;
};
FollowupGrouper.prototype.addToSelectedFolUps=function(item){var arrLen=this.selectedFolUps.length;
this.selectedFolUps.push(item);
if(this.getGrouper()){this.updateHeaderCount();
}return arrLen;
};
FollowupGrouper.prototype.updateHeaderCount=function(){this.getGrouper().updateHeader(this.getHeader()+" ("+this.getSelection().length+")");
};
FollowupGrouper.prototype.updateSelectedFolUps=function(action,index,valueId){switch(action){case"followup":this.selectedFolUps[index]=valueId;
break;
case"checked":this.selectedFolUps[index].SELECTED_IND=parseInt(valueId,10);
break;
default:throw new Error("FollowupGrouper.prototype.updateSelectedFolUps expect at least one argument");
}this.updateHeaderCount();
};
FollowupGrouper.prototype.getSelection=function(){var folUps=this.getSelectedFolUps();
var folUpCnt=0;
var selectedFolUps=[];
var folUp=null;
var isQuickPick=true;
for(folUpCnt=0;
folUpCnt<folUps.length;
folUpCnt++){folUp=folUps[folUpCnt];
if(folUp){isQuickPick=((typeof folUp.CODE_SET==="undefined")&&!folUp.IS_QUICK_PICK)?false:true;
selectedFolUps.push({selected_ind:folUp.SELECTED_IND?folUp.SELECTED_IND:0,is_quick_pick:isQuickPick,follow_up_id:folUp.FOLLOW_UP_ID?folUp.FOLLOW_UP_ID:folUp.CODE});
}}return selectedFolUps;
};
FollowupGrouper.prototype.getSuggestionList=function(){return this.suggestionList;
};
FollowupGrouper.prototype.setSuggestionList=function(arr){if(arr.constructor!==Array){throw new Error("FollowupGrouper.prototype.setSuggestionList expects an array.");
}this.suggestionList=arr;
};
FollowupGrouper.prototype.setGrouper=function(obj){this.grouper=obj;
};
FollowupGrouper.prototype.getGrouper=function(){return this.grouper;
};
FollowupGrouper.prototype.setPopup=function(obj){this.popup=obj;
};
FollowupGrouper.prototype.getPopup=function(){return this.popup;
};
FollowupGrouper.prototype.setCaption=function(str){if(typeof str!=="string"){throw new Error("FollowupGrouper.prototype.setCaption expects a string.");
}this.caption=str;
};
FollowupGrouper.prototype.getCaption=function(){return this.caption;
};
FollowupGrouper.prototype.setPlusAddEnabled=function(bool){if(typeof bool!=="boolean"){throw new Error("FollowupGrouper.prototype.setPlusAddEnabled expects a boolean.");
}this.isPlusAddEnabled=bool;
};
FollowupGrouper.prototype.getPlusAddEnabled=function(){return this.isPlusAddEnabled;
};
FollowupGrouper.prototype.setHeader=function(header){if(typeof header!=="string"){throw new Error("FollowupGrouper.prototype.setHeader expects a string.");
}this.header=header;
};
FollowupGrouper.prototype.getHeader=function(){return this.header;
};
FollowupGrouper.prototype.setPreloadData=function(data){this.preloadData=data;
};
FollowupGrouper.prototype.getPreloadData=function(){return this.preloadData;
};
FollowupGrouper.prototype.setTarget=function(target){if(typeof target!=="string"){throw new Error("FollowupGrouper.prototype.setTarget expects a string.");
}this.target=$(target);
};
FollowupGrouper.prototype.getTarget=function(){return this.target;
};
FollowupGrouper.prototype.render=function(){var $target=this.getTarget();
$($target).empty().append("<div class='qv-form-followUp-sec'>"+this.createFolUpsSec()+"</div>");
this.getGrouper().attachEvents();
this.updateHeaderCount();
this.postProcessing();
return this;
};
FollowupGrouper.prototype.createFolUpsSec=function(){var preloadData=this.getPreloadData();
var plusCSSClass=this.getPlusAddEnabled()?"quick-visit-add-icon":"";
var isCollapsed=preloadData.length===0;
var contentHtml="";
var grouper=new MPageUI.Grouper();
this.setGrouper(grouper);
contentHtml="<div class='followUp-sec-detail'>"+this.createFolUpDetails(preloadData)+"</div>";
grouper.setHeader(this.getHeader());
grouper.setBody(contentHtml);
grouper.setIsCollapsed(isCollapsed);
grouper.setAddIconCssClass(plusCSSClass);
return grouper.render();
};
FollowupGrouper.prototype.createFolUpDetails=function(displayData){var html="";
var count=0;
var checkedAttr="";
var dataLen=displayData.length;
var removeIconHtml="";
var arrIndex=0;
removeIconHtml=this.getPlusAddEnabled()?"<div class='followUp-remove remove-icon'></div>":"";
for(count=0;
count<dataLen;
count++){arrIndex=this.addToSelectedFolUps(displayData[count]);
checkedAttr=displayData[count].SELECTED_IND?"checked":"";
html+="<div class='selected-form-items followUp-item' id='followUp-item-"+arrIndex+"' index='"+arrIndex+"'><label class='followUp-label'><input type='checkbox' value='followUp-check-"+displayData[count].FOLLOW_UP_ID+"' class='followUp-item-checkbox' "+checkedAttr+"><span>"+displayData[count].DESCRIPTION+"</span></label>"+removeIconHtml+"</div>";
}return html;
};
FollowupGrouper.prototype.removeFolUpDetails=function(index){this.updateSelectedFolUps("followup",index,null);
$(this.getTarget()).find(" #followUp-item-"+index).remove();
};
FollowupGrouper.prototype.generatePopup=function(anchor){var popup=null;
var html="";
var self=this;
$("#orderAdd").attr("id","");
$(anchor).attr("id","orderAdd");
popup=new MPageUI.Popup();
popup.setAnchorId("orderAdd");
html="<div id='qvFollowUpPopupHeader'><span>"+this.getCaption()+":</span></div>";
popup.setHeader(html);
html="<div id='followUpPopup' class='followup-popup-type'><div id='followUpPopupSearch'><div class='auto-suggest input'><div id='control_1_closebtn' class='close-btn' style='display: none;'>&nbsp;</div><div class='auto-suggest-input-wrapper'><input type='text' class='search-box' id='control_1_textbox' placeholder='"+this.getCaption()+"'></div></div></div><div class='qv-followUp-suggest-list'></div></div>";
popup.setBodyContent(html);
html="<div id='qvFollowUpPopupFooter'><div class='close-btn'><input type='button' value='"+this.i18n.closeLbl+"'></div></div>";
popup.setFooter(html);
popup.setWidth(400);
popup.setPosition(MPageUI.POPUP_OPTIONS.POSITION.BOTTOM_LEFT);
popup.setScrollableParent(".bundle-new-content");
popup.hideOnScroll(true);
popup.attachEvents();
popup.toggle();
GLOBAL_ORDER_POPUP.popup=popup;
this.setPopup(popup);
MP_Util.GetCodeSetAsync(20701,function(response){self.loadSearchResults(response);
});
$("#"+popup.getId()).find("#followUpPopupSearch input[type='text']").click().focus();
};
FollowupGrouper.prototype.loadSearchResults=function(folUpArr){var html="";
var popup=this.getPopup();
var folUpCnt=0;
this.setSuggestionList(folUpArr);
for(folUpCnt=0;
folUpCnt<folUpArr.length;
folUpCnt++){html+="<div class='qv-followUp-suggest-item' index='"+folUpCnt+"'><span>"+folUpArr[folUpCnt].DISPLAY+"</span></div>";
}$("#"+popup.getId()).find(".qv-followUp-suggest-list").empty().append(html);
};
FollowupGrouper.prototype.handleFolUpSelection=function(item){var folUpCnt=0;
var selection=this.getSelection();
var folUpLen=selection.length;
var $folUpSec=this.getTarget().find(" .followUp-sec-detail");
var deepClone=$.extend(true,{},item);
var grouper=this.getGrouper();
for(folUpCnt=0;
folUpCnt<folUpLen;
folUpCnt++){if(parseInt(item.CODE,10)===parseInt(selection[folUpCnt].follow_up_id,10)){this.showAlert(true);
return;
}}$folUpSec.append(this.createFolUpDetails([deepClone]));
this.showAlert(false);
if(this.getTarget().find(".collapse").hasClass("collapsed")){grouper.expand();
}};
FollowupGrouper.prototype.showAlert=function(isAlertShowed){var $popup=$("#"+this.getPopup().getId());
var alertBanner;
if(isAlertShowed&&!$popup.find(".alert-msg").length){alertBanner=new MPageUI.AlertBanner();
alertBanner.setType(MPageUI.ALERT_OPTIONS.TYPE.ERROR);
alertBanner.setPrimaryText(this.i18n.dupSelectionErr+".");
alertBanner.setSecondaryText(this.i18n.dupSelectionErrMsg+".");
$popup.prepend(alertBanner.render());
return;
}if(!isAlertShowed){$popup.find(".alert-msg").remove();
}};
FollowupGrouper.prototype.postProcessing=function(){var $target=this.getTarget();
var self=this;
var $popup=null;
if(this.getPopup()){$popup=$("#"+this.getPopup().getId());
}$target.find(".quick-visit-add-icon").click(function(){if(self.getPopup()&&self.getPopup().isOpen()){self.getPopup().destroy();
self.setPopup(null);
}else{if(GLOBAL_ORDER_POPUP.popup){GLOBAL_ORDER_POPUP.popup.destroy();
}self.generatePopup(this);
}if(self.getPopup()){$popup=$("#"+self.getPopup().getId());
$popup.on("click",".qv-followUp-suggest-item",function(){var index=$(this).attr("index");
self.handleFolUpSelection(self.getSuggestionList()[index]);
}).on("click",".auto-suggest .close-btn",function(){$popup.find(".search-box").val("");
$popup.find(".auto-suggest .close-btn").css("display","none");
$popup.find(".qv-followUp-suggest-item").show();
}).keyup(function(){var term=$popup.find(".search-box").val();
$popup.find(".qv-followUp-suggest-item").hide();
$popup.find(".qv-followUp-suggest-item:icontains('"+term+"')").show();
if(term===""){$popup.find(".auto-suggest .close-btn").css("display","none");
}else{$popup.find(".auto-suggest .close-btn").css("display","inline-block");
}});
$("#qvFollowUpPopupFooter").on("click",".close-btn",function(){self.getPopup().destroy();
self.setPopup(null);
});
}});
$target.find(".followUp-sec-detail").on("click",".remove-icon",function(){self.removeFolUpDetails($(this).closest(".followUp-item").attr("index"));
});
$target.find(".followUp-sec-detail").on("change",".followUp-item-checkbox",function(){var index=$(this).closest(".followUp-item").attr("index");
if($(this).prop("checked")){self.updateSelectedFolUps("checked",index,1);
}else{self.updateSelectedFolUps("checked",index,0);
}});
};
jQuery.expr[":"].icontains=jQuery.expr.createPseudo(function(arg){return function(elem){return jQuery(elem).text().toUpperCase().indexOf(arg.toUpperCase())>=0;
};
});
if(typeof GLOBAL_ORDER_POPUP==="undefined"){var GLOBAL_ORDER_POPUP={popup:null};
}var OrdersGrouper=function(options){options=options||{};
this.isPlusAddEnabled=!!options.isPlusAddEnabled;
this.header=options.header?options.header:"";
this.preloadData=options.preloadData?options.preloadData:[];
this.target=options.target?options.target:"";
this.caption=options.searchBoxCaption?options.searchBoxCaption:"";
this.type=options.type?options.type:"";
this.popup=null;
this.suggestionList=[];
this.selectedOrders=[];
this.grouper=null;
this.i18n=i18n.quickVisit;
};
OrdersGrouper.prototype.getSelectedOrders=function(){return this.selectedOrders;
};
OrdersGrouper.prototype.addToSelectedOrders=function(item){var arrLen=this.selectedOrders.length;
this.selectedOrders.push(item);
if(this.getGrouper()){this.updateHeaderCount();
}return arrLen;
};
OrdersGrouper.prototype.updateHeaderCount=function(){this.getGrouper().updateHeader(this.getHeader()+" ("+this.getSelection().length+")");
};
OrdersGrouper.prototype.getSuggestionList=function(){return this.suggestionList;
};
OrdersGrouper.prototype.setSuggestionList=function(arr){if(typeof arr==="string"){throw new Error("OrdersGrouper.prototype.setSuggestionList expects an array.");
}this.suggestionList=arr;
};
OrdersGrouper.prototype.setPopup=function(obj){this.popup=obj;
};
OrdersGrouper.prototype.getPopup=function(){return this.popup;
};
OrdersGrouper.prototype.setGrouper=function(obj){this.grouper=obj;
};
OrdersGrouper.prototype.getGrouper=function(){return this.grouper;
};
OrdersGrouper.prototype.getType=function(){return this.type;
};
OrdersGrouper.prototype.getCaption=function(){return this.caption;
};
OrdersGrouper.prototype.getPlusAddEnabled=function(){return this.isPlusAddEnabled;
};
OrdersGrouper.prototype.getHeader=function(){return this.header;
};
OrdersGrouper.prototype.getPreloadData=function(){return this.preloadData;
};
OrdersGrouper.prototype.getTarget=function(){return $(this.target);
};
OrdersGrouper.prototype.updateSelectedOrders=function(action,index,valueId,isDefault){var sentenceList=this.selectedOrders[index].SELECTED_SENTENCES?this.selectedOrders[index].SELECTED_SENTENCES:[];
var isSentencePresent=false;
switch(action.toLowerCase()){case"sentence":if(isDefault){this.selectedOrders[index].DEFAULT_SENTENCE_ID=parseInt(valueId,10);
}sentenceList.forEach(function(element){if(element&&(parseInt(element.SENTENCE_ID,10)===parseInt(valueId,10))){isSentencePresent=true;
}});
if(!isSentencePresent){sentenceList.push({SENTENCE_ID:parseInt(valueId,10)});
}this.selectedOrders[index].SELECTED_SENTENCES=sentenceList;
break;
case"order":this.selectedOrders[index]=valueId;
break;
case"checked":this.selectedOrders[index].SELECTED_IND=parseInt(valueId,10);
break;
default:throw new Error("OrdersGrouper.prototype.updateSelectedOrders expect at least one argument");
}this.updateHeaderCount();
};
OrdersGrouper.prototype.getSelection=function(){var orders=this.getSelectedOrders();
var orderCnt=0;
var selectedOrders=[];
var order=null;
var groupCnt=0;
var orderSentCnt=0;
var orderSentArr=[];
var orderSent=null;
for(orderCnt=0;
orderCnt<orders.length;
orderCnt++){orderSentArr=[];
order=orders[orderCnt];
if(order){if(order.SELECTED_SENTENCES){for(orderSentCnt=0;
orderSentCnt<order.SELECTED_SENTENCES.length;
orderSentCnt++){orderSent=order.SELECTED_SENTENCES[orderSentCnt];
if(orderSent){if(order.DEFAULT_SENTENCE_ID&&(parseInt(orderSent.SENTENCE_ID,10)===parseInt(order.DEFAULT_SENTENCE_ID,10))){orderSentArr.unshift({sentence_id:orderSent.SENTENCE_ID});
}else{orderSentArr.push({sentence_id:orderSent.SENTENCE_ID});
}}}}for(orderSentCnt=0;
orderSentCnt<orderSentArr.length;
orderSentCnt++){orderSentArr[orderSentCnt].sequence=orderSentCnt+1;
}selectedOrders.push({selected_ind:order.SELECTED_IND?order.SELECTED_IND:0,synonym_id:order.SYNONYM_ID,group:++groupCnt,sentence_list:orderSentArr});
}}return selectedOrders;
};
OrdersGrouper.prototype.render=function(){var $target=this.getTarget();
$($target).empty().append("<div class='qv-form-order-sec'>"+this.createOrdersSec()+"</div>");
this.getGrouper().attachEvents();
this.updateHeaderCount();
this.postProcessing();
return this;
};
OrdersGrouper.prototype.createOrdersSec=function(){var preloadData=this.getPreloadData();
var plusAddCss=this.getPlusAddEnabled()?"quick-visit-add-icon":"";
var isCollapsed=preloadData.length===0;
var grouper=new MPageUI.Grouper();
var contentHtml="";
var isDropDown=this.getPlusAddEnabled()?false:true;
var isPreloaded=preloadData.length>0;
this.setGrouper(grouper);
contentHtml="<div class='order-sec-detail'>"+this.createOrderDetails(isDropDown,preloadData,isPreloaded)+"</div>";
grouper.setHeader(this.getHeader());
grouper.setBody(contentHtml);
grouper.setIsCollapsed(isCollapsed);
grouper.setAddIconCssClass(plusAddCss);
return grouper.render();
};
OrdersGrouper.prototype.createOrderDetails=function(isDropdown,data,isPreloaded){var html="";
var count=0;
var selectHtml="";
var synCnt=0;
var selectedAttr="";
var checkedAttr="";
var dataLen=data.length;
var orderItem="";
var removeIconHtml="";
var arrIndex=0;
var arrlen=0;
var isDefault=false;
var radiobtnHtml="";
removeIconHtml=this.getPlusAddEnabled()?"<div class='order-remove remove-icon'></div>":"";
for(count=0;
count<dataLen;
count++){radiobtnHtml="";
selectHtml="";
arrIndex=this.addToSelectedOrders(data[count]);
checkedAttr=data[count].SELECTED_IND?"checked":"";
arrlen=data[count].SENTENCE_LIST.length;
if(arrlen>0){if(isDropdown){selectHtml="<select class='order-sentence-dropdown' id='order-select-"+data[count].SYNONYM_ID+"'><option selected disabled></option>";
for(synCnt=0;
synCnt<arrlen;
synCnt++){orderItem=data[count].SENTENCE_LIST[synCnt];
selectedAttr="";
isDefault=synCnt===0;
if(this.getPlusAddEnabled()===false&&isDefault){selectedAttr="selected";
}if(isDefault&&isPreloaded){this.updateSelectedOrders("sentence",arrIndex,orderItem.SENTENCE_ID,true);
}else{if(isPreloaded){this.updateSelectedOrders("sentence",arrIndex,orderItem.SENTENCE_ID,false);
}}selectHtml+="<option sentName='"+orderItem.SENTENCE+"' sentId='"+orderItem.SENTENCE_ID+"' id='sentence-id-"+arrIndex+orderItem.SENTENCE_ID+"' "+selectedAttr+" index='"+synCnt+"'>"+orderItem.SENTENCE+"</option>";
}selectHtml+="</select>";
}else{radiobtnHtml="";
for(synCnt=0;
synCnt<arrlen;
synCnt++){orderItem=data[count].SENTENCE_LIST[synCnt];
isDefault=synCnt===0;
if(isDefault&&isPreloaded){this.updateSelectedOrders("sentence",arrIndex,orderItem.SENTENCE_ID,true);
}else{if(isPreloaded){this.updateSelectedOrders("sentence",arrIndex,orderItem.SENTENCE_ID,false);
}}radiobtnHtml+=this.renderOrderSentence(synCnt,orderItem.SENTENCE_ID,orderItem.SENTENCE,isDefault,count);
}}}html+="<div class='selected-form-items order-item' id='order-item-"+arrIndex+"' index='"+arrIndex+"'><label class='order-label'><input type='checkbox' value='order-check-"+data[count].SYNONYM_ID+"' class='order-item-checkbox' "+checkedAttr+"><span>"+data[count].SYNONYM+"</span></label><div class='order-sentence-group'><div class='order-sentence-radio' index='"+count+"'>"+radiobtnHtml+"</div>"+selectHtml+"</div>"+removeIconHtml+"</div>";
}return html;
};
OrdersGrouper.prototype.removeOrderDetails=function(index){this.updateSelectedOrders("order",index,null);
this.getTarget().find(" #order-item-"+index).remove();
};
OrdersGrouper.prototype.removeOrderSentenceDetails=function(index,sentenceIdx,sentenceID){var selectedOrders=this.getSelectedOrders();
selectedOrders[index].SELECTED_SENTENCES[sentenceIdx]=null;
this.getTarget().find("#sentence-id-"+index+sentenceID).removeAttr("disabled");
this.getTarget().find("#order-select-sentence-"+index+sentenceIdx).remove();
};
OrdersGrouper.prototype.generatePopup=function(anchor){var popup=null;
var control=null;
var html="";
var searchType;
var self=this;
$("#orderAdd").attr("id","");
$(anchor).attr("id","orderAdd");
popup=new MPageUI.Popup();
popup.setAnchorId("orderAdd");
html="<div id='qvOrderPopupHeader'><span>"+this.getCaption()+":</span></div>";
popup.setHeader(html);
html="<div id='orderPopup' class='"+this.getType()+"-popup-type'><div id='qvOrderPopupSearch'></div><div class='qv-order-suggest-list'></div></div>";
popup.setBodyContent(html);
html="<div id='qvOrderPopupFooter'><div class='close-btn'><input type='button' value='"+this.i18n.closeLbl+"'></div></div>";
popup.setFooter(html);
popup.setWidth(400);
popup.setPosition(MPageUI.POPUP_OPTIONS.POSITION.BOTTOM_LEFT);
popup.setScrollableParent(".bundle-new-content");
popup.hideOnScroll(true);
popup.attachEvents();
popup.toggle();
GLOBAL_ORDER_POPUP.popup=popup;
this.setPopup(popup);
control=new MPageControls.OrderSearch($("#qvOrderPopupSearch"),false);
control.setCaption(this.getCaption());
control.setProgramName("mp_search_orders_syn");
searchType=(this.getType().toLowerCase()==="prescriptions")?1:0;
control.setSearchType(searchType);
control.activateCaption();
$("#"+popup.getId()).find("#qvOrderPopupSearch input[type='text']").click().focus();
control.setOnEnter(function(){var selections=control.getList().m_Items?control.getList().m_Items:[];
self.loadSearchResults(selections);
});
control.getList().setOnSelect(function(){control.close();
control.activateCaption();
self.handleOrderSelection(control.getList().getSelectedItem());
});
control.getList().setOnEnter(function(){control.close();
control.activateCaption();
self.handleOrderSelection(control.getList().getSelectedItem());
});
};
OrdersGrouper.prototype.loadSearchResults=function(orderArr){var html="";
var popup=this.getPopup();
var orderCnt=0;
this.setSuggestionList(orderArr);
for(orderCnt=0;
orderCnt<orderArr.length;
orderCnt++){html+="<div class='qv-order-suggest-item' index='"+orderCnt+"'><span>"+orderArr[orderCnt].SYNONYM+"</span></div>";
}$("#"+popup.getId()+" .qv-order-suggest-list").empty().append(html);
};
OrdersGrouper.prototype.handleOrderSelection=function(item){var $orderSec=this.getTarget().find(" .order-sec-detail");
var deepClone=$.extend(true,{},item);
var isDropDown=true;
var isPreloaded=false;
var grouper=this.getGrouper();
if(this.getTarget().find(".collapse").hasClass("collapsed")){grouper.expand();
}$orderSec.append(this.createOrderDetails(isDropDown,[deepClone],isPreloaded));
};
OrdersGrouper.prototype.renderOrderSentence=function(index,sentenceId,sentence,isChecked,orderIdx){var html="";
var checkedAttr=(isChecked||(index===0))?"checked":"";
html+="<div class='order-select-sentence' id='order-select-sentence-"+orderIdx+index+"' index='"+index+"' sentId='"+sentenceId+"'><label class='sentence-label'><input type='radio' class='order-select-sentence-name' name='sentence"+this.getHeader()+orderIdx+"' value='"+sentenceId+"' "+checkedAttr+"> "+sentence+"</label><div class='remove-icon order-select-sentence-del'></div></div>";
return html;
};
OrdersGrouper.prototype.postProcessing=function(){var $target=this.getTarget();
var self=this;
var $popup=null;
if(this.getPopup()){$popup=$("#"+this.getPopup().getId());
}$target.find(".quick-visit-add-icon").click(function(){if(self.getPopup()&&self.getPopup().isOpen()){self.getPopup().destroy();
self.setPopup(null);
}else{if(GLOBAL_ORDER_POPUP.popup){GLOBAL_ORDER_POPUP.popup.destroy();
}self.generatePopup(this);
}if(self.getPopup()){$popup=$("#"+self.getPopup().getId());
$popup.on("click",".qv-order-suggest-item",function(){var index=$(this).attr("index");
self.handleOrderSelection(self.getSuggestionList()[index]);
}).on("click",".auto-suggest .close-btn",function(){self.setSuggestionList([]);
$popup.find(".qv-order-suggest-list").empty();
});
$("#qvOrderPopupFooter").on("click",".close-btn",function(){self.getPopup().destroy();
self.setPopup(null);
});
}});
$target.find(".order-sec-detail").on("click",".order-remove",function(){self.removeOrderDetails($(this).closest(".order-item").attr("index"));
});
$target.find(".order-sec-detail").on("click",".order-select-sentence-del",function(){var orderIdx=parseInt($(this).closest(".order-item").attr("index"),10);
var $sentence=$(this).closest(".order-select-sentence");
var sentenceIdx=parseInt($sentence.attr("index"),10);
var sentenceID=parseInt($sentence.attr("sentId"),10);
var selectedSentence=$(this).closest(".order-sentence-radio");
var selectedOrders=self.getSelectedOrders();
var defaultSentenceId=selectedOrders[orderIdx].DEFAULT_SENTENCE_ID;
self.removeOrderSentenceDetails(orderIdx,sentenceIdx,sentenceID);
if(defaultSentenceId&&(parseInt(defaultSentenceId,10)===sentenceID)){if(selectedSentence.find(".order-select-sentence-name").length>0){$(selectedSentence.find(".order-select-sentence-name")[0]).trigger("change").prop("checked",true);
}else{delete selectedOrders[orderIdx].DEFAULT_SENTENCE_ID;
}}});
$target.find(".order-sec-detail").on("change",".order-sentence-dropdown",function(){var index=$(this).closest(".order-item").attr("index");
var sentenceList=self.getSelectedOrders()[index].SELECTED_SENTENCES?self.getSelectedOrders()[index].SELECTED_SENTENCES:[];
var sentenceIndex=sentenceList.length;
var $selectedOpt=$(this).find(":selected");
var sentenceId=$selectedOpt.attr("sentId");
var sentence=$selectedOpt.attr("sentName");
var isFirstOrderSentence=true;
var selectedSentence=$(this).parent().find(".order-sentence-radio");
if(self.getPlusAddEnabled()){sentenceList.forEach(function(element){if(element){isFirstOrderSentence=false;
}});
$(this).parent().find(".order-sentence-radio").append(self.renderOrderSentence(sentenceIndex,sentenceId,sentence,false,index));
if(isFirstOrderSentence){$(selectedSentence[0]).find(".order-select-sentence-name").attr("checked",true).trigger("click");
}self.updateSelectedOrders("sentence",index,sentenceId,isFirstOrderSentence);
$(this).prop("selectedIndex",0);
$selectedOpt.attr("disabled","disabled");
}else{self.updateSelectedOrders("sentence",index,sentenceId,true);
}}).on("change",".order-item-checkbox",function(){var index=$(this).closest(".order-item").attr("index");
if($(this).prop("checked")){self.updateSelectedOrders("checked",index,1);
}else{self.updateSelectedOrders("checked",index,0);
}}).on("change",".order-select-sentence-name",function(){if($(this).is(":checked")){self.updateSelectedOrders("sentence",$(this).closest(".order-item").attr("index"),$(this).closest(".order-select-sentence").attr("sentId"),true);
}});
};
