function SmartReviewComponentStyle(){this.initByNamespace("dqr");
}SmartReviewComponentStyle.inherits(ComponentStyle);
function SmartReviewComponent(criterion){this.clarifications=[];
this.m_authorityLevel=0;
this.m_DQR=null;
this.m_dynDoc=null;
this.m_powerNote=null;
this.m_clinDoc=null;
this.m_prefsObject=null;
this.m_nProcessing=0;
this.m_nWaitCursor=0;
this.m_srActiveHvr="";
this.setCriterion(criterion);
this.setStyles(new SmartReviewComponentStyle());
this.setComponentLoadTimerName("USR: Load SmartReview Historical Clarifications");
this.setComponentRenderTimerName("ENG:MPG.SmartReview.01 - render component");
this.setIncludeLineNumber(false);
this.m_editMode=false;
this.setScope(2);
window.dqr_mpage=criterion.category_mean;
SmartReviewComponent.method("InsertData",function(){CERN_DQR_O1.GetClarifications(this);
});
SmartReviewComponent.method("HandleSuccess",function(conditionData){CERN_DQR_O1.RenderClarifications(this,conditionData);
});
SmartReviewComponent.method("openTab",function(){var criterion=this.getCriterion();
var sParms="/PERSONID="+criterion.person_id+" /ENCNTRID="+criterion.encntr_id+" /FIRSTTAB=^"+this.getLink()+"+^";
APPLINK(0,criterion.executable,sParms);
this.InsertData();
});
SmartReviewComponent.method("getDateFormatter",function(){if(!this.m_df){this.m_df=new mp_formatter.DateTimeFormatter(MPAGE_LOCALE);
}return this.m_df;
});
}SmartReviewComponent.inherits(MPageComponent);
var CERN_DQR_O1=function(){return{GetClarifications:function(component){var timerLoadSmartReview=MP_Util.CreateTimer("CAP:MPG.SmartReview.01 - Load SmartReview Component");
if(timerLoadSmartReview){timerLoadSmartReview.SubtimerName=dqr_mpage;
timerLoadSmartReview.Stop();
}try{var personId=component.getCriterion().person_id.toFixed(1);
var encounterId=component.getCriterion().encntr_id.toFixed(1);
var prsnlId=component.getCriterion().provider_id.toFixed(1);
var pprCode=component.getCriterion().ppr_cd.toFixed(1);
component.m_DQR=window.external.DiscernObjectFactory("DOCUMENTQUALITYREVIEW");
if(component.m_DQR==null){component.m_authorityLevel=-1;
}else{component.m_authorityLevel=component.m_DQR.DetermineSmartReviewType(personId,encounterId);
}var dqrCompId=component.getComponentId();
var dqrModRootId="dqr"+dqrCompId;
var dqrCompSec=$("#"+dqrModRootId).get(0);
var titleFrag=$("<span/>");
var innerHTMLArr=[];
innerHTMLArr.push('<span id="dqrProcessing',dqrCompId,'" class="dqr-processing dqr-hide">',i18n.discernabu.smartreview_o1.PROCESSING,"</span>");
$(titleFrag).html(innerHTMLArr.join(""));
var secTitle=$(dqrCompSec).find(".sec-title").first();
$(secTitle).after(titleFrag);
var sendAr=[];
sendAr.push("^MINE^");
sendAr.push(personId);
sendAr.push(encounterId);
sendAr.push(prsnlId);
sendAr.push(pprCode);
if(component.m_authorityLevel==2){sendAr.push(0);
}else{sendAr.push(1);
}sendAr.push(1);
sendAr.join(",");
if(component.m_authorityLevel>0){MP_Core.XMLCclRequestWrapper(component,"MP_GET_CLARIFICATION_HISTORY",sendAr,true);
}else{if(component.m_authorityLevel==0){MP_Util.Doc.FinalizeComponent(MP_Util.HandleNoDataResponse(component.getStyles().getNameSpace()),component,"");
}else{MP_Util.Doc.FinalizeComponent(MP_Util.HandleErrorResponse(component.getStyles().getNameSpace(),i18n.discernabu.smartreview_o1.ERROR_CCL),component,"");
}}}catch(err){component.m_authorityLevel=-1;
}},RenderClarifications:function(component,conditionData){if(!conditionData){MP_Util.Doc.FinalizeComponent(MP_Util.HandleErrorResponse(component.getStyles().getNameSpace(),i18n.discernabu.smartreview_o1.ERROR_CCL),component,"");
return;
}var compId=component.getComponentId();
var patientId=component.getCriterion().person_id.toFixed(1);
var encounterId=component.getCriterion().encntr_id.toFixed(1);
var secHTMLArray=[];
if(component.m_authorityLevel>0){secHTMLArray.push("<div class='dqr-component-container'>");
secHTMLArray.push("<div class='dqr-topsection'>");
secHTMLArray.push("<div class='dqr-topsection-label'>");
secHTMLArray.push("<span class='dqr-topsection-label-largerText'>"+i18n.discernabu.smartreview_o1.LAST_RUN_ON+"&nbsp</span>");
if(conditionData.TRANSACTION_DT_TM){var dateTime=new Date();
var dateFormatter=component.getDateFormatter();
dateTime.setISO8601(conditionData.TRANSACTION_DT_TM);
var transactionDateTime=dateFormatter.format(dateTime,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_4YEAR);
var personnelName=CERN_DQR_O1.ReplaceInvalidStringCharacters(conditionData.PRSNL_NAME);
secHTMLArray.push("<span class='dqr-topsection-label-smallerText'>"+i18n.discernabu.smartreview_o1.ALL_NOTES+"&nbsp</span>");
secHTMLArray.push("<span class='dqr-topsection-label-time'>"+i18n.discernabu.smartreview_o1.DATE_BY.replace("{0}",transactionDateTime).replace("{1}",personnelName)+" </span>");
}else{secHTMLArray.push("<span class='dqr-topsection-label-time'>"+i18n.discernabu.smartreview_o1.NA+"</span>");
}secHTMLArray.push("</div>");
var valid=(component.m_authorityLevel==1);
if(component.m_authorityLevel==2){component.m_prefsObject=JSON.parse(component.m_DQR.RetrievePrefsForNewNoteDocumentation(patientId,encounterId));
if(component.m_prefsObject.ValidPrefs&&CERN_DQR_O1.CheckIfCorrectDllIsLoaded(component)){valid=true;
}}if(valid){secHTMLArray.push("<div class='dqr-topsection-button-div'><input type='button' class='dqr-smartReview-button' value='"+i18n.discernabu.smartreview_o1.SMARTREVIEW+"' onclick='CERN_DQR_O1.OnSmartReviewClick("+compId+");'></div>");
}secHTMLArray.push("</div>");
if(!conditionData.CLARIFICATIONS||conditionData.CLARIFICATIONS.length==0){secHTMLArray.push(CERN_DQR_O1.RenderEmptyTable(component));
}else{for(var i=0;
i<conditionData.CLARIFICATIONS.length;
i++){component.clarifications[component.clarifications.length]=conditionData.CLARIFICATIONS[i];
}CERN_DQR_O1.RenderTable(component,secHTMLArray);
}secHTMLArray.push("</div>");
var secHTML=secHTMLArray.join("");
MP_Util.Doc.FinalizeComponent(secHTML,component,"");
CERN_DQR_O1.RefreshClarificationBorders(component);
CERN_DQR_O1.UpdateScroll(compId);
}else{if(component.m_authorityLevel==0){MP_Util.Doc.FinalizeComponent(MP_Util.HandleNoDataResponse(component.getStyles().getNameSpace()),component,"");
}else{MP_Util.Doc.FinalizeComponent(MP_Util.HandleErrorResponse(component.getStyles().getNameSpace(),i18n.discernabu.smartreview_o1.ERROR_DLL),component,"");
}}},CheckIfCorrectDllIsLoaded:function(component){var framework=component.m_prefsObject.FrameworkPref;
if(framework=="powernote"){component.m_powerNote=window.external.DiscernObjectFactory("POWERNOTE");
if(component.m_powerNote==null){return false;
}}else{if(framework=="clinical_documentation"){component.m_clinDoc=window.external.DiscernObjectFactory("CLINICALNOTE");
if(component.m_clinDoc==null){return false;
}}else{if(framework=="dynamic_documentation"){component.m_dynDoc=window.external.DiscernObjectFactory("DYNDOC");
if(component.m_dynDoc==null){return false;
}}else{return false;
}}}return true;
},OnSmartReviewClick:function(compId){var component=MP_Util.GetCompObjById(compId);
if(component.m_authorityLevel==2){CERN_DQR_O1.PhysicianSmartReviewClick(component);
}else{if(component.m_authorityLevel==1){CERN_DQR_O1.NonPhysicianSmartReviewClick(compId);
}else{return;
}}},NonPhysicianSmartReviewClick:function(compId){var component=MP_Util.GetCompObjById(compId);
var personId=component.getCriterion().person_id.toFixed(1);
var encounterId=component.getCriterion().encntr_id.toFixed(1);
var prsnlId=component.getCriterion().provider_id.toFixed(1);
var pprCode=component.getCriterion().ppr_cd.toFixed(1);
var sendAr=[];
sendAr.push("^MINE^");
sendAr.push(personId);
sendAr.push(encounterId);
sendAr.push(prsnlId);
sendAr.push(pprCode);
sendAr.push(0);
sendAr.push(0);
CERN_DQR_O1.loadWithCBParameters(compId,"mp_get_clarification_history",CERN_DQR_O1.RenderOutstandingClarifications,sendAr.join(","));
},PhysicianSmartReviewClick:function(component){var personId=component.getCriterion().person_id.toFixed(1);
var encounterId=component.getCriterion().encntr_id.toFixed(1);
var result=component.m_DQR.LaunchEncounterDQRDialog(0,personId,encounterId);
if(result!==0){return;
}var dxCollection=component.m_DQR.RetrieveDxCollection();
var strCollection=component.m_DQR.RetrieveStrCollection();
if(dxCollection.Count>0&&strCollection.Count>0){CERN_DQR_O1.LaunchDocumentation(component,dxCollection,strCollection);
}},LaunchDocumentation:function(component,dxCollection,strCollection){var personId=component.getCriterion().person_id.toFixed(1);
var encounterId=component.getCriterion().encntr_id.toFixed(1);
var framework=component.m_prefsObject.FrameworkPref;
if(framework=="powernote"){try{component.m_powerNote.BeginNoteFromEncounterPathwayWithReview(personId,encounterId,component.m_prefsObject.EPCKISourcePref,component.m_prefsObject.EPCKIIdentifierPref,component.m_prefsObject.NoteTypeEventCdPref,dxCollection,strCollection);
}catch(err){alert(i18n.discernabu.smartreview_o1.ERROR_NEW_NOTE);
}}else{if(framework=="clinical_documentation"){try{component.m_clinDoc.BeginNoteWithReview(personId,encounterId,component.m_prefsObject.NoteTypeEventCdPref,dxCollection,strCollection);
}catch(err){alert(i18n.discernabu.smartreview_o1.ERROR_NEW_NOTE);
}}else{if(framework=="dynamic_documentation"){try{component.m_dynDoc.OpenNewDocumentByReferenceTemplateIdWithReview(personId,encounterId,component.m_prefsObject.RefTemplatePref,component.m_prefsObject.NoteTypeEventCdPref,dxCollection,strCollection);
}catch(err){alert(i18n.discernabu.smartreview_o1.ERROR_NEW_NOTE);
}}else{alert(i18n.discernabu.smartreview_o1.ERROR_NEW_NOTE);
}}}},RemovePreviousOutstandingClarifications:function(){if($(".dqr-removableOutstandingClarifications").length>0){$(".dqr-removableOutstandingClarifications").remove();
}},RenderOutstandingClarifications:function(component,outstandingClarifications){var compId=component.getComponentId();
var secHTMLArray=new Array();
var jQueryHTMLObject=$("<span/>");
var json=JSON.parse(outstandingClarifications);
var transactionDateTime="";
var zeroTime="/Date(0000-00-00T00:00:00.000+00:00)/";
if(json.RECORD_DATA.TRANSACTION_DT_TM&&json.RECORD_DATA.TRANSACTION_DT_TM!=zeroTime){var dateTime=new Date();
var dateFormatter=component.getDateFormatter();
dateTime.setISO8601(json.RECORD_DATA.TRANSACTION_DT_TM);
transactionDateTime=dateFormatter.format(dateTime,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_4YEAR);
}var sectionCount=$("#dqrContents"+compId).children().length;
secHTMLArray.push('<div id="dqr-section'+compId+""+sectionCount+'" class="dqr-removableOutstandingClarifications">');
var replyStatus=json.RECORD_DATA.STATUS_DATA.STATUS.toUpperCase();
if(replyStatus=="S"&&json.RECORD_DATA.CLARIFICATIONS.length>0){CERN_DQR_O1.RenderEntryHeader(compId,transactionDateTime,"",true,secHTMLArray,sectionCount);
var clarSequence=0;
for(var i=0;
i<json.RECORD_DATA.CLARIFICATIONS.length;
i++){var identifier=compId+""+sectionCount+"-row-"+clarSequence;
secHTMLArray.push('<div id="dqr-section-',identifier,'" class="dqr-table-entryContainer-div-border">');
if(json.RECORD_DATA.CLARIFICATIONS[i].CONFIDENCE_FLAG==2){secHTMLArray.push('<div id="clarEntryContainer',identifier,'" class="dqr-table-positionEntry dqr-table-entryContainer dqr-darkGrayBorder">');
secHTMLArray.push('<div id="clarEntry',identifier,'" class="dqr-table-entryLowConfidence-div" onmouseenter="CERN_DQR_O1.mEnterEntry(',compId,",",sectionCount,",",clarSequence,')" onmouseleave="CERN_DQR_O1.mLeaveEntry(',compId,",",sectionCount,",",clarSequence,')">');
}else{secHTMLArray.push('<div id="clarEntryContainer',identifier,'" class="dqr-table-positionEntry dqr-table-entryContainer dqr-lightGrayBorder">');
secHTMLArray.push('<div id="clarEntry',identifier,'" class="dqr-table-entry-div" onmouseenter="CERN_DQR_O1.mEnterEntry(',compId,",",sectionCount,",",clarSequence,')" onmouseleave="CERN_DQR_O1.mLeaveEntry(',compId,",",sectionCount,",",clarSequence,')">');
}secHTMLArray.push('<div id="expandDiv',identifier,'" class="dqr-table-entry-expand-div">');
secHTMLArray.push('<div id="expandIcon',identifier,'" onclick="CERN_DQR_O1.onClickExpandEntry(',compId,",",sectionCount,",",clarSequence,')" class="dqr-table-expand-img-hidden"></div></div>');
secHTMLArray.push('<div class="dqr-table-entry-action-div"></div>');
secHTMLArray.push('<div class="dqr-table-entry-clarification-div">',CERN_DQR_O1.ReplaceInvalidStringCharacters(json.RECORD_DATA.CLARIFICATIONS[i].DISPLAY),"</div>");
secHTMLArray.push("</div>");
var clarification=json.RECORD_DATA.CLARIFICATIONS[i];
if(clarification.EXISTING_CONDITION.DISPLAY==""){CERN_DQR_O1.RenderSupportingFindings(component,clarification,identifier,secHTMLArray);
}else{CERN_DQR_O1.RenderClarifyFindings(component,clarification,identifier,secHTMLArray);
}secHTMLArray.push("</div>");
secHTMLArray.push("</div>");
clarSequence++;
}}else{var message=i18n.discernabu.smartreview_o1.NO_OUTSTANDING_CLARIFICATIONS;
if(replyStatus=="F"){message=i18n.discernabu.smartreview_o1.OUTSTANDING_ERROR;
}CERN_DQR_O1.RenderEntryHeader(compId,transactionDateTime,"",false,secHTMLArray);
secHTMLArray.push('<div class="dqr-table-notificationContainer">');
secHTMLArray.push('<div class="dqr-table-notificationContainer-notificationText">',message,"</div>");
secHTMLArray.push("</div>");
}secHTMLArray.push("</div>");
jQueryHTMLObject.html(secHTMLArray.join(""));
var firstSection=$("#dqrContents"+compId).children().first();
if(firstSection.length>0){firstSection.prepend(jQueryHTMLObject);
}else{var contents=$("#dqrContents"+compId);
contents.remove();
var tableHeader=$("#dqr-table-header"+compId);
tableHeader.append(jQueryHTMLObject);
}CERN_DQR_O1.UpdateScroll(compId);
$("#dqrContents"+compId).scrollTo(0,0);
CERN_DQR_O1.updateExpandAll(compId);
CERN_DQR_O1.processingUI(component,"dqrProcessing"+compId,-1,true,null,compId);
},RenderEmptyTable:function(component){var array=[];
var compId=component.getComponentId();
array.push('<div class="dqr-table">');
array.push('<div class="dqr-table-title-div">');
array.push('<div class="dqr-table-title-text">',i18n.discernabu.smartreview_o1.HISTORY,"</div>");
array.push('<div class="dqr-table-title-controls"></div>');
array.push("</div>");
array.push('<div id="dqr-table-header'+compId+'" class="dqr-table-header-div">');
array.push('<div class="dqr-table-entry-expand-div"></div>');
array.push('<div class="dqr-table-header-action"><p class="dqr-table-header-text">',i18n.discernabu.smartreview_o1.ACTION,"</p></div>");
array.push('<div class="dqr-table-header-clarification">',i18n.discernabu.smartreview_o1.CLARIFICATION,"</div>");
array.push("</div>");
array.push('<div id="dqrContents'+compId+'" class="dqr-emptyTable">',i18n.discernabu.smartreview_o1.NO_CLARIFICATIONS_RETURNED,"</div></div>");
return array.join("");
},RenderTable:function(component,secHTMLArray){var compId=component.getComponentId();
secHTMLArray.push('<div class="dqr-table">');
secHTMLArray.push('<div class="dqr-table-title-div">');
secHTMLArray.push('<div class="dqr-table-title-text">',i18n.discernabu.smartreview_o1.HISTORY,"</div>");
secHTMLArray.push('<div class="dqr-table-title-controls"><input id="showAcceptedCheck'+compId+'" type="checkbox" checked="checked" onclick="CERN_DQR_O1.ShowAccepted('+compId+')" name="show-accepted" value="all">',i18n.discernabu.smartreview_o1.SHOW_ACCEPTED+"<span class='dqr-table-title-acceptedCheckBox'></span>",'<a id="dqrExpandAll" onclick="CERN_DQR_O1.ExpandAll('+compId+')" class = "dqr-expand-link-text" tabindex="0">',i18n.discernabu.smartreview_o1.EXPAND_ALL,"</a></div>");
secHTMLArray.push("</div>");
secHTMLArray.push('<div class="dqr-table-header-div">');
secHTMLArray.push('<div class="dqr-table-entry-expand-div"></div>');
secHTMLArray.push('<div class="dqr-table-header-action"><p class="dqr-table-header-text">',i18n.discernabu.smartreview_o1.ACTION,"</p></div>");
secHTMLArray.push('<div class="dqr-table-header-clarification">',i18n.discernabu.smartreview_o1.CLARIFICATION,"</div>");
secHTMLArray.push("</div>");
secHTMLArray.push('<div id="dqrContents'+compId+'" class="dqr-table-contents-div" onscroll="CERN_DQR_O1.OnScrollContent(',compId,')">');
var dateTime=null;
var sectionCount=0;
var clarSequence=0;
for(var i=0;
i<component.clarifications.length;
i++){if(component.clarifications[i].ACTION_DT_TM!=dateTime){dateTime=new Date();
var dateFormatter=component.getDateFormatter();
dateTime.setISO8601(component.clarifications[i].ACTION_DT_TM);
var transactionDateTime=dateFormatter.format(dateTime,mp_formatter.DateTimeFormatter.FULL_DATE_TIME_4YEAR);
secHTMLArray.push('<div id="dqr-section'+compId+""+sectionCount+'">');
clarSequence=0;
dateTime=component.clarifications[i].ACTION_DT_TM;
CERN_DQR_O1.RenderEntryHeader(compId,transactionDateTime,component.clarifications[i].ACTION_PRSNL_NAME,true,secHTMLArray,sectionCount);
}CERN_DQR_O1.RenderEntry(component,component.clarifications[i],clarSequence,secHTMLArray,sectionCount);
if(component.clarifications[i+1]==null||component.clarifications[i+1].ACTION_DT_TM!=dateTime){secHTMLArray.push("</div>");
sectionCount++;
}clarSequence++;
}secHTMLArray.push("</div></div>");
},RenderEntryHeader:function(compId,dateTime,actionBy,displayExpand,secHTMLArray,sectionCount){var component=getCompObjByStringOrIntId(compId);
var identifier="dqr-section-"+compId+""+sectionCount;
secHTMLArray.push('<div id="',identifier,'-header" class="dqr-table-entryHeader-div">');
secHTMLArray.push('<div class="dqr-table-entryHeader-date-div">',dateTime,"</div>");
if(actionBy!=""){secHTMLArray.push('<div class="dqr-table-entryHeader-physician-div">',CERN_DQR_O1.ReplaceInvalidStringCharacters(actionBy),"</div>");
}if(displayExpand){secHTMLArray.push('<div class="dqr-table-entryHeader-controls"><a id="SectionExpandAll',compId+""+sectionCount,'" class="dqr-expand-link-text" onclick="CERN_DQR_O1.ExpandSection(',compId,",",sectionCount,')" tabindex="0">',i18n.discernabu.smartreview_o1.EXPAND,"</a></div>");
}secHTMLArray.push("</div>");
},RenderEntry:function(component,clarification,clarSequence,secHTMLArray,sectionCount){var compId=component.getComponentId();
var loc=component.getCriterion().static_content;
var identifier=compId+""+sectionCount+"-row-"+clarSequence;
secHTMLArray.push('<div id="dqr-section-',identifier,'" class="dqr-table-entryContainer-div-border">');
if(clarification.CONFIDENCE_FLAG==2){secHTMLArray.push('<div id="clarEntryContainer',identifier,'" class="dqr-table-positionEntry dqr-table-entryContainer dqr-darkGrayBorder">');
secHTMLArray.push('<div id="clarEntry',identifier,'" class="dqr-table-entryLowConfidence-div" onmouseenter="CERN_DQR_O1.mEnterEntry(',compId,",",sectionCount,",",clarSequence,')" onmouseleave="CERN_DQR_O1.mLeaveEntry(',compId,",",sectionCount,",",clarSequence,')">');
}else{if(clarification.ACTION_FLAG==4){secHTMLArray.push('<div id="clarEntryContainer',identifier,'" class="dqr-table-positionEntry dqr-table-entryContainer dqr-orangeBorder">');
secHTMLArray.push('<div id="clarEntry',identifier,'" class="dqr-table-entryRestrictedPrivs-div" onmouseenter="CERN_DQR_O1.mEnterEntry(',compId,",",sectionCount,",",clarSequence,')" onmouseleave="CERN_DQR_O1.mLeaveEntry(',compId,",",sectionCount,",",clarSequence,')">');
}else{secHTMLArray.push('<div id="clarEntryContainer',identifier,'" class="dqr-table-positionEntry dqr-table-entryContainer dqr-lightGrayBorder">');
secHTMLArray.push('<div id="clarEntry',identifier,'" class="dqr-table-entry-div" onmouseenter="CERN_DQR_O1.mEnterEntry(',compId,",",sectionCount,",",clarSequence,')" onmouseleave="CERN_DQR_O1.mLeaveEntry(',compId,",",sectionCount,",",clarSequence,')">');
}}secHTMLArray.push('<div id="expandDiv',identifier,'" class="dqr-table-entry-expand-div">');
secHTMLArray.push('<div id="expandIcon',identifier,'" onclick="CERN_DQR_O1.onClickExpandEntry(',compId,",",sectionCount,",",clarSequence,')" class="dqr-table-expand-img-hidden"></div></div>');
secHTMLArray.push('<div class="dqr-table-entry-action-div">');
if(clarification.ACTION_FLAG==0&&clarification.CONFIDENCE_FLAG==3){secHTMLArray.push(CERN_DQR_O1.SetImageAndLabelHover(component,identifier,clarSequence,"noAction","dqr-noAction",i18n.discernabu.smartreview_o1.NO_ACTION,sectionCount));
}else{if(clarification.ACTION_FLAG==1){secHTMLArray.push(CERN_DQR_O1.SetImageAndLabelHover(component,identifier,clarSequence,"accepted","dqr-acceptedReviewed",i18n.discernabu.smartreview_o1.ACCEPTED,sectionCount));
}else{if(clarification.ACTION_FLAG==2){secHTMLArray.push(CERN_DQR_O1.SetImageAndLabelHover(component,identifier,clarSequence,"skipped","dqr-skipped",i18n.discernabu.smartreview_o1.ASK_LATER,sectionCount));
}else{if(clarification.ACTION_FLAG==3){secHTMLArray.push(CERN_DQR_O1.SetImageAndLabelHover(component,identifier,clarSequence,"accepted","dqr-acceptedReviewed",i18n.discernabu.smartreview_o1.REVIEWED,sectionCount));
}else{if(clarification.ACTION_FLAG==4){secHTMLArray.push(CERN_DQR_O1.SetImageAndLabelHover(component,identifier,clarSequence,"restrictedPrivs","dqr-noPrivs",i18n.discernabu.smartreview_o1.RESTRICTED_VIEW,sectionCount));
}else{if(clarification.ACTION_FLAG==6){secHTMLArray.push(CERN_DQR_O1.SetImageAndLabelHover(component,identifier,clarSequence,"accepted","dqr-acceptedReviewed",i18n.discernabu.smartreview_o1.OTHER,sectionCount));
}else{if(clarification.ACTION_FLAG==7){secHTMLArray.push(CERN_DQR_O1.SetImageAndLabelHover(component,identifier,clarSequence,"doesNotApply","dqr-doesNotApply",i18n.discernabu.smartreview_o1.DOES_NOT_APPLY,sectionCount));
}else{if(clarification.CONFIDENCE_FLAG==2){secHTMLArray.push(CERN_DQR_O1.SetImageAndLabelHover(component,identifier,clarSequence,"noAction","dqr-lowConfidence",i18n.discernabu.smartreview_o1.LIMITED_FINDINGS,sectionCount));
}else{secHTMLArray.push("</div>");
}}}}}}}}if(clarification.ACTION_FLAG==6||(clarification.ACTION_FLAG==1&&clarification.EXISTING_CONDITION.DISPLAY!="")){secHTMLArray.push('<div class="dqr-table-entry-clarification-strikeout-div">',CERN_DQR_O1.ReplaceInvalidStringCharacters(clarification.DISPLAY),"</div>");
if(clarification.ACTION_FLAG==1){secHTMLArray.push('<div class="dqr-table-entry-clarification-clarifiedCondition-div">',CERN_DQR_O1.ReplaceInvalidStringCharacters(clarification.POTENTIAL_CONDITION.DISPLAY),"</div>");
}else{secHTMLArray.push('<div class="dqr-table-entry-clarification-clarifiedCondition-div">',CERN_DQR_O1.ReplaceInvalidStringCharacters(clarification.OTHER_CONDITION.DISPLAY),"</div>");
}}else{if(clarification.ACTION_FLAG==5){secHTMLArray.push('<div class="dqr-table-entry-clarification-div">',i18n.discernabu.smartreview_o1.ERROR,"</div>");
}else{secHTMLArray.push('<div class="dqr-table-entry-clarification-div">',CERN_DQR_O1.ReplaceInvalidStringCharacters(clarification.DISPLAY),"</div>");
}}secHTMLArray.push("</div>");
if(clarification.EXISTING_CONDITION.DISPLAY==""&&clarification.ACTION_FLAG!=6){CERN_DQR_O1.RenderSupportingFindings(component,clarification,identifier,secHTMLArray);
}else{CERN_DQR_O1.RenderClarifyFindings(component,clarification,identifier,secHTMLArray);
}secHTMLArray.push("</div>");
secHTMLArray.push("</div>");
},SetImageAndLabelHover:function(component,identifier,clarSequence,idName,cssImageName,labelText,sectionCount){var compId=component.getComponentId();
var html=[];
html.push('<div id="',idName+""+identifier,'" class="dqr-table-action-img ',cssImageName,'" onmouseenter="CERN_DQR_O1.mEnterAction(',compId,",",sectionCount,",",clarSequence,')" onmouseleave="CERN_DQR_O1.mLeaveAction(',compId,",",sectionCount,",",clarSequence,')"></div></div>');
html.push('<span id="labelHover',identifier,'" class="dqr-hvr hover">',labelText,"</span>");
return html.join("");
},mEnterAction:function(compId,sectionSequence,clarSequence){var component=getCompObjByStringOrIntId(compId);
var hvr=$("#labelHover"+compId+""+sectionSequence+"-row-"+clarSequence);
CERN_DQR_O1.clearActiveHover(compId);
component.m_srActiveHvr=hvr;
$(component.m_srActiveHvr).appendTo($("body"));
$(hvr).css("display","inline");
CERN_DQR_O1.updateActiveHover(component);
},mLeaveAction:function(compId,sectionSequence,clarSequence){var component=getCompObjByStringOrIntId(compId);
var identifier=compId+""+sectionSequence+"-row-"+clarSequence;
var hvr=$("#labelHover"+identifier);
$(hvr).css("display","none");
if($("accepted"+compId+""+clarSequence)!=null){$(component.m_srActiveHvr).appendTo($("accepted"+identifier));
}if($("skipped"+compId+""+clarSequence)!=null){$(component.m_srActiveHvr).appendTo($("skipped"+identifier));
}if($("noAction"+compId+""+clarSequence)!=null){$(component.m_srActiveHvr).appendTo($("noAction"+identifier));
}CERN_DQR_O1.clearActiveHover(compId);
},clearActiveHover:function(compId){var component=getCompObjByStringOrIntId(compId);
if(component.m_srActiveHvr){$(component.m_srActiveHvr).css("display","none");
component.m_srActiveHvr="";
}},updateActiveHover:function(component){var mousePos=CERN_DQR_O1.absoluteCursorPosition();
if(component.m_srActiveHvr&&mousePos){if(mousePos.Y+component.m_srActiveHvr.height()<$(window).height()-10){var top_pos=mousePos.Y+10;
}else{var top_pos=mousePos.Y-component.m_srActiveHvr.height()-10;
}if(mousePos.X+component.m_srActiveHvr.width()<$(window).width()-10){var left_pos=mousePos.X+10;
}else{var left_pos=mousePos.X-component.m_srActiveHvr.width()-10;
}$(component.m_srActiveHvr).offset({top:top_pos,left:left_pos});
}},RenderClarifyFindings:function(component,clarification,clarSequence,secHTMLArray){var compId=component.getComponentId();
var patientId=component.getCriterion().person_id.toFixed(1);
var encounterId=component.getCriterion().encntr_id.toFixed(1);
secHTMLArray.push(CERN_DQR_O1.RenderFindingsBackground(clarSequence,clarification));
var condition=(clarification.ACTION_FLAG==6)?clarification.OTHER_CONDITION:clarification.POTENTIAL_CONDITION;
secHTMLArray.push('<table class="dqr-table-findings-table">');
secHTMLArray.push("<tr>");
secHTMLArray.push('<td class="dqr-table-findings-condition-column-1"></td>');
secHTMLArray.push('<td class="dqr-table-findings-condition-column-2">');
if(clarification.ACTION_FLAG==1||clarification.ACTION_FLAG==6){secHTMLArray.push('<div class="dqr-table-findings-clarification-name-current-div">',CERN_DQR_O1.ReplaceInvalidStringCharacters(condition.DISPLAY),"</div>");
}else{secHTMLArray.push('<div class="dqr-table-findings-clarification-name-potential-div">',CERN_DQR_O1.ReplaceInvalidStringCharacters(condition.DISPLAY),"</div>");
}secHTMLArray.push('<div class="dqr-table-findings-typeContainer">');
secHTMLArray.push('<div class="dqr-table-findings-typeContainer-typeLabel">',i18n.discernabu.smartreview_o1.TYPE,"</div>");
if(clarification.EXISTING_CONDITION.DISPLAY==""){secHTMLArray.push('<div class="dqr-table-findings-typeContainer-typeName">',i18n.discernabu.smartreview_o1.SUPPORTED_DIAGNOSIS,"</div>");
}else{secHTMLArray.push('<div class="dqr-table-findings-typeContainer-typeName">',i18n.discernabu.smartreview_o1.CURRENT_DIAGNOSIS,"</div>");
}secHTMLArray.push("</div>");
secHTMLArray.push(CERN_DQR_O1.AddDocuments(clarification,patientId,encounterId));
secHTMLArray.push(CERN_DQR_O1.RenderFindingsDiv(clarification,condition));
secHTMLArray.push("</td>");
secHTMLArray.push('<td class="dqr-table-findings-condition-column-3"></td>');
secHTMLArray.push("</tr>");
secHTMLArray.push("</table>");
secHTMLArray.push("</div>");
},RenderSupportingFindings:function(component,clarification,clarSequence,secHTMLArray){var compId=component.getComponentId();
var condition=(clarification.ACTION_FLAG==6)?clarification.OTHER_CONDITION:clarification.POTENTIAL_CONDITION;
var patientId=component.getCriterion().person_id.toFixed(1);
var encounterId=component.getCriterion().encntr_id.toFixed(1);
secHTMLArray.push(CERN_DQR_O1.RenderFindingsBackground(clarSequence,clarification));
secHTMLArray.push('<div class="dqr-table-findingsContainer-div">');
secHTMLArray.push('<div class="dqr-table-findings-typeContainer">');
secHTMLArray.push('<div class="dqr-table-findings-typeContainer-typeLabel">',i18n.discernabu.smartreview_o1.TYPE,"</div>");
secHTMLArray.push('<div class="dqr-table-findings-typeContainer-typeName">',i18n.discernabu.smartreview_o1.SUPPORTED_DIAGNOSIS,"</div>");
secHTMLArray.push("</div>");
secHTMLArray.push(CERN_DQR_O1.AddDocuments(clarification,patientId,encounterId));
secHTMLArray.push(CERN_DQR_O1.RenderFindingsDiv(clarification,condition));
secHTMLArray.push("</div>");
secHTMLArray.push("</div>");
},RenderFindingsBackground:function(clarSequence,clarification){var html=[];
if(clarification.CONFIDENCE_FLAG==2){html.push('<div id="clarFindings',clarSequence,'" class="dqr-table-findingsLowConfidence-div dqr-hidden">');
}else{if(clarification.ACTION_FLAG==4){html.push('<div id="clarFindings',clarSequence,'" class="dqr-table-findingsRestrictedPrivs-div dqr-hidden">');
}else{html.push('<div id="clarFindings',clarSequence,'" class="dqr-table-findings-div dqr-hidden">');
}}return html.join("");
},RenderFindingsDiv:function(clarification,condition){if(clarification==null||condition==null){return[];
}var html=[];
html.push('<div class="dqr-table-findings-SupportingFindings-div">');
html.push('<div class="dqr-table-findings-SupportingFindings-label-div">',i18n.discernabu.smartreview_o1.SUPPORTING_FINDINGS,"</div>");
if(clarification.SUPPORTING_DATA.SUPPORTING_CODES.length==0&&clarification.SUPPORTING_DATA.SUPPORTING_TREATMENTS.length==0&&clarification.SUPPORTING_DATA.LAB_VITALS.length==0){html.push('<div class="dqr-table-findings-noSupportingFindings">',i18n.discernabu.smartreview_o1.NO_SUPPORTING_FINDINGS,"</div>");
}else{html.push('<div class="dqr-table-findings-SupportingFindings-columnContainer">');
if(clarification.SUPPORTING_DATA.SUPPORTING_CODES.length!=0){html.push(CERN_DQR_O1.AddFindings(i18n.discernabu.smartreview_o1.FINDINGS,clarification.SUPPORTING_DATA.SUPPORTING_CODES));
}if(clarification.SUPPORTING_DATA.SUPPORTING_TREATMENTS.length!=0){html.push(CERN_DQR_O1.AddFindings(i18n.discernabu.smartreview_o1.MEDICATIONS,clarification.SUPPORTING_DATA.SUPPORTING_TREATMENTS));
}if(clarification.SUPPORTING_DATA.LAB_VITALS.length!=0){html.push(CERN_DQR_O1.AddFindings(i18n.discernabu.smartreview_o1.MEASUREMENTS,clarification.SUPPORTING_DATA.LAB_VITALS));
}html.push("</div>");
}if(condition.NOTE_TEXT!=""){html.push(CERN_DQR_O1.RenderNoteText(clarification.ACTION_FLAG,condition.NOTE_TEXT));
}html.push("</div>");
return html.join("");
},AddDocuments:function(clarification,patientId,encounterId){if(clarification==null){return[];
}var html=[];
html.push('<div class="dqr-table-findings-ContributingDoc-div">');
html.push('<div class="dqr-table-findings-ContributingDoc-label-div">',i18n.discernabu.smartreview_o1.CONTRIBUTING_DOCUMENTS,"</div>");
html.push('<div class="dqr-table-findings-ContributingDoc-details-div">');
if(clarification.SUPPORTING_DATA.SUPPORTING_DOCUMENTS.length<1){html.push('<div class="dqr-table-findings-ContributingDoc-noDocs-div">',i18n.discernabu.smartreview_o1.NO_DOCUMENTS,"</div>");
}else{for(var i=0;
i<clarification.SUPPORTING_DATA.SUPPORTING_DOCUMENTS.length;
i++){html.push(MP_Util.CreateClinNoteLink(patientId,encounterId,clarification.SUPPORTING_DATA.SUPPORTING_DOCUMENTS[i].ID,CERN_DQR_O1.ReplaceInvalidStringCharacters(clarification.SUPPORTING_DATA.SUPPORTING_DOCUMENTS[i].NAME),"DOC",0));
if(i+1!=clarification.SUPPORTING_DATA.SUPPORTING_DOCUMENTS.length){html.push(", ");
}}}html.push("</div></div>");
return html.join("");
},AddFindings:function(headerDisp,findings){if(findings==null||findings.length==0){return[];
}var html=[];
html.push('<div class="dqr-table-findings-SupportingFindings-column-div">');
html.push("<ul>");
html.push('<li class="dqr-table-findings-SupportingFindings-entry-div">');
html.push('<span class="dqr-table-findings-SupportingFindings-header-text">',headerDisp,"</span></li>");
for(var i=0;
i<findings.length;
i++){var findingsDisplay=findings[i].DISPLAY;
if(findings[i].NEGATIVE_IND==1){findingsDisplay=i18n.discernabu.smartreview_o1.NEGATIVE_FORMAT.replace("{0}",findings[i].DISPLAY).replace("{1}",i18n.discernabu.smartreview_o1.NEGATIVE);
}html.push('<li class="dqr-table-findings-SupportingFindings-entry-div">',CERN_DQR_O1.ReplaceInvalidStringCharacters(findingsDisplay),"</li>");
}html.push("</ul>");
html.push("</div>");
return html.join("");
},RenderNoteText:function(actionFlag,noteText){if(noteText==null){return[];
}var html=[];
html.push('<div class="dqr-table-findings-NoteText-div">');
if(actionFlag==1||actionFlag==6){html.push('<div class="dqr-table-findings-NoteText-label-div">',i18n.discernabu.smartreview_o1.NOTE_TEXT,"</div>");
}else{html.push('<div class="dqr-table-findings-NoteText-label-div">',i18n.discernabu.smartreview_o1.CLARIFICATION_TEXT,"</div>");
}html.push('<div class="dqr-table-findings-NoteText-details-div">',CERN_DQR_O1.ReplaceInvalidStringCharacters(noteText),"</div>");
html.push("</div>");
return html.join("");
},ReplaceInvalidStringCharacters:function(stringToValidate){var returnString="";
returnString=stringToValidate.replace(/</g,"&lt;").replace(/>/g,"&gt;");
return returnString;
},RefreshClarificationBorders:function(component){var compId=component.getComponentId();
var sectionCount=$("#dqrContents"+compId).children().length;
for(var i=0;
i<sectionCount;
i++){var section=$("#dqr-section"+compId+""+i);
var header=section.children().first();
var bottom=section.children().last();
var lastVisible;
var previous;
if(!bottom.hasClass("dqr-hidden")){lastVisible=bottom;
}else{previous=bottom.prev();
while(previous.hasClass("dqr-hidden")&&!previous.is(header)){previous=previous.prev();
}if(previous.is(header)){continue;
}lastVisible=previous;
}CERN_DQR_O1.SetClarificationToBottom(lastVisible);
previous=lastVisible.prev();
while(!previous.is(header)){CERN_DQR_O1.SetClarificationToNonBottom(previous);
previous=previous.prev();
}}},SetClarificationToBottom:function(entryWrapper){entry=entryWrapper.children().first();
if(entry.hasClass("dqr-table-entryContainer")){entry.removeClass("dqr-table-entryContainer");
entry.addClass("dqr-table-entryContainer-bottom");
}if(entry.hasClass("dqr-table-entryContainer-expanded")){entry.removeClass("dqr-table-entryContainer-expanded");
entry.addClass("dqr-table-entryContainer-expanded-bottom");
}},SetClarificationToNonBottom:function(entryWrapper){entry=entryWrapper.children().first();
if(entry.hasClass("dqr-table-entryContainer-bottom")){entry.removeClass("dqr-table-entryContainer-bottom");
entry.addClass("dqr-table-entryContainer");
}if(entry.hasClass("dqr-table-entryContainer-expanded-bottom")){entry.removeClass("dqr-table-entryContainer-expanded-bottom");
entry.addClass("dqr-table-entryContainer-expanded");
}},OnScrollContent:function(compId){$("#dqrContents"+compId).scrollLeft(0);
},UpdateScroll:function(compId){var component=getCompObjByStringOrIntId(compId);
if(component.isScrollingEnabled()==false){return;
}var entryInfo=CERN_DQR_O1.GetVisibleEntryInfo(compId);
var numOfVisibleEntries=entryInfo[0];
var tableContents=document.getElementById("dqrContents"+compId);
if(numOfVisibleEntries>component.getScrollNumber()){tableContents.setAttribute("class","dqr-table-contents-div-scroll");
CERN_DQR_O1.SetOptimalContentHeight(compId,entryInfo);
}else{tableContents.setAttribute("class","dqr-table-contents-div");
tableContents.style.height="auto";
}},GetVisibleEntryInfo:function(compId){var component=getCompObjByStringOrIntId(compId);
var i=0;
var numOfVisibleEntries=0;
var numOfExpandedEntries=0;
var totalHeightOfEntry=0;
var totalHeightOfSupFinding=0;
var averageHeightOfEntry=0;
var averageHeightOfSupFinding=0;
var sectionCount=$("#dqrContents"+compId).children().length;
for(var i=0;
i<sectionCount;
i++){var children=$("#dqr-section"+compId+""+i).children().not(":first");
children.each(function(){var sectionEntry=$(this);
var entryContainer=sectionEntry.children().first();
var entry=entryContainer.children().first();
if(entry.hasClass("dqr-hidden")){return true;
}numOfVisibleEntries++;
totalHeightOfEntry+=entry.height();
var findings=entry.children().last();
if(!findings.hasClass("dqr-hidden")){numOfExpandedEntries++;
totalHeightOfSupFinding+=findings.height();
}});
}if(numOfVisibleEntries!=0){var averageHeightOfEntry=totalHeightOfEntry/numOfVisibleEntries;
}if(numOfExpandedEntries!=0){var averageHeightOfSupFinding=totalHeightOfSupFinding/numOfExpandedEntries;
}return[numOfVisibleEntries,numOfExpandedEntries,averageHeightOfEntry,averageHeightOfSupFinding];
},SetOptimalContentHeight:function(compId,entryInfo){var component=getCompObjByStringOrIntId(compId);
var contents=document.getElementById("dqrContents"+compId);
var numOfVisibleEntries=entryInfo[0];
var numOfExpandedEntries=entryInfo[1];
var heightOfEntry=entryInfo[2];
var heightOfSupFinding=entryInfo[3];
var totalVisibleHeight=contents.scrollHeight;
var ratioHeight=totalVisibleHeight*(component.getScrollNumber()/numOfVisibleEntries);
var minNumOfExpandedEntriesVisible=Math.min(numOfExpandedEntries,Math.ceil(component.getScrollNumber()*0.5));
var minHeight=(minNumOfExpandedEntriesVisible*heightOfSupFinding)+(component.getScrollNumber()*heightOfEntry);
minHeight=Math.min(minHeight,totalVisibleHeight);
contents.style.height=Math.max(minHeight,ratioHeight)+"px";
},ShowAccepted:function(compId){var showAccepted=document.getElementById("showAcceptedCheck"+compId).checked;
var i=0;
var section=$("#dqr-section"+compId+""+i);
var component=getCompObjByStringOrIntId(compId);
if(showAccepted){while(section.length>0){var j=0;
var entry=$("#dqr-section-"+compId+""+i+"-row-"+j);
while(entry.length>0){if(CERN_DQR_O1.CheckIfEntryAccepted(compId,i,j)){CERN_DQR_O1.ShowEntry(compId,i,j);
}j++;
entry=$("#dqr-section-"+compId+""+i+"-row-"+j);
}i++;
section=$("#dqr-section"+compId+""+i);
}CERN_DQR_O1.RefreshClarificationBorders(component);
}else{while(section.length>0){var j=0;
var entry=$("#dqr-section-"+compId+""+i+"-row-"+j);
while(entry.length>0){if(CERN_DQR_O1.CheckIfEntryAccepted(compId,i,j)){CERN_DQR_O1.HideEntry(compId,i,j);
}j++;
entry=$("#dqr-section-"+compId+""+i+"-row-"+j);
}i++;
section=$("#dqr-section"+compId+""+i);
}CERN_DQR_O1.RefreshClarificationBorders(component);
}CERN_DQR_O1.HideSections(compId);
secExpands=$("[id^=SectionExpandAll"+compId+"]");
for(i=0;
i<secExpands.length;
i++){if(CERN_DQR_O1.CheckIfSectionExpanded(compId,i)){CERN_DQR_O1.SetSectionExpandLabel(compId,i,false);
}else{CERN_DQR_O1.SetSectionExpandLabel(compId,i,true);
}}CERN_DQR_O1.updateExpandAll(compId);
CERN_DQR_O1.UpdateScroll(compId);
},HideSections:function(compId){secExpands=$("[id^=SectionExpandAll"+compId+"]");
for(i=0;
i<secExpands.length;
i++){if(CERN_DQR_O1.CheckIfHideSection(compId,i)){$("#dqr-section"+compId+""+i).addClass("dqr-hidden");
}else{if($("#dqr-section"+compId+""+i).hasClass("dqr-hidden")){$("#dqr-section"+compId+""+i).removeClass("dqr-hidden");
}}}},CheckIfHideSection:function(compId,sectionSequence){var i=0;
var entry=$("#dqr-section-"+compId+""+sectionSequence+"-row-"+i);
while(entry.length>0){if(!entry.hasClass("dqr-hidden")){return false;
}i++;
entry=$("#dqr-section-"+compId+""+sectionSequence+"-row-"+i);
}return true;
},ExpandEntry:function(compId,sectionSequence,clarSequence){var identifier=compId+""+sectionSequence+"-row-"+clarSequence;
var clarification=$("#clarEntryContainer"+identifier);
if(clarification.hasClass("dqr-table-entryContainer")&&!clarification.hasClass("dqr-table-entryContainer-expanded")){clarification.addClass("dqr-table-entryContainer-expanded");
}if(clarification.hasClass("dqr-table-entryContainer-bottom")&&!clarification.hasClass("dqr-table-entryContainer-expanded-bottom")){clarification.addClass("dqr-table-entryContainer-expanded-bottom");
}if(clarification.hasClass("dqr-lightGrayBorder")||clarification.hasClass("dqr-darkGrayBorder")){clarification.addClass("dqr-blueBorder");
}$("#dqr-section-"+identifier).attr("class","dqr-table-entryContainer-div-border-expanded");
$("#clarFindings"+identifier).removeClass("dqr-hidden");
$("#expandIcon"+identifier).attr("class","dqr-table-expand-img-expanded");
},CollapseEntry:function(compId,sectionSequence,clarSequence){var identifier=compId+""+sectionSequence+"-row-"+clarSequence;
var clarification=$("#clarEntryContainer"+identifier);
if(clarification.hasClass("dqr-table-entryContainer-expanded")){clarification.removeClass("dqr-table-entryContainer-expanded");
}if(clarification.hasClass("dqr-table-entryContainer-expanded-bottom")){clarification.removeClass("dqr-table-entryContainer-expanded-bottom");
}if(clarification.hasClass("dqr-blueBorder")){clarification.removeClass("dqr-blueBorder");
}$("#dqr-section-"+identifier).attr("class","dqr-table-entryContainer-div-border");
$("#clarFindings"+identifier).addClass("dqr-hidden");
$("#expandIcon"+identifier).attr("class","dqr-table-expand-img-hidden");
},ShowEntry:function(compId,sectionSequence,clarSequence){var entryContainer=$("#clarEntryContainer"+compId+""+sectionSequence+"-row-"+clarSequence);
if(entryContainer.length>0){entryContainer.removeClass("dqr-hidden");
$("#dqr-section-"+compId+""+sectionSequence+"-row-"+clarSequence).removeClass("dqr-hidden");
var expandImg=$("#expandIcon"+compId+""+sectionSequence+"-row-"+clarSequence);
CERN_DQR_O1.CollapseEntry(compId,sectionSequence,clarSequence);
expandImg.attr("class","dqr-table-expand-img-hidden");
}},HideEntry:function(compId,sectionSequence,clarSequence){var entryRow=$("#dqr-section-"+compId+""+sectionSequence+"-row-"+clarSequence);
if(entryRow.length>0){entryRow.addClass("dqr-hidden");
}if(CERN_DQR_O1.CheckIfSectionExpanded(compId,sectionSequence)){CERN_DQR_O1.SetSectionExpandLabel(compId,sectionSequence,false);
}},CheckIfEntryAccepted:function(compId,sectionSequence,clarSequence){var accepted=$("#accepted"+compId+""+sectionSequence+"-row-"+clarSequence);
if(accepted.length>0){return true;
}return false;
},ExpandAll:function(compId){var sectionCount=$("[id^=dqr-section"+compId+"]").length;
for(i=0;
i<sectionCount;
i++){CERN_DQR_O1.ExpandSection(compId,i);
}var expandAll=document.getElementById("dqrExpandAll");
expandAll.innerHTML=i18n.discernabu.smartreview_o1.COLLAPSE_ALL;
expandAll.onclick=function(){CERN_DQR_O1.CollapseAll(compId);
};
CERN_DQR_O1.UpdateScroll(compId);
},CollapseAll:function(compId){var sectionCount=$("[id^=dqr-section"+compId+"]").length;
for(i=0;
i<sectionCount;
i++){CERN_DQR_O1.CollapseSection(compId,i);
}var expandAll=document.getElementById("dqrExpandAll");
expandAll.innerHTML=i18n.discernabu.smartreview_o1.EXPAND_ALL;
expandAll.onclick=function(){CERN_DQR_O1.ExpandAll(compId);
};
CERN_DQR_O1.UpdateScroll(compId);
},SetSectionExpandLabel:function(compId,sectionSequence,setToExpandRun){var section=$("#SectionExpandAll"+compId+""+sectionSequence).get(0);
if(setToExpandRun){section.innerHTML=i18n.discernabu.smartreview_o1.EXPAND;
section.onclick=function(){CERN_DQR_O1.ExpandSection(compId,sectionSequence);
};
}else{section.innerHTML=i18n.discernabu.smartreview_o1.COLLAPSE;
section.onclick=function(){CERN_DQR_O1.CollapseSection(compId,sectionSequence);
};
}},CheckIfSectionExpanded:function(compId,sectionSequence){var i=0;
var entry=$("#dqr-section-"+compId+""+sectionSequence+"-row-"+i);
while(entry.length>0){if(entry.hasClass("dqr-table-entryContainer-div-border")){return false;
}i++;
entry=$("#dqr-section-"+compId+""+sectionSequence+"-row-"+i);
}return true;
},ExpandSection:function(compId,sectionSequence){var i=0;
var entry=$("#dqr-section-"+compId+""+sectionSequence+"-row-"+i);
while(entry.length>0){if(entry.attr("class")=="dqr-table-entryContainer-div-border"){CERN_DQR_O1.ExpandEntry(compId,sectionSequence,i);
}i++;
entry=$("#dqr-section-"+compId+""+sectionSequence+"-row-"+i);
}var sectionExpand=document.getElementById("SectionExpandAll"+compId+sectionSequence);
if(sectionExpand){sectionExpand.innerHTML=i18n.discernabu.smartreview_o1.COLLAPSE;
sectionExpand.onclick=function(){CERN_DQR_O1.CollapseSection(compId,sectionSequence);
};
}CERN_DQR_O1.updateExpandAll(compId);
CERN_DQR_O1.UpdateScroll(compId);
},CollapseSection:function(compId,sectionSequence){var i=0;
var entry=$("#dqr-section-"+compId+""+sectionSequence+"-row-"+i);
while(entry.length>0){if(entry.attr("class")=="dqr-table-entryContainer-div-border-expanded"){CERN_DQR_O1.CollapseEntry(compId,sectionSequence,i);
}i++;
entry=$("#dqr-section-"+compId+""+sectionSequence+"-row-"+i);
}var sectionExpand=document.getElementById("SectionExpandAll"+compId+sectionSequence);
if(sectionExpand){sectionExpand.innerHTML=i18n.discernabu.smartreview_o1.EXPAND;
sectionExpand.onclick=function(){CERN_DQR_O1.ExpandSection(compId,sectionSequence);
};
}CERN_DQR_O1.updateExpandAll(compId);
CERN_DQR_O1.UpdateScroll(compId);
},mEnterEntry:function(compId,sectionSequence,clarSequence){var expandImg=document.getElementById("expandIcon"+compId+""+sectionSequence+"-row-"+clarSequence);
if(expandImg.getAttribute("class").match("expanded")==null){expandImg.setAttribute("class","dqr-table-expand-img-collapsed");
}},mLeaveEntry:function(compId,sectionSequence,clarSequence){var expandImg=document.getElementById("expandIcon"+compId+""+sectionSequence+"-row-"+clarSequence);
if(expandImg.getAttribute("class").match("expanded")==null){expandImg.setAttribute("class","dqr-table-expand-img-hidden");
}},onClickExpandEntry:function(compId,sectionSequence,clarSequence){var expandImg=document.getElementById("expandIcon"+compId+""+sectionSequence+"-row-"+clarSequence);
if(expandImg.getAttribute("class").match("expanded")==null){CERN_DQR_O1.ExpandEntry(compId,sectionSequence,clarSequence);
if(CERN_DQR_O1.CheckIfSectionExpanded(compId,sectionSequence)){CERN_DQR_O1.SetSectionExpandLabel(compId,sectionSequence,false);
}}else{CERN_DQR_O1.CollapseEntry(compId,sectionSequence,clarSequence);
expandImg.setAttribute("class","dqr-table-expand-img-collapsed");
CERN_DQR_O1.SetSectionExpandLabel(compId,sectionSequence,true);
}CERN_DQR_O1.updateExpandAll(compId);
CERN_DQR_O1.UpdateScroll(compId);
},checkIfAllExpanded:function(compId){secExpands=$("[id^=SectionExpandAll"+compId+"]");
for(var i=0;
i<secExpands.length;
i++){if(!CERN_DQR_O1.CheckIfSectionExpanded(compId,i)){return false;
}}return true;
},updateExpandAll:function(compId){var expandAll=document.getElementById("dqrExpandAll");
if(!expandAll){return;
}if(CERN_DQR_O1.checkIfAllExpanded(compId)){expandAll.innerHTML=i18n.discernabu.smartreview_o1.COLLAPSE_ALL;
expandAll.onclick=function(){CERN_DQR_O1.CollapseAll(compId);
};
}else{expandAll.innerHTML=i18n.discernabu.smartreview_o1.EXPAND_ALL;
expandAll.onclick=function(){CERN_DQR_O1.ExpandAll(compId);
};
}},loadWithCBParameters:function(compId,url,callback,parameters){function checkReady(){var timerLoadClarifications=MP_Util.CreateTimer("USR: Launch SmartReview");
timerLoadClarifications.SubtimerName=dqr_mpage;
if(xhr.readyState===4){if(xhr.status===200){try{var component=MP_Util.GetCompObjById(compId);
CERN_DQR_O1.processingUI(component,"dqrProcessing"+compId,1,true,null,compId);
MP_Util.LogScriptCallInfo(getCompObjByStringOrIntId(compId),this,"SmartReview.js","loadWithCBParameters");
CERN_DQR_O1.RemovePreviousOutstandingClarifications();
callback(component,xhr.responseText);
CERN_DQR_O1.checkIfAllExpanded(compId);
CERN_DQR_O1.updateExpandAll(compId);
if(timerLoadClarifications){timerLoadClarifications.Stop();
}}catch(err){if(timerLoadClarifications){timerLoadClarifications.Abort();
}CERN_DQR_O1.processingUI(component,"dqrProcessing"+compId,-1,true,null,compId);
}}else{if(timerLoadClarifications){timerLoadClarifications.Abort();
}var component=getCompObjByStringOrIntId(compId);
CERN_DQR_O1.processingUI(component,"dqrProcessing"+compId,-1,true,null,compId);
component.m_nRefreshCount--;
alert("Problem retrieving results");
}}}var component=getCompObjByStringOrIntId(compId);
var xhr=(CERN_BrowserDevInd)?new XMLHttpRequest():new XMLCclRequest();
xhr.onreadystatechange=checkReady;
if(!parameters){parameters="^MINE^, "+component.getCriterion().person_id.toFixed(1)+","+component.getCriterion().encntr_id.toFixed(1)+","+component.getCriterion().provider_id.toFixed(1)+","+component.getCriterion().ppr_cd.toFixed(1)+","+0+","+0;
}if(CERN_BrowserDevInd){var requestUrl=url+"?parameters="+parameters;
xhr.open("GET",requestUrl,true);
xhr.send(null);
}else{xhr.open("GET",url,true);
xhr.send(parameters);
}},processingUI:function(oNamespace,sElementId,nIncrement,bChangeCursor,updateCallback,compID){var processingElement=$("#"+sElementId);
if(processingElement){if(nIncrement===0){oNamespace.m_nProcessing=0;
oNamespace.m_nWaitCursor=0;
}else{oNamespace.m_nProcessing+=nIncrement;
if(bChangeCursor){oNamespace.m_nWaitCursor+=nIncrement;
}if(oNamespace.m_nProcessing<0){oNamespace.m_nProcessing=0;
}if(oNamespace.m_nWaitCursor<0){oNamespace.m_nWaitCursor=0;
}}var bodyElement=$("body");
if(oNamespace.m_nProcessing===0){$(processingElement).addClass("dqr-hide");
}else{$(processingElement).removeClass("dqr-hide");
}if(oNamespace.m_nWaitCursor===0){$(bodyElement).removeClass("dqr-busy");
}else{$(bodyElement).addClass("dqr-busy");
}if(updateCallback){updateCallback(compID);
}}},Position:function(x,y){this.X=x;
this.Y=y;
},absoluteCursorPosition:function(eventObj){eventObj=eventObj?eventObj:window.event;
if(isNaN(window.scrollX)){return new CERN_DQR_O1.Position(eventObj.clientX+document.documentElement.scrollLeft+document.body.scrollLeft,eventObj.clientY+document.documentElement.scrollTop+document.body.scrollTop);
}else{return new CERN_DQR_O1.Position(eventObj.clientX+window.scrollX,eventObj.clientY+window.scrollY);
}}};
function getCompObjByStringOrIntId(compID){var intComponentId=parseInt(compID,10);
var component=MP_Util.GetCompObjById(intComponentId);
if(!component){component=MP_Util.GetCompObjById(compID);
}return component;
}}();
MP_Util.setObjectDefinitionMapping("SMART_REVIEW_PARAM",SmartReviewComponent);
