function VitalSignComponentWFStyle(){this.initByNamespace("WF_VS");
}VitalSignComponentWFStyle.prototype=new ComponentStyle();
VitalSignComponentWFStyle.prototype.constructor=ComponentStyle;
function VitalSignComponentWF(criterion){this.setCriterion(criterion);
this.setStyles(new VitalSignComponentWFStyle());
this.setComponentLoadTimerName("USR:MPG.VITALSIGNS.WF - load component");
this.setComponentRenderTimerName("ENG:MPG.VITALSIGNS.WF - render component");
this.setIncludeLineNumber(false);
this.m_iViewAdd=false;
this.bandName="";
this.sectionName="";
this.itemName="";
this.m_recordData=null;
this.m_showAmbulatoryView=null;
this.m_showTodayValue=null;
this.m_ambTableContainer=null;
this.m_flowsheetTableContainer=null;
this.m_flowsheetTableObject=null;
this.sidePanel=null;
this.m_sidePanelMinHeight="187px";
this.m_showPanel=false;
this.m_sidePanelContainer=null;
this.m_clickedLabel="";
this.m_graphData=null;
this.m_plot=null;
this.m_bpGraph=null;
this.m_maxFlowsheetResultCap=4000;
this.m_flowsheetResultCap=this.m_maxFlowsheetResultCap;
this.m_latestColumnCap=0;
this.m_showingLatestResults=false;
this.SIDE_PANEL_AVAILABLE=CERN_Browser.isCanvasAvailable();
this.m_ambViewColumnCnt=7;
this.m_resultRangeSelectionDisplayString=i18n.LATEST+"*";
this.setLookbackUnits(10);
this.setLookbackUnitTypeFlag(ResultRangeSelectionUtility.CustomType);
this.m_panelElementData={};
}VitalSignComponentWF.prototype=new MPageComponent();
VitalSignComponentWF.prototype.constructor=MPageComponent;
VitalSignComponentWF.prototype.setRecordData=function(recordData){this.m_recordData=recordData;
};
VitalSignComponentWF.prototype.getRecordData=function(){return this.m_recordData;
};
VitalSignComponentWF.prototype.handleHeaderToggleClick=function(index){this.m_flowsheetTable=null;
this.m_componentTable=null;
this.setShowAmbulatoryView((index===1)?1:0);
MP_Util.LoadSpinner("WF_VSContent"+this.getComponentId(),1);
this.retrieveComponentData();
};
VitalSignComponentWF.prototype.createDisclaimerMessage=function(){var lookbackDisplay="";
switch(this.getBrLookbackUnitTypeFlag()){case 1:lookbackDisplay=i18n.discernabu.LAST_N_HOURS_LOWER.replace("{0}",this.getBrLookbackUnits());
break;
case 2:lookbackDisplay=i18n.discernabu.LAST_N_DAYS_LOWER.replace("{0}",this.getBrLookbackUnits());
break;
case 3:lookbackDisplay=i18n.discernabu.LAST_N_WEEKS_LOWER.replace("{0}",this.getBrLookbackUnits());
break;
case 4:lookbackDisplay=i18n.discernabu.LAST_N_MONTHS_LOWER.replace("{0}",this.getBrLookbackUnits());
break;
case 5:lookbackDisplay=i18n.discernabu.LAST_N_YEARS_LOWER.replace("{0}",this.getBrLookbackUnits());
break;
default:lookbackDisplay=(this.getScope()===2)?i18n.discernabu.SELECTED_VISIT_LOWER:i18n.discernabu.All_VISITS_LOWER;
}return"* "+i18n.discernabu.FLOWSHEET_DISCLAIMER.replace("{0}",this.m_latestColumnCap).replace("{1}",lookbackDisplay);
};
VitalSignComponentWF.prototype.preProcessing=function(){if(this.getShowAmbulatoryView()){this.setActiveHeaderToggleIndex(1);
}else{this.setActiveHeaderToggleIndex(0);
}this.setHeaderToggleStyles([{active:"table_active",inactive:"table_inactive"},{active:"viewer_active",inactive:"viewer_inactive"}]);
var customMenuItem=new ResultRangeSelection();
customMenuItem.setType(ResultRangeSelectionUtility.CustomType);
customMenuItem.setDirection(ResultRangeSelectionUtility.direction.BACKWARD);
customMenuItem.setUnits(0);
customMenuItem.setScope(this.getScope());
customMenuItem.setDisplay(this.m_resultRangeSelectionDisplayString);
ResultRangeSelectionUtility.addCustomResultRangeSelectionItem(this,customMenuItem);
};
VitalSignComponentWF.prototype.setShowAmbulatoryView=function(showAmbulatoryView){this.m_showAmbulatoryView=showAmbulatoryView;
};
VitalSignComponentWF.prototype.getShowAmbulatoryView=function(){return this.m_showAmbulatoryView;
};
VitalSignComponentWF.prototype.setShowTodayValue=function(showTodayValue){this.m_showTodayValue=showTodayValue;
};
VitalSignComponentWF.prototype.getShowTodayValue=function(){return this.m_showTodayValue;
};
VitalSignComponentWF.prototype.loadFilterMappings=function(){this.addFilterMappingObject("WF_VS_CHART_LAUNCH_IND",{setFunction:this.setIViewAdd,type:"BOOLEAN",field:"FREETEXT_DESC"});
this.addFilterMappingObject("WF_VS_DISPLAY",{setFunction:this.setShowAmbulatoryView,type:"BOOLEAN",field:"FREETEXT_DESC"});
this.addFilterMappingObject("WF_VS_RESULTS_IND",{setFunction:this.setShowTodayValue,type:"BOOLEAN",field:"FREETEXT_DESC"});
};
VitalSignComponentWF.prototype.retrieveComponentData=function(){var temperatureParams="^^";
var hrParams="^^";
var bloodPressureParams="";
var otherParams="^^";
var seqParams="^^";
var groups=this.getGroups();
var groupLength=groups.length;
var z=0;
var zl=0;
var x=0;
var y=0;
this.m_showPanel=false;
this.m_clickedLabel="";
this.setGraphData(null);
this.setVitalsPlot(null);
if(groups&&groupLength>0){for(x=0,xl=groupLength;
x<xl;
x++){var group=groups[x];
switch(group.getGroupName()){case"WF_TEMP_CE":temperatureParams=MP_Util.CreateParamArray(group.getEventSets(),1);
break;
case"WF_HR_CE":hrParams=MP_Util.CreateParamArray(group.getEventSets(),1);
break;
case"WF_BP_CE":if(group instanceof MPageGrouper){var bpGroups=group.getGroups();
for(z=0,zl=bpGroups.length;
z<zl;
z++){var tempParams="";
var bpCodes=bpGroups[z].getEventCodes();
if(bpCodes.length===2){tempParams=bpGroups[z].getGroupName()+","+bpCodes[0]+","+bpCodes[1];
if(z>0){bloodPressureParams+=String.fromCharCode(42)+tempParams;
}else{bloodPressureParams=tempParams;
}}}}bloodPressureParams=bloodPressureParams.replace(/&#(\d+);/g,function(m,n){return String.fromCharCode(n);
});
break;
case"WF_VS_CE":case"WF_VS_CE_SEQ":if(group instanceof MPageSequenceGroup){var mapItems=group.getMapItems();
var tGroupFilterIds=MP_Util.GetValueFromArray("BR_DATAMART_FILTER",mapItems);
for(y=0,yl=tGroupFilterIds.length;
y<yl;
y++){for(z=0,zl=groupLength;
z<zl;
z++){if(groups[z].getGroupId()===tGroupFilterIds[y]){switch(groups[z].getGroupName()){case"WF_TEMP_CE":group.m_items[group.m_items.indexOf(tGroupFilterIds[y])]=-11111;
continue;
case"WF_HR_CE":group.m_items[group.m_items.indexOf(tGroupFilterIds[y])]=-22222;
continue;
case"WF_BP_CE":group.m_items[group.m_items.indexOf(tGroupFilterIds[y])]=-33333;
continue;
default:continue;
}}}}otherParams=MP_Util.CreateParamArray(MP_Util.GetValueFromArray("CODE_VALUE",mapItems),1);
seqParams=MP_Util.CreateParamArray(group.getItems(),1);
}else{otherParams=MP_Util.CreateParamArray(group.getEventSets(),1);
}break;
default:break;
}}}var sendAr=[];
var resultCap=-1;
var criterion=this.getCriterion();
var sEncntr=(this.getScope()===2)?criterion.encntr_id+".0":"0.0";
var lookbackUnits=this.getLookbackUnits();
var lookbackType=this.getLookbackUnitTypeFlag();
if(lookbackType===ResultRangeSelectionUtility.CustomType){lookbackUnits=this.getBrLookbackUnits();
lookbackType=this.getBrLookbackUnitTypeFlag();
this.m_latestColumnCap=this.getNumOfColumns();
this.m_flowsheetResultCap=this.m_latestColumnCap+5;
this.m_showingLatestResults=true;
}else{this.m_showingLatestResults=false;
this.m_flowsheetResultCap=this.m_maxFlowsheetResultCap;
}if(this.getShowAmbulatoryView()){if(this.SIDE_PANEL_AVAILABLE){resultCap=10;
}else{resultCap=this.m_ambViewColumnCnt;
}}else{resultCap=this.m_flowsheetResultCap;
}var minMaxTemperatureLookBackHour=24;
sendAr.push("^MINE^",criterion.person_id+".0",sEncntr,criterion.provider_id+".0",criterion.ppr_cd+".0",lookbackUnits,lookbackType,"^^","^^",temperatureParams,hrParams,otherParams,"^"+bloodPressureParams+"^",seqParams,resultCap,minMaxTemperatureLookBackHour);
MP_Core.XMLCclRequestWrapper(this,"MP_RETRIEVE_VITALS_GROUP_DATA",sendAr,true);
};
VitalSignComponentWF.prototype.getNumOfColumns=function(){var componentWidth=$(this.getSectionContentNode()).width();
var labelColumnWidth=204;
var columnWidth=72;
var pixelBuffer=2;
var numColumns=Math.max(1,Math.floor((componentWidth-labelColumnWidth-pixelBuffer)/columnWidth)-1);
return numColumns;
};
VitalSignComponentWF.prototype.setIViewAdd=function(value){this.m_iViewAdd=value;
};
VitalSignComponentWF.prototype.isIViewAdd=function(){return(this.m_iViewAdd);
};
VitalSignComponentWF.prototype.openIView=function(){var criterion=this.getCriterion();
var paramString="'"+this.bandName+"','"+this.sectionName+"','"+this.itemName+"',"+criterion.person_id+criterion.encntr_id;
MP_Util.LogMpagesEventInfo(this,"IVIEW",paramString,"vitals-o2.js","openIView");
try{var launchIViewApp=window.external.DiscernObjectFactory("TASKDOC");
launchIViewApp.LaunchIView(this.bandName,this.sectionName,this.itemName,criterion.person_id,criterion.encntr_id);
CERN_EventListener.fireEvent(null,this,EventListener.EVENT_CLINICAL_EVENT,"vitals");
}catch(err){MP_Util.LogJSError(err,null,"vitals-o2","openIView");
}};
VitalSignComponentWF.prototype.openTab=function(){var criterion=this.getCriterion();
var paramString=criterion.person_id+"|"+criterion.encntr_id+"|"+0+"|0|0";
MP_Util.LogMpagesEventInfo(null,"POWERFORM",paramString,"vitals-o2.js","openTab");
MPAGES_EVENT("POWERFORM",paramString);
this.retrieveComponentData();
};
VitalSignComponentWF.prototype.openDropDown=function(formID){var criterion=this.getCriterion();
var paramString=criterion.person_id+"|"+criterion.encntr_id+"|"+formID+"|0|0";
MP_Util.LogMpagesEventInfo(null,"POWERFORM",paramString,"vitals-o2.js","openDropDown");
MPAGES_EVENT("POWERFORM",paramString);
this.retrieveComponentData();
};
VitalSignComponentWF.prototype.getModifyIndicator=function(statusMean){return(statusMean==="MODIFIED"||statusMean==="ALTERED")?"<span class='res-modified'>&nbsp</span>":"";
};
VitalSignComponentWF.prototype.formatResult=function(result){var numberFormatter=MP_Util.GetNumericFormatter();
if(mp_formatter._isNumber(result.RESULT)){result.RESULT=numberFormatter.format(result.RESULT,"^."+MP_Util.CalculatePrecision(result.RESULT));
}else{if(result.RES_TYPE===3&&(typeof result.DATE_FORMATTED=="undefined")){dateResult=new Date();
dateResult.setISO8601(result.RESULT);
result.RESULT=dateResult.format("longDateTime3");
result.DATE_FORMATTED=true;
}}};
VitalSignComponentWF.prototype.getNormalcy=function(normalcyValue,resultIndex,hoverNormalcyClass){var normalcyClassObj={NORMALCY:"res-normal",HOVERNORMALCY:hoverNormalcyClass,CRITICAL_IND:false};
switch(normalcyValue){case"CRITICAL":case"EXTREMEHIGH":case"PANICHIGH":case"EXTREMELOW":case"PANICLOW":case"VABNORMAL":case"POSITIVE":normalcyClassObj.CRITICAL_IND=true;
normalcyClassObj.NORMALCY="res-severe";
if(resultIndex>0){normalcyClassObj.HOVERNORMALCY="res-severe";
}break;
case"HIGH":normalcyClassObj.NORMALCY="res-high";
if(resultIndex>0&&!(hoverNormalcyClass==="res-severe")){normalcyClassObj.HOVERNORMALCY="res-high";
}break;
case"LOW":normalcyClassObj.NORMALCY="res-low";
if(resultIndex>0&&!("res-high|res-severe".indexOf(hoverNormalcyClass)>=0)){normalcyClassObj.HOVERNORMALCY="res-low";
}break;
case"ABNORMAL":normalcyClassObj.NORMALCY="res-abnormal";
if(resultIndex>0&&!("res-high|res-severe|res-low".indexOf(hoverNormalcyClass)>=0)){normalcyClassObj.HOVERNORMALCY="res-abnormal";
}break;
}return normalcyClassObj;
};
VitalSignComponentWF.prototype.resultTableCellClickHandler=function(event,dataObj,tableTriggeredFrom){var results=[];
var resultCnt=0;
var x=0;
var event_id="";
var target_id=$(event.target).data("id");
var resultViewerTimer=null;
var self=this;
try{results=dataObj.RESULT_DATA.RESULT_OBJ[dataObj.COLUMN_ID].OBJECT_ARR;
resultCnt=results.length;
if(resultCnt===0){return;
}if(event.target.nodeName.toUpperCase()==="SPAN"){var events=[];
for(x=0;
x<resultCnt;
x++){switch(target_id){case dataObj.NAMESPACE+"diastolic":event_id=results[x].DIA_EVENTS[0]?results[x].DIA_EVENTS[0].EVENT_ID:"";
break;
case dataObj.NAMESPACE+"systolic":event_id=results[x].SYS_EVENTS[0]?results[x].SYS_EVENTS[0].EVENT_ID:"";
break;
default:event_id=results[x].EVENT_ID;
}if(event_id){events.push(event_id);
}}ResultViewer.launchAdHocViewer(events,dataObj.RESULT_DATA.GROUP_NAME);
resultViewerTimer=new CapabilityTimer("CAP:MPG Vitals O2 View Result",this.criterion.category_mean);
if(resultViewerTimer){resultViewerTimer.addMetaData("rtms.legacy.metadata.1",tableTriggeredFrom);
resultViewerTimer.capture();
}}}catch(err){MP_Util.LogJSError(err,null,"vitals_o2.js","resultTableCellClickHandler");
}};
VitalSignComponentWF.prototype.getVitalsPlot=function(){return this.m_plot;
};
VitalSignComponentWF.prototype.setVitalsPlot=function(plot){this.m_plot=plot;
};
VitalSignComponentWF.prototype.getGraphData=function(){return this.m_graphData;
};
VitalSignComponentWF.prototype.setGraphData=function(data){this.m_graphData=data;
};
VitalSignComponentWF.prototype.plotGraph=function(){var graphArray=this.getGraphData();
var graphDivId="#WF_VS"+this.getComponentId()+"graphHolder";
var vitalsPlot=this.getVitalsPlot();
var chartOptions=null;
var vitalsI18N=i18n.discernabu.vitals_o2;
var self=this;
$("#WF_VS"+this.getComponentId()+"graphHolder").bind("jqplotMouseMove",function(ev,gridpos,datapos,neighbor,plot){var x=gridpos.x;
var y=gridpos.y;
var plotWidth=plot._width;
var limitWidth=plotWidth-x;
var leftMargin=190;
var tooltip=$(graphDivId).find(".jqplot-highlighter-tooltip");
if(limitWidth<leftMargin){if(x>leftMargin){tooltip.css("margin-left","-195px");
}else{if(x<limitWidth){tooltip.css("margin-left","-85px");
}else{tooltip.css("margin-left","-150px");
}}}else{tooltip.css("margin-left","0");
}if(y<tooltip.height()){tooltip.css("top","0px");
}});
function tooltipEditor(str,seriesIndex,pointIndex,plot){var plotLength=plot.data[seriesIndex].length;
var newPointIndex=pointIndex;
var data=plot.data[seriesIndex][pointIndex];
var numberFormatter=MP_Util.GetNumericFormatter();
if(data==undefined){if(newPointIndex>=plotLength){newPointIndex=newPointIndex-plotLength;
}}data=plot.data[seriesIndex][newPointIndex];
if(!self.m_bpGraph){return"<div class ='vitals-graph-tooltip'>"+data[3]+": <span class ='hover-primary-data'><span class='"+data[2]+"'>&nbsp;<span>"+numberFormatter.format(data[1],"^."+MP_Util.CalculatePrecision(data[1]))+"</span></span></span><br><span>"+vitalsI18N.DATE_TIME+": <span class ='hover-primary-data'>"+data[0].format("mediumDate")+"&nbsp;"+data[0].format("militaryTime")+" </span></span></span></div>";
}else{return"<div class ='vitals-graph-tooltip'>"+data[3]+": <span class ='hover-primary-data'>"+data[4]+"</span></span><br><span>"+vitalsI18N.DATE_TIME+": <span class ='hover-primary-data'>"+data[0].format("mediumDate")+"&nbsp;"+data[0].format("militaryTime")+"</span></span></div>";
}}if(!this.m_bpGraph){chartOptions={axes:{axesDefaults:{pad:2},xaxis:{renderer:$.jqplot.DateAxisRenderer,rendererOptions:{drawBaseline:false},tickOptions:{formatString:"%m/%d/%Y",showGridline:false,showMark:false,fontSize:"8pt",show:false},max:graphArray[graphArray.length-1][0],min:graphArray[0][0],numberTicks:2,useDST:true},yaxis:{pad:2,tickOptions:{show:false},rendererOptions:{drawBaseline:false}}},highlighter:{show:true,tooltipContentEditor:tooltipEditor,tooltipLocation:"ne",sizeAdjust:7},cursor:{show:false},series:[{lineWidth:2,shadow:false,color:"#505050",markerOptions:{show:true,size:8,color:"#505050",shadow:false}}],grid:{background:"#FFFFFF",borderColor:"#DDDDDD",borderWidth:0.25,shadow:false,showBorder:true}};
}else{chartOptions={axes:{axesDefaults:{pad:2},xaxis:{renderer:$.jqplot.DateAxisRenderer,rendererOptions:{drawBaseline:false},tickOptions:{formatString:"%m/%d/%Y",showGridline:false,showMark:false,fontSize:"8pt",show:false},max:graphArray[graphArray.length-1][0].getTime()+6000*60*60*24*2,min:graphArray[0][0].getTime()-6000*60*60*24*2,useDST:true},yaxis:{min:Math.floor((this.m_minBP-15)/10)*10,max:Math.ceil((this.m_maxBP+15)/10)*10,tickInterval:10,pad:2,tickOptions:{show:false},rendererOptions:{drawBaseline:false}}},highlighter:{show:true,tooltipContentEditor:tooltipEditor,tooltipLocation:"ne",sizeAdjust:7},cursor:{show:false},series:[{renderer:$.jqplot.HLWhiskerRenderer,showLine:false,rendererOptions:{hiColor:"#505050",lowColor:"#505050",hiWidth:2,lowWidth:2,lineWidth:2,wickColor:"#505050",wickWidth:1,tickLength:4},markerOptions:{show:true,size:2,color:"#505050",shadow:false}}],grid:{background:"#FFFFFF",borderColor:"#DDDDDD",borderWidth:0.25,shadow:false,showBorder:true}};
}vitalsPlot=$.jqplot("WF_VS"+this.getComponentId()+"graphHolder",[graphArray],chartOptions);
this.setVitalsPlot(vitalsPlot);
};
VitalSignComponentWF.prototype.groupNameCellClickHandler=function(event,dataObj){var componentId=this.getComponentId();
var vitalsI18N=i18n.discernabu.vitals_o2;
var criterion=this.getCriterion();
var isAmbView=this.getShowAmbulatoryView();
var tableHeight=null;
if(this.m_clickedLabel.length){if(dataObj.RESULT_DATA.GROUP_NAME==this.m_clickedLabel){this.sidePanel.m_closeButton.trigger("click");
this.m_clickedLabel="";
return;
}}if(!this.m_showPanel){if(isAmbView){this.m_ambTableContainer.addClass("vitals-wf-side-panel-addition");
tableHeight=$("#WF_VS"+this.getComponentId()+"table").css("height");
}else{this.m_flowsheetTableObject.setSidePanelWidth(this.m_sidePanelContainer.outerWidth()+11);
this.m_flowsheetTableContainer.addClass("vitals-wf-side-panel-addition");
this.m_flowsheetTableObject.updateAfterResize();
tableHeight=$("#WF_VS"+this.getComponentId()+"resultsTabletable").css("height");
}this.sidePanel.setHeight(tableHeight);
this.sidePanel.resizePanel();
this.m_sidePanelContainer.css("display","inline-block");
this.m_showPanel=true;
this.sidePanel.showPanel();
}var numberOfMostRecentResults=10;
var differentUOM=false;
var nonNumericBP=false;
var nameAndUOM="";
if(event){var currentRowSelected=$(event.currentTarget.parentNode);
this.highlightSelectedRow(currentRowSelected);
}if(!isAmbView&&dataObj.RESULT_DATA.RESULT_UOM){nameAndUOM=dataObj.RESULT_DATA.RESULT_GROUP_NAME+"<br />"+dataObj.RESULT_DATA.RESULT_UOM;
}else{nameAndUOM=dataObj.RESULT_DATA.RESULT_GROUP_NAME;
}var sidePanelHTML="<div id='WF_VS"+componentId+"sidePanelResultsContainer'><div id='WF_VS"+componentId+"sidePanelGroupName' class='vitals-wf-side-panel-groupname'>"+nameAndUOM+"</div><div id = 'WF_VS"+componentId+"testResult' class = 'vitals-flex-text'></div><div id='WF_VS"+componentId+"graphHolder' class='vitals-canvas-height'></div><div id='WF_VS"+componentId+"dateRange' class = 'vitals-date-range'></div><div id='sidePanelScrollContainer"+componentId+"'><div id='WF_VS"+componentId+"sidePanelResultList' class='vitals-wf-side-panel-result-list'>";
var measurementLength=0;
var resultHTML="";
var todaysDate=new Date();
var graphArray=[];
if(dataObj.RESULT_DATA.IS_BP_RESULT){var systolicBPResult="";
var diastolicBPResult="";
var sysResultObjInfo={};
var diaResultObjInfo={};
var resultClass="";
this.m_bpGraph=true;
var allBPResults=[];
var bpResultDateTime=null;
var bpResultDateTimeStr="";
if(isAmbView){measurementLength=Math.min(dataObj.RESULT_DATA.length,numberOfMostRecentResults);
}else{measurementLength=dataObj.RESULT_DATA.RESULTS_SHOWN;
}for(var idx=0;
idx<measurementLength;
idx++){var bpMeasurement=dataObj.RESULT_DATA[idx];
BPGraphHover="";
var systolicResultObj=bpMeasurement.SYS_EVENTS[0];
var diastolicResultObj=bpMeasurement.DIA_EVENTS[0];
var bpSysId="WF_VS"+componentId+"bpSysResult"+idx;
var bpDiaId="WF_VS"+componentId+"bpDiaResult"+idx;
if(bpMeasurement.SYS_EVENTS.length){bpResultDateTime=new Date();
bpResultDateTime.setISO8601(systolicResultObj.DTTM);
this.formatResult(bpMeasurement.SYS_EVENTS[0]);
if(bpResultDateTime.getDate()===todaysDate.getDate()&&bpResultDateTime.getMonth()===todaysDate.getMonth()&&bpResultDateTime.getFullYear()===todaysDate.getFullYear()){bpResultDateTimeStr="<span>"+vitalsI18N.TODAY+"</span>";
}else{bpResultDateTimeStr="<span>"+bpResultDateTime.format("mediumDate")+"</span>";
}bpResultDateTimeStr+="<span class='vitals-wf-side-panel-result-item'>"+bpResultDateTime.format("militaryTime")+"</span>";
systolicBPResult=systolicResultObj.RESULT;
bpMeasurement.SYS_MODIFIED_IND=this.getModifyIndicator(systolicResultObj.STATUS_MEAN);
if(!bpMeasurement.SYS_NORMALCY_CLASS){bpMeasurement.SYS_NORMALCY_CLASS=this.getNormalcy(bpMeasurement.SYS_EVENTS[0].NORMALCY,0).NORMALCY;
}if(bpMeasurement.SYS_EVENTS[0].HAS_COMMENTS_IND){bpMeasurement.SYS_COMMENT_IND=1;
}sysResultObjInfo={EVENT_ID:systolicResultObj.EVENT_ID,NAME:dataObj.RESULT_DATA.GROUP_NAME};
this.m_panelElementData[bpSysId]=sysResultObjInfo;
}else{systolicBPResult="--";
bpMeasurement.SYS_MODIFIED_IND="";
bpMeasurement.SYS_COMMENT_IND=0;
}if(bpMeasurement.DIA_EVENTS.length){bpResultDateTime=new Date();
bpResultDateTime.setISO8601(diastolicResultObj.DTTM);
this.formatResult(bpMeasurement.DIA_EVENTS[0]);
if(bpResultDateTime.getDate()===todaysDate.getDate()&&bpResultDateTime.getMonth()===todaysDate.getMonth()&&bpResultDateTime.getFullYear()===todaysDate.getFullYear()){bpResultDateTimeStr="<span>"+vitalsI18N.TODAY+"</span>";
}else{bpResultDateTimeStr="<span>"+bpResultDateTime.format("mediumDate")+"</span>";
}bpResultDateTimeStr+="<span class='vitals-wf-side-panel-result-item'>"+bpResultDateTime.format("militaryTime")+"</span>";
diastolicBPResult=diastolicResultObj.RESULT;
bpMeasurement.DIA_MODIFIED_IND=this.getModifyIndicator(diastolicResultObj.STATUS_MEAN);
if(!bpMeasurement.DIA_NORMALCY_CLASS){bpMeasurement.DIA_NORMALCY_CLASS=this.getNormalcy(bpMeasurement.DIA_EVENTS[0].NORMALCY,0).NORMALCY;
}if(bpMeasurement.DIA_EVENTS[0].HAS_COMMENTS_IND){bpMeasurement.DIA_COMMENT_IND=1;
}diaResultObjInfo={EVENT_ID:diastolicResultObj.EVENT_ID,NAME:dataObj.RESULT_DATA.GROUP_NAME};
this.m_panelElementData[bpDiaId]=diaResultObjInfo;
}else{diastolicBPResult="--";
bpMeasurement.DIA_MODIFIED_IND="";
bpMeasurement.DIA_COMMENT_IND=0;
}resultClass=(systolicBPResult!=="--")?"result-variable":"";
resultHTML+="<dl><dd class='vitals-wf-bp-result-value'><span class="+bpMeasurement.SYS_NORMALCY_CLASS+"><span class='res-ind'></span><span class='"+resultClass+"' id='"+bpSysId+"'>"+systolicBPResult;
BPGraphHover+="<span class='vitals-wf-bp-result-value'><span class="+bpMeasurement.SYS_NORMALCY_CLASS+"><span class='"+resultClass+"' id='"+bpSysId+"'>"+systolicBPResult;
if(bpMeasurement.SYS_COMMENT_IND){resultHTML+="<span class='vitals-wf-comments-ind'></span>";
}BPGraphHover+=bpMeasurement.SYS_MODIFIED_IND+"</span></span>  /  ";
resultHTML+=bpMeasurement.SYS_MODIFIED_IND+"</span></span>  /  ";
resultClass=(diastolicBPResult!=="--")?"result-variable":"";
BPGraphHover+="<span class="+bpMeasurement.DIA_NORMALCY_CLASS+"><span class='"+resultClass+"' id='"+bpDiaId+"'>"+diastolicBPResult;
resultHTML+="<span class="+bpMeasurement.DIA_NORMALCY_CLASS+"><span class='res-ind'></span><span class='"+resultClass+"' id='"+bpDiaId+"'>"+diastolicBPResult;
if(bpMeasurement.DIA_COMMENT_IND){resultHTML+="<span class='vitals-wf-comments-ind'></span>";
}BPGraphHover+=bpMeasurement.DIA_MODIFIED_IND+"</span></span>";
resultHTML+=bpMeasurement.DIA_MODIFIED_IND+"</span></span></dd>";
resultHTML+="<dd  class='secondary-text vitals-wf-bp-result-date'>"+bpResultDateTimeStr+"</dd>";
resultHTML+="<dd  class='secondary-text vitals-wf-bp-result-name'>"+bpMeasurement.BP_GROUP_NAME+"</dd>";
resultHTML+="</dl>";
if(!isNaN(systolicBPResult)){allBPResults.push(parseFloat(systolicBPResult));
}if(!isNaN(diastolicBPResult)){allBPResults.push(parseFloat(diastolicBPResult));
}if(isNaN(systolicBPResult)&&isNaN(diastolicBPResult)){nonNumericBP=true;
}else{graphArray.push([bpResultDateTime,parseFloat(diastolicBPResult)||Number(NaN),parseFloat(systolicBPResult)||Number(NaN),bpMeasurement.BP_GROUP_NAME,BPGraphHover]);
}}this.m_clickedLabel=vitalsI18N.BLOOD_PRESSURE;
this.m_minBP=Math.min.apply(Math,allBPResults);
this.m_maxBP=Math.max.apply(Math,allBPResults);
}else{var firstResultUOM=dataObj.RESULT_DATA.FIRST_RES_UOM;
var resultDiffUOM="";
var measurement=null;
var dateTime=null;
var elementId="";
var resultObjInfo=null;
this.m_bpGraph=false;
if(isAmbView){measurementLength=Math.min(dataObj.RESULT_DATA.MEASUREMENTS.length,numberOfMostRecentResults);
}else{measurementLength=dataObj.RESULT_DATA.RESULTS_SHOWN;
}for(var measIdx=0;
measIdx<measurementLength;
measIdx++){measurement=dataObj.RESULT_DATA.MEASUREMENTS[measIdx];
dateTime=new Date();
dateTime.setISO8601(measurement.DTTM);
measurement.MODIFIED_IND=this.getModifyIndicator(measurement.STATUS_MEAN);
if(!measurement.NORMALCY_CLASS){measurement.NORMALCY_CLASS=this.getNormalcy(measurement.NORMALCY,0).NORMALCY;
}this.formatResult(measurement);
var localeGraphArrayValue=0;
if(isFinite(measurement.RESULT)){localeGraphArrayValue=parseFloat(measurement.RESULT);
}else{if((/^\d+(?:[,]\d+)$/gm).test(measurement.RESULT)){var actualGraphArrayValue=measurement.RESULT.toString().split(",");
localeGraphArrayValue=actualGraphArrayValue[0]+(actualGraphArrayValue[1]?"."+actualGraphArrayValue[1]:"");
localeGraphArrayValue=parseFloat(localeGraphArrayValue);
}}resultDiffUOM="";
if(measurement.UOM===firstResultUOM){graphArray.push([dateTime,localeGraphArrayValue,measurement.NORMALCY_CLASS,measurement.RESULT_NAME,measurement.RES_TYPE]);
}else{if(measurement.UOM){resultDiffUOM=" "+measurement.UOM;
differentUOM=true;
}else{resultDiffUOM=" --";
}}elementId="WF_VS"+componentId+"otherResult"+measIdx;
resultObjInfo={EVENT_ID:measurement.EVENT_ID,NAME:dataObj.RESULT_DATA.GROUP_NAME};
this.m_panelElementData[elementId]=resultObjInfo;
resultHTML+="<dl><dd class='vitals-wf-result-value'><span class="+measurement.NORMALCY_CLASS+"><span class='res-ind'></span>";
resultHTML+="<span class='result-variable' id='"+elementId+"'>"+measurement.RESULT+resultDiffUOM;
if(measurement.HAS_COMMENTS_IND){resultHTML+="<span class='vitals-wf-comments-ind'></span>";
}resultHTML+=measurement.MODIFIED_IND+"</span></span></dd>";
if(dateTime.getDate()===todaysDate.getDate()&&dateTime.getMonth()===todaysDate.getMonth()&&dateTime.getFullYear()===todaysDate.getFullYear()){resultHTML+="<dd class='secondary-text vitals-wf-result-date'><span>"+vitalsI18N.TODAY+"</span>";
}else{resultHTML+="<dd class='secondary-text vitals-wf-result-date'><span>"+dateTime.format("mediumDate")+"</span>";
}resultHTML+="<span class='vitals-wf-side-panel-result-item'>"+dateTime.format("militaryTime")+"</span></dd>";
resultHTML+="<dd class='secondary-text vitals-wf-result-name'>"+measurement.RESULT_NAME+"</dd>";
resultHTML+="</dl>";
}this.m_clickedLabel=dataObj.RESULT_DATA.GROUP_NAME;
}sidePanelHTML+=resultHTML+"</div></div></div>";
this.sidePanel.setContents(sidePanelHTML,"WF_VSContent"+componentId);
this.addClickToResult();
var namespaceId=this.getStyles().getId();
var graphDivId="#"+namespaceId+"graphHolder";
var graphHolder=$(graphDivId);
var testResult=$("#"+namespaceId+"testResult");
var graphDateRange=$("#"+namespaceId+"dateRange");
var minDate=null;
var maxDate=null;
var testResultHTML="";
var graphDateHTML="";
testResult.empty();
graphDateRange.empty();
if(graphArray.length>0){minDate=graphArray[graphArray.length-1][0].format("mediumDate");
maxDate=graphArray[0][0].format("mediumDate");
}graphDateHTML+="<div><span class = 'graph-date-left'>"+minDate+"</span><span class='graph-date-right'>"+maxDate+"</span></div>";
if(!this.m_bpGraph){if(graphArray.length===0||(isNaN(graphArray[0][1]))){testResultHTML+="<div class = 'vitals-no-graph-results'><span class='vitals-warning-image'>&nbsp;</span>"+vitalsI18N.NODATA+"</div>";
graphHolder.hide();
graphDateRange.hide();
}else{if(differentUOM&&graphArray.length>1){testResultHTML+="<div class = 'vitals-not-all-results'><span class='vitals-warning-image'>&nbsp;</span>"+vitalsI18N.NOTALLDATA+"</div>";
}else{if((graphArray[0][4]>1)&&!differentUOM){testResultHTML+="<div class = 'vitals-no-graph-results'><span class='vitals-warning-image'>&nbsp;</span>"+vitalsI18N.NODATA+"</div>";
graphHolder.hide();
graphDateRange.hide();
}}}}else{if(graphArray.length===0){testResultHTML+="<div class = 'vitals-no-graph-results'><span class='vitals-warning-image'>&nbsp;</span>"+vitalsI18N.NODATA+"</div>";
graphHolder.hide();
graphDateRange.hide();
}else{if(nonNumericBP&&graphArray.length>1){testResultHTML+="<div class = 'vitals-not-all-results'><span class='vitals-warning-image'>&nbsp;</span>"+vitalsI18N.NOTALLDATA+"</div>";
}}}if(graphArray.length==1&&!isNaN(graphArray[0][1])){testResultHTML+="<div class = 'vitals-no-graph-results'><span class='vitals-warning-image'>&nbsp;</span>"+vitalsI18N.SINGLEDATAPOINT+"</div>";
graphHolder.hide();
graphDateRange.hide();
}testResult.append(testResultHTML);
graphDateRange.append(graphDateHTML);
graphArray.reverse();
if(graphArray.length>0){this.setGraphData(graphArray);
this.plotGraph();
}else{this.setGraphData(null);
this.setVitalsPlot(null);
}};
VitalSignComponentWF.prototype.addClickToResult=function(){var self=this;
var compID=this.getComponentId();
var resultViewerTimer=null;
$("#WF_VS"+compID+"sidePanelResultList").on("click",".result-variable",function(event){var results={};
var target_id=event.target.id;
try{results=self.m_panelElementData[target_id];
if(results){ResultViewer.launchAdHocViewer(results.EVENT_ID,results.NAME);
resultViewerTimer=new CapabilityTimer("CAP:MPG Vitals O2 View Result",self.criterion.category_mean);
if(resultViewerTimer){resultViewerTimer.addMetaData("rtms.legacy.metadata.1","Ambulatory Side Panel");
resultViewerTimer.capture();
}}}catch(err){MP_Util.LogJSError(err,null,"vitals_o2.js","addClickToResult");
}});
};
VitalSignComponentWF.prototype.createResultGroupObj=function(result,criticalResultInd){return{RESULTS:result,CRITICAL_IND:criticalResultInd};
};
VitalSignComponentWF.prototype.formatDate=function(dateTime){var date=new Date();
date.setISO8601(dateTime);
return date.format("longDateTime3");
};
VitalSignComponentWF.prototype.processResultsForAmbulatoryView=function(recordData){var self=this;
var criticalResultInd=false;
var meas=null;
var groupName="";
var columnObj={};
var measCnt=0;
var resultGroup=null;
var nameSpace=this.getStyles().getId();
var resultGroupCnt=recordData.RG.length;
var vitalsI18N=i18n.discernabu.vitals_o2;
var todaysDate=new Date();
this.setRecordData(recordData);
var z=0;
function createDateResultHTML(resultDateTime){var resultDate=new Date();
resultDate.setISO8601(resultDateTime);
return"<span class='vitals-wf-time-display'>"+MP_Util.DisplayDateByOption(self,resultDate)+"</span>";
}function resultObjConstructor(){var resultObj={};
var i=0;
var columnCount=self.m_ambViewColumnCnt;
for(i=columnCount;
i--;
){resultObj["column"+i]={DISPLAY:"--",OBJECT_ARR:[]};
}return resultObj;
}function createResultDisplay(resultObj,isBpResult,unitOfMeasure){var resultDisplay="";
var normalcyClassObj;
var resultDateTime=null;
var dateTimeString="";
var resultTime="";
var firstResUOM=unitOfMeasure;
var diffUOM="";
if(isBpResult){var sysResult="";
var diaResult="";
var resultClass="";
if(resultObj[0].SYS_EVENTS.length){normalcyClassObj=self.getNormalcy(resultObj[0].SYS_EVENTS[0].NORMALCY,0);
self.formatResult(resultObj[0].SYS_EVENTS[0]);
resultObj[0].SYS_RESULT=resultObj[0].SYS_EVENTS[0].RESULT;
resultObj[0].SYS_NORMALCY_CLASS=normalcyClassObj.NORMALCY;
resultObj[0].SYS_MODIFIED_IND=self.getModifyIndicator(resultObj[0].SYS_EVENTS[0].STATUS_MEAN);
if(!criticalResultInd){criticalResultInd=normalcyClassObj.CRITICAL_IND;
}if(resultObj[0].SYS_EVENTS[0].HAS_COMMENTS_IND){resultObj[0].SYS_COMMENT_IND="<span class='vitals-wf-comments-ind'></span>";
}else{resultObj[0].SYS_COMMENT_IND="";
}resultDateTime=resultObj[0].SYS_EVENTS[0].DTTM;
}else{resultObj[0].SYS_RESULT="--";
resultObj[0].SYS_NORMALCY_CLASS="";
resultObj[0].SYS_MODIFIED_IND="";
resultObj[0].SYS_COMMENT_IND="";
}if(resultObj[0].DIA_EVENTS.length){normalcyClassObj=self.getNormalcy(resultObj[0].DIA_EVENTS[0].NORMALCY,0);
self.formatResult(resultObj[0].DIA_EVENTS[0]);
resultObj[0].DIA_RESULT=resultObj[0].DIA_EVENTS[0].RESULT;
resultObj[0].DIA_MODIFIED_IND=self.getModifyIndicator(resultObj[0].DIA_EVENTS[0].STATUS_MEAN);
resultObj[0].DIA_NORMALCY_CLASS=normalcyClassObj.NORMALCY;
resultDateTime=resultObj[0].DIA_EVENTS[0].DTTM;
if(!criticalResultInd){criticalResultInd=normalcyClassObj.CRITICAL_IND;
}if(resultObj[0].DIA_EVENTS[0].HAS_COMMENTS_IND){resultObj[0].DIA_COMMENT_IND="<span class='vitals-wf-comments-ind'></span>";
}else{resultObj[0].DIA_COMMENT_IND="";
}}else{resultObj[0].DIA_RESULT="--";
resultObj[0].DIA_NORMALCY_CLASS="";
resultObj[0].DIA_MODIFIED_IND="";
resultObj[0].DIA_COMMENT_IND="";
}resultClass=(resultObj[0].SYS_RESULT!=="--")?"result-variable":"";
sysResult='<span class="'+resultObj[0].SYS_NORMALCY_CLASS+'"><span class="res-ind"></span><span data-id = "'+nameSpace+'systolic" class='+resultClass+">"+resultObj[0].SYS_RESULT+resultObj[0].SYS_COMMENT_IND+resultObj[0].SYS_MODIFIED_IND+"</span></span>";
resultClass=(resultObj[0].DIA_RESULT!=="--")?"result-variable":"";
diaResult=resultObj[0].DIA_RESULT+resultObj[0].DIA_COMMENT_IND+resultObj[0].DIA_MODIFIED_IND;
diaResult='<span class="'+resultObj[0].DIA_NORMALCY_CLASS+'"><span class="res-ind"></span><span data-id ="'+nameSpace+'diastolic" class='+resultClass+">"+diaResult+"</span></span>";
if(self.getDateFormat()!==4){dateTimeString=createDateResultHTML(resultDateTime);
}resultDisplay=sysResult+" / "+diaResult+dateTimeString;
return resultDisplay;
}else{normalcyClassObj=self.getNormalcy(resultObj[0].NORMALCY,0);
resultObj[0].NORMALCY_CLASS=normalcyClassObj.NORMALCY;
if(!criticalResultInd){criticalResultInd=normalcyClassObj.CRITICAL_IND;
}resultDateTime=resultObj[0].DTTM;
resultObj[0].MODIFIED_IND=self.getModifyIndicator(resultObj[0].STATUS_MEAN);
self.formatResult(resultObj[0]);
if(self.getDateFormat()!==4){dateTimeString=createDateResultHTML(resultDateTime);
}if(resultObj[0].UOM===firstResUOM){}else{if(resultObj[0].UOM){diffUOM=" "+resultObj[0].UOM;
}else{diffUOM=" --";
}}if(resultObj[0].HAS_COMMENTS_IND){resultObj[0].COMMENT_IND="<span class='vitals-wf-comments-ind'></span>";
}else{resultObj[0].COMMENT_IND="";
}return'<span class="'+resultObj[0].NORMALCY_CLASS+'"><span class="res-ind">&nbsp;</span><span class="result-variable" data-id = "'+nameSpace+'other">'+resultObj[0].RESULT+diffUOM+resultObj[0].COMMENT_IND+resultObj[0].MODIFIED_IND+"</span></span>"+resultDisplay+dateTimeString;
}}var measResult=[];
for(y=0;
y<resultGroupCnt;
y++){resultGroup=recordData.RG[y];
switch(resultGroup.GROUP_TYPE){case 1:groupName="<span title='"+vitalsI18N.TEMPERATURE+"'>"+vitalsI18N.TEMPERATURE+"</span>";
break;
case 2:groupName="<span title='"+vitalsI18N.BLOOD_PRESSURE+"'>"+vitalsI18N.BLOOD_PRESSURE+"</span>";
break;
case 3:groupName="<span title='"+vitalsI18N.HEART_RATE+"'>"+vitalsI18N.HEART_RATE+"</span>";
break;
case 4:groupName="<span title='"+resultGroup.GROUP_NAME+"'>"+resultGroup.GROUP_NAME+"</span>";
break;
default:}if(resultGroup.GROUP_TYPE==2){resultGroup=recordData.BP_RESULTS;
measCnt=recordData.BP_RESULTS.length;
resultGroup.GROUP_TYPE=2;
resultGroup.GROUP_NAME=vitalsI18N.BLOOD_PRESSURE;
}else{measCnt=resultGroup.MEASUREMENTS.length;
}resultGroup.RESULT_OBJ=resultObjConstructor();
resultGroup.RESULT_GROUP_NAME=groupName;
var measureCnt=0;
var columnCnt=0;
while(measureCnt<this.m_ambViewColumnCnt&&columnCnt<this.m_ambViewColumnCnt){var firstResultUOM="";
meas=resultGroup[measureCnt];
if(resultGroup.GROUP_TYPE==2){if(meas){resultTime=meas.DIA_EVENTS[0]?meas.DIA_EVENTS[0].DTTM:meas.SYS_EVENTS[0].DTTM;
}resultGroup.IS_BP_RESULT=true;
}else{if(resultGroup.MEASUREMENTS){meas=resultGroup.MEASUREMENTS[measureCnt];
if(meas){resultTime=meas.DTTM;
}resultGroup.IS_BP_RESULT=false;
resultGroup.IS_TEMP_RESULT=resultGroup.GROUP_TYPE==1?true:false;
if(resultGroup.IS_TEMP_RESULT){resultGroup.TEMP_MIN_MAX=recordData.MIN_MAX_TEMP;
}}}if(resultGroup.GROUP_TYPE!==2){if(measureCnt===0&&meas&&!resultGroup.FIRST_RES_UOM){firstResultUOM=meas.UOM;
resultGroup.FIRST_RES_UOM=firstResultUOM;
}}else{if(measureCnt===0&&meas&&!resultGroup.FIRST_RES_UOM){if(meas.SYS_EVENTS.length&&meas.SYS_EVENTS[0].UOM){firstResultUOM=meas.SYS_EVENTS[0].UOM;
}else{if(meas.DIA_EVENTS.length&&meas.DIA_EVENTS[0].UOM){firstResultUOM=meas.DIA_EVENTS[0].UOM;
}}resultGroup.FIRST_RES_UOM=firstResultUOM;
}}if(firstResultUOM){resultGroup.RESULT_GROUP_NAME+="<br /><span class='vitals-wf-result-info'>"+resultGroup.FIRST_RES_UOM+"</span>";
}if(meas){resultGroup.RESULT_OBJ["column"+columnCnt].OBJECT_ARR.push(meas);
if(columnCnt===0){if(self.getShowTodayValue()){var dateTime=new Date();
dateTime.setISO8601(resultTime);
if((dateTime.getDate()===todaysDate.getDate())&&(dateTime.getMonth()===todaysDate.getMonth())&&(dateTime.getFullYear()===todaysDate.getFullYear())){resultGroup.RESULT_OBJ["column"+columnCnt].DISPLAY=createResultDisplay(resultGroup.RESULT_OBJ["column"+columnCnt].OBJECT_ARR,resultGroup.IS_BP_RESULT,resultGroup.FIRST_RES_UOM);
measureCnt++;
}else{resultGroup.RESULT_OBJ["column"+columnCnt].DISPLAY="--";
resultGroup.RESULT_OBJ["column"+columnCnt].OBJECT_ARR=[];
}}else{resultGroup.RESULT_OBJ["column"+columnCnt].DISPLAY=createResultDisplay(resultGroup.RESULT_OBJ["column"+columnCnt].OBJECT_ARR,resultGroup.IS_BP_RESULT,resultGroup.FIRST_RES_UOM);
measureCnt++;
}}else{resultGroup.RESULT_OBJ["column"+columnCnt].DISPLAY=createResultDisplay(resultGroup.RESULT_OBJ["column"+columnCnt].OBJECT_ARR,resultGroup.IS_BP_RESULT,resultGroup.FIRST_RES_UOM);
measureCnt++;
}}else{resultGroup.RESULT_OBJ["column"+columnCnt].DISPLAY="--";
}columnCnt++;
}measResult.push(resultGroup);
}columnObj=this.createResultGroupObj(measResult,criticalResultInd);
return columnObj;
};
VitalSignComponentWF.prototype.processResultsForFlowsheetView=function(recordData){var self=this;
var criticalResultInd=false;
var meas=null;
var measCnt=0;
var curDate=null;
var nextDate=null;
var hoverNormalcyClass="res-normal";
var resultGroup=null;
var resultGroupCnt=recordData.RG.length;
var timeBucketCnt=0;
var timeBucketRef="";
var vitalsI18N=i18n.discernabu.vitals_o2;
var nameSpace=this.getStyles().getId();
var todaysDate=new Date();
var dateTime=null;
this.setRecordData(recordData);
var x=0;
var y=0;
var z=0;
function resultObjConstructor(timeGroups,groupType){var resultObj={};
var i=0;
for(i=timeGroups.length;
i--;
){resultObj[timeGroups[i].TIME_ADJUSTED]={DISPLAY:"<span class='"+timeGroups[i].NEW_DAY_CLASS+"'>--</span>",OBJECT_ARR:[]};
}return resultObj;
}function createResultDisplay(resultObj,isBpResult,unitOfMeasure){var dateResult=null;
var result=null;
var resultCnt=resultObj.length;
var resultDisplay="";
var normalcyClassObj;
var groupName="";
var i=0;
var columnObj={};
var timeBucket=null;
var resultClass="";
var firstResUOM=unitOfMeasure;
var diffUOM="";
hoverNormalcyClass="res-normal";
if(isBpResult){var sysResult="";
var diaResult="";
resultObj[0].HAS_SYS_RESULT=0;
resultObj[0].HAS_DIA_RESULT=0;
resultObj[0].SYS_COMMENT_IND="";
resultObj[0].DIA_COMMENT_IND="";
for(i=0;
i<resultCnt;
i++){if(resultObj[i].SYS_EVENTS.length){normalcyClassObj=self.getNormalcy(resultObj[i].SYS_EVENTS[0].NORMALCY,i,hoverNormalcyClass);
resultObj[i].SYS_NORMALCY_CLASS=normalcyClassObj.NORMALCY;
hoverNormalcyClass=normalcyClassObj.HOVERNORMALCY;
if(!criticalResultInd){criticalResultInd=normalcyClassObj.CRITICAL_IND;
}if(i===0){self.formatResult(resultObj[0].SYS_EVENTS[0]);
resultObj[0].SYS_RESULT=resultObj[0].SYS_EVENTS[0].RESULT;
resultObj[0].SYS_MODIFIED_IND=self.getModifyIndicator(resultObj[0].SYS_EVENTS[0].STATUS_MEAN);
}if(resultObj[i].SYS_EVENTS[0].HAS_COMMENTS_IND){resultObj[0].SYS_COMMENT_IND="<span class='vitals-wf-comments-ind'></span>";
}resultObj[0].HAS_SYS_RESULT=1;
}else{resultObj[i].SYS_RESULT="--";
resultObj[i].SYS_NORMALCY_CLASS="";
resultObj[i].SYS_MODIFIED_IND="";
resultObj[i].SYS_COMMENT_IND="";
}if(resultObj[i].DIA_EVENTS.length){normalcyClassObj=self.getNormalcy(resultObj[i].DIA_EVENTS[0].NORMALCY,i,hoverNormalcyClass);
resultObj[i].DIA_NORMALCY_CLASS=normalcyClassObj.NORMALCY;
hoverNormalcyClass=normalcyClassObj.HOVERNORMALCY;
if(!criticalResultInd){criticalResultInd=normalcyClassObj.CRITICAL_IND;
}if(i===0){self.formatResult(resultObj[0].DIA_EVENTS[0]);
resultObj[0].DIA_RESULT=resultObj[0].DIA_EVENTS[0].RESULT;
resultObj[0].DIA_MODIFIED_IND=self.getModifyIndicator(resultObj[0].DIA_EVENTS[0].STATUS_MEAN);
}if(resultObj[i].DIA_EVENTS[0].HAS_COMMENTS_IND){resultObj[0].DIA_COMMENT_IND="<span class='vitals-wf-comments-ind'></span>";
}resultObj[0].HAS_DIA_RESULT=1;
}else{resultObj[i].DIA_RESULT="--";
resultObj[i].DIA_NORMALCY_CLASS="";
resultObj[i].DIA_MODIFIED_IND="";
resultObj[i].DIA_COMMENT_IND="";
}}sysResult=((resultCnt>1)?"<span class='fs-res-bracket'>[<span class='"+hoverNormalcyClass+"'>"+resultCnt+"</span>]</span>":"");
resultClass=(resultObj[0].HAS_SYS_RESULT!==0)?"result-variable":"";
sysResult='<span class="'+resultObj[0].SYS_NORMALCY_CLASS+'"><span class="res-ind"></span><span  data-id = "'+nameSpace+'systolic" class='+resultClass+">"+resultObj[0].SYS_RESULT+resultObj[0].SYS_COMMENT_IND+resultObj[0].SYS_MODIFIED_IND+"</span></span>";
resultClass=(resultObj[0].HAS_DIA_RESULT!==0)?"result-variable":"";
diaResult=resultObj[0].DIA_RESULT+resultObj[0].DIA_COMMENT_IND+resultObj[0].DIA_MODIFIED_IND;
diaResult='<span class="'+resultObj[0].DIA_NORMALCY_CLASS+'"><span class="res-ind"></span><span data-id ="'+nameSpace+'diastolic" class='+resultClass+">"+diaResult+"</span></span>";
resultDisplay=sysResult+" / "+diaResult;
return resultDisplay;
}else{resultObj[0].COMMENT_IND="";
for(i=0;
i<resultCnt;
i++){normalcyClassObj=self.getNormalcy(resultObj[i].NORMALCY,i,hoverNormalcyClass);
resultObj[i].NORMALCY_CLASS=normalcyClassObj.NORMALCY;
hoverNormalcyClass=normalcyClassObj.HOVERNORMALCY;
if(!criticalResultInd){criticalResultInd=normalcyClassObj.CRITICAL_IND;
}if(resultObj[i].HAS_COMMENTS_IND){resultObj[0].COMMENT_IND="<span class='vitals-wf-comments-ind'></span>";
}}resultObj[0].MODIFIED_IND=self.getModifyIndicator(resultObj[0].STATUS_MEAN);
if(resultObj[0].UOM===firstResUOM){}else{if(resultObj[0].UOM){diffUOM=" "+resultObj[0].UOM;
}else{diffUOM=" --";
}}self.formatResult(resultObj[0]);
resultDisplay=" "+((resultCnt>1)?"<span class='fs-res-bracket'>[<span class='"+hoverNormalcyClass+"'>"+resultCnt+"</span>]</span>":"");
return'<span class="'+resultObj[0].NORMALCY_CLASS+'"><span class="res-ind">&nbsp;</span><span class="result-variable" data-id = "'+nameSpace+'other">'+resultObj[0].RESULT+diffUOM+resultObj[0].COMMENT_IND+resultObj[0].MODIFIED_IND+"</span></span>"+resultDisplay;
}}timeBucketCnt=recordData.TG.length;
var isTimeBucketsChopped=(this.m_showingLatestResults&&timeBucketCnt>this.m_latestColumnCap);
if(isTimeBucketsChopped){timeBucketCnt=this.m_latestColumnCap;
}var timeBucketSeqMap={};
var timeBucketSequence=[];
var timeBucketDisplay=null;
for(x=0;
x<timeBucketCnt;
x++){timeBucket=recordData.TG[x];
timeBucketDisplay=self.formatDate(timeBucket.TIME_DISP);
timeBucket.TIME_ADJUSTED=timeBucketDisplay;
timeBucketSequence.push(timeBucketDisplay);
timeBucketSeqMap[timeBucketDisplay]=x;
nextDate=new Date();
nextDate.setISO8601(timeBucket.TIME_DISP);
if(x===0){timeBucket.NEW_DAY_CLASS="fs-new-day";
timeBucket.COLUMN_DISPLAY="<span class='"+timeBucket.NEW_DAY_CLASS+"'>"+nextDate.format("mediumDate")+"<br />"+nextDate.format("militaryTime")+"</span>";
if(nextDate.getDate()===todaysDate.getDate()&&nextDate.getMonth()===todaysDate.getMonth()&&nextDate.getFullYear()===todaysDate.getFullYear()){timeBucket.COLUMN_DISPLAY="<span class='"+timeBucket.NEW_DAY_CLASS+"'>"+vitalsI18N.TODAY+"<br />"+nextDate.format("militaryTime")+"</span>";
}curDate=nextDate;
}else{timeBucket.NEW_DAY_CLASS="";
if(nextDate.getDate()===curDate.getDate()&&nextDate.getMonth()===curDate.getMonth()&&nextDate.getFullYear()===curDate.getFullYear()){timeBucket.NEW_DAY_CLASS="fs-time-display";
timeBucket.COLUMN_DISPLAY="<span class='"+timeBucket.NEW_DAY_CLASS+"'>&nbsp;<br />"+nextDate.format("militaryTime")+"</span>";
}else{timeBucket.NEW_DAY_CLASS="fs-new-day";
timeBucket.COLUMN_DISPLAY="<span class='"+timeBucket.NEW_DAY_CLASS+"'>"+nextDate.format("mediumDate")+"<br />"+nextDate.format("militaryTime")+"</span>";
curDate=nextDate;
}}}var hasDataInRow=false;
var lastColumnDate=null;
if(isTimeBucketsChopped){lastColumnDate=new Date();
lastColumnDate.setISO8601(recordData.TG[this.m_latestColumnCap-1].TIME_DISP);
}var formattedTimeBucketRef=null;
var measResult=[];
var lastOccupiedTimeBucketRef=null;
var aResultObject=null;
var resultsShownInRow=0;
for(y=0;
y<resultGroupCnt;
y++){resultGroup=recordData.RG[y];
switch(resultGroup.GROUP_TYPE){case 1:groupName="<span title='"+vitalsI18N.TEMPERATURE+"'>"+vitalsI18N.TEMPERATURE+"</span>";
break;
case 2:groupName="<span title='"+vitalsI18N.BLOOD_PRESSURE+"'>"+vitalsI18N.BLOOD_PRESSURE+"</span>";
break;
case 3:groupName="<span title='"+vitalsI18N.HEART_RATE+"'>"+vitalsI18N.HEART_RATE+"</span>";
break;
case 4:groupName="<span title='"+resultGroup.GROUP_NAME+"'>"+resultGroup.GROUP_NAME+"</span>";
break;
default:}if(resultGroup.GROUP_TYPE==2){resultGroup=recordData.BP_RESULTS;
measCnt=recordData.BP_RESULTS.length;
resultGroup.GROUP_TYPE=2;
resultGroup.GROUP_NAME=vitalsI18N.BLOOD_PRESSURE;
}else{measCnt=resultGroup.MEASUREMENTS.length;
}hasDataInRow=false;
resultGroup.RESULT_OBJ=resultObjConstructor(recordData.TG,resultGroup.GROUP_TYPE);
resultGroup.RESULT_GROUP_NAME=groupName;
resultsShownInRow=0;
for(z=0;
z<measCnt;
z++){var firstResultUOM="";
if(resultGroup.GROUP_TYPE==2){meas=resultGroup[z];
timeBucketRef=meas.DIA_EVENTS[0]?meas.DIA_EVENTS[0].DTTM:meas.SYS_EVENTS[0].DTTM;
timeBucketRef=timeBucketRef.replace(/:[0-9][0-9]Z/,":00Z");
resultGroup.IS_BP_RESULT=true;
}else{if(resultGroup.MEASUREMENTS){meas=resultGroup.MEASUREMENTS[z];
timeBucketRef=meas.DTTM.replace(/:[0-9][0-9]Z/,":00Z");
resultGroup.IS_BP_RESULT=false;
resultGroup.IS_TEMP_RESULT=resultGroup.GROUP_TYPE==1?true:false;
if(resultGroup.IS_TEMP_RESULT){resultGroup.TEMP_MIN_MAX=recordData.MIN_MAX_TEMP;
}}}if(resultGroup.GROUP_TYPE!==2){if(z===0&&meas&&!resultGroup.FIRST_RES_UOM){firstResultUOM=meas.UOM;
resultGroup.FIRST_RES_UOM=firstResultUOM;
}}else{if(z===0&&meas&&!resultGroup.FIRST_RES_UOM){if(meas.SYS_EVENTS.length&&meas.SYS_EVENTS[0].UOM){firstResultUOM=meas.SYS_EVENTS[0].UOM;
}else{if(meas.DIA_EVENTS.length&&meas.DIA_EVENTS[0].UOM){firstResultUOM=meas.DIA_EVENTS[0].UOM;
}}resultGroup.FIRST_RES_UOM=firstResultUOM;
}}if(firstResultUOM){resultGroup.RESULT_UOM="<span title='"+resultGroup.FIRST_RES_UOM+"' class='vitals-wf-result-info'>"+resultGroup.FIRST_RES_UOM+"</span>";
}if(isTimeBucketsChopped){dateTime=new Date();
dateTime.setISO8601(timeBucketRef);
if(dateTime>=lastColumnDate){hasDataInRow=true;
}}formattedTimeBucketRef=self.formatDate(timeBucketRef);
aResultObject=resultGroup.RESULT_OBJ[formattedTimeBucketRef];
if(typeof aResultObject!=="undefined"){aResultObject.OBJECT_ARR.push(meas);
aResultObject.DISPLAY=createResultDisplay(aResultObject.OBJECT_ARR,resultGroup.IS_BP_RESULT,resultGroup.FIRST_RES_UOM);
aResultObject.TIME=formattedTimeBucketRef;
resultsShownInRow++;
}if(z===measCnt-1){lastOccupiedTimeBucketRef=formattedTimeBucketRef;
}}resultGroup.RESULTS_SHOWN=resultsShownInRow;
if(this.m_showingLatestResults){if(isTimeBucketsChopped&&!hasDataInRow){continue;
}if(measCnt>=this.m_flowsheetResultCap){var lastOccupiedIdx=timeBucketSeqMap[lastOccupiedTimeBucketRef];
for(z=timeBucketCnt-1;
z>lastOccupiedIdx;
z--){var curTimeBucketRef=timeBucketSequence[z];
resultGroup.RESULT_OBJ[curTimeBucketRef].DISPLAY="<span class='vitals-wf-result-unknown'>&nbsp;</span>";
}}}measResult.push(resultGroup);
}columnObj=this.createResultGroupObj(measResult,criticalResultInd);
return columnObj;
};
VitalSignComponentWF.prototype.createResultHoverForFlowsheetView=function(dataObj){var additionalClass="";
var hoverHTML=[];
var vitalsI18N=i18n.discernabu.vitals_o2;
var moreHoverHTML=[];
var numberFormatter=MP_Util.GetNumericFormatter();
var result=null;
var resultCnt=0;
var x=0;
var tempHTML=[];
var bpResult="";
var group=dataObj.RESULT_DATA;
var curTimeBucket=group.RESULT_OBJ[dataObj.COLUMN_ID];
var timeBucketResults=curTimeBucket.OBJECT_ARR;
resultCnt=timeBucketResults.length;
if(resultCnt===0){if(curTimeBucket.DISPLAY.indexOf("vitals-wf-result-unknown")>=0){return"<div class='hvr vitals-wf-hover'>"+i18n.discernabu.LIMITED_RESULTS+"</div>";
}return null;
}hoverHTML.push("<div class='hvr vitals-wf-hover'>");
if(resultCnt>1){moreHoverHTML.push("<div class='vitals-wf-hover-additional'><div>"+vitalsI18N.ADDITIONAL_RESULTS+"</div><dl>");
additionalClass=(resultCnt>1)?"vitals-wf-hover-seperator":"";
}for(x=0;
x<resultCnt;
x++){result=timeBucketResults[x];
if(x===0){if(group.IS_BP_RESULT){if(result.DIA_EVENTS.length){result.DIA_UOM=result.DIA_EVENTS[0].UOM;
result.DIA_NLOW=result.DIA_EVENTS[0].NLOW;
result.DIA_NHIGH=result.DIA_EVENTS[0].NHIGH;
result.DIA_CLOW=result.DIA_EVENTS[0].CLOW;
result.DIA_CHIGH=result.DIA_EVENTS[0].CHIGH;
result.DIA_STATUS=result.DIA_EVENTS[0].STATUS;
result.DIA_MODIFIED_IND=this.getModifyIndicator(result.DIA_EVENTS[0].STATUS_MEAN);
result.DTTM=result.DIA_EVENTS[0].DTTM;
}else{result.DIA_UOM="";
result.DIA_NLOW="--";
result.DIA_NHIGH="--";
result.DIA_CLOW="--";
result.DIA_CHIGH="--";
result.DIA_STATUS="";
result.DIA_MODIFIED_IND="";
}if(result.SYS_EVENTS.length){result.SYS_NLOW=(result.SYS_EVENTS[0].NLOW);
result.SYS_NHIGH=(result.SYS_EVENTS[0].NHIGH);
result.SYS_CLOW=(result.SYS_EVENTS[0].CLOW);
result.SYS_CHIGH=(result.SYS_EVENTS[0].CHIGH);
result.SYS_UOM=(result.SYS_EVENTS[0].UOM);
result.SYS_STATUS=(result.SYS_EVENTS[0].STATUS);
result.SYS_MODIFIED_IND=this.getModifyIndicator(result.SYS_EVENTS[0].STATUS_MEAN);
result.DTTM=result.SYS_EVENTS[0].DTTM;
}else{result.SYS_NLOW="--";
result.SYS_NHIGH="--";
result.SYS_CLOW="--";
result.SYS_CHIGH="--";
result.SYS_UOM="";
result.SYS_STATUS="";
result.SYS_MODIFIED_IND="";
}bpResult="<dd><span class='"+result.SYS_NORMALCY_CLASS+"'>"+result.SYS_RESULT+" "+result.SYS_UOM+"</span>"+result.SYS_MODIFIED_IND;
bpResult+="/<span class='"+result.DIA_NORMALCY_CLASS+"'>"+result.DIA_RESULT+" "+result.DIA_UOM+"</span>"+result.DIA_MODIFIED_IND+"</dd>";
hoverHTML.push("<div class='vitals-wf-hover-main ",additionalClass,"'><dl><dt><span>",result.BP_GROUP_NAME,":</span></dt>"+bpResult+"<dt><span>",vitalsI18N.DATE_TIME,":</span></dt><dd><span>",this.formatDate(result.DTTM),"</span></dd><dt><span>",vitalsI18N.STATUS,":</span></dt><dd><span>",result.SYS_STATUS||"--","/",result.DIA_STATUS||"--","</span></dd><dt><span>",vitalsI18N.NORMAL_LOW,":</span></dt><dd><span>",result.SYS_NLOW||"--","/",result.DIA_NLOW||"--","</span></dd><dt><span>",vitalsI18N.NORMAL_HIGH,":</span></dt><dd><span>",result.SYS_NHIGH||"--","/",result.DIA_NHIGH||"--","</span></dd><dt><span>",vitalsI18N.CRITICAL_LOW,":</span></dt><dd><span>",result.SYS_CLOW||"--","/",result.DIA_CLOW||"--","</span></dd><dt><span>",vitalsI18N.CRITICAL_HIGH,":</span></dt><dd><span>",result.SYS_CHIGH||"--","/",result.DIA_CHIGH||"--","</span></dd></dl></div>");
}else{if(group.IS_TEMP_RESULT&&group.TEMP_MIN_MAX){var minMaxData=group.TEMP_MIN_MAX;
var tempMin=(this.getNormalcy(minMaxData.MIN_NORMALCY)).NORMALCY;
var tempMax=(this.getNormalcy(minMaxData.MAX_NORMALCY)).NORMALCY;
var minDate=minMaxData.MIN_DTTM?this.formatDate(minMaxData.MIN_DTTM):"";
var maxDate=minMaxData.MAX_DTTM?this.formatDate(minMaxData.MAX_DTTM):"";
var min_value=minMaxData.MIN_VALUE?(mp_formatter._isNumber(minMaxData.MIN_VALUE)?numberFormatter.format(minMaxData.MIN_VALUE,"^."+MP_Util.CalculatePrecision(minMaxData.MIN_VALUE)):minMaxData.MIN_VALUE):"--";
var max_value=minMaxData.MAX_VALUE?(mp_formatter._isNumber(minMaxData.MAX_VALUE)?numberFormatter.format(minMaxData.MAX_VALUE,"^."+MP_Util.CalculatePrecision(minMaxData.MAX_VALUE)):minMaxData.MAX_VALUE):"--";
tempHTML.push("<dt><span>",vitalsI18N.ONE_DAY_MAX,":</span></dt><dd><span class='",tempMax,"'>",max_value,"&nbsp;",minMaxData.MAX_UOM,this.getModifyIndicator(minMaxData.MAX_STATUS_MEAN),"</span>&nbsp;",maxDate,"</dd>","<dt><span>",vitalsI18N.ONE_DAY_MIN,":</span></dt><dd><span class='",tempMin,"'>",min_value,"&nbsp;",minMaxData.MIN_UOM,this.getModifyIndicator(minMaxData.MIN_STATUS_MEAN),"</span>&nbsp;",minDate,"</dd>");
}hoverHTML.push("<div class='vitals-wf-hover-main ",additionalClass,"'><dl><dt><span>",result.RESULT_NAME,":</span></dt><dd><span class='",result.NORMALCY_CLASS,"'>",result.RESULT," ",result.UOM,"</span>",result.MODIFIED_IND,"</dd><dt><span>",vitalsI18N.DATE_TIME,":</span></dt><dd><span>",this.formatDate(result.DTTM),"</span></dd><dt><span>",vitalsI18N.STATUS,":</span></dt><dd><span>",result.STATUS||"--","</span></dd><dt><span>",vitalsI18N.NORMAL_LOW,":</span></dt><dd><span>",result.NLOW||"--","</span></dd><dt><span>",vitalsI18N.NORMAL_HIGH,":</span></dt><dd><span>",result.NHIGH||"--","</span></dd><dt><span>",vitalsI18N.CRITICAL_LOW,":</span></dt><dd><span>",result.CLOW||"--","</span></dd><dt><span>",vitalsI18N.CRITICAL_HIGH,":</span></dt><dd><span>",result.CHIGH||"--","</span></dd>",tempHTML.join(""),"</dl></div>");
}}else{if(group.IS_BP_RESULT){if(result.DIA_EVENTS.length){result.DIA_UOM=result.DIA_EVENTS[0].UOM;
this.formatResult(result.DIA_EVENTS[0]);
result.DIA_RESULT=result.DIA_EVENTS[0].RESULT;
result.DIA_MODIFIED_IND=this.getModifyIndicator(result.DIA_EVENTS[0].STATUS_MEAN);
}else{result.DIA_UOM="";
result.DIA_RESULT="--";
result.DIA_MODIFIED_IND="";
}if(result.SYS_EVENTS.length){result.SYS_UOM=result.SYS_EVENTS[0].UOM;
this.formatResult(result.SYS_EVENTS[0]);
result.SYS_RESULT=result.SYS_EVENTS[0].RESULT;
result.SYS_MODIFIED_IND=this.getModifyIndicator(result.SYS_EVENTS[0].STATUS_MEAN);
}else{result.SYS_UOM="";
result.SYS_RESULT="--";
result.SYS_MODIFIED_IND="";
}bpResult="<span class='"+result.SYS_NORMALCY_CLASS+"'>"+result.SYS_RESULT+" "+result.SYS_UOM+"</span>"+result.SYS_MODIFIED_IND+"/<span class='"+result.DIA_NORMALCY_CLASS+"'>"+result.DIA_RESULT+" "+result.DIA_UOM+"</span>"+result.DIA_MODIFIED_IND;
moreHoverHTML.push("<dd>",bpResult,"</dd>");
}else{this.formatResult(result);
modifiedDisplay=this.getModifyIndicator(result.STATUS_MEAN);
moreHoverHTML.push("<dd><span class='",result.NORMALCY_CLASS,"'><span class='res-ind'>&nbsp;</span>",result.RESULT," ",result.UOM,"</span>",modifiedDisplay,"</dd>");
}}}if(resultCnt>1){moreHoverHTML.push("</dl></div>");
hoverHTML.push(moreHoverHTML.join(""));
}hoverHTML.push("</div>");
return hoverHTML.join("");
};
VitalSignComponentWF.prototype.toggleButtonHover=function(){this.onmouseover=function(event){var objectClass=$(event.target).attr("class");
if(objectClass=="hdr-toggle table_active"||objectClass=="hdr-toggle table_inactive"){$(event.target).attr("title",i18n.discernabu.vitals_o2.FLOWSHEET_VIEW);
}else{if(objectClass=="hdr-toggle viewer_active"||objectClass=="hdr-toggle viewer_inactive"){$(event.target).attr("title",i18n.discernabu.vitals_o2.AMBULATORY_VIEW);
}}};
};
VitalSignComponentWF.prototype.renderComponent=function(recordData){var vitalsTable=null;
var results=null;
var column="";
var criterion=this.getCriterion();
var nameSpace=this.getStyles().getId();
var compId=this.getComponentId();
var self=this;
var columnCntForFlowsheetView=recordData.TG.length;
var j=0;
var hoverExtension=new TableCellHoverExtension();
var vitalsCombinedHTML="";
var viewTypeTimer=null;
vitalsCombinedHTML+=("<div id ='WF_VS"+compId+"mainContainer'>");
if(this.getShowAmbulatoryView()){var columnClass="";
var columnName="";
vitalsTable=new ComponentTable();
vitalsTable.addExtension(hoverExtension);
hoverExtension.setTarget("td.table-cell");
vitalsTable.setNamespace(this.getStyles().getId());
vitalsTable.setBodyTag("table");
vitalsTable.setRowTag("tr");
vitalsTable.setColumnTag("td");
vitalsTable.setCustomClass("vitals-wf-amb");
vitalsTable.renderHeader=function(){var gSequence=vitalsTable.getGroupSequence();
var numberOfGroups=gSequence.length;
if(vitalsTable.getActiveRows().length>0||numberOfGroups>0){var headerWrapper="<div id='"+nameSpace+"outerHeaderWrapper' class='content-hdr'>";
var startInnerBodyTag=vitalsTable.getBodyTag()?"<"+vitalsTable.getBodyTag()+">":"";
var endInnerBodyTag=vitalsTable.getBodyTag()?"</"+vitalsTable.getBodyTag()+">":"";
var headerHTML=startInnerBodyTag+"<"+vitalsTable.getRowTag()+" id='"+nameSpace+"header' class='"+(vitalsTable.sortable?"sort-control":"")+" hdr'>";
var columnSequence=vitalsTable.getColumnSequence();
var numberColumns=columnSequence.length;
var headerItemClass="";
var column=null;
var style="";
for(j=0;
j<numberColumns;
j++){headerItemClass="header-item";
column=vitalsTable.getColumnMap()[columnSequence[j]];
style=column.getWidth()?" style='width:"+column.getWidth()+"px;'":"";
headerItemClass+=(column.getCustomClass()?(" "+column.getCustomClass()):"");
headerItemClass+=(column.getIsSortable()?" sort-option":"");
if(column.getColumnSortDirection()!==TableColumn.SORT.NONE){headerItemClass+=(" "+vitalsTable.getSortClass(column.getColumnSortDirection()));
}headerHTML+=("<"+vitalsTable.getColumnTag()+" id='"+nameSpace+"columnHeader"+column.getColumnId()+"' class='"+headerItemClass+"'"+style+"><span id='"+nameSpace+"headerItemDisplay"+column.getColumnId()+"' class='header-item-display'>"+column.getColumnDisplay()+"</span></"+vitalsTable.getColumnTag()+">");
}return headerWrapper+"<div id='"+nameSpace+"innerHeaderWrapper' class='hdr'>"+headerHTML+"</"+vitalsTable.getRowTag()+">"+endInnerBodyTag+"</div></div>";
}else{return"";
}};
vitalsTable.updateAfterResize=function(){var tableBody=$("#"+vitalsTable.namespace+"tableBody");
if(!tableBody||!tableBody.length){return;
}if(tableBody[0].scrollHeight>tableBody.outerHeight()){$("#"+vitalsTable.namespace+"innerHeaderWrapper").addClass("shifted");
}else{$("#"+vitalsTable.namespace+"innerHeaderWrapper").removeClass("shifted");
}};
results=recordData.RG;
numberResults=results.length;
results=this.processResultsForAmbulatoryView(recordData);
vitalsTable.addColumn(new TableColumn().setCustomClass("vitals-wf-amb-name").setColumnId("GroupName").setRenderTemplate("<span>${RESULT_GROUP_NAME}</span>"));
for(j=0;
j<this.m_ambViewColumnCnt;
j++){columnClass=j?"vitals-wf-amb-result-clmn":"vitals-wf-amb-result-clmn vitals-wf-amb-frst-clmn";
columnName="";
var midColumnIndex=Math.floor(this.m_ambViewColumnCnt/2);
if(j===0){if(self.getShowTodayValue()){columnName="<span>"+i18n.discernabu.vitals_o2.TODAY+"</span>";
}else{columnName="<span>"+i18n.discernabu.vitals_o2.LATEST+"</span>";
}}else{if(j==(midColumnIndex-1)||j==midColumnIndex){columnClass="vitals-wf-amb-prv-clmn vitals-wf-amb-col-"+(j+2);
columnName="<span>"+i18n.discernabu.vitals_o2.PREVIOUS+"</span>";
}}column=new TableColumn().setColumnDisplay(columnName).setColumnId("column"+j).setCustomClass(columnClass).setRenderTemplate("${RESULT_OBJ['column"+j+"'].DISPLAY}");
vitalsTable.addColumn(column);
hoverExtension.addHoverForColumn(column,function(dataObj){return self.createResultHoverForFlowsheetView(dataObj);
});
}vitalsTable.addExtension(new TableCellClickCallbackExtension().setCellClickCallback(function(event,data){data.NAMESPACE=nameSpace;
if(data.COLUMN_ID==="GroupName"&&self.SIDE_PANEL_AVAILABLE){self.groupNameCellClickHandler(event,data);
}else{self.resultTableCellClickHandler(event,data,"Ambulatory View");
}}));
vitalsTable.bindData(results.RESULTS);
this.setComponentTable(vitalsTable);
vitalsCombinedHTML+=vitalsTable.render();
if(this.SIDE_PANEL_AVAILABLE){vitalsCombinedHTML+="<div id ='WF_VS"+compId+"sidePanelContainer' class='vitals-wf-side-panel'>&nbsp;</div>";
}this.finalizeComponent(vitalsCombinedHTML);
this.m_ambTableContainer=$("#WF_VS"+compId+"table");
if(this.SIDE_PANEL_AVAILABLE){this.initializeSidePanel();
}viewTypeTimer=new CapabilityTimer("CAP:MPG Vitals O2 View Type",this.criterion.category_mean);
viewTypeTimer.addMetaData("rtms.legacy.metadata.1","Ambulatory View");
viewTypeTimer.capture();
if(results.CRITICAL_IND){CERN_EventListener.fireEvent(this,this,EventListener.EVENT_CRITICAL_UPDATE,{critical:true});
}}else{vitalsTable=new FlowsheetTable();
vitalsTable.addExtension(hoverExtension,2);
vitalsTable.setNamespace(nameSpace);
results=this.processResultsForFlowsheetView(recordData);
vitalsTable.addLabelColumn(new TableColumn().setColumnDisplay("&nbsp;<br />&nbsp;").setColumnId("GroupName").setCustomClass("vitals-wf-label-name").setRenderTemplate("<span>${RESULT_GROUP_NAME}</span>"));
vitalsTable.addLabelColumn(new TableColumn().setColumnDisplay("&nbsp;<br />&nbsp;").setColumnId("UOM").setCustomClass("vitals-wf-label-uom").setRenderTemplate("<span>${RESULT_UOM}</span>"));
if(this.m_showingLatestResults){if(columnCntForFlowsheetView>this.m_latestColumnCap){columnCntForFlowsheetView=this.m_latestColumnCap;
}vitalsTable.setDisclaimer(this.createDisclaimerMessage());
}else{vitalsTable.setDisclaimer(null);
}for(j=0;
j<columnCntForFlowsheetView;
j++){column=new TableColumn().setColumnId(recordData.TG[j].TIME_ADJUSTED).setColumnDisplay(recordData.TG[j].COLUMN_DISPLAY).setCustomClass(recordData.TG[j].NEW_DAY_CLASS).setRenderTemplate("${RESULT_OBJ['"+recordData.TG[j].TIME_ADJUSTED+"'].DISPLAY}");
vitalsTable.addResultColumn(column);
hoverExtension.addHoverForColumn(column,function(dataObj){return self.createResultHoverForFlowsheetView(dataObj);
});
}vitalsTable.addExtension(new TableCellClickCallbackExtension().setCellClickCallback(function(event,data){data.NAMESPACE=nameSpace;
if((data.COLUMN_ID==="GroupName"||data.COLUMN_ID==="UOM")&&self.SIDE_PANEL_AVAILABLE){self.groupNameCellClickHandler(event,data);
}}),1);
vitalsTable.addExtension(new TableCellClickCallbackExtension().setCellClickCallback(function(event,data){data.NAMESPACE=nameSpace;
self.resultTableCellClickHandler(event,data,"Flowsheet View");
}),2);
vitalsTable.bindData(results.RESULTS);
this.setFlowsheetTable(vitalsTable);
this.m_flowsheetTableObject=vitalsTable;
vitalsCombinedHTML+=vitalsTable.render();
if(this.SIDE_PANEL_AVAILABLE){vitalsCombinedHTML+="<div id ='WF_VS"+compId+"sidePanelContainer' class='vitals-wf-side-panel'>&nbsp;</div>";
}this.finalizeComponent(vitalsCombinedHTML);
this.m_flowsheetTableContainer=$("#WF_VS"+compId+"flowsheetContainer");
$("#"+nameSpace).find(".vitals-wf-result-unknown").parent().addClass("vitals-wf-unknown-parent");
if(this.SIDE_PANEL_AVAILABLE){this.initializeSidePanel();
}viewTypeTimer=new CapabilityTimer("CAP:MPG Vitals O2 View Type",this.criterion.category_mean);
viewTypeTimer.addMetaData("rtms.legacy.metadata.1","Flowsheet View");
viewTypeTimer.capture();
if(results.CRITICAL_IND){CERN_EventListener.fireEvent(this,this,EventListener.EVENT_CRITICAL_UPDATE,{critical:true});
}}this.toggleButtonHover.call();
};
VitalSignComponentWF.prototype.initializeSidePanel=function(){var self=this;
var compID=this.getComponentId();
var sidePanelContId="WF_VS"+compID+"sidePanelContainer";
this.m_sidePanelContainer=$("#"+sidePanelContId);
var isAmbView=this.getShowAmbulatoryView();
var tableHeight=null;
if(isAmbView){tableHeight=this.m_ambTableContainer.css("height");
}else{tableHeight=$("#WF_VS"+compID+"resultsTabletable").css("height");
}var sidePanelHTML="<div id='WF_VS"+compID+"sidePanelResultsContainer'><div id='WF_VS"+compID+"sidePanelGroupName' class='vitals-wf-side-panel-groupname'>&nbsp;</div><div id='sidePanelScrollContainer"+compID+"'><div class='vitals-wf-section-separator'><div class='vitals-wf-title-text'>"+i18n.discernabu.vitals_o2.RESULTS+"</div><div class='sp-separator'>&nbsp;</div></div><div id='WF_VS"+compID+"sidePanelResultList' class='vitals-wf-side-panel-result-list'>&nbsp;</div></div></div>";
if(this.m_sidePanelContainer.length){this.sidePanel=new CompSidePanel(compID,sidePanelContId);
this.sidePanel.setExpandOption(this.sidePanel.expandOption.EXPAND_DOWN);
this.sidePanel.setHeight(tableHeight);
this.sidePanel.setMinHeight(this.m_sidePanelMinHeight);
this.sidePanel.renderSidePanel();
this.sidePanel.setContents(sidePanelHTML,"WF_VSContent"+compID);
this.sidePanel.showCloseButton();
this.sidePanel.setCloseFunction(function(){if(isAmbView){self.m_ambTableContainer.removeClass("vitals-wf-side-panel-addition");
}else{self.m_flowsheetTableObject.setSidePanelWidth(0);
self.m_flowsheetTableContainer.removeClass("vitals-wf-side-panel-addition");
self.m_flowsheetTableObject.updateAfterResize();
}self.highlightSelectedRow(false);
self.m_showPanel=false;
self.m_clickedLabel="";
self.m_sidePanelContainer.hide();
});
this.sidePanel.setOnCollapseFunction(function(){self.m_sidePanelContainer.css({position:"absolute"});
});
}};
VitalSignComponentWF.prototype.resizeComponent=function(){if(!this.getShowAmbulatoryView()&&this.m_showPanel){this.m_flowsheetTableObject.setSidePanelWidth(this.m_sidePanelContainer.outerWidth()+11);
}MPageComponent.prototype.resizeComponent.call(this,null);
if(this.SIDE_PANEL_AVAILABLE&&this.sidePanel){var tableHeight=null;
if(this.getShowAmbulatoryView()){tableHeight=$("#WF_VS"+this.getComponentId()+"table").css("height");
}else{tableHeight=$("#WF_VS"+this.getComponentId()+"resultsTabletable").css("height");
}this.sidePanel.setHeight(tableHeight);
this.sidePanel.resizePanel();
var vitalsPlot=this.getVitalsPlot();
if(vitalsPlot){vitalsPlot.replot();
}}};
VitalSignComponentWF.prototype.highlightSelectedRow=function(selRowObj){var compID=this.getComponentId();
var isAmbView=this.getShowAmbulatoryView();
var tableViewObj=null;
if(isAmbView){tableViewObj=$("#WF_VS"+compID+"table");
}else{tableViewObj=this.m_flowsheetTableContainer;
}var prevRow=tableViewObj.find(".selected");
if(prevRow.length){if(prevRow.hasClass("vitals-wf-selected-row selected")){prevRow.removeClass("vitals-wf-selected-row selected");
}}if(selRowObj){selRowObj.find(".mpage-tooltip-hover").removeClass("mpage-tooltip-hover");
selRowObj.addClass("vitals-wf-selected-row selected");
}if(!isAmbView){if(selRowObj){var currentRowLabelSelectedId=selRowObj[0].id;
var labelParts=currentRowLabelSelectedId.split(":");
currentRowLabelSelectedId="";
for(var i=0;
i<labelParts.length;
i++){currentRowLabelSelectedId+=labelParts[i];
if((i+1)!==labelParts.length){currentRowLabelSelectedId+="\\:";
}}var currentRowResultsSelectedId=currentRowLabelSelectedId.replace("label","results");
var currentRowResultsSelectObj=$("#"+currentRowResultsSelectedId);
if(currentRowResultsSelectObj.length){currentRowResultsSelectObj.find(".mpage-tooltip-hover").removeClass("mpage-tooltip-hover");
currentRowResultsSelectObj.addClass("vitals-wf-selected-row selected");
}}}};
MP_Util.setObjectDefinitionMapping("WF_VS",VitalSignComponentWF);
