var Rcm_Floating_Header=function(){this.floatingDiv;
this.headerRowYPos=0;
this.table;
this.headerRowYMax;
this.getRealPosition=function(obj){var y=0;
var x=0;
while(obj.offsetParent){obj=obj.offsetParent;
y+=obj.offsetTop;
x+=obj.offsetLeft;
}return{x:x,y:y};
};
this.floatingTableListener=function(){var windowOffsetHeight=window.offsetHeight?window.offsetHeight:0;
var scrollTop=0;
if(document.documentElement.scrollTop){scrollTop=document.documentElement.scrollTop;
}else{if(document.body.scrollTop){scrollTop=document.body.scrollTop;
}else{if(window.pageYOffset){scrollTop=window.pageYOffset;
}}}var curPos=0;
if(scrollTop&&(windowOffsetHeight===0||clientHeight>scrollTop)){curPos=scrollTop;
}else{curPos=windowOffsetHeight;
}if(this.headerRowYPos<curPos){this.floatingDiv.style.top=curPos;
this.floatingDiv.style.display="block";
}else{this.floatingDiv.style.display="none";
}};
this.copyTableHeader=function(tableHeaderRow){this.table=tableHeaderRow.parentNode;
if(!this.floatingDiv){if(!tableHeaderRow){alert("Rcm_floating_header error: can not find table header row when calling Rcm_Floating_Header.addFloatingTableHeader(tableRowId).");
return;
}if(!this.table){alert("Rcm_floating_header error: can not find parent table when calling Rcm_Floating_Header.addFloatingTableHeader(tableRowId).");
return;
}this.headerRowYMax=this.getRealPosition(tableHeaderRow).y+this.table.scrollHeight;
this.headerRowYPos=this.getRealPosition(tableHeaderRow).y;
this.floatingDiv=document.createElement("div");
this.floatingDiv.id="copied"+tableHeaderRow.id;
this.floatingDiv.style.position="absolute";
this.floatingDiv.setAttribute("z-index",1);
this.floatingDiv.style.display="none";
document.body.appendChild(this.floatingDiv);
var tablePosition=getRealPosition(this.table);
this.floatingDiv.style.top=tablePosition.y;
this.floatingDiv.style.left=tablePosition.x;
this.floatingDiv.style.width=this.table.offsetWidth;
}else{var copiedFloatingTable=document.getElementById("copiedFloatingTable");
if(copiedFloatingTable){copiedFloatingTable.parentNode.removeChild(copiedFloatingTable);
}}this.createFloatingChildTable(tableHeaderRow);
};
this.createFloatingChildTable=function(tableHeaderRow){var floatingTable=document.createElement("TABLE");
floatingTable.id="copiedFloatingTable";
floatingTable.className=this.table.className;
this.floatingDiv.appendChild(floatingTable);
var floatingTableThread=document.createElement("THEAD");
floatingTable.appendChild(floatingTableThread);
var floatingTableRow=document.createElement("TR");
floatingTableRow.className=tableHeaderRow.className;
floatingTableThread.appendChild(floatingTableRow);
var fromThs=tableHeaderRow.getElementsByTagName("TH");
for(var x=0;
x<fromThs.length;
x++){var floatingCell=fromThs[x].cloneNode(true);
floatingTableRow.appendChild(floatingCell);
floatingCell.id=fromThs[x].id;
var pl,pr,pt,pb,bl,br,bt,bb,width,height=0;
if(fromThs[x].style.paddingLeft){pl=fromThs[x].style.paddingLeft.replace("px","");
}if(fromThs[x].style.paddingRight){pr=fromThs[x].style.paddingRight.replace("px","");
}if(fromThs[x].style.paddingTop){pt=fromThs[x].style.paddingTop.replace("px","");
}if(fromThs[x].style.paddingBottom){pb=fromThs[x].style.paddingBottom.replace("px","");
}if(fromThs[x].style.borderLeftWidth){bl=fromThs[x].style.borderLeftWidth.replace("px","");
}if(fromThs[x].style.borderRightWidth){br=fromThs[x].style.borderRightWidth.replace("px","");
}if(fromThs[x].style.borderTopWidth){bt=fromThs[x].style.borderTopWidth.replace("px","");
}if(fromThs[x].style.borderBottomWidth){bb=fromThs[x].style.borderBottomWidth.replace("px","");
}if(fromThs[x].currentStyle){for(var y in fromThs[x].currentStyle){if(y=="font"||y=="top"){continue;
}if(floatingCell.style[y]&&fromThs[x].currentStyle[y]){floatingCell.style[y]=fromThs[x].currentStyle[y];
}}pl=fromThs[x].currentStyle.paddingLeft.replace("px","");
pr=fromThs[x].currentStyle.paddingRight.replace("px","");
pt=fromThs[x].currentStyle.paddingTop.replace("px","");
pb=fromThs[x].currentStyle.paddingBottom.replace("px","");
bl=fromThs[x].currentStyle.borderLeftWidth.replace("px","");
br=fromThs[x].currentStyle.borderRightWidth.replace("px","");
bt=fromThs[x].currentStyle.borderTopWidth.replace("px","");
bb=fromThs[x].currentStyle.borderBottomWidth.replace("px","");
var floatingBorder=Math.round((bl+br)/2);
if(fromThs[x].offsetWidth-pl-pr-floatingBorder>0){width=fromThs[x].offsetWidth-pl-pr-floatingBorder;
}else{width=fromThs[x].offsetWidth;
}if(fromThs[x].offsetHeight-pt-pb-bt-bb>0){height=fromThs[x].offsetHeight-pt-pb-bt-bb;
}else{height=fromThs[x].offsetHeight;
}}else{width=document.defaultView.getComputedStyle(fromThs[x],"").getPropertyValue("width");
var floatingBorder=Math.round((bl+br)/2);
if(width-pl-pr-floatingBorder>0){width=width-pl-pr-floatingBorder;
}height=document.defaultView.getComputedStyle(fromThs[x],"").getPropertyValue("height");
if(height-pt-pb-bt-bb>0){height=height-pt-pb-bt-bb;
}}floatingCell.style.width=width;
floatingCell.style.height=height;
var top=fromThs[x].offsetTop;
floatingCell.style.top=top;
var left=fromThs[x].offsetLeft;
floatingCell.style.left=left;
floatingCell.style.position=fromThs[x].style.position;
}};
this.copyDivTableHeader=function(headerDiv,tableHeaderRow){this.table=tableHeaderRow.parentNode;
if(!this.floatingDiv){if(!tableHeaderRow){alert("Rcm_floating_header error: can not find table header row when calling Rcm_Floating_Header.addFloatingDivAndTableHeader(tableRowId, divId , caller, notifyListener).");
return;
}if(!this.table){alert("Rcm_floating_header error: can not find parent table when calling Rcm_Floating_Header.addFloatingDivAndTableHeader(tableRowId, divId , caller, notifyListener).");
return;
}this.headerRowYMax=this.getRealPosition(tableHeaderRow).y+this.table.scrollHeight;
this.headerRowYPos=this.getRealPosition(tableHeaderRow).y;
this.floatingDiv=document.createElement("div");
this.floatingDiv.id="copied"+tableHeaderRow.id;
this.floatingDiv.style.position="absolute";
this.floatingDiv.setAttribute("z-index",1);
this.floatingDiv.style.display="none";
document.body.appendChild(this.floatingDiv);
var tablePosition=getRealPosition(this.table);
this.floatingDiv.style.top=tablePosition.y;
this.floatingDiv.style.left=tablePosition.x;
this.floatingDiv.style.width=this.table.offsetWidth;
}else{while(this.floatingDiv.firstChild){this.floatingDiv.removeChild(this.floatingDiv.firstChild);
}}var floatingChildDiv=headerDiv.cloneNode(true);
floatingChildDiv.className=headerDiv.className;
floatingDiv.appendChild(floatingChildDiv);
this.createFloatingChildTable(tableHeaderRow);
};
this.resizeHeader=function(tableRowId){var tableHeaderRow=document.getElementById(tableRowId);
this.table=tableHeaderRow.parentNode;
var tablePosition=getRealPosition(this.table);
this.floatingDiv.style.top=tablePosition.y;
this.floatingDiv.style.left=tablePosition.x;
this.floatingDiv.style.width=this.table.offsetWidth;
var fromThs=this.table.getElementsByTagName("TH");
var toThs=this.floatingDiv.getElementsByTagName("TH");
for(var x=0;
x<fromThs.length;
x++){var pl,pr,pt,pb,bl,br,bt,bb,width,height=0;
if(fromThs[x].style.paddingLeft){pl=fromThs[x].style.paddingLeft.replace("px","");
}if(fromThs[x].style.paddingRight){pr=fromThs[x].style.paddingRight.replace("px","");
}if(fromThs[x].style.paddingTop){pt=fromThs[x].style.paddingTop.replace("px","");
}if(fromThs[x].style.paddingBottom){pb=fromThs[x].style.paddingBottom.replace("px","");
}if(fromThs[x].style.borderLeftWidth){bl=fromThs[x].style.borderLeftWidth.replace("px","");
}if(fromThs[x].style.borderRightWidth){br=fromThs[x].style.borderRightWidth.replace("px","");
}if(fromThs[x].style.borderTopWidth){bt=fromThs[x].style.borderTopWidth.replace("px","");
}if(fromThs[x].style.borderBottomWidth){bb=fromThs[x].style.borderBottomWidth.replace("px","");
}if(fromThs[x].currentStyle){for(var y in fromThs[x].currentStyle){if(y=="font"||y=="top"){continue;
}if(toThs[x].style[y]&&fromThs[x].currentStyle[y]){toThs[x].style[y]=fromThs[x].currentStyle[y];
}}pl=fromThs[x].currentStyle.paddingLeft.replace("px","");
pr=fromThs[x].currentStyle.paddingRight.replace("px","");
pt=fromThs[x].currentStyle.paddingTop.replace("px","");
pb=fromThs[x].currentStyle.paddingBottom.replace("px","");
bl=fromThs[x].currentStyle.borderLeftWidth.replace("px","");
br=fromThs[x].currentStyle.borderRightWidth.replace("px","");
bt=fromThs[x].currentStyle.borderTopWidth.replace("px","");
bb=fromThs[x].currentStyle.borderBottomWidth.replace("px","");
var floatingBorder=Math.round((bl+br)/2);
if(fromThs[x].offsetWidth-pl-pr-floatingBorder>0){width=fromThs[x].offsetWidth-pl-pr-floatingBorder;
}else{width=fromThs[x].offsetWidth;
}if(fromThs[x].offsetHeight-pt-pb-bt-bb>0){height=fromThs[x].offsetHeight-pt-pb-bt-bb;
}else{height=fromThs[x].offsetHeight;
}}else{width=document.defaultView.getComputedStyle(fromThs[x],"").getPropertyValue("width");
var floatingBorder=Math.round((bl+br)/2);
if(width-pl-pr-floatingBorder>0){width=width-pl-pr-floatingBorder;
}height=document.defaultView.getComputedStyle(fromThs[x],"").getPropertyValue("height");
if(height-pt-pb-bt-bb>0){height=height-pt-pb-bt-bb;
}}toThs[x].style.width=width;
toThs[x].style.height=height;
var top=fromThs[x].offsetTop;
toThs[x].style.top=top;
var left=fromThs[x].offsetLeft;
toThs[x].style.left=left;
toThs[x].style.position=fromThs[x].style.position;
}};
return{addFloatingTableHeader:function(tableRowId){var tableHeaderRow=document.getElementById(tableRowId);
if(tableHeaderRow){copyTableHeader(tableHeaderRow);
window.onscroll=function(){if(!tableHeaderRow||tableHeaderRow.offsetWidth===0&&tableHeaderRow.offsetHeight===0){this.floatingDiv.style.display="none";
}else{floatingTableListener();
}};
window.onresize=function(){if(!tableHeaderRow||tableHeaderRow.offsetWidth===0&&tableHeaderRow.offsetHeight===0){this.floatingDiv.style.display="none";
}else{resizeHeader(tableRowId);
floatingTableListener();
}};
}},addFloatingDivAndTableHeader:function(tableRowId,divId,caller,notifyListener){var headerDiv=document.getElementById(divId);
var tableHeaderRow=document.getElementById(tableRowId);
if(headerDiv&&tableHeaderRow){copyDivTableHeader(headerDiv,tableHeaderRow);
if(caller&&notifyListener){notifyListener.call(caller);
}window.onscroll=function(){if(!tableHeaderRow||tableHeaderRow.offsetWidth===0&&tableHeaderRow.offsetHeight===0){this.floatingDiv.style.display="none";
}else{floatingTableListener();
}};
window.onresize=function(){if(!tableHeaderRow||tableHeaderRow.offsetWidth===0&&tableHeaderRow.offsetHeight===0){this.floatingDiv.style.display="none";
}else{resizeHeader(tableRowId);
floatingTableListener();
}};
}}};
}();
